### ISSUE TITLE
Downloaded files with itag '140' can't play/seek in some players

### ISSUE THREAD

**Issue by nukeop** [fent/node-ytdl-core#100]
```
ytdl('http://www.youtube.com/watch?v=KMU0tzLwhbE', {quality: '140'})
      .pipe(fs.createWriteStream('out.m4a'));
```

If you download a file requesting this itag (or use audio only), it will crash some players.

Probably related to this:
https://github.com/rg3/youtube-dl/issues/3681

**Comment by fent** [comment]
If the solution is to use ffmpeg to rewrite headers, I'm hesitant about adding that in, as I'm trying to keep the module purely js. I guess it could be an optional dependency.

**Comment by fent** [comment]
Decided not to go with this one, sorry. This module's main goal will continue to be getting metadata, and downloading raw video streams. And any additional processing should be done outside, as it can be applied to any video, and not just YouTube videos.

[pully](https://github.com/JimmyBoh/pully) can do additional processing to videos.
