### ISSUE TITLE
All the video formats  has no audio except 360p.

### ISSUE THREAD

**Issue by ankiyzxi25** [fent/node-ytdl-core#1001]
### Before creating an issue, please try the following

- Are you on the latest version of ytdl-core?
  - To check, run `npm ls ytdl-core`
  - If you're using a bot or application that depends on ytdl-core, look at the bottom of the readme on how to update the library
  - Otherwise, if you're directly importing ytdl-core, to install the latest version, run `npm install ytdl-core@latest`
- Search the list of issues for a possible duplicate.
  - If there is a duplicate issue thread, but it's closed, only post in it if it's been active in the past month. Otherwise, creating a new issue thread is fine.
- If your question is about using the library for a specific use case, check out the [examples folder](https://github.com/fent/node-ytdl-core/tree/master/example).

### Otherwise, feel free to open an issue

Include the following if your issue is a bug

- If you're getting a specific error message, include the full stack trace
- If you're getting unexpected behavior without an error message
  - What should happen?
  - What happens instead?
- Include any relevant code around ytdl-core. You don't have to upload your entire program, small snippets are fine.
- If this error happens only on some videos, include a link or links to videos.

**Comment by ankiyzxi25** [comment]
All the video has hasaudio:false

**Comment by gatecrasher777** [comment]
Sometimes you get 720p with audio, but generally, YouTube video and audio media is in separated files, especially for 1080p and above.  You can mux separate YouTube video and audio files easily using ffmpeg.

```javascript
const spawn = require('child_process').spawnSync;
const ffmpeg = require('ffmpeg-static');

...
spawn(ffmpeg,['-i',videoFilename,'-i',audioFilename,'-map','0:v:0','-map','1:a:0','-vcodec','copy','-acodec','copy',outputFilename]);
...
```

**Comment by ankiyzxi25** [comment]
> Sometimes you get 720p with audio, but generally, YouTube video and audio media is in separated files, especially for 1080p and above. You can mux separate YouTube video and audio files easily using ffmpeg without recoding.
> 
> ```js
> const spawn = require('child_process').spawnSync;
> const ffmpeg = require('ffmpeg-static');
> 
> ...
> spawn(ffmpeg,['-i',videoFilename,'-i',audioFilename,'-map','0:v:0','-map','1:a:0','-vcodec','copy','-acodec','copy',outputFilename]);
> ...
> 


Can i do this in ffmpeg.wasm so that i can provide the download link as blob after mux??
