### ISSUE TITLE
No sounds when downloading unlisted videos

### ISSUE THREAD

**Issue by Bebiezaza** [fent/node-ytdl-core#1008]
I was using ytdl to download videos from youtube, but when I tried to download unlisted videos, it doesn't download sounds with the video, resulting in complete silence. This is not a complete duplicate of #601.

The code is as below
```
const fs = require('fs');
const ytdl = require('ytdl-core');

ytdl('https://www.youtube.com/watch?v=IA_Pufhe-Wk') // public vid test
  .pipe(fs.createWriteStream('video.mp4'));
ytdl('https://www.youtube.com/watch?v=qFadZs0lt0A') // unlisted vid test
  .pipe(fs.createWriteStream('video2.mp4'));
```

The unlisted video in the code is just an example, but the problem also persists on other unlisted videos too.

**Comment by Bebiezaza** [comment]
seems like it's happening to at least one public video too.
https://www.youtube.com/watch?v=5ovI8UwUPZw

**Comment by ItsLeon15** [comment]
Downloading and/or streaming the video works for me?

**Comment by Bebiezaza** [comment]
another public video 🤔 
https://www.youtube.com/watch?v=wvsndffjlZg

**Comment by Bebiezaza** [comment]
another public one that I cannot fetch the sound
https://www.youtube.com/watch?v=5ovI8UwUPZw

**Comment by Bebiezaza** [comment]
here's an unlisted video, although there's no footage as it's a song video.
https://www.youtube.com/watch?v=cOWibD865hs

**Comment by ItsLeon15** [comment]
Might be Youtube Server Side's issue?

**Comment by TimeForANinja** [comment]
ytdl-core might be picking the wrong itags 🤔 
should be worth checking which itags are provided / picked

**Comment by Bebiezaza** [comment]
Well, I forgot to make a follow-up to this issue. I fixed the issue by adding `filter:"audioonly"` to ytdl options.

It is playing unlisted videos now, so I am closing this issue.
