### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ImKill6r** [fent/node-ytdl-core#1011]
I get this error when I didn't get it before
The error is this:
TypeError: Cannot read property 'author' of undefined

**Comment by ImKill6r** [comment]
https://pastebin.com/b98qwRj7

**Comment by TimeForANinja** [comment]
you should get an error-stack with your `TypeError` pointing you to the lines your error resides on
without that it's like searching for a needle in a haystack

so have a look at that stack and if you can't figure it out feel free to reopen this issue
