### ISSUE TITLE
Thoughts on 403/410 issue and my hacky solution.

### ISSUE THREAD

**Issue by C-Lunn** [fent/node-ytdl-core#1021]
Firstly, I am by no means an expert in JS/TS so there may be a much easier solution than the one outlined here.

I've been thinking about the 410 issue a lot. For me, modifying the URL didn't work, but that's not really good enough anyway as there are other reasons videos might not be able to be played. As such, this issue needs dealing with gracefully.

`ytdl()` is synchronous, but the `stream` object initialised and returned by it relies on an async `getInfo()` function. As a result, it's not possible to know (as far as I'm aware) the result of this promise and deal with it gracefully from the caller. Whilst yes, if `getInfo()` rejects the promise the stream emits an error, there's no confirmation emitted on success, so there's no way to know that it was successful.

In the case of discord-player (or more accurately the unofficial fix for discord-player that uses ytdl directly for videos that use old codecs, [link](https://github.com/Androz2091/discord-music-bot/issues/24) the caller `queue.play()` function is, in practice, synchronous (I believe the TS implementation is written asynchronously but is compiled for an ES2015 target so we get this spaghetti mess of `_awaiter()` functions that do not themselves support `async/await`), and so I see no way out of this without changing both.

However, this presents another issue -- ytdl-core has one default export (`ytdl()`) and other modules in the project (namely discord-ytdl-core) rely on that not changing. So, here's what I did.

1. Create a copy of the `ytdl-core` folder in node-modules, and named it `ytdl-core-as`.
2. Edited the `package.json` file so the name matches the folder (`"name": "ytdl-core-as",`).
3. Opened the `ytdl-core-as/lib/index.js` file, and replaced the ytdl function with an asynchronous variant as follows:
```js,
/**
 * @param {string} link
 * @param {!Object} options
 * @returns {ReadableStream}
 */
 const ytdl = async (link, options) => {
  const stream = createStream(options);
  return new Promise(async (r,j) => {
    let rejected = false;
    let info = await ytdl.getInfo(link, options).catch(() => { rejected = true; });
    if(rejected) return void r(null);
    downloadFromInfoCallback(stream, info, options);
    r(stream)
  })
}
```
It's important everything stays as `ytdl` to not break everything else in the module, but we can import it under a different name to avoid conflicts. 

In my solution, the promise is always accepted and if there is an issue it simply returns `null` (as personally I don't care what the issue was), but this is fairly trivial to also reject it with the error code if you need.

4. Now, in discord-player's `discord-player/dist/Structures/Queue.js`, I can import my new module with `const ytdl_as = require("ytdl-core-as");`.

However, like I mentioned earlier, discord-player's play function is effectively synchronous which means we'll need to double up some code -- namely leave the old playing stuff as it was, but duplicate it inside a `.then()` to deal with the newly asynchronous nature of my new ytdl.
 
I modified the `play()` function like so:

```js,
if (["youtube"].includes(track.raw.source)) {
                //console.log(`line 625 for ${track.title}`);
                ytdl_as(track.url, {
                    requestOptions: {
                        headers: {
                            //header info
                        },
                    },
                    filter: "audioonly",
                    passes: 3,
                    highWaterMark: 1 << 27
                }).then((res) => {
                    //console.log(`line 636 for ${track.title}`);
                    if (!res) {
                        console.log("skipping, sending msg");
                        this.player.client.channels.cache.get(this.metadata.channel).send(`Sorry, there was a problem with \`${track.title}\`. Skipping.`);
                        const nextTrack = this.tracks.shift();
                        if(!nextTrack) {
                            this.destroy();
                            return;
                        }
                        this.play(nextTrack, { immediate: true });
                        return;
                    } else {
                        stream = res;
                        const resource = this.connection.createStream(stream, {
                            type: track.raw.source === "youtube" ? voice_1.StreamType.WebmOpus : voice_1.StreamType.Raw,
                            data: track,
                        });
                        if (options.seek) this._streamTime = options.seek;
                        this._filtersUpdate = options.filtersUpdate;
                        this.setVolume(this.options.initialVolume);
                        setTimeout(() => {
                            this.connection.playStream(resource);
                        }, __classPrivateFieldGet(this, _Queue_instances, "m", _Queue_getBufferingTimeout).call(this)).unref();
                    }
                });
                return;
```

This, whilst hacky, works for me.

I hope someone more skilled than I can come up with a more elegant solution.

**Comment by KAAquilla** [comment]
Just make it a Pull Request and you can then do install the package version from that pull request even if its not merged yet.
Like this: npm install <user>/<repo>#pull/<id>/head
Also makes it easier for others to confirm your code.

**Comment by ravindu01manoj** [comment]
> I don't use discord-plauet. Does that mean I just use ytdl-core-as

Is it work without this error?

**Comment by SuperSweatyTejas** [comment]
still receiving the status code 403 while still using this version unfortunately

**Comment by Nyako01** [comment]
i got error code 410 when using `getBasicInfo()`. and this happens in all videos. but lucky me. This problem has been solved by changing the hosting region [heroku] from US to Europe. but sometimes i get error 403
does ytdl get region lock in US?

btw. how to get the error code data in `getBasicInfo.catch()` and store to variable?

I want to make a kind of `switch..case` for a specific error code and execute code based on that error code
example:
```js
ytdl.getBasicInfo(url).then(data => {
  //do something
}).catch(err => {
  switch (err) {
    case 410:
      //do something
      break;
    case 430:
      //do something
      break;
  }
})
```

**Comment by idk-pixel** [comment]
No problem
Just do
let e;
then when you do .catch do
e = error
And e is now the error

**Comment by Nyako01** [comment]
> e = error

Okay. i think it will be like `const error = e.errcode`

**Comment by idk-pixel** [comment]
@Nyako01 nope
error.code

**Comment by TimeForANinja** [comment]
closing since #1022 was merged
