### ISSUE TITLE
No contentLength for 720p Videos

### ISSUE THREAD

**Issue by VishwaGauravIn** [fent/node-ytdl-core#1033]
No contentLength for 720p Videos, other resolutions are working fine please fix this

**Comment by tinazhe** [comment]
and only on 720p.

**Comment by tinazhe** [comment]
> No contentLength for 720p Videos, other resolutions are working fine please fix this

did you find a worrkaround?

**Comment by VishwaGauravIn** [comment]
> > No contentLength for 720p Videos, other resolutions are working fine please fix this
> 
> did you find a worrkaround?

not yet :(

**Comment by TimeForANinja** [comment]
kinda hard for us to fix
if youtube doesn't provide the information we don't know it....

**Comment by WaqasIbrahim** [comment]
You can send a HEAD request to get the content length.

**Comment by TimeForANinja** [comment]
> You can send a HEAD request to get the content length.

that would solve it but i don't see us implementing this as a feature of the library
a video returns tens of formats - and it makes no sense to HEAD-request all of them
if you really need the content-length you can use 2 approaches
* use ytdl.getInfo -> use ytdl.chooseFormat -> do head request on format url -> use ytdl.downloadFromInfo
* use ytdl() and listen to either progress or miniget response events
