### ISSUE TITLE
MinigetError [PlayingError]: Status code: 429

### ISSUE THREAD

**Issue by CyBerFeNix-debug** [fent/node-ytdl-core#1039]
Gating this error when  i   try to play  URL or just  music name  when i run  in my terminal  npm update  the  bot works again and all good after some time   the error shows again  trying to search fix method but no help.

**Comment by ddries** [comment]
HTTP 429 means Too Many Requests. You are being rate-limited (IP ban probably?). The error should disappear after some hours or day(s).

**Comment by CyBerFeNix-debug** [comment]
> 
 Idk  the problem  like  im using  the bot only sometimes  and that error shows  and   idk how to solve that Music bot

**Comment by CyBerFeNix-debug** [comment]
using  heroku  for   host my bot  when  i restart the app  the error   gone

**Comment by Clemens-E** [comment]
heroku shares ip, probably most of theirs ip are banned

**Comment by TimeForANinja** [comment]
yep, 429 looks like a ratelimit
attached is what we usually advice to get rid of them
![image](https://user-images.githubusercontent.com/17046330/146318574-5c9eb643-0f33-4895-acb8-552e61c217e9.png)
