### ISSUE TITLE
Error 404; Discovered problem. Please see pull request #105 for fix

### ISSUE THREAD

**Issue by HcgRandon** [fent/node-ytdl-core#104]
**My initial thoughts were incorrect.  It was a a change to a script, please see pr #105 for fix**

thanks to @Fabricio20 for helping me figure it out faster then It would of taken to debug

**Comment by EdibleDerpy** [comment]
This seems to be a pretty big issue, seems like ytdl-core will be broke for right now.

**Comment by FireController1847** [comment]
Ytdl-core is dying, all music bots that use it on discord are getting ecconnreset now.

**Comment by CyberiumShadow** [comment]
Calm down.

Google took down the API for scheduled Maintainence

**Comment by EdibleDerpy** [comment]
And where was this said @CyberiumShadow

**Comment by WistRBLX** [comment]
Getting errors. form my bot [https://i.typicalbot.com/fad63f](url)

**Comment by EdibleDerpy** [comment]
Not even your bot.... It's the public open source Sexual Rhino code. But yes the YouTube API seems down right now.

**Comment by EdibleDerpy** [comment]
@WistRBLX

**Comment by EdibleDerpy** [comment]
They didn't drop the URL it seems. They are actually doing maintenance at least that is what i heard by doing some google searching.

**Comment by HcgRandon** [comment]
@EdibleDerpy Please link it here then

**Comment by HcgRandon** [comment]
@EdibleDerpy @CyberiumShadow Have provided no proof nor a link to any statement from Google. I think it is very plausible that google has discontinued that endpoint.

**Comment by HcgRandon** [comment]
https://github.com/rg3/youtube-dl/issues/11890 youtube-dl also having issues

**Comment by CyberiumShadow** [comment]
@HcgRandon Google discontinued the endpoint.

New Endpoint is supposed to be  googleapis.com/youtube

**Comment by EdibleDerpy** [comment]
Where are you getting this info @CyberiumShadow

**Comment by CyberiumShadow** [comment]
Given the fact that this is up https://developers.google.com/youtube/v3/docs/

**Comment by CyberiumShadow** [comment]
and the API endpoint it references is this `https://www.googleapis.com/youtube/v3`

**Comment by EdibleDerpy** [comment]
Maybe you should confirm this shit before you go commenting and leading people on a wild goose chase.

**Comment by EdibleDerpy** [comment]
@CyberiumShadow

**Comment by EdibleDerpy** [comment]
You have no valid confirmation about anything.

**Comment by EdibleDerpy** [comment]
Gus is a Discord Bot developer... He doesn't work for google. Get a valid source.. Then comment.

**Comment by chrisakers** [comment]
He left a link to the API showing the endpoint URL. Maybe read all the comments?

**Comment by GusCaplan** [comment]
leave me out of this

**Comment by FireController1847** [comment]
@chrisakers The API endpoint there is not valid, we've tried multiple things.

@GusCaplan Stop stalking us ;.;

**Comment by CyberiumShadow** [comment]
I don't see how its not valid
![image](https://cloud.githubusercontent.com/assets/4259904/22453192/1ad854da-e7d1-11e6-879b-07a400d4a7be.png)

**Comment by GusCaplan** [comment]
@CyberiumShadow that is unrelated to the endpoint we are discussing

**Comment by EdibleDerpy** [comment]
Thank you gus,

**Comment by HcgRandon** [comment]
Taking another look at what the code does I am not getting a 404 on this https://www.youtube.com/get_video_info?video_id=szIDM99kRNM&eurl=https://youtube.googleapis.com/v/szIDM99kRNM&ps=default&gl=US&hl=en

which is what is called here: https://github.com/fent/node-ytdl-core/blob/master/lib/info.js#L120

**Comment by FireController1847** [comment]
@HcgRandon Getting video information doesn't seem to be an issue, but getting the video itself does.

**Comment by EdibleDerpy** [comment]
The endpoint obviously still exists. Because this can be accessed in the browser. https://youtube.googleapis.com/v/jjNBN2ORzIc

**Comment by HcgRandon** [comment]
yeah so its something else, my bad

**Comment by Fabricio20** [comment]
The only issue spotted so far is the lack of hostname on the core/base.js file

**Comment by EdibleDerpy** [comment]
Obviously, because there was no information about them dropping the endpoint.

**Comment by CyberiumShadow** [comment]
Obviously, I stand corrected. I was working under the impression of the original issue name.

**Comment by HcgRandon** [comment]
https://github.com/rg3/youtube-dl/pull/11892/commits/f729f1ceed92b24380805685d071ec99519ddeac#diff-bd8242a0122c5207531954b67e6e51f0R1031

**Comment by FireController1847** [comment]
@HcgRandon That's youtube-dl, not ytdl-core

**Comment by EdibleDerpy** [comment]
That seems completely unrelated.

**Comment by EdibleDerpy** [comment]
Considering it's tied to this issue. 

> https://github.com/rg3/youtube-dl/issues/11890

**Comment by Fabricio20** [comment]
@FireController1847  @EdibleDerpy That issue affects this lib too, take a look at the decipher code block here.

https://github.com/fent/node-ytdl-core/blob/master/lib/info.js#L137

**Comment by FireController1847** [comment]
@Fabricio20 Can you submit a pull request, since you understand what's wrong?

**Comment by HcgRandon** [comment]
lol look at the commit. They use similar methods of resolving. I am working on a fix. unless fab gets to it first

**Comment by Fabricio20** [comment]
Sorry I can't, not really a Javascript developer. Though one of you guys could, the issue is simple:

Youtube has rolled out an update some days ago that is now taking effect on the majority of videos, it removes the hostname from the remote.js script tag, replacing it by a local path only.  (Not sure if there was an official statement but the Java library LavaPlayer spotted this and fixed this some days ago).

`<script src="/yts/jsbin/player-pt_BR-vflY5OaCe/remote.js" class="js-httpswwwyoutubecomytsjsbinplayerpt_BRvflY5OaCeremotejs"></script>`

The current url after this supposed change is `/yts/jsbin`, before we had `youtube.com/`.

**Comment by FireController1847** [comment]
@HcgRandon I really hope you know what he meant, I have no idea.

**Comment by HcgRandon** [comment]
Yes I understood and found the issue. I am attempting to get a pr now.

**Comment by GusCaplan** [comment]
i have no idea how this lib works but it looks like the change should be made around here https://github.com/fent/node-ytdl-core/blob/adab6bbef34f85ede410e18b9fd93d84c5168b93/lib/sig.js#L28

**Comment by HcgRandon** [comment]
Taking a little longer to fix then I thought. I'll let you know when i get it working

**Comment by FireController1847** [comment]
@HcgRandon It's fine, take your time. Anything to get this working again.

**Comment by FireController1847** [comment]
@HcgRandon Where do you think the current issue is at?

**Comment by FireController1847** [comment]
@Fabricio20 What about the line is the issue?

**Comment by FireController1847** [comment]
@HcgRandon I am very, very proud of you!

**Comment by EdibleDerpy** [comment]
@HcgRandon Thank you! Added you on discord ;) Glad you know what you're doing.

**Comment by HcgRandon** [comment]
Its a hacky fix and it doesn't pass all checks. But Its super late for me. This will at least get it to a working point till @fent can look at it

**Comment by trinitynet** [comment]
confirm it works 👌
