### ISSUE TITLE
Cancel download

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [fent/node-ytdl-core#1040]
Hey guys, I'm using `ytdl-core` as a backend for my app, and I need something that's able to cancel an ongoing download.

I didn't find anything like it on the docs and example (maybe I missed it?). Does anyone knows any way to do it? Like sending a kill signal to the ffmpeg process or something, anything really. :+1:

**Comment by developomp** [comment]
Right [here](https://github.com/fent/node-ytdl-core#streamdestroy)
