### ISSUE TITLE
Pause and resume doesn't seem to work

### ISSUE THREAD

**Issue by developomp** [fent/node-ytdl-core#1041]
Hi. I want to pause and resume download of video based on user input, but neither `pause` nor `resume` function doesn't do anything. I've read some other issues, and many of them seem to be node API changes related. Perhaps this is one of it?

- ytdl-core version: 4.9.1
- node version: 16.13.0
- Error log: None. Completely empty.

Minimal reproducible code:

```typescript
import ytdl from "ytdl-core"
import fs from "fs"

const video = ytdl("https://www.youtube.com/watch?v=gTjTBjUdjLE")

console.log("download!")

// save to file
video.pipe(fs.createWriteStream("video.mp4"))

video.on("progress", (_, downloadedBytes) => {
	console.log("downloaded bits:", downloadedBytes)
})

setTimeout(() => {
	console.log("pause!")
	video.pause()
}, 5000)

setTimeout(() => {
	console.log("resume!")
	video.resume()
}, 8000)

```

**Comment by TimeForANinja** [comment]
if you'd alter your code a bit to this
```js
video.on('progress', (_, downloadedBytes, totalBytes) => {
  console.log(`downloaded bits: ${downloadedBytes} of ${totalBytes}`);
});
```
you'd see that the 5 seconds until you pause are enough to download that 30 second clip you defined.
Replacing it with a 1h Music Compilation was enough to get pause / resume to work in your code.
