### ISSUE TITLE
can not download video with audioonly

### ISSUE THREAD

**Issue by m-ilk** [fent/node-ytdl-core#1047]
version: 4.9.2
im trying to download youtube video with `audioonly` filter. i am able to download the file and store it locally, but the mp3 file is not able to be played. here is my code:

```
ytdl('http://www.youtube.com/watch?v=OIJuQ9MQHPY',{ 
    filter: 'audioonly'
})
  .pipe(fs.createWriteStream('resource/mp3/abc.mp3'));
```

if i remove the filter or change the filter to 'audio' and change the output file format to mp4. then it is working fine the file can be played

**Comment by gitpierpy** [comment]
@m-ilk  Hi, YouTube  never uses mp3 codec in audio streams. However, you can use ffmpeg  for final conversion  - there is a good example in [convert_to_mp3.js](https://github.com/fent/node-ytdl-core/blob/22669827cd38bd62e2f4cf1798142dfac1f34501/example/convert_to_mp3.js)

**Comment by m-ilk** [comment]
hey @gitpierpy, thank you so much for you help. it used to work with this way. and i tried with a few videos, some works, some were not . i think the old videos were able to download as mp3 but the new videos were not able any more?

**Comment by gitpierpy** [comment]
I dont't know that... Never seen MP3 audio in YouTube videos!

**Comment by TimeForANinja** [comment]
there is mp3 on youtube but the library should nearly never pick that
so check which format ur getting (there's an event for that) and update the file extension accordingly

**Comment by gitpierpy** [comment]
@TimeForANinja can you provide a link  with mp3 audio? Just curious, as said before I never  found mp3 in all yt  :-)

**Comment by TimeForANinja** [comment]
@gitpierpy i can't provide a link to a video
made that comment based on this https://github.com/fent/node-ytdl-core/blob/master/lib/formats.js#L7
