### ISSUE TITLE
Proxy Pac

### ISSUE THREAD

**Issue by lollita** [fent/node-ytdl-core#1051]
Do it is possible to use a Proxy Pac?

**Comment by TimeForANinja** [comment]
you can use the ytdl's `requestOptions`-Option to pass various things to miniget
with miniget you can then use the `transform`-Option to change the request settings however you want

**Comment by lollita** [comment]
I'm new to this node, is there a complete example?

**Comment by TimeForANinja** [comment]
https://github.com/fent/node-ytdl-core/blob/master/example/proxy.js

**Comment by lollita** [comment]
I see it but not use PAC.

**Comment by TimeForANinja** [comment]
as far as i know there is no general PAC support in all of node
so you have write something yourself or search for packages on npm that do the auto-config for you and drop out the target proxy

**Comment by lollita** [comment]
miniget support pac.
