### ISSUE TITLE
Inconsistent Video Playback

### ISSUE THREAD

**Issue by PrestonN** [fent/node-ytdl-core#1054]
Looks like YouTube has made a change today that breaks video playback. Videos are still playing however buffering is extremely slow. This change seems to affect all major YouTube scraper projects. Using latest version of `ytdl-core`.

The good news is that the fix seems to be quick. I'm not sure if the same fix applies here, but I'll go ahead and link to the [fix](https://github.com/TeamNewPipe/NewPipeExtractor/pull/785) that NewPipe made for the same / similar issue that they experienced today.

Let me know if you need any more information from me. Thanks!

**Comment by gatecrasher777** [comment]
Opened PR #1055
