### ISSUE TITLE
"No such format found" for non-numeral quality values (tiny, large, small, medium etc.)

### ISSUE THREAD

**Issue by Ivanmatthew** [fent/node-ytdl-core#1059]
As title prescribes:
![image](https://user-images.githubusercontent.com/76107136/152694168-b7b82333-93d1-4c9e-904d-25517c1e00a3.png)

**Comment by TimeForANinja** [comment]
as you can see [here](https://github.com/fent/node-ytdl-core/blob/master/typings/index.d.ts#L43) the labels are supported by the Library as part of the videoFormats (as shown in the upper part of your Screenshot)

the Error in the lower Part of the Screenshot is a different Quality
it's the Quality you pass to ytdl to decide which format to choose
you can find the available values for quality in the readme
![image](https://user-images.githubusercontent.com/17046330/156869039-caa180c8-347b-42d8-b000-224bdfc38b3d.png)
there is no plan to support youtubes inaccurate tiny,small,... naming scheme for this parameter
