### ISSUE TITLE
Download not starting, no progress emitted

### ISSUE THREAD

**Issue by ypinskiy** [fent/node-ytdl-core#1068]
Latest version of ytdl-core

Currently using the example in ffmpeg.js as my basis. 2 days ago it worked, ran same script today on multiple computers and the video does not start downloading/no progress is being emitted.

```
let audioDL = ytdl(videoOBJ.url, {
  quality: 'highestaudio',
  highWaterMark: 1 << 32,
  liveBuffer: 5500
})
.on('progress', (_, downloaded, total) => {
	console.log('Downloading audio...', downloaded, total);
})
.on('error', (err) => {
	console.log("Error downloading audio: ", err);
})
.on('end', () => {
	console.log("Audio download complete.");
})
.on("start", () => console.log("Audio download started."))
.on("finish", () => console.log("Audio download complete."));
```

None of these logs get called, nothing gets piped when I try to pipe to ffmpeg, no error messages are shown.

**Comment by TimeForANinja** [comment]
can you check if `ytdl#getInfo` errors?

**Comment by ypinskiy** [comment]
It does not error out, but it also does not return ever. Interestingly enough, I also tried using `youtube-dl-exec` package and it had same issue. Using youtube-dl executable directly did work without any issues.

**Comment by ypinskiy** [comment]
I apologize for the confusion, seems that the queuing algorithmn that I wrote was not resolving the promises that I wrapped around these properly. I will close this issue as it does not seem to be the fault of this library.
