### ISSUE TITLE
content length header with ffmpeg doesn't work

### ISSUE THREAD

**Issue by only1drhex** [fent/node-ytdl-core#1072]
I'm trying to add the content length header while converting to mp3 with ffmpeg but this just results in an endless download loop

```js
var audio =  ytdl(url, {
            format: 'mp3',
            filter: 'audioonly',
            quality: 'highest'
        }).on("response", response => {

res.setHeader("content-length", response.headers["content-length"])
       var ffmpegProcess = spawn(ffmpeg,['-i','pipe:0','-acodec','libmp3lame','-b','128k','-f','mp3','-'])
         audio.pipe(ffmpegProcess.stdin)   
       ffmpegProcess.stdout.pipe(res)

       
 
  }) 
```

**Comment by TimeForANinja** [comment]
i would actually expect this to straight up fail
* `options#format` is not supposed to be a string and should result in the library throwing an error (see [here](https://github.com/fent/node-ytdl-core/blob/8e1a5096edaf5317f49ef6d4f74cfa7ccaf10dfd/lib/format-utils.js#L96))
* you can't set the content-length header before being finished with the ffmpeg reencode... there's just no way of knowing the final size...

**Comment by Cipherjet** [comment]
I never actually got that error and thanks by the way.
