### ISSUE TITLE
ECONNREFUSED 127.0.0.1:80 (sudden, consistent error)

### ISSUE THREAD

**Issue by curz46** [fent/node-ytdl-core#108]
![image](https://cloud.githubusercontent.com/assets/7423545/22524805/a1bbe46c-e8bc-11e6-9d6f-45b23390f00e.png)
I haven't been able to use the tests on this repo because they only seem to be catered towards bash command syntax (I use Windows), but I assume that this error is because of a change in YouTube (tried on multiple machines, URLs worked before).
If you aren't able to reproduce the error, I can help to provide more details.

**Comment by TimeForANinja** [comment]
can u try checking ur version? had that problem some days ago and should be fixed https://github.com/fent/node-ytdl-core/issues/104

**Comment by curz46** [comment]
@TimeForANinja Right you are!
