### ISSUE TITLE
File without audio but not get the error

### ISSUE THREAD

**Issue by zNexusonMK** [fent/node-ytdl-core#1082]
Hello i dont get any error message, and the code works and download the video, but when i open the sound it says the time but not play anything like a mp3 file without audio... i found this error only with 2 videos, with other videos it works fine, i link the video
// https://www.youtube.com/watch?v=5OjYT-nONSg
// https://www.youtube.com/watch?v=n4wfkua-D0I
dont ask me what music i listen XD...

**Comment by zNexusonMK** [comment]
the day later, idk how but now its fixec

**Comment by zNexusonMK** [comment]
the day later, idk how but now its fixec

**Comment by zNexusonMK** [comment]
just kidding... not working again with that songs

**Comment by TimeForANinja** [comment]
a) check if the format it picked includes audio
b) write the video to a file and use sth. like ffprobe to see if there is a audio stream in the file
c) try setting the `audioandvideo` filter

**Comment by zNexusonMK** [comment]
i dont understand the option b can you explain?

**Comment by fdciabdul** [comment]
> i dont understand the option b can you explain?

here some example for stream the Buffer audio file
```
ytdl(url, {
      format: "mp3",
      filter: "audioonly",
      filter: "audioonly",
    }).pipe(res);
````

Go here [L66](https://github.com/fdciabdul/ytdl-rest-api/blob/b47feab1ee94359966e7f38d3cb928bd8feda689/server.js#L66)

**Comment by zNexusonMK** [comment]
> > i dont understand the option b can you explain?
> 
> here some example for stream the Buffer audio file
> 
> ```
> ytdl(url, {
>       format: "mp3",
>       filter: "audioonly",
>       filter: "audioonly",
>     }).pipe(res);
> ```
> 
> Go here [L66](https://github.com/fdciabdul/ytdl-rest-api/blob/b47feab1ee94359966e7f38d3cb928bd8feda689/server.js#L66)

Thanks now work
