### ISSUE TITLE
NO PRIORITY: Slash Commands bugged when using YTD;

### ISSUE THREAD

**Issue by ItsGamingTube** [fent/node-ytdl-core#1083]
![image](https://user-images.githubusercontent.com/66141420/161394804-620876d3-6161-4546-9b22-892bb29ecdae.png)

This happens when using slash commands.

**Comment by TimeForANinja** [comment]
check that the id you provide to `ytdl#validateID` is actually a string...

**Comment by ItsGamingTube** [comment]
Whee i can find that?

**Comment by ItsGamingTube** [comment]
I use discordplayer

**Comment by TimeForANinja** [comment]
no idea - we don't provide support for `discordplayer` here
all i can tell you is that the parameter you pass to `ytdl#validateID` is not a string
if you call it yourself then log what you're passing
if `discordplayer` calls the function ask them for support
