### ISSUE TITLE
Video Duration

### ISSUE THREAD

**Issue by Samiul30** [fent/node-ytdl-core#1086]
I have downloaded video using ffmpeg-static and ytdl. But the total duration of the video is not showing in my phone. Video is fully downloaded and playable.

**Comment by TimeForANinja** [comment]
most phone apps only go by the fine appendix (e.g. `.mp4`) to choose the decoder
so make sure you didn't e.g. name a `matroska` file `xxx.mp4`
you can use ffprobe from the ffmpeg suite to easily check this 😉
