### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by voxsoftware** [fent/node-ytdl-core#109]
Here the error: 

Error: Status code 404↵    at ClientRequest.<anonymous> (/home/james/dev/youtube-downloader-site/node_modules/ytdl-core/lib/request.js:32:18)↵    at emitOne (events.js:96:13)↵    at ClientRequest.emit (events.js:188:7)↵    at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)↵    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)↵    at Socket.socketOnData (_http_client.js:363:20)↵    at emitOne (events.js:96:13)↵    at Socket.emit (events.js:188:7)↵    at readableAddChunk (_stream_readable.js:176:18)↵    at Socket.Readable.push (_stream_readable.js:134:10)↵    at TCP.onread (net.js:548:20)

**Comment by fent** [comment]
What video resulted in this?

By last release do you mean the current version v0.8.1? Or the previous version 0.7.x?
