### ISSUE TITLE
Can't get youtube token for age restricted or private

### ISSUE THREAD

**Issue by Lakomka2204** [fent/node-ytdl-core#1090]
I tried [this](https://github.com/fent/node-ytdl-core/blob/master/example/cookies.js) and it didn't work.
There was token in source code that's called `ID_TOKEN` but it doesn't work and i can't get age restricted or private videos.
Here's code:
index.js
```js
await ytcore.getBasicInfo(req.query.url, {
      requestOptions: {
        headers: {
          cookie: req.cookies,
        },
      },
    });
```
HTTP request
```http
GET http://localhost/info?url=https://www.youtube.com/watch?v=EX_8ZjT2sO4
Cookie: VISITOR_INFO1_LIVE=secret; YSC=secret; NID=511=secret; PREF=tz=secret&f6=40000000&f7=1; SID=secret; __Secure-1PSID=secret; __Secure-3PSID=secret; HSID=secret; SSID=secret; APISID=secret; SAPISID=secret; __Secure-1PAPISID=secret; __Secure-3PAPISID=secret; LOGIN_INFO=secret; SIDCC=secret; __Secure-3PSIDCC=secret
```
Is there any recent and working tutorial on how to get that token?

**Comment by pkamenkovich** [comment]
Also experiencing this issue. Storing cookies from youtube and passing them into the "cookie" header does not work.

**Comment by kamalkech** [comment]
so what issue still not fixed !!
