### ISSUE TITLE
Downloading audio as mp3 downloads in wav format.

### ISSUE THREAD

**Issue by MistakingManx** [fent/node-ytdl-core#1096]
**Unexpected behavior:**
  - What should happen?
  When you download a file with the mp3 format, it downloads in `mp3` format.
  - What happens instead?
  It downloads into a semi-readable mp3 format, but isn't viewable on all platforms as it actually downloads in `wav`, opening it in Audacity after renaming it to .wav lets you convert it to an `mp3` which fixes the issue.

**Trying to explain better:**
I download videos in `mp3` format, but even though SOME apps can play it, it's encoded in the `wav` format, it's most obvious when using Safari and Audacity, renaming the audio file to end with .wav instead of .mp3 lets those apps read it, which is why I assume it's a `wav` instead of `mp3`.

**Comment by wc2184** [comment]
I don't believe this package supports mp3, as you say it's kind of a fake mp3 format that many media players don't work (VLC mobile and Apple Music MacOS player can't play the 'mp3' file i generate from this package, while browsers can and elmedia video player).

I have to get the ytdl as an mp4 file with the options `{ filter: 'audioonly' }` then use a package like fluent-ffmpeg to convert it to a 'real' mp3.

**Comment by LuanRT** [comment]
> I don't believe this package supports mp3, as you say it's kind of a fake mp3 format that many media players don't work with (VLC mobile and Apple Music MacOS player can't play the 'mp3' file i generate from this package, while browsers can and elmedia video player).

YouTube does not deliver `mp3` and neither does this package. What you have there is an `m4a`.
