### ISSUE TITLE
where is the bytestotal

### ISSUE THREAD

**Issue by michapixel** [fent/node-ytdl-core#11]
i must be missing something, but i need the bytestotal of the video i want to download (for progress as you might have guessed) and i cannot find anything in the info objects i am getting.
( via getInfo() )
besides that:
the info-event never gets fired. 
simplified code would be

```
var stream = fs.createWriteStream('video' + '.' + type));
stream.on('drain', function(){
            trace('drain')
        });
        stream.on('error', function(){
            trace('error')
        });
        stream.on('info', function(){
            trace('info')
        });
        stream.on('end', function(){
            trace('end')
        });
        stream.on('finish', function(){
            trace('fin')
        });
        setInterval(function(){
            trace(stream);
        }, 5000);
        ytdl(url, options).pipe(stream);
```

**Comment by kostasx** [comment]
I've just wrote a [small script](https://gist.github.com/kostasx/6ebfe030d44c59662c4721e2336a7cd4) that uses the [progress](https://www.npmjs.com/package/progress) module to show the download progress.
