### ISSUE TITLE
Some audio links throw 403

### ISSUE THREAD

**Issue by A-Y-U-S-H-Y-A** [fent/node-ytdl-core#1101]
After extracting the audio link using the package, I'm getting a 403 error for some links. E.g. https://youtu.be/dI3xkL7qUAc

**Comment by bangnopal** [comment]
try using a proxy, it worked with me

**Comment by fsholehan** [comment]
> try using a proxy, it worked with me

How to use it?

**Comment by Orivoir** [comment]
@fsholehan i think that @bangnopal wants the server to resend the stream directly instead of resending the link to the client.
I can't provide sample code because i'm on my phone.

**Comment by fsholehan** [comment]
> @fsholehan i think that @bangnopal wants the server to resend the stream directly instead of resending the link to the client. I can't provide sample code because i'm on my phone.

hello, can you shrae the code?
