### ISSUE TITLE
ffmpeg.js issue

### ISSUE THREAD

**Issue by Sacha-Bombard** [fent/node-ytdl-core#1104]
Hi,

I'm coding a small application via NodeJs to download Youtube videos. For this, I use the ytdl-core and ffmpeg libraries.
By launching my file `main.js` via the terminal everything works perfectly `node ./main.js`. So I write `pkg ./main js` in order to have a Mac/Windows executable and be able to use my application on any computer without NodeJs.

However, when I launch via this executable my server launches correctly but when I want to download the video I get this in the terminal.
```
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn /snapshot/Server/node_modules/ffmpeg-static/ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /snapshot/Server/node_modules/ffmpeg-static/ffmpeg',
  path: '/snapshot/Server/node_modules/ffmpeg-static/ffmpeg',
  spawnargs: [
    '-loglevel',
    '8',
    '-hide_banner',
    '-i',
    'pipe:4',
    '-i',
    'pipe:5',
    '-map',
    '0:a',
    '-map',
    '1:v',
    '-c:v',
    'copy',
    'title.mkv'
  ]
}

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

Here my main.js

```javascript
/**
 * Build-In with Nodejs
 */
const cp = require('child_process');;
/**
 * External modules
 */
const ytdl = require('ytdl-core');
const ffmpeg = require('ffmpeg-static');
const express = require('express');
const cors = require('cors');

const app = express();

app.use(cors());

app.listen(8080, () => {
    console.log('Please open "index.html" file.');
});

app.get('/download', async (req, res, next) => {
	try {
		let url = req.query.url;
                let info = await ytdl.getInfo(url);
                let title = `${info.videoDetails.title}`.replace(/[^\x00-\x7F]/g, "");
            
                /**
                 * Get video & audio
                 */
                const audio = ytdl(url, { quality: 'highestaudio' });
                const video = ytdl(url, { quality: 'highestvideo' });
            
                /**
                 * Ffmpeg process
                 */
                const ffmpegProcess = cp.spawn(ffmpeg, [
                  // Remove ffmpeg's console spamming
                  '-loglevel', '8', '-hide_banner',
                  // Set inputs
                  '-i', 'pipe:4',
                  '-i', 'pipe:5',
                  // Map audio & video from streams
                  '-map', '0:a',
                  '-map', '1:v',
                  // Keep encoding
                  '-c:v', 'copy',
                  // Define output file
                  `${title}.mkv`,
                ], {
                  windowsHide: true,
                  stdio: [
                    /* Standard: stdin, stdout, stderr */
                    'inherit', 'inherit', 'inherit',
                    /* Custom: pipe:3, pipe:4, pipe:5 */
                    'pipe', 'pipe', 'pipe',
                  ],
                });
            
                // Link streams
                audio.pipe(ffmpegProcess.stdio[4]);
                video.pipe(ffmpegProcess.stdio[5]);

	} catch (err) {
		console.error(err);
	}
});
```

Here my package.json

```JSON
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Stoll",
  "license": "ISC",
  "dependencies": {
    "cors": "^2.8.5",
    "express": "^4.18.1",
    "ffmpeg-static": "^5.0.2",
    "ytdl-core": "^4.11.0"
  }
}

```

Here the script to get YouTube URL from the input.

```javascript
const downloadBtn = document.getElementById('btn');
const URLinput = document.querySelector('.URL-input');
const serverURL = 'http://localhost:8080';

downloadBtn.addEventListener('click', () => { download(URLinput.value); });

async function download(query) {
	var a = document.createElement('a');
	a.href = `${serverURL}/download?url=${query}`;
	a.setAttribute('download', '');
	a.click();
};
```

I would like to know how to solve this problem. I'm a beginner in these languages and I think I've been through the Google answers which unfortunately don't work.

Thanks.

**Comment by WaqasIbrahim** [comment]
You are not using ytdl properly, after extracting video information you should use `chooseFormat` method to get audio and video urls. What you are doing will get video info and then make two more calls for video and audio url. Secondly you can use [fluent-ffmpeg](https://www.npmjs.com/package/fluent-ffmpeg) to combine audio and video. It's a simple wrapper so you don't need to manage the process manually. Instead of passing two streams to ffmpeg, just give both audio and video urls as input.

**Comment by Sacha-Bombard** [comment]
Okay, thanks for your advice.

Firstly, I modified my code to use `chooseFormat`. Secondly, I wanted to use `fluent-ffmpeg` but I struggle with an error : 
`An error occurred: Cannot find ffprobe`.
So, I installed ffprobe and FFmpeg dependencies, but it doesn't work.

**main.js**

```javascript
/**
 * Build-In with Nodejs
 */
const cp = require('child_process');
/**
* External modules
*/
const ytdl = require('ytdl-core');
const ffmpeg = require('fluent-ffmpeg');
const express = require('express');
const cors = require('cors');

const app = express();

app.use(cors());

app.listen(8080, () => {
    console.log('Please open "index.html" file.');
});

app.get('/download', async (req, res, next) => {
  try {
    let url = req.query.url;
    let info = await ytdl.getInfo(url);
    let title = `${info.videoDetails.title}`.replace(/[^\x00-\x7F]/g, "");

    /**
    * Get video & audio
    */
    let video = ytdl.chooseFormat(info.formats, { quality: 'highestvideo' });
    let audio = ytdl.chooseFormat(info.formats, { quality: 'highestaudio' });

    /**
    * Merge video & audio
    */
   
    ffmpeg()
      .input(`${video.url}`)
      .input(`${audio.url}`)
      .on('error', function(err) {console.log('An error occurred: ' + err.message);})
      .on('end', function() {console.log('Merging finished !');})
      .mergeToFile('out.mkv');

  } catch (err) {
    console.error(err);
  }
});
```

**package.json**

```JSON
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Stoll",
  "license": "ISC",
  "dependencies": {
    "cors": "^2.8.5",
    "express": "^4.18.1",
    "ffmpeg": "^0.0.4",
    "ffmpeg-static": "^5.0.2",
    "ffprobe": "^1.1.2",
    "fluent-ffmpeg": "^2.1.2",
    "ytdl-core": "^4.11.0"
  }
}
```

**Comment by Sacha-Bombard** [comment]
Okay, thanks for your advice.

Firstly, I modified my code to use `chooseFormat`. Secondly, I installed `fluent-ffmpeg` but I struggle with an error : 
`ffmpeg exited with code 1: Cannot find a matching stream for unlabeled input pad 1 on filter Parsed_concat_0`.

**main.js**

```javascript
/**
* External modules
*/
const ytdl = require('ytdl-core');
const ffmpeg = require('fluent-ffmpeg');
ffmpeg.setFfmpegPath('./node_modules/ffmpeg-static/ffmpeg');
ffmpeg.setFfprobePath('./node_modules/ffprobe-static/bin/darwin/arm64/ffprobe');
const express = require('express');
const cors = require('cors');

const app = express();

app.use(cors());

app.listen(8080, () => {
    console.log('Please open "index.html" file.');
});

app.get('/download', async (req, res, next) => {
  try {
    let url = req.query.url;
    let info = await ytdl.getInfo(url);
    let title = `${info.videoDetails.title}`.replace(/[^\x00-\x7F]/g, "");

    /**
    * Get video & audio
    */
    let video = ytdl.chooseFormat(info.formats, { quality: 'highestvideo' });
    let audio = ytdl.chooseFormat(info.formats, { quality: 'highestaudio' });

    /**
    * Merge video & audio
    */
    ffmpeg()
      .input(`${audio.url}`)
      .input(`${video.url}`)
      .on('error', function(err) {console.log('An error occurred: ' + err.message);})
      .on('end', function() {console.log('Merging finished !');})
      .mergeToFile('out.mkv');

  } catch (err) {
    console.error(err);
  }
});
```

**package.json**

```JSON
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Stoll",
  "license": "ISC",
  "dependencies": {
    "cors": "^2.8.5",
    "express": "^4.18.1",
    "ffmpeg-static": "^5.0.2",
    "ffprobe-static": "^3.1.0",
    "fluent-ffmpeg": "^2.1.2",
    "ytdl-core": "^4.11.0"
  }
}
```

_PS: I am a beginner in this language, before coming back to the forum I really try to search by myself with Google ..._

**Comment by wolf-yuan-6115** [comment]
> Okay, thanks for your advice.
> 
> I modified my code to use `chooseFormat`. I don't want to use fluent-ffmpeg because there are a lot of issues with 'mergeToFile' without the fact the process is very slow... So could help me to solve the main problem with 'pkg' ... please.
> 
> **main.js**
> 
> ```js
> /**
>  * Build-In with Nodejs
>  */
>  const cp = require('child_process');
>  /**
>   * External modules
>   */
>  const ytdl = require('ytdl-core');
>  const ffmpeg = require('ffmpeg-static');
>  const express = require('express');
>  const cors = require('cors');
>  
>  const app = express();
>  
>  app.use(cors());
>  
>  app.listen(8080, () => {
>     console.log('Please open "index.html" file.');
>  });
>  
>  app.get('/download', async (req) => {
>   try {
>     let url = req.query.url;
>     let info = await ytdl.getInfo(url);
>     let title = `${info.videoDetails.title}`.replace(/[^\x00-\x7F]/g, "");
> 
>     /**
>     * Get video & audio
>     */
>     let video = ytdl.chooseFormat(info.formats, { quality: 'highestvideo' });
>     let audio = ytdl.chooseFormat(info.formats, { quality: 'highestaudio' });
> 
>     /**
>     * Ffmpeg merge
>     */
>     cp.spawn(ffmpeg, [
>       // Remove ffmpeg's console spamming
>       '-loglevel', '8', '-hide_banner',
>       // Set inputs
>       '-i', `${audio.url}`,
>       '-i', `${video.url}`,
>       // Map audio & video from streams
>       '-map', '0:a',
>       '-map', '1:v',
>       // Keep encoding
>       '-c:v', 'copy',
>       // Define output file
>       `${title}.mkv`
>       ],
>       { windowsHide: true,}
>     );
> 
>   } catch (err) {
>     console.error(err);
>   }
>  });
> ```
> 
> **package.json**
> 
> ```json
> {
>   "name": "server",
>   "version": "1.0.0",
>   "description": "",
>   "main": "main.js",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "author": "Stoll",
>   "license": "ISC",
>   "dependencies": {
>     "cors": "^2.8.5",
>     "express": "^4.18.1",
>     "ffmpeg-static": "^5.0.2",
>     "ytdl-core": "^4.11.0"
>   }
> }
> ```
> 
> _PS: I am a beginner in this language, before coming back to the forum I really try to search by myself with Google ..._

You need to let `pkg` pack FFmpeg binary

**Comment by Sacha-Bombard** [comment]
> You need to let `pkg` pack FFmpeg binary

I added that on package.json and run `pkg .` to compile with package.json settings

```
"pkg": {
    "assets": [
      "./node_modules/ffmpeg-static/ffmpeg",
      "./node_modules/ffmpeg-static/index.js",
    ],
    "targets": [
      "node16-macos-arm64"
    ]
  }
```

It doesn't worked ...
