### ISSUE TITLE
Can't play more than a few seconds from a Youtube live stream

### ISSUE THREAD

**Issue by CDavidSV** [fent/node-ytdl-core#1105]
Hi, I'm currently using ytdl-core for a discord music bot. Everything works fine with regular videos, but it stops after a few seconds whenever I try live video. I've read at issue #1015 that you must change livebuffer to 4900 as seen in the following code. This worked initially, but it stopped again after 30 minutes or so.

Code:
`const stream = ytdl(url, { highWaterMark: 1 << 25, dlChunkSize: 1<<12, quality: [91,92,93,94,95], opusEncoded: true, liveBuffer: 4900 });`

I also tried playing with the highWaterMark and dlChunkSize options but they don't seem to fix it either. 
I have the latest version of Node and ytdl-core.

**Comment by Kiri836** [comment]
Change `liveBuffer: 4900` to `liveBuffer: 1 << 62`, this makes the liveBuffer much bigger and should solve the issue for long live streams.
