### ISSUE TITLE
Is there an easy way to create 2 different file from the same stream?

### ISSUE THREAD

**Issue by romain130492** [fent/node-ytdl-core#1106]
## Description

Just wondering if we can currently create 2 types of files from a same pipe?
For example :
- mp4
- mp3
-
Thanks!

**Comment by TimeForANinja** [comment]
since it looks like you want specific formats (mp4 and mp3 don't get used that often for web-streaming) i'd recommend using ffmpeg
it has full support for multiple inputs and multiple outputs
