### ISSUE TITLE
filterFormats,  chooseFormat - audio , video doesnt work in production 

### ISSUE THREAD

**Issue by Whil117** [fent/node-ytdl-core#1109]
Hi, i have problems with the library, im trying use the library in production, but its very rarely because when i raise my backend  in local, every track that i request works very well, but when i deploy my backend in nodejs. the url give me an error with permissions or that request was reject, somebody have this problem?

**Comment by absidue** [comment]
You can only use the URL on the device that requested it, it's a YouTube limitation so you can't get around it. If you want to be able to access the video on another machine you need to proxy the request through the server that got the URLs from YouTube.

**Comment by Whil117** [comment]
> 

yeap, i was trying with a proxy, but neither work. do you know some config?
I have been trying this config https://github.com/fent/node-ytdl-core/blob/master/example/proxy.js
but doesnt work for me :c

**Comment by absidue** [comment]
not that kind of proxy. instead of sending the URL to your frontend you need to send the video to the frontend, through your server.

requesting video data: frontend -> backend -> YouTube
video data response: YouTube -> backend -> frontend

The URLs can only be used on the machine that got said URLs from YouTube, there is no way around that.

**Comment by TimeForANinja** [comment]
yep as @absidue mentioned most url's are ip-locked
so if you run the script that resolves a youtube url to a video link on your server the server is also the one that has to fetch the data from youtube
what you can however do is use your backend to download the data from youtube, then copy that data to your own http(s) server connected to your frontend - that's what's called proxying
