### ISSUE TITLE
evalmachine error

### ISSUE THREAD

**Issue by sametserpil** [fent/node-ytdl-core#1112]
Hello, I'm using version 4.11.0. Since yesterday I'm getting following error for every video.

```
evalmachine.<anonymous>:24
c[72],c[6]),(0,c[85])(c[11]),(0,c[41])(c[39],c[28],(0,c[66])()),(0,c[78])(c[Math.pow(6,2)+122+-119],c[new Date("Wednesday December 31 1969 19:00:14 CDT")/1E3])}catch(d){(0<c[0]||(((0,c[80])(c[60],c[88]),c[80])(c[21],c[88]),0))&&(
0,c[17])((0,c[70])(c[6]),c[78],c[88],c[12])}try{2<c[91]&&(1<c[53]?(0,c[17])((0,c[80])(c[82],c[6]),c[78],c[39],c[5]):((0,c[45])(c[49],c[88]),c[78])(c[88],c[86])),(0,c[17])((0,c[85])(c[31]),c[41],c[88],c[75],(0,c[35])())}catch(d){}
};Wka(ncode);



^

SyntaxError: Missing catch or finally after try
    at new Script (node:vm:100:7)
    at Object.exports.decipherFormats (D:\WebstormProjects\deneme\node_modules\ytdl-core\lib\sig.js:116:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)

```
Is there something I can do to fix this?

Best.

**Comment by gatecrasher777** [comment]
Until adopted, you can edit lib/sig.js with changes proposed in PR #1110  

https://github.com/fent/node-ytdl-core/pull/1111/files

**Comment by sametserpil** [comment]
I've updated sig.js but nothing changed. I guess this might not be the same error you mentioned at #1111

**Comment by AanupBhattarai** [comment]
I think downgrading to **`4.10.0`** or **`4.9.1`** will work fine for now.

**Comment by sametserpil** [comment]
same error with 4.9.1

**Comment by vikodk67** [comment]
version 4.9.1 Also can't, please anyone fix this problem :) My customer is disappointed. Because I made a playmusic website for an outdoor cafe without ads

**Comment by gatecrasher777** [comment]
> I've updated sig.js but nothing changed. I guess this might not be the same error you mentioned at #1111

if you use the changed sig.js you could not get:

```javascript
evalmachine.<anonymous>:24
c[72],c[6]),(0,c[85])(c[11]),(0,c[41])(c[39],c[28],(0,c[66])()),(0,c[78])(c[Math.pow(6,2)+122+-119],c[new Date("Wednesday December 31 1969 19:00:14 CDT")/1E3])}catch(d){(0<c[0]||(((0,c[80])(c[60],c[88]),c[80])(c[21],c[88]),0))&&(
0,c[17])((0,c[70])(c[6]),c[78],c[88],c[12])}try{2<c[91]&&(1<c[53]?(0,c[17])((0,c[80])(c[82],c[6]),c[78],c[39],c[5]):((0,c[45])(c[49],c[88]),c[78])(c[88],c[86])),(0,c[17])((0,c[85])(c[31]),c[41],c[88],c[75],(0,c[35])())}catch(d){}
};Wka(ncode);
```

That code string would have to end with

```javascript
   .join("")};Wka(ncode);
```

by virtue of

```javascript
    const functionBody = `${subBody}.join("")};${functionName}(ncode);`;
```

**Comment by lomaster1** [comment]
I got the same error and PR #1111 fixing the issue. Thanks

**Comment by sametserpil** [comment]
> > I've updated sig.js but nothing changed. I guess this might not be the same error you mentioned at #1111
> 
> if you use the changed sig.js you could not get:
> 
> ```js
> evalmachine.<anonymous>:24
> c[72],c[6]),(0,c[85])(c[11]),(0,c[41])(c[39],c[28],(0,c[66])()),(0,c[78])(c[Math.pow(6,2)+122+-119],c[new Date("Wednesday December 31 1969 19:00:14 CDT")/1E3])}catch(d){(0<c[0]||(((0,c[80])(c[60],c[88]),c[80])(c[21],c[88]),0))&&(
> 0,c[17])((0,c[70])(c[6]),c[78],c[88],c[12])}try{2<c[91]&&(1<c[53]?(0,c[17])((0,c[80])(c[82],c[6]),c[78],c[39],c[5]):((0,c[45])(c[49],c[88]),c[78])(c[88],c[86])),(0,c[17])((0,c[85])(c[31]),c[41],c[88],c[75],(0,c[35])())}catch(d){}
> };Wka(ncode);
> ```
> 
> That code string would have to end with
> 
> ```js
>    .join("")};Wka(ncode);
> ```
> 
> by virtue of
> 
> ```js
>     const functionBody = `${subBody}.join("")};${functionName}(ncode);`;
> ```

Ok you're right. I think I made a mistake while changing those lines. I've copied entire file and updated it. Now, it works.

Thank you.
