### ISSUE TITLE
how to fix?

### ISSUE THREAD

**Issue by bartadenis** [fent/node-ytdl-core#1114]
![image](https://user-images.githubusercontent.com/64473239/185721508-ec7f6775-8689-4a5c-9b30-36d047217d55.png)

**Comment by dsnsgithub** [comment]
reference https://github.com/fent/node-ytdl-core/issues/1113 for issue/fix

**Comment by AbubakarZorrain** [comment]
Yeah, facing the same issue. I also share it with stackoverflow community but no one respond. https://stackoverflow.com/questions/73421033/ytdl-core-is-not-downloading-and-even-not-getting-videos-info

**Comment by arcovoltaico** [comment]
same here, from this morning I'm not able to download any video. Maybe you could update the subject of the issue?

**Comment by AbubakarZorrain** [comment]
> same here, from this morning I'm not able to download any video. Maybe you could update the subject of the issue?

No I can't update the subject of issue, But I opened a new issue related to 4.10.0 #1115
