### ISSUE TITLE
4.10.0 is outdated, giving us a warning. No version is applicable at this time. 

### ISSUE THREAD

**Issue by AbubakarZorrain** [fent/node-ytdl-core#1115]
As latest version is  not working, giving error of #1113  . 4.10.1 and 4.10.0 both are not working giving us a warning of outdated.

**Comment by dskaiser82** [comment]
I went into package.json changed the version to
"ytdl-core": "4.10.0"

deleted my node modules
and ran yarn (yarn for me)

**Comment by dskaiser82** [comment]
But Greepthe Sheep has a fork for a fix and we have a PR waiting for approvals from maintainers

**Comment by cutdown** [comment]
> As latest version is not working, giving error of #1113 . 4.10.1 and 4.10.0 both are not working giving us a warning of outdated.



> But Greepthe Sheep has a fork for a fix and we have a PR waiting for approvals from maintainers

How to fix the issue bro?!

**Comment by dskaiser82** [comment]
@cutdown see PR
https://github.com/fent/node-ytdl-core/pull/1111

**Comment by dskaiser82** [comment]
And adding GreepSheep fork update (temp fork until the PR is merged in)


You can add it on your package.json with npm npm i ytdl-core@https://github.com/GreepTheSheep/node-ytdl-core

**Comment by CuteSkyler** [comment]
> And adding GreepSheep fork update (temp fork until the PR is merged in)
> 
> You can add it on your package.json with npm npm i ytdl-core@https://github.com/GreepTheSheep/node-ytdl-core

Every time I try to use that NPM command it doesn't work. Any help?
NPM works fine otherwise.

**Comment by TimeForANinja** [comment]
closing as dup of #1113
