### ISSUE TITLE
4.10.0 is outdated, giving us a warning. No version is applicable at this time

### ISSUE THREAD

**Issue by cutdown** [fent/node-ytdl-core#1122]
As latest version is not working, giving error of https://github.com/fent/node-ytdl-core/issues/1113 . 4.10.1 and 4.10.0 both are not working giving us a warning of outdated.

**Comment by dskaiser82** [comment]
See this comment from a#1100

-------
Made a fork of the temporary fix here: https://github.com/GreepTheSheep/node-ytdl-core

You can add it on your package.json with npm npm i ytdl-core@https://github.com/GreepTheSheep/node-ytdl-core

--------
I have a PR for the fix but no maintainer approvals

May be helpful  to remove the node modules folder, and then can yarn install again for a fresh node modules folder

**Comment by TimeForANinja** [comment]
Closing as dup of #1113
