### ISSUE TITLE
How to use yt-dlp with node-ytdl-core?

### ISSUE THREAD

**Issue by romain130492** [fent/node-ytdl-core#1128]
How to use `yt-dlp` instead of `yt-dl` with node-ytdl-core?
thanks

**Comment by TimeForANinja** [comment]
node-ytdl-core is it's own, fully independant library
it does not use `yt-dl`

**Comment by romain130492** [comment]
I see, any idea why the download speed is 20 slower with node-ytdl-core
than when using yt-dlp?
