### ISSUE TITLE
ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by GeoffreyPlitt** [fent/node-ytdl-core#113]
I'm getting the following error when getting metadata for the same video that used to work. Is this a sign that our IP is blocked, or something? Anyone else seeing this?

{ Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 } undefined

**Comment by GeoffreyPlitt** [comment]
Also, why is the library using that IP address? Looks like localhost.

**Comment by diogoalmiro** [comment]
I have an HTTP server and when I call ytdl-core it emits a 301 Status.
In the log of my server I can see a request like this: `localhost/yts/jsbin/player-pt_PT-vflV63_UA/base.js`

**Comment by fent** [comment]
This was fixed recently. Please update to the latest version.

Let me know if it still happens on latest.

**Comment by GeoffreyPlitt** [comment]
Thanks!
