### ISSUE TITLE
Version update warning when running the latest version.

### ISSUE THREAD

**Issue by abaza738** [fent/node-ytdl-core#1134]
I'm running the latest version of `ytld-core@4.11.1` (as of the day I'm writing this issue) as a package for a Discord bot.

### Current Behavior
This warning appears in the console every time the player is fired up.
```
WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
```
Currently `ytdl-core` is a dependency of a package `@discordx/music` as so:
```
$ npm ls ytdl-core
jo-ts@1.1.2 [deprecated]\jo-ts
└─┬ @discordx/music@4.1.0
  └── ytdl-core@4.11.1
```
This behavior is observed with several other people running `ytdl-core`. I hope someone with more knowledge can shed some light on this, as I lack debugging skills.

### Expected Behavior
No warnings, as I'm running the latest version.

**Comment by Kiri836** [comment]
Have you actually run `npm install ytdl-core@latest`? Since this is just a warning for a package update I wouldn't really worry about it, as long as its not affecting anything then it doesn't matter. I have never experienced this issue so the issue seems to be with the dependency or something else on your system.

**Comment by abaza738** [comment]
> Have you actually run `npm install ytdl-core@latest`? Since this is just a warning for a package update I wouldn't really worry about it, as long as its not affecting anything then it doesn't matter. I have never experienced this issue so the issue seems to be with the dependency or something else on your system.

I have run an install again. I also tried deleting node_modules and installing again.  
Since this seems to be just myself and another couple of friends, I'm gonna clear the way for more important issues.  
Thanks for your help 😄
