### ISSUE TITLE
Access Denied 403

### ISSUE THREAD

**Issue by Zainmansour** [fent/node-ytdl-core#1135]
I made a html yt downloader so I send the video url that generated from ytdl.getInfo to the ejs file It works locally but when I deploy the project on heroku  and try to download a video the following error appears:

You don't have authorization to view this page.
HTTP ERROR 403

I tried with and without vpn but It didn't work any help?

**Comment by TimeForANinja** [comment]
the url's are ip-locked
so that'll never work
what you can do though is proxy the request to download the file via your app

**Comment by Zainmansour** [comment]
> 

any references??

**Comment by Orivoir** [comment]
You can see [Limitations ](https://github.com/fent/node-ytdl-core/blob/master/README.md#limitations) at README.md
that indicate:
> Generated download links are valid for 6 hours, and may only be downloadable from the same IP address.
