### ISSUE TITLE
Author avatar URL not including https: / http:

### ISSUE THREAD

**Issue by FireController1847** [fent/node-ytdl-core#114]
Not sure where this issue is which is why I didn't create a pull request, but sometimes the author's avatar URL is not inlcuding the https: and http:, so I created a simple fix below, if that helps.

My personal fix:

`info.author.avatar = (info.author.avatar.includes("https://") || info.author.avatar.includes("http://") ? info.author.avatar : "https:" + info.author.avatar);`

It's basically an if-else statement in one line.

**Comment by TimeForANinja** [comment]
all the ones i can find include it...
should be here https://github.com/fent/node-ytdl-core/blob/514debc33ee55547649ef98760ef6b8918f22fb7/lib/util.js#L316

**Comment by FireController1847** [comment]
It seems to be at random, because it only happens with a few songs in my database. so when I find one I'll give you the link.

**Comment by FireController1847** [comment]
Found one. https://www.youtube.com/watch?v=Qc6zo5jZpPs

**Comment by FireController1847** [comment]
![Example](http://img.hexacircle.com/images/Fire/26chxs1.png)
