### ISSUE TITLE
Firefox downloads all links in .mp4 instead of the desired file type

### ISSUE THREAD

**Issue by JackW25** [fent/node-ytdl-core#1140]
I'm on the latest version of ytdl-core.

Some browsers, such as Firefox and Safari (that I know of) will only download .mp4 files when I try to download them in webm or wav

It works completely fine in Chrome based browsers that I've tested (Vivaldi, Opera, Edge, & Chrome) but for some reason will only download .mp4's in Firefox and Safari browsers (Firefox issue occurs on windows as well as mac)

**Comment by scott1991** [comment]
is there any sample code for reproducing?

**Comment by JackW25** [comment]
@scott1991 Thanks for the reply

This is the js for when .wav is selected

`app.get('/wav', (request, response) => {
    var url = request.query.url;
        ytdl.getInfo(url).then(info => {
           console.log(info.videoDetails.title);
           var title = info.videoDetails.title
        response.header("Content-Disposition", `attachment; filename="${title}.wav`);
    ytdl(url, {format: 'wav'}).pipe(response);
    });
}); `

its fairly basic but it works on browsers such as Chrome, Edge, and the likes. It has issues on Firefox mainly, as it will only download mp4.
