### ISSUE TITLE
404 error due to null hostname

### ISSUE THREAD

**Issue by mel4tonin4** [fent/node-ytdl-core#115]
Hello.

Sometimes the YouTube API uses a null hostname to refer to the same domain hosting the API itself.

Currently request.js can't handle this and ytdl will receive and display a 404 error.
The fix is a 4 lines change.

```
var defaultHostName = "www.youtube.com";

  if (options) { util.objectAssign(parsed, options, true); }
  if (parsed.hostname == null) {
    parsed.hostname = defaultHostName;
  }
```

Can I have permission to push the change or create a pull request?

Thanks!

**Comment by fent** [comment]
Do you know for which request? It's better to do it per request like [here](https://github.com/fent/node-ytdl-core/blob/master/lib/sig.js#L31) since fixing it in `request.js` wouldn't be backwards compatible with the `options.request` option.

**Comment by mel4tonin4** [comment]
First thing, I'm sorry: I misunderstood the whole logic of your code. My code snippet actually fixed the problem but the explanation that I gave for its origin was totally nonsense.

Second thing: I attempted to provide a better fix, following your suggestion. In order to do so, I downloaded the latest version of the sources. By virtue of the behaviour of `url.resolve()` that you are now using, the bug is already fixed.

If you check the third example in the [documentation ](https://nodejs.org/docs/latest/api/url.html#url_url_resolve_from_to) of `url.resolve()`, you'll see that it handles this kind of calls gracefully:

`url.resolve('http://example.com/one', '/two') // 'http://example.com/two'`

You may use this behaviour or fix the issue more explicitly, it's your call. Since "resolving" is something more sophisticated from "joining" or "concatenating", it could be considered ok to pass `VIDEO_URL` as base url in any case.

I apologize for the poor quality of my first message. I attempted to use your library as a black box until today.

**Comment by fent** [comment]
Ah, ok. I'm glad it worked out.

Still, I wasn't sure if your issue was referring to the recent patch with html5player url changing. Or if it was another url that had also changed, so I had to ask.
