### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by dohdoh64** [fent/node-ytdl-core#116]
Hi, I am slightly familiar with this, but I have been using another library that uses this library to download YouTube videos. When I download a video, only recently it has been throwing this error:
`connect ECONNREFUSED 127.0.0.1:80`
I can't seem to locate where it is throwing the error.
Thanks for the help!

**Comment by dohdoh64** [comment]
I saw #113 and tried updating my ytdl-core, but it only updates to 0.7.24 where the issue is not resolved.

**Comment by fent** [comment]
The library you're using might have a specific version of ytdl-core listed. You might need to update by specifying a later version directly by running `npm install ytdl-core@latest`

The library should also know that they should update the dependency version.

**Comment by dohdoh64** [comment]
It still throws an ECONNREFUSED error. When i try `npm outdated` it says
`Package     Current  Wanted  Latest`
`ytdl-core     0.9.1  0.7.24   0.9.1`

**Comment by fent** [comment]
Is that the only version of ytdl-core you have in your tree?

**Comment by dohdoh64** [comment]
Yes, I believe so.

**Comment by fent** [comment]
What's the library that uses this library?

**Comment by dohdoh64** [comment]
I said library, i'm not sure if that is the right word, but [this npm package](https://github.com/tobilg/youtube-mp3-downloader) uses it.

**Comment by fent** [comment]
Hmm, I just tried the first example on that library and it works. I'm not sure where to go from here. You could try removing the `node_modules` folder and installing your packages again. Maybe you got stuck on a version where before this error was fixed.

**Comment by dohdoh64** [comment]
Thanks for all the help, I reinstalled youtube-mp3-downloader and now there is no error. Thanks a lot for the help.
