### ISSUE TITLE
downloaded mp4 can not be opened 

### ISSUE THREAD

**Issue by wahengchang** [fent/node-ytdl-core#117]
the mp4 download works so well by the example url, however it is not working with the video that I would like to download, files are download but does not look like MP4 because they could not be opened by the players.

for example:
https://www.youtube.com/watch?v=6kOBN_b6d7Q
and 
https://www.youtube.com/watch?v=d89h5jLF0k0

**Comment by fent** [comment]
I tried playing playing both of those videos with the default itag, in mplayer and mpv and they both play fine. Maybe you're downloading a format that is not supported by your player?

**Comment by wahengchang** [comment]
actually, I dont think the video is download as 'MP4' format, if it is not mp4, and i am not able to turn it to mp3 (my final goal is extract the mp3 from youtube). do you have any idea of the code ?

```
var path = require('path');
var fs   = require('fs');
var ytdl = require('ytdl-core');

var url = 'https://www.youtube.com/watch?v=d89h5jLF0k0';
var output = path.resolve(__dirname, 'video.mp4');

var video = ytdl(url);
video.pipe(fs.createWriteStream(output));
video.on('response', function(res) {
  var totalSize = res.headers['content-length'];
  var dataRead = 0;
  res.on('data', function(data) {
    dataRead += data.length;
    var percent = dataRead / totalSize;
    process.stdout.cursorTo(0);
    process.stdout.clearLine(1);
    process.stdout.write((percent * 100).toFixed(2) + '% ');
  });
  res.on('end', function() {
    process.stdout.write('\n');
  });
});
```

<img width="465" alt="screen shot 2017-02-25 at 9 05 41 pm" src="https://cloud.githubusercontent.com/assets/5538753/23331311/3949251c-fb9e-11e6-94bb-d122cd116832.png">

**Comment by fent** [comment]
If you're looking for an audio stream, you can use the `filter: 'audioonly'` option. If you specifically want it in the mp3 format, you'll have to convert it with something like ffmpeg.
