### ISSUE TITLE
Bug: result has no audio!

### ISSUE THREAD

**Issue by santi100a** [fent/node-ytdl-core#1171]
# Bug: result has no audio!

This is my code:
```javascript
function downloadVideo(url: URL, writeStream?: NodeJS.WritableStream): Readable {
    const stream: Readable = ytdl(url.toString(), { 
        quality: 'highest',
        filter: 'audioandvideo'
    });
    if (writeStream) stream.pipe(writeStream);
    return stream;
} 
``` 

I expected it to return a `Readable` that is a video with audio; however, I receive a soundless video. **EVEN IF I SPECIFY** the filter.

**Comment by Haiz14** [comment]
Videos with quality higher than 360p don't have audio encode in them. You have to download and mix them separately.

https://github.com/fent/node-ytdl-core#handling-separate-streams

**Comment by santi100a** [comment]
Already changed. Problem solved. But only under Linux...
