### ISSUE TITLE
Bug: Video format not supported

### ISSUE THREAD

**Issue by hashirnouman** [fent/node-ytdl-core#1176]
I hist the /download endpoint to download the youtube videos it was working fine a few days ago but for video any change it is malfunctioning. video gets downloaded instantly but when I open the file it the file format is not supported
`
import express from "express";
import ytdl, { videoInfo } from "ytdl-core";
import cors from "cors";
const route = express.Router();
route.get("/download", async (req, res) => {
  try {
    let link: any = req.query.link;
    res.header("Content-Disposition", 'attachment; filename="video.mp4');
    const str: any = "mp4";
    const id = ytdl.getVideoID(link);
    console.log(id);
    ytdl(`https://youtu.be/${id}`, {
      format: str,
      filter: "videoandaudio",
    }).pipe(res);
    res.send("ok");
  } catch (e) {
    console.log("error 1");
  }
});

route.post("/view", async (req, res) => {
  try {
    const link: any = req.body.link;
    console.log(link);
    const resp = await ytdl.getBasicInfo(link);

    res.send({
      iframe: resp.videoDetails.embed.iframeUrl,
      link: link,
    });
  } catch (error) {
    console.log("error");
  }
});

export default route;

`

**Comment by nukeop** [comment]
Also experiencing this in my project: https://github.com/nukeop/nuclear
