### ISSUE TITLE
Memory leak when calling ytdl.getInfo multiple times?

### ISSUE THREAD

**Issue by Yonle** [fent/node-ytdl-core#1181]
![Screenshot_2023_0119_074758](https://user-images.githubusercontent.com/63401712/213330223-c06329f7-1b50-4228-b057-499e3cbc0e48.png)

I am testing with this:
```
const ytdl = require("ytdl-core");

async function getInfo(id) {
  let info = await ytdl.getInfo(id);
  console.log("Got info for", id);

  getInfo(info.related_videos[0].id);

  let { rss, external } = process.memoryUsage();
  console.log((rss + external) / 1024 / 1024)
}

getInfo("VIDEO-ID")
```

Running:
```
"ytdl-core": "4.11.2"
```

With nodejs version:
```
v16.14.2
```

**Comment by TimeForANinja** [comment]
this is most likely caused by the build-in cache
https://github.com/fent/node-ytdl-core/blob/master/lib/cache.js
