### ISSUE TITLE
Bug audio download is corrupt

### ISSUE THREAD

**Issue by officialdittaz** [fent/node-ytdl-core#1184]
The file audio can't play

**Comment by Erozionn** [comment]
It appears to be happening on my end too. Stream will completely cut out at set time, everytime. No errors emitted either. Seems like the stream is left open is some weird state.

**Comment by officialdittaz** [comment]
> 

Can you fix it ?

**Comment by aymendps** [comment]
The same is happening to my discord music bot which used to play from youtube links / searches just fine. Since three days ago the stream started to cut out at a set time everytime, the url / song does not matter. No errors are emitted and the discord bot thinks it's still playing the stream just fine.

**Comment by aymendps** [comment]
> This issue appeared with the change of voice connection by discord (for more informations, I invite you to join the server of discord developers: https://discord.gg/discord-developers in the "api-annoucements" channel). For the moment there's any update from @discordjs/voice, as a temporary solution you can do this if you use the @discordjs/voice:
> 
> ```
> const { VoiceConnectionStatus } = require('@discordjs/voice');
> 
> connection.on('stateChange', (old_state, new_state) => {
>  if (old_state.status === VoiceConnectionStatus.Ready && new_state.status === VoiceConnectionStatus.Connecting) {
>   connection.configureNetworking();
>  }
> })
> ```
> 
> (You have to put this where you have the connection, more informations here: [discordjs/discord.js#9185](https://github.com/discordjs/discord.js/issues/9185))

This actually solves it in my case, even though some small stutter is noticeable at the time the stream used to cut out. thank you! My bad for not checking the new api announcements. I hope the maintainer(s) will consider adapting to the changes.

**Comment by hockeyduck3** [comment]
> > This issue appeared with the change of voice connection by discord (for more informations, I invite you to join the server of discord developers: https://discord.gg/discord-developers in the "api-annoucements" channel). For the moment there's any update from @discordjs/voice, as a temporary solution you can do this if you use the @discordjs/voice:
> > ```
> > const { VoiceConnectionStatus } = require('@discordjs/voice');
> > 
> > connection.on('stateChange', (old_state, new_state) => {
> >  if (old_state.status === VoiceConnectionStatus.Ready && new_state.status === VoiceConnectionStatus.Connecting) {
> >   connection.configureNetworking();
> >  }
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (You have to put this where you have the connection, more informations here: [discordjs/discord.js#9185](https://github.com/discordjs/discord.js/issues/9185))
> 
> This actually solves it in my case, even though some small stutter is noticeable at the time the stream used to cut out. thank you! My bad for not checking the new api announcements. I hope the maintainer(s) will consider adapting to the changes.

I tried this fix on my bot as well and luckily it works! But the stutter is a bit annoying to me. Is there any to fix the stutter?

**Comment by aymendps** [comment]
> > > This issue appeared with the change of voice connection by discord (for more informations, I invite you to join the server of discord developers: https://discord.gg/discord-developers in the "api-annoucements" channel). For the moment there's any update from @discordjs/voice, as a temporary solution you can do this if you use the @discordjs/voice:
> > > ```
> > > const { VoiceConnectionStatus } = require('@discordjs/voice');
> > > 
> > > connection.on('stateChange', (old_state, new_state) => {
> > >  if (old_state.status === VoiceConnectionStatus.Ready && new_state.status === VoiceConnectionStatus.Connecting) {
> > >   connection.configureNetworking();
> > >  }
> > > })
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > (You have to put this where you have the connection, more informations here: [discordjs/discord.js#9185](https://github.com/discordjs/discord.js/issues/9185))
> > 
> > 
> > This actually solves it in my case, even though some small stutter is noticeable at the time the stream used to cut out. thank you! My bad for not checking the new api announcements. I hope the maintainer(s) will consider adapting to the changes.
> 
> I tried this fix on my bot as well and luckily it works! But the stutter is a bit annoying to me. Is there any to fix the stutter?

I've added this block of code that I found in the discordjs issue mentioned above to the same listener function and it seemed to eliminate the stutter in my case:

```
    connection.on("stateChange", (oldState, newState) => {
      if (
        oldState.status === VoiceConnectionStatus.Ready &&
        newState.status === VoiceConnectionStatus.Connecting
      ) {
        connection.configureNetworking();
      }

      // Seems to eliminate some keepAlive timer that's making the bot auto-pause
      const oldNetworking = Reflect.get(oldState, "networking");
      const newNetworking = Reflect.get(newState, "networking");

      const networkStateChangeHandler = (
        oldNetworkState: any,
        newNetworkState: any
      ) => {
        const newUdp = Reflect.get(newNetworkState, "udp");
        clearInterval(newUdp?.keepAliveInterval);
      };

      oldNetworking?.off("stateChange", networkStateChangeHandler);
      newNetworking?.on("stateChange", networkStateChangeHandler);
    });
```

**Comment by hockeyduck3** [comment]
Thanks @aymendps! That got rid of my stutter as well 😄
