### ISSUE TITLE
how to use it react native ( is it possible cuz its all javascript ) ? 

### ISSUE THREAD

**Issue by Mohammad-DH** [fent/node-ytdl-core#1194]

**Comment by TimeForANinja** [comment]
even though it is javascript it uses a few node.js modules
some of those can be polyfilled, others (especially `vm`) not quite
so in the current form i'd say no

**Comment by warren-bank** [comment]
fwiw:
* [PR #1253](https://github.com/fent/node-ytdl-core/pull/1253) adds the tooling to bundle a browser build
* the [_browser-build_ branch of this forked repo](https://github.com/warren-bank/fork-node-ytdl-core/tree/browser-build) contains the code for the PR
  - the resulting JS bundle be [downloaded via CDN](https://cdn.jsdelivr.net/gh/warren-bank/fork-node-ytdl-core@browser-build/browser-build/dist/ytdl-core.js)
  - there are 2x userscript examples that demo its functionality:
    1. [without a proxy](https://cdn.jsdelivr.net/gh/warren-bank/fork-node-ytdl-core@browser-build/browser-build/example/ytdl-core.no-proxy.user.js)
       - only works on pages hosted by `youtube.com`
    3. [with a proxy](https://cdn.jsdelivr.net/gh/warren-bank/fork-node-ytdl-core@browser-build/browser-build/example/ytdl-core.with-proxy.user.js)
       - that only works on pages hosted by `example.com`
       - requires [manually acquiring temporary access to the _CORS Anywhere_ demo server](https://cors-anywhere.herokuapp.com/corsdemo)

**Comment by incidentist** [comment]
@warren-bank Thanks! Those links are currently incorrect. The correct URLs are:
core: https://cdn.jsdelivr.net/gh/warren-bank/fork-node-ytdl-core@browser-build/browser-build/dist/es2020/ytdl-core.js
without proxy: https://cdn.jsdelivr.net/gh/warren-bank/fork-node-ytdl-core@browser-build/browser-build/example/es2020/ytdl-core.no-proxy.user.js
with proxy: https://cdn.jsdelivr.net/gh/warren-bank/fork-node-ytdl-core@browser-build/browser-build/example/es2020/ytdl-core.with-proxy.user.js

For es5 versions, replace `es2020` with `es5`.
