### ISSUE TITLE
is there any doc for development , i was thinking about forking it ?

### ISSUE THREAD

**Issue by Mohammad-DH** [fent/node-ytdl-core#1196]
i want to update react-native-ytdl ( its been discontinued ) so i want to first understand the core , so plz if there is a doc for development or just simply explained about base code let me know 

// this is my first time trying to change a package base on my own needs

**Comment by TimeForANinja** [comment]
There's not a lot you have to do
* clone / fork the repo
* go into the library dir and run `npm install`
* before opening a pr run `npm run-script lint` and `npm run-script test`
