### ISSUE TITLE
Major bug in sig.js - ncode & decipher

### ISSUE THREAD

**Issue by milanbabiclibrafire** [fent/node-ytdl-core#1197]
"ytdl-core": "^4.11.3"

error:
- ... [])||(0,c[2])((0,c[45])((0,c[25])(c[21],c[55],(0,c[11] ... c[28])(c[56],c[50])};lma(ncode);
- SyntaxError: Missing catch or finally after try
- at new Script (node:vm:100:7)
- at Object.exports.decipherFormats (/app/node_modules/ytdl-core/lib/sig.js:116:51)

This happens a lot!

**Comment by piotrek-szczygiel** [comment]
Same error today, yesterday everything was working fine.

**Comment by ShantanuNair** [comment]
Also affected, starting today.

**Comment by javadjh** [comment]
i have same problem : 
0|app  | evalmachine.<anonymous>:25
0|app  | [])||(0,c[2])((0,c[45])((0,c[25])(c[21],c[55],(0,c[11])()),c[2],(0,c[86])(c[55],c[53]),c[13],c[77],c[27]),c[52],c[62],c[74]),1==c[43]&&((0,c[45])((0,c[2])((0,c[13])(c[65+Math.pow(3,2)%391],c[85]),c[78],c[35],c[68]),c[2],((0,c[76])(c[3],c[77]),c[40])(c[77]),c[40],c[87]),1)||(((((0,c[13])(c[87],c[65]),c[52])(c[46],c[Math.pow(5,3)%149+-51]),c[47])(c[63],c[1]),c[62])(c[50],c[18]),c[28])(c[56],c[50])};lma(ncode);
0|app  |
                                                                                                                                                                                                         ^
0|app  | SyntaxError: Missing catch or finally after try
0|app  |     at new Script (node:vm:100:7)
0|app  |     at Object.exports.decipherFormats (/root/youtube-downloader/backend/node_modules/ytdl-core/lib/sig.js:116:51)
0|app  |     at runMicrotasks (<anonymous>)
0|app  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|app  |     at async Promise.all (index 0)
0|app  |     at async exports.getInfo (/root/youtube-downloader/backend/node_modules/ytdl-core/lib/info.js:401:17)

**Comment by zniazi** [comment]
Same problem: 

evalmachine.<anonymous>:25
[])||(0,c[2])((0,c[45])((0,c[25])(c[21],c[55],(0,c[11])()),c[2],(0,c[86])(c[55],c[53]),c[13],c[77],c[27]),c[52],c[62],c[74]),1==c[43]&&((0,c[45])((0,c[2])((0,c[13])(c[65+Math.pow(3,2)%391],c[85]),c[78],c[35],c[68]),c[2],((0,c[76])(c[3],c[77]),c[40])(c[77]),c[40],c[87]),1)||(((((0,c[13])(c[87],c[65]),c[52])(c[46],c[Math.pow(5,3)%149+-51]),c[47])(c[63],c[1]),c[62])(c[50],c[18]),c[28])(c[56],c[50])};lma(ncode);
                                                                                                                                                                                                                                                                                                                                                                                                              ^

SyntaxError: Missing catch or finally after try
    at new Script (node:vm:100:7)
    at Object.exports.decipherFormats (/home/zniazi/programs/youtube/node_modules/ytdl-core/lib/sig.js:116:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async exports.getInfo (/home/zniazi/programs/youtube/node_modules/ytdl-core/lib/info.js:401:17)
Emitted 'error' event on PassThrough instance at:
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Yesterday was working fine

**Comment by moodejb123** [comment]
Yup same issue happening to me

**Comment by TheNicestDev** [comment]
I've been having the exact same problem for a few hours!

**Comment by cchen028** [comment]
4.9.1 verison still work for getting youtube info.

**Comment by javadjh** [comment]
> 4.9.1 verison still work for getting youtube info.

Thanks :)

**Comment by fakesamgregory** [comment]
Same issue. Downgrade works.

**Comment by parsaatef** [comment]
Same issue. Downgrade didn't work work for me

**Comment by parsaatef** [comment]
Can you also share your node version?

**Comment by ttrreevvoorr** [comment]
I am using node version `v16.17.0` and I downgraded ytdl-core to ^4.9.1 and the error stopped.

**Comment by rfcrocha** [comment]
i'm also having the issue and i can work around it with v4.9.1 and 4.10.0. One thing to add - this problem actually started yesterday for me although it was only a problem 10% of the time. Today it doesn't work at all with v=>4.11

**Comment by parsaatef** [comment]
it's wired. it didn't work for me even with Node v16.17.0 and downgraded ytdl-core to ^4.9.1

**Comment by devAshutoshkarn** [comment]
I have also face this issue today.

**Comment by fakesamgregory** [comment]
downgrade to 4.9.1 on node 19.6.1 worked for me

**Comment by Amatog94** [comment]
I get the same error since yesterday I think

**Comment by dim4ik1106** [comment]
I get the same error since yesterday I think, but downgrade helped

**Comment by TheGauntt** [comment]
Works (albeit slowly) with downgrade

**Comment by milanbabiclibrafire** [comment]
v4.10.0 for download video worked for some time. Now stopped working. @ShantanuNair - could you confirm this? (as you suggested working downgraded version)

**Comment by zachaxd** [comment]
v4.10 still works but super slow

**Comment by ShantanuNair** [comment]
@milanbabiclibrafire As you stated, it still works just is unusably slow. For serverless use cases, it's breaking. I haven't tested  if 4.9.1 is just as slow

**Comment by fpsone** [comment]
I'm using `@distube/ytdl-core@4.11.7` and it works smoothly.
This fork is optimized for distube package (discord.js music bot) so it works well with hls stream and opus stream. I haven't tested with other itag formats but it seems working normally.

**Comment by oskar2594** [comment]
It appears that the function in the base.js file of the YouTube Player is missing a catch block. To address this issue, I have created a workaround by adding the catch block when retrieving the function in the sig.js file. You can find the player script at https://www.youtube.com/s/player/7da8dd3e/player_ias.vflset/de_DE/base.js (Line 1457).

**Comment by Sansekai** [comment]
@fpsone thx work for me

while I have to use this library

**Comment by khlevon** [comment]
Hi guys, I found and fixed the problem. To test it, you can change the package source in your package.json to this until the maintainer merges my PR.
PR: https://github.com/fent/node-ytdl-core/pull/1203

```
"ytdl-core": "git+ssh://git@github.com:khlevon/node-ytdl-core.git#v4.11.3-patch.1"
```

**Comment by nukeop** [comment]
I think Yeah I think I'll just switch to this fork, ytsr is already a fork as well.

**Comment by nezort11** [comment]
This worked for me:
```json
"ytdl-core": "https://github.com/khlevon/node-ytdl-core.git#v4.11.3-patch.1"
```

**Comment by sajjadmrx** [comment]
this version worked:

`npm i ytdl-core@4.9.1`

**Comment by HerickSz** [comment]
this error is in the lib.
 try to get the lib in ytdl-core and replace.
link -> https://github.com/ShantanuNair/node-ytdl-core#v4.11.3-patch.1

**Comment by ahmedkh19** [comment]
> Anyone find a version to downgrade to that works?
> 
> EDIT: I created my own fork (in case the repo/branch went down) with @khlevon's changes applied. In my package.json I have:
> 
> ```
> "ytdl-core": "https://github.com/ShantanuNair/node-ytdl-core#v4.11.3-patch.1"
> ```
> 
> which is the exact same as @khlevon's `"ytdl-core": "https://github.com/khlevon/node-ytdl-core.git#v4.11.3-patch.1"`
> 
> Working branches if you want to downgrade instead of use the patch on v4.11.3:
> 
> * 4.10.0 @ShantanuNair but SLOW
> * 4.9.1 @cchen028 for metadata retrieval

Thanks! your patch is working very well

**Comment by dim4ik1106** [comment]
Im still facing this issue, even with path from @khlevon and with v4.11.4
evalmachine.<anonymous>:24
c[74]),c[64])((0,c[25])(c[24],c[41]),c[35],c[33+Math.pow(8,3)%229],c[92]),c[70])(c[87],c[27])}try{8>=c[92]&&(0,c[15])((0,c[35])(c[36],c[20]),c[11],c[29])}catch(d){(0,c[60])(c[92],c[93])}try{1>c[45]?((0,c[60])(c[2],c[93]),c[60])(c[91],c[93]):((0,c[88])(c[93],c[86]),c[11])(c[57])}catch(d){(0,c[85])((0,c[80])(),c[56],c[0])}};qma(ncode);
                                                                                                                                                                                                                                                                                                                                  ^

SyntaxError: Missing catch or finally after try
    at new Script (node:vm:100:7)
    at exports.decipherFormats (/Users/kashenko/Sites/SpeechToTextApp/node_modules/ytdl-core/lib/sig.js:116:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async exports.getInfo (/Users/kashenko/Sites/SpeechToTextApp/node_modules/ytdl-core/lib/info.js:402:19)
/Users/kashenko/Sites/SpeechToTextApp/node_modules/ytdl-core/lib/format-utils.js:168
    throw Error(`No such format found: ${quality}`);
          ^

Error: No such format found: highestaudio
    at exports.chooseFormat (/Users/kashenko/Sites/SpeechToTextApp/node_modules/ytdl-core/lib/format-utils.js:168:11)
    at downloadFromInfoCallback (/Users/kashenko/Sites/SpeechToTextApp/node_modules/ytdl-core/lib/index.js:86:26)
    at /Users/kashenko/Sites/SpeechToTextApp/node_modules/ytdl-core/lib/index.js:20:5
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on PassThrough instance at:
    at downloadFromInfoCallback (/Users/kashenko/Sites/SpeechToTextApp/node_modules/ytdl-core/lib/index.js:88:12)
    at /Users/kashenko/Sites/SpeechToTextApp/node_modules/ytdl-core/lib/index.js:20:5
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.0.0

**Comment by TheGauntt** [comment]
Working with `ytdl-core@4.10.0`

Seeing the same with latest:
```SyntaxError: Missing catch or finally after try```

**Comment by TheGauntt** [comment]
@dim4ik1106 Tracked here BTW - https://github.com/fent/node-ytdl-core/issues/1216

**Comment by dim4ik1106** [comment]
> @dim4ik1106 Tracked here BTW - #1216

thx

**Comment by cybervaldez** [comment]
Seeing the same issue on 4.11.5

**Comment by fpsone** [comment]
https://github.com/fent/node-ytdl-core/issues/1197#issuecomment-1499179175
> I'm using `@distube/ytdl-core@4.11.7` and it works smoothly. This fork is optimized for distube package (discord.js music bot) so it works well with hls stream and opus stream. I haven't tested with other itag formats but it seems working normally.

I still using this fork and it works normally. Btw, at the present, the latest version is `@distube/ytdl-core@4.11.17`
