### ISSUE TITLE
Missing catch or finally after try

### ISSUE THREAD

**Issue by aymenitc** [fent/node-ytdl-core#1198]
I'm using latest 4.11.3
It was working fine last night.
Today I have this error:
```
Missing catch or finally after try
```
I downgraded to 4.11.2 and .4.11.1 which gives the same error.
4.11.0 give another different error

**Comment by TheNicestDev** [comment]
I've been having the exact same problem for a few hours!

**Comment by TheNicestDev** [comment]
https://github.com/fent/node-ytdl-core/issues/1197

**Comment by moon91210** [comment]
Same here! Just happened, was working fine earlier today.

**Comment by ShantanuNair** [comment]
Duplicate of https://github.com/fent/node-ytdl-core/issues/1197

**Comment by salahmedamin** [comment]
was working earlier this week, getting same error now

**Comment by sjasik** [comment]
Same here, is there any immediate fix for this?

**Comment by aymenitc** [comment]
4.10.0 is working

**Comment by tomasXwhite** [comment]
Someone could find the solution? 4.10.0 is working veery slow

**Comment by TimeForANinja** [comment]
closing as dup

**Comment by zyrostran** [comment]
too

**Comment by tomasXwhite** [comment]
> 4.10.0 is working but it is slow

Now it isnt working anymore. Anyone found a solution?
