### ISSUE TITLE
Missing catch or finally after try

### ISSUE THREAD

**Issue by darkdeathoriginal** [fent/node-ytdl-core#1207]
It is showing Missing catch or finally after try even tho i am not using try.

**Comment by ItsPerona** [comment]
Correct, I have the same problem and I did not modify anything in the package.

**Comment by ItsPerona** [comment]
Downgrade to 4.9.1 temporaly. 
`npm i ytdl-core@4.9.1`

**Comment by ShlomoCode** [comment]
Duplicate: https://github.com/fent/node-ytdl-core/issues/1204

**Comment by ShlomoCode** [comment]
> Downgrade to 4.9.1 temporaly. `npm i ytdl-core@4.9.1`

This fixes the error, but the download slows down terribly!

**Comment by jnomikos** [comment]
This broke my bot, but downgrading fixed it

**Comment by hugoderre** [comment]
> > Downgrade to 4.9.1 temporaly. `npm i ytdl-core@4.9.1`
> 
> This fixes the error, but the download slows down terribly! See [#1204 (comment)](https://github.com/fent/node-ytdl-core/issues/1204#issuecomment-1501202288) for a better solution

This solution is better thank you!
