### ISSUE TITLE
I'll get this error

### ISSUE THREAD

**Issue by solcabz** [fent/node-ytdl-core#1208]
getting this error down know why

evalmachine.<anonymous>:25
[])||(0,c[2])((0,c[45])((0,c[25])(c[21],c[55],(0,c[11])()),c[2],(0,c[86])(c[55],c[53]),c[13],c[77],c[27]),c[52],c[62],c[74]),1==c[43]&&((0,c[45])((0,c[2])((0,c[13])(c[65+Math.pow(3,2)%391],c[85]),c[78],c[35],c[68]),c[2],((0,c[76])(c[3],c[77]),c[40])(c[77]),c[40],c[87]),1)||(((((0,c[13])(c[87],c[65]),c[52])(c[46],c[Math.pow(5,3)%149+-51]),c[47])(c[63],c[1]),c[62])(c[50],c[18]),c[28])(c[56],c[50])};lma(ncode);

            ^

SyntaxError: Missing catch or finally after try
    at new Script (node:vm:100:7)
    at exports.decipherFormats (C:\Users\PC1\Desktop\IconiqYTDownloader\youtubeDLIconiq\node_modules\ytdl-core\lib\sig.js:116:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async exports.getInfo (C:\Users\PC1\Desktop\IconiqYTDownloader\youtubeDLIconiq\node_modules\ytdl-core\lib\info.js:401:17)
Emitted 'error' event on PassThrough instance at:
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Anket11** [comment]
Duplicate: https://github.com/fent/node-ytdl-core/issues/1197
Solution:

1. Downgrade to 4.9.1 temporarily.
   `npm i ytdl-core@4.9.1`
2. Use this patch instead.
    "ytdl-core": "https://github.com/khlevon/node-ytdl-core.git#v4.11.3-patch.1"

**Comment by SantaBoost** [comment]
Hello

> Duplicate: #1197
> 
> Solution:
> 
> 1. Downgrade to 4.9.1 temporarily.
>    `npm i ytdl-core@4.9.1`
> 2. Use this patch instead.
>    "ytdl-core": "https://github.com/khlevon/node-ytdl-core.git#v4.11.3-patch.1"

hello I am another user who issusing the same problem, I tried using your link and it send me to the normal page is there anything special I need to do there? or does the patch means update it to the latest version?

**Comment by solcabz** [comment]
i did downgrade it 4.9.1 seems theres a bug to the sig,js and info.js of
ytdl-core

**Comment by Anket11** [comment]
Easiest fix would be replace that line in package.json and install libraries.
