### ISSUE TITLE
call to getInfo() might result in surprising exception being thrown

### ISSUE THREAD

**Issue by azrafe7** [fent/node-ytdl-core#121]
Not sure if this should be fixed somehow, but thought I'd report it anyway (as a heads-up)... :stuck_out_tongue: 

Using `getInfo()` would _force_ you to wrap the call in a try/catch block, as the [inner call](https://github.com/fent/node-ytdl-core/blob/e24253e3c031467593b6c8eeb12ac37260585966/lib/info.js#L47) to `getVideoID()` [might throw](https://github.com/fent/node-ytdl-core/blob/23e6436c30e449c5a4cd324d6da494096d8a1ba5/lib/util.js#L236-L241) an `Error` if no id is found.

Now - especially when using the promisified version - this behaviour might be surpising from a user point of view, which probably expects to grab the error in a `.catch()` statement.

**Comment by fent** [comment]
It was originally made that way because I compared it to how other native js functions handle bad parameters. But it does make sense, since this is an async function, to pass the error to the callback or the promise. Rather than having the user check two places.

**Comment by ChingChang9** [comment]
I'm facing this issue on `v4.3.0` when the input is not a youtube link. When I call
```js
ytdl.getInfo("https://github.com").catch(error => console.log(error));
```
The catch block doesn't seem to catch anything and I get an error from the parent function instead
