### ISSUE TITLE
Unable to resolve module stream

### ISSUE THREAD

**Issue by shivampandey551** [fent/node-ytdl-core#1229]
I am trying to add this package in react-native project.
Getting this error when added the package "yarn add ytdl-core@latest"

![simulator_screenshot_A9036008-78BD-4D96-8D8D-B32B868E2ABF](https://github.com/fent/node-ytdl-core/assets/131258242/7e9a5a65-4012-467b-884b-76f54220e10b)

Can anyone please help me resolve the error.

Thanks

**Comment by nukeop** [comment]
Try configuring it like this:

```typescript
resolver: {
  extraNodeModules: {
      stream: require.resolve('readable-stream')
  }
},
```

**Comment by TimeForANinja** [comment]
closing this since react is outside of support scope
