### ISSUE TITLE
ECONNRESET error

### ISSUE THREAD

**Issue by Wodki** [fent/node-ytdl-core#123]
Okay so when I use `yt.getInfo(args, (err, info) => ` I get the error below
![screensho](https://cloud.githubusercontent.com/assets/26030259/23723610/81b4a4b8-0452-11e7-91cf-7e10dd560ebf.png)

**Comment by FireController1847** [comment]
Can also report this issue. Happens randomly through playback, just started happening recently. I've always had this with connection loss, but the bot is currently not losing connection and it's just happening while the song was playing fine.

**Comment by FireController1847** [comment]
Nevermind, this is a separate issue. #81 is actually the issue I'm getting.

**Comment by iCrawl** [comment]
This issue is not related to ytdl-core. You simply lost connection to the discord websocket in whatever library you use.

**Comment by fent** [comment]
Yeah.. `url: 'wss://eu-central475.discord.gg',`
