### ISSUE TITLE
Download videos consecutively

### ISSUE THREAD

**Issue by Creative-Difficulty** [fent/node-ytdl-core#1236]
Im trying to iterate over an array of youtube video IDs and download each one to a folder. My current code looks something like this:
```ts
videoIDsToDownload.forEach(async videoIDToDownload => {
    await new Promise<void>(async (resolve) => {
            const rawVideoURL = `https://www.youtube.com/watch?v=${videoIDToDownload}`;
            let videoInfo = await ytdl.getInfo(videoIDToDownload);
            console.log(`Downloading video: ${videoInfo.videoDetails.title}`);
            const videoDir = path.join("C:", "test", "channelll", `${videoInfo.videoDetails.title.replace(/[/\\?%*:|"<>]/g, '-')}.mp4`);
            ytdl(rawVideoURL, { filter: 'audioandvideo', quality: 'highestvideo' }).pipe(fs.createWriteStream(videoDir)).on('close', () => {
                resolve(); // finish
            })
        })
});
```
However this downloads all videos at once and eventually throws a `410` (deleted) status code for some reason:
```ts
MinigetError: Status code: 410
    at ClientRequest.<anonymous> (Project_folder\node_modules\miniget\dist\index.js:206:27)
    at Object.onceWrapper (node:events:652:26)
    at ClientRequest.emit (node:events:537:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:642:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:505:22)
    at TLSSocket.emit (node:events:537:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  statusCode: 410
}
```
I dont know why, and in my opinion it would be much smarter to write this library async from the beginning. But ok, pls somebody help me.

**Comment by Creative-Difficulty** [comment]
@fent This is VERY URGENT

**Comment by TimeForANinja** [comment]
listening for the error event and handling it accordingly should resolve your problem

**Comment by Creative-Difficulty** [comment]
> listening for the error event and handling it accordingly should resolve your problem this is in no way urgent

pls provide example

**Comment by Fyphen1223** [comment]
This might be an error that caused by calling too many download request, in my opinion.

**Comment by Creative-Difficulty** [comment]
But it isnt downloading any videos. Please help me

**Comment by TimeForANinja** [comment]
a) if you want to download in seriel instead of parallel you should find resources for that on the web

b) listening for error events:
```js
const stream = ytdl('<some url or id>')
stream.on('error', e => {
  console.error(e);
});
```

**Comment by Creative-Difficulty** [comment]
> 

THERE ARE NO RESOURCES for this on the web. I have been searching for multiple weeks, but have not found any working solutions, PLEASE provide a working solution.

**Comment by Creative-Difficulty** [comment]
@TimeForANinja THIS IS NOT SOLVED please help
