### ISSUE TITLE
Cannot download specific YouTube video

### ISSUE THREAD

**Issue by Fyphen1223** [fent/node-ytdl-core#1238]
## Cannot download specific YouTube video
such as [https://www.youtube.com/watch?v=qlinKNqHCyg&pp=ygUPdG9idSBpbmZlY3Rpb3Vz]

Error Message:

```
 Error: No such format found: highest
    at exports.chooseFormat (/node_modules/ytdl-core/lib/format-utils.js:168:11)
    at downloadFromInfoCallback (/node_modules/ytdl-core/lib/index.js:86:26)
    at /node_modules/ytdl-core/lib/index.js:20:5
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

Thanks,

**Comment by jakubfalkiewicz** [comment]
can you provide some code? The url works fine for me

**Comment by Fyphen1223** [comment]
Sorry i missed the link

https://music.youtube.com/watch?v=pOeWEMTKYxI

This won't work

**Comment by TimeForANinja** [comment]
how exactly are you calling ytdl-core?

**Comment by Fyphen1223** [comment]
I'm calling this;

```js
    downloadRaw = function (url) {
        const stream = ytdl(ytdl.getURLVideoID(url), {
            filter: format => format.audioCodec === 'opus' && format.container === 'webm',
            //quality: 'audioonly',
            highWaterMark: 16 * 1024 * 1024
        });
        return stream;
    }
```

**Comment by Fyphen1223** [comment]
is the way to call ytdl affect the issue?

**Comment by TimeForANinja** [comment]
You do filtering and the above error also appears when you filter out all formats 😉 
so youtube simply doesn't provide webm w. opus for the requested video
should maybe add another error directly after filtering... 🤷

**Comment by Fyphen1223** [comment]
ohhhhh ahhh I see
then if i need webm format and opus codec, I have to use ffmpeg libraries such as prism-media to convert them to webm opus?

**Comment by TimeForANinja** [comment]
not sure what prism-media does exactly but in general yes

**Comment by Fyphen1223** [comment]
oh ok thank you so much
