### ISSUE TITLE
Random end of stream

### ISSUE THREAD

**Issue by theoaker** [fent/node-ytdl-core#124]
I have been using node-ytdl-core for more than two months now and the past few days I am getting a sudden end of stream. The yt song stops playing, for no reason, no errors or anything, just stops sending the data, it only happens with some specific songs though which didn't happen to a few days ago.

**Comment by TimeForANinja** [comment]
Having the same problem
Only happening when stream is getting "throttled", so not like `fs.createWriteStream('file')` but sth like `.pipe(ffmpeg)`
also tracked the 'close' all the way to index.js L115's res closing before finishing

**Comment by fent** [comment]
This looks to be the same issue as #81 

Let's keep discussion in one place.
