### ISSUE TITLE
Downloading way slower than usual

### ISSUE THREAD

**Issue by erturkdotgg** [fent/node-ytdl-core#1240]
Ytdl core is working so slow since last 2 days. Its downloading files very very slow. 

Many people are also experiencing same issue at the ytdl-core discord server. Need a fix right now.

**Comment by endblack** [comment]
Também estou com o mesmo problema

**Comment by nextpier** [comment]
Same for me...

**Comment by yyildiz** [comment]
We've been experiencing this issue for the past two days now.

**Comment by gathilas** [comment]
This is happening to me too. Slow is kind of an understatement, it can take hours to download a video and a lot of times it'll just stop downloading all together.

**Comment by supun-adithya** [comment]
same for me

**Comment by matthewredmongross** [comment]
same

**Comment by chenaaron3** [comment]
Seeing problems with this too. My lambda functions are timing out.

**Comment by gatecrasher777** [comment]
I've picked up, in another project, that there is in the past 24 hours, a syntax error in extracting the n-transform function.  You will always get very slow speeds without the n-transform working properly. Will try to trace the problem today.

**Comment by preetam52c** [comment]
ytdl-core downloading video very slowly. We are facing major issue for this. Does anyone fond any solution? It's taking hours to download. Please fix it. 🙏🏼

**Comment by gatecrasher777** [comment]
line 59 in sig.js
```javascript
  if (functionName.includes('[')) functionName = utils.between(body, `${functionName.split('[')[0]}=[`, `]`);
```

needs to be 
```javascript
  if (functionName.includes('[')) functionName = utils.between(body, `var ${functionName.split('[')[0]}=[`, `]`);
```
Because if other functions end in the same character sequence it fails to find the correct function. In this case, the functionName was "ata" and there is a bunch of other functions called "Data"

**Comment by chenaaron3** [comment]
lgtm, can we publish this to a new version?

**Comment by nextpier** [comment]
@gatecrasher777  thank you. It works fine

**Comment by gatecrasher777** [comment]
```
  "dependencies": {
    "ytdl-core": "github:gatecrasher777/node-ytdl-core#master"
  }
```
@nextpier 
Tested this and it seems to work. 
May have to delete ```package-lock.json``` and ```node-modules``` folder. 
Then run ```npm install.``` 
Then revert back to version number if/when the PR is merged.

**Comment by endblack** [comment]
> 

This really worked, thank you very much.

**Comment by TimeForANinja** [comment]
Closed with the merge of https://github.com/fent/node-ytdl-core/pull/1242
let's say poorly maintained and not "no longer mantained" 😉
