### ISSUE TITLE
FFMPEG Get FileStream rather than writing straight to a file

### ISSUE THREAD

**Issue by UtterDonkey** [fent/node-ytdl-core#1274]
Using the FFMPEG example, is it possible to get a readable stream rather than immediately writing the output to a file?

**Comment by TimeForANinja** [comment]
```js
const ytdl = require('ytdl-core');
const ref = 'https://www.youtube.com/watch?v=aqz-KE-bpKQ';
// Get audio and video streams
const audio = ytdl(ref, { quality: 'highestaudio' })
const video = ytdl(ref, { quality: 'highestvideo' })
```

**Comment by UtterDonkey** [comment]
I want to combine the audio and video streams using FFMPEG, like in the FFMPEG example, but get a readable stream instead of FFMPEG writing it straight to a file.
