### ISSUE TITLE
Playlist support

### ISSUE THREAD

**Issue by dasmikko** [fent/node-ytdl-core#13]
Are there any possibility for playlist support?

**Comment by trustedtomato** [comment]
The v3 of the YouTube API requires an API key. Would it be possible to get the playlist items without it?

**Comment by TimeForANinja** [comment]
theres at least one packet on npm that allows u to do that
i guess it wont get added to ytdl in the near future

**Comment by trustedtomato** [comment]
I only saw one which parses the playlist page and gets the titles from their visible locations, so it only gets the first 100 video & it doesn't seem to be well maintained. 

The other packages (which I saw) require API key.

**Comment by TimeForANinja** [comment]
Check mine,  works with more then 100 but ull have to live with scraping
