### ISSUE TITLE
ERROR in ./~/ytdl-core/test/html5player.json

### ISSUE THREAD

**Issue by shanethmoore** [fent/node-ytdl-core#130]
Looks like this was introduced in https://github.com/fent/node-ytdl-core/releases/tag/v0.9.2

It seems that the sig.js file in `lib` is referencing a file in `test`. https://github.com/fent/node-ytdl-core/blob/master/lib/sig.js#L38

When I install the package locally and then try to interact with the lib or compile it, I get the error. 

```
ERROR in ./~/ytdl-core/test/html5player.json
Module build failed: Error: ENOENT: no such file or directory, open '/Users/shane/*******/node_modules/ytdl-core/test/html5player.json'
    at Error (native)
 @ ./~/ytdl-core/lib/sig.js 38:28-63
 @ ./~/ytdl-core/lib/info.js
 @ ./~/ytdl-core/lib/index.js
```

**Comment by shanethmoore** [comment]
Personally I think its OK for test to reference core JS files, but not vice versa. Core module's being dependent on test dependencies seems like something of an anti-pattern.

The right solution would be to have these teased out, but in the interim, I've opened up a PR to allow the test directory in the bundled package https://github.com/fent/node-ytdl-core/pull/131

**Comment by fent** [comment]
It is an anti-pattern. I added that code a few years ago when I was having a hard time keeping track of all the changes to the html5player file. I think it's safe to remove now. And anyway I think a better solution for debugging would be to record all requests not just that one.

But I can do that later. I'll accept your PR.

**Comment by shanethmoore** [comment]
@fent One last thing I just discovered worth noting 😅 

If installing this package with yarn instead of npm, the test directory will automatically be ignored.
