### ISSUE TITLE
Pausing Terminates Buffer

### ISSUE THREAD

**Issue by FireController1847** [fent/node-ytdl-core#132]
I've had issues on Discord.js (It's not a Discord.js issue, since other yt downloaders do not get this error) where the stream ends with reason, "Stream is not generating quickly enough." It seems that people have narrowed it down to pausing. Not sure if you want to work _with_ Discord.js or not, all I know is that it terminates the buffer on pause. https://github.com/hydrabolt/discord.js/issues/1225#issuecomment-285088057

**Comment by fent** [comment]
> It's not a Discord.js issue, since other yt downloaders do not get this error

I didn't see this mentioned in the d.js issue. Could I see an example?

**Comment by FireController1847** [comment]
Mentioned here. Not sure about an example, just heard it and thought I'd report it. 

"the issue is the pausing, it causes the buffer to terminate if used with ytdl, Cant say ive looked into what causes this but ive known of this issue for a long time now"

**Comment by CrimsonXV** [comment]
Try download the song first, or use TimeForANinja's fork, which supposedly works better with things like Discord.JS.

**Comment by fent** [comment]
> "the issue is the pausing, it causes the buffer to terminate if used with ytdl, Cant say ive looked into what causes this but ive known of this issue for a long time now"

That doesn't mention that they tried other yt downloaders, or other sources of voice media though.

Anyway, this might just be an issue with ytdl-core, in that pausing the download halfway will either delay it or disconnect it. I'll see what I can do to test for it.

**Comment by CrimsonXV** [comment]
Downloading the files rather than streaming directly with ytdl-core seems one way to improve reliability much more, I've noticed a lot less issues using the former.

**Comment by TimeForANinja** [comment]
ye

**Comment by fent** [comment]
With the new econnreset fix, I tested pausing a video halfway for several minutes. Before the fix, resuming the video would sometimes econnreset or end the video, but I did not experience it hanging and clearing the buffer. Please test this issue again with the newest version.

**Comment by FireController1847** [comment]
I'm getting a "The stream is not generating quickly enough" without pausing, as well.

**Comment by fent** [comment]
See the latest comment on the econnreset issue

https://github.com/fent/node-ytdl-core/issues/81#issuecomment-292766492
