### ISSUE TITLE
ENOENT: no such file or directory - error

### ISSUE THREAD

**Issue by MatisiekPL** [fent/node-ytdl-core#133]
Hello, I have a problem with my script:
`ytdl.getInfo('https://www.youtube.com/watch?v=' + value['id'], {}, function(err, response) {
				console.log("Downloading file called: " + response['title']);
				
				ytdl('https://www.youtube.com/watch?v=' + value['id'])
					.pipe(fs.createWriteStream(response['title'] + '.flv'))
					.on('response', function(res) {
						console.log(JSON.stringify(res));
					});
						
			});`

When I run app system shows randomly error:
`ENOENT: no such file or directory, open...`

What should I do to resolve this error?

**Comment by CrimsonXV** [comment]
Try specify a path explicitly. E.g. if on Linux: "/home/<user>/video.flv"

**Comment by fent** [comment]
Maybe the video title contains folder separator characters. But anyway... this isn't an issue with ytdl.
