### ISSUE TITLE
getInfo doesn't work on videos with age restrictions

### ISSUE THREAD

**Issue by CrimsonXV** [fent/node-ytdl-core#135]
Returns a content warning error.

**Comment by fent** [comment]
There's a [test file](https://github.com/fent/node-ytdl-core/blob/master/test/irl-test.js) with an age restricted video that tests this. And I just successfully ran it.

What video did this happen on for you?

**Comment by TimeForANinja** [comment]
Was the error message in english or was the content warning in some different language?

**Comment by CrimsonXV** [comment]
It was in French

**Comment by TimeForANinja** [comment]
Then its a known but sadly unsolved problem #134

**Comment by fent** [comment]
Ah yeah, if that's the case, let's keep it to one issue.
