### ISSUE TITLE
Not downloadable video

### ISSUE THREAD

**Issue by kale20** [fent/node-ytdl-core#136]
Hello
I use always node-ytdl-core, 

Previously version,
Request URL:
add title query  to url of source  -> &title=blabla.mp4 
Response :
*.googlevideo.com -> response -> Header "attachment;filename=blabla.mp4"

But **now** not downloadable this video. Only watching this video. Don't response "attachment-file " header on Youtube.

Thank you

**Comment by fent** [comment]
I'm not sure what the issue is. Could you post a code snippet or the stack trace?
