### ISSUE TITLE
Content-Length is with range setting smaller than the file really is.

### ISSUE THREAD

**Issue by MJunghenn** [fent/node-ytdl-core#138]
If i'm using the range option ({range: "x-xx"}) to load a part of a video the "response" event will fire a smaller "content-length" than the file really is. It's also not the chunksize. ;-) 

If i try the same video (every video) without the range option i get the correct content-length in the "response" event. 

Did you have an idea how to fix that?

**Comment by fent** [comment]
By smaller "content-length", do you mean the new length is the actual video size - the starting range, or ending range - starting range?

Or is it some other length? If it's the former, wouldn't that be expected?

If your goal is to continue a download, there's a PR for it that keeps track of progress too: https://github.com/fent/node-ytdl-core/pull/128

**Comment by MJunghenn** [comment]
My goal is it to partial stream the video into a video player. 

I found out now that the content-length header on the response event will substract the start range bytes from the original filesize. 

So if you load a 4000kb file and request the range 1000-1500 you will get 3000kb as content-length instead of 4000kb. 

The problem is that we need the full filesize, otherway you will load a range of 
2500-3000 and will get a content-length of 1500kb.
That will confuse any player because you cant load the 2500kb-3000kb from a 1500kb file. 

You know what i mean?

**Comment by MJunghenn** [comment]
Here is my workaround for that (Underscore.JS needed):

`
settings = {range: 'xxxx-xxxxx', }

ytdl("http://...../watch?v=....", settings)
.on('response', (response) => {
        
        if(!_.isUndefined(response.headers['content-length'])) {
          
          let totalSize = parseInt(response.headers['content-length'], 10);
          if(!_.isUndefined(settings.range)) { 
            
            let parts = settings.range.split("-");
            let partialstart = parts[0];
            let partialend = parts[1] || false;
            
            
            let start = parseInt(partialstart, 10);
            //Temporary fix for wrong content-length
            if(start != 0) {
              
              totalSize += start;
            }
            let end = partialend ? parseInt(partialend, 10) : totalSize - 1;
            let chunksize = (end - start) + 1;
            
            if(start <= totalSize) {
              
              res.writeHead(206, {            
                'Content-Range': 'bytes ' + start + '-' + end + '/' + totalSize,
                'Accept-Ranges': 'bytes',
                'Content-Length': chunksize,
                'Content-Type': 'video/mp4'
              });
            } else {
              
              res.writeHead(416, {});
            }
          } else {
            
            res.writeHead(200, {
              'Content-Length': totalSize,
            });
          }
        }
      })`

**Comment by fent** [comment]
That's interesting. But anyway, the reconnect PR should fix that too, it looks at the smallest out of `content-length` and `range.end - range.start`.

**Comment by fent** [comment]
> So if you load a 4000kb file and request the range 1000-1500 you will get 3000kb as content-length instead of 4000kb.

Does this mean that it ignores the `end` of the range? So instead of `500` for the `content-length` it will give `3000`?

**Comment by MJunghenn** [comment]
That's not the thing. 

The thing is if we use the range option in ytdl-node it seems that the "response" event returns exactly the Filesize - {Start Bytes from range} as "Content-Length" header. Maybe youtube returns that. 

To redirect the received byte range to a Browser/Video player we need to set the header
"Content-Range": "{StartByte}-{EndByte}/{Fullfilesize}"
And in this case we don't get the full filesize. We get the Fullfilesize - StartByte from the ytdl-node response event.

I have not looked into the ytdl-node source at that event, but maybe youtube creates a partial file from the original file for that request and starts from the received startbytes to end and responsed with that filelength. That would explain the issue.

**Comment by fent** [comment]
I'm not sure I can help here since short of making another request to YouTube without range, there's no way to get the full `content-length`.
