### ISSUE TITLE
Thumbnail_url ridiculously small, no other thumbnail available.

### ISSUE THREAD

**Issue by FireController1847** [fent/node-ytdl-core#141]
There used to be three values for thumbnails, iurlhq, iurlmq, and idk about iurllq. Now, there's only one that I can find, which is very, very low quality, essentially making it useless. Only fix I've found is changing it from default.jpg to hqdefault.jpg

```javascript
info.thumbnail_url.replace("default.jpg", "hqdefault.jpg")
```

**Comment by iCrawl** [comment]
I don't think this will work on every video.
When I built that function into my bot I basically just went with `https://img.youtube.com/vi/${this.id}/mqdefault.jpg` since older videos do not have a `hqdefault.jpg` only mqdefault, so old videos were not able to retrieve a HQ thumbnail.

**Comment by FireController1847** [comment]
@iCrawl That's interesting, did not know that.

**Comment by fent** [comment]
What old videos have you tested where it doesn't work? I'm testing with both domains `img.youtube.com` and `i.ytimg.com` and haven't ran into one without a `hqdefault.jpg`, but a lot don't have `maxresdefault.jpg`

https://i.ytimg.com/vi/dMH0bHeiRNg/hqdefault.jpg

**Comment by iCrawl** [comment]
Oh. I see.
I might have been going with the maxresdefault because I assumed you'd just get whatever is available in the highest res available. 🤔 

I did some more tests (~50 videos), all get a result with hqdefault.jpg, I guess that means this is good to go.

**Comment by FireController1847** [comment]
Was this reversed at any point? The URL's are no longer available in the info.
