### ISSUE TITLE
dispatcher.end not ending/unlocking the file for edit

### ISSUE THREAD

**Issue by godleydemon** [fent/node-ytdl-core#146]
[javascript index.js](https://hastebin.com/oluyuwesol.php)

So the problem I'm currently having is when !prefix music stop is called, it's sending the dispatch.end event correctly it seems like. Since it does stop the playfile to the discord server, but it doesn't unlock the file. So I can't remove it with the fs unlink event that's called from my if dispatcher.on('end', () => event.  Don't know if this is an issue with ytdl, youtube-dl or fs to be honest. But if I add in the fs unlink event in the stop command the bot on discord will crash instead, since it's saying the file is locked. 

---
what console is outputting on the crash after trying to remove with fs
`[09:00:32] { Error: EPERM: operation not permitted, open 'C:\Users\Work2\Desktop
\Athena\music\music.flv'
    at Error (native)
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Work2\\Desktop\\Athena\\music\\music.flv' }`

**Comment by TimeForANinja** [comment]
That issue is on you,
it can't unlink a file ytdl is still writing to.
You have to also stop the ytdl stream before u unlink the file.
Consider just playing the stream and u won't have to unlink/end the download...

**Comment by godleydemon** [comment]
@TimeForANinja I'm trying to create a stop command so I need to end the ytdl stream. Apparently I'm not sending the right thing?

**Comment by fent** [comment]
This uses youtube-dl not ytdl.
