### ISSUE TITLE
Change language?

### ISSUE THREAD

**Issue by FireController1847** [fent/node-ytdl-core#150]
I'm currently having an issue, because my server is in a 'spanish' region, all of my errors and stuff is coming up in spanish. How do I fix this without using a different module to translate it back to English?

![Example](https://img.visual-fire.com/gfyvt.png)

**Comment by TimeForANinja** [comment]
u can modify all request url's to include `hl=en` in the query...

**Comment by fent** [comment]
Do you have an example of that @TimeForANinja ?

**Comment by briantanner** [comment]
Same issue, and same question as fent, have tried this without much success so far @TimeForANinja

**Comment by briantanner** [comment]
Sorry for the mention, I got it working by appending `hl=en` to the video url and embed url in `lib/info.js`

**Comment by FireController1847** [comment]
@briantanner So it'd just be `https://www.youtube.com/watch?v=QG8Zs-iskfs?hl=en`? So I'm just appending `?hl=en` to the end of the video link.

**Comment by TimeForANinja** [comment]
Sry wasn't around...
U die what i meant thou ^^
