### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by vyky** [fent/node-ytdl-core#151]
Hi nice library

For some reason I can't stram video from server. I need download link

I try example info.js and get info.json but I cant find download link

I assume it is `formats[i].url` but I can't download either from browser or wget

Any clue?

Thanks

**Comment by fent** [comment]
Please look at the first example in the readme.

**Comment by vyky** [comment]
Yes I did try that. It download video to node directory. What I mean is download link so that I can stream/download from other device without having to download first on node server or create file on server

**Comment by fent** [comment]
Yes that is in the format object as the `url` property.

**Comment by vyky** [comment]
But when I simply download with

```
wget "https://r2---sn-2uuxa3vh-jcoe.googlevideo.com/videoplayback?source=youtube&pcm2cms=yes&ratebypass=yes&dur=190.055&lmt=1472145955212339&ei=DMUPWarVBMHqogOEuIGwAw&ms=au&ipbits=0&mv=m&pl=21&ip=0.0.0.0&id=o-AJyUAvI9Dc4oBY05Rdopo261TeK8VNR4DyuNPRNZZF4p&mm=31&expire=1494227308&itag=22&upn=Zi0WUJGunSA&mt=1494205643&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&initcwndbps=1712500&mn=sn-2uuxa3vh-jcoe&mime=video%2Fmp4&key=yt6&signature=70E6127D391A315E29212EC764DBDEED83D60F24.889C3F159ACB32F18A1EADBF53034384DD88793B"
```

I got 403 forbidden

**Comment by fent** [comment]
The link is only available for a short bit.

**Comment by vyky** [comment]
Yeah it have `expire` parameter. Thank you

**Comment by towfiqi** [comment]
how long does it take to expire? Anyone has any idea?

**Comment by fent** [comment]
6 hours to expire. Last checked this 2 months ago.

**Comment by towfiqi** [comment]
Thanks :)

**Comment by djraval** [comment]
Even newly generated urls give 403. 
Has your issue been fixed?

**Comment by shu-vro** [comment]
The urls also have a `ip` parameter. Which means you cannot download it from another device or a different ip. You can only download it using your node project. However, I was in my nextjs project and tried to use the url in a audio/video element and it plays the video in my pc. However, I didn't test it in production.
