### ISSUE TITLE
How does one check if the video supports maxresdefault?

### ISSUE THREAD

**Issue by FireController1847** [fent/node-ytdl-core#155]
I want to check if the video supports maxresdefsult, and if not, then use a lower quality. Is this possible?

**Comment by fent** [comment]
From a quick test, it looks like videos that have a 720p version or above have `maxresdefault`, so you could search through `info.formats` and see if there is anything 720p or above.

**Comment by FireController1847** [comment]
@fent I've come up with a simple solution. 
```javascript
let is720 = false;
for (let i = 0; i < s.info.formats.length; i++) {
  if (s.info.formats[i].quality_label == "720p") {
    is720 = true;
  }
}
console.log(is720);
```
The question is, will this work EVERY time? If so, I might submit a pull request to make the maxresdefault null if it does not support 720p, allowing users to do this:
```javascript
let thumbnail = (info.iurlmaxres ? info.iurlmaxres : info.iurlhq);
```
Or even better, I might be able to add a new item to the info overall.
```js
info.hqthumbnail
```
This would get the most high quality thumbnail available. Idk, it's just a theory. Don't know which one you would prefer, if either.

**Comment by FireController1847** [comment]
WAIT! STOP EVERYTHING! The 720p check does NOT work. I found [this](https://www.youtube.com/watch?v=p13lhwtSaQc) video and [this](https://www.youtube.com/watch?v=UT6d6RC2gS8) video are both 720p, but do not support the iurlmaxres.

**Comment by fent** [comment]
Interesting. I'm not sure then... requires more research.

And if we do figure it out and create a PR, I'd prefer the former solution of making `iurlmaxres` null if there isn't one.

**Comment by FireController1847** [comment]
@fent I may have a way to possibly fix this, but it would include sending a get request. It might be better to end up making urlmaxres a function, that way we only call the request every time the user needs it. Otherwise, we could ask for the request in the getInfo command. Which would you rather do?

**Comment by fent** [comment]
I'd rather not make another request, it's too much to justify how much this would be used. And if it really is the only way to figure out if `iurlmaxres` is available, then it seems like something the user could simply check themselves with the `http` lib.

**Comment by FireController1847** [comment]
@fent That's why I suggest making it only call the request when the user wants it, as then it's not making a request every time we getInfo. That'd then make iurlmaxres a function.

**Comment by FireController1847** [comment]
Due to a change in YouTube's info system, this issue has become present again. This is the only fix I've been able to come up with.
```js
try {
  const newt = info.thumbnail_url.replace("default", "maxresdefault");
  const res = await snekfetch.get(newt);
  info.thumbnail = (res.status == 404 ? info.thumbnail_url.replace("default", "hqdefault") : newt);
} catch(e) {
  info.thumbnail = info.thumbnail_url.replace("default", "hqdefault");
}
```
