### ISSUE TITLE
Can i use only for getting the youtube video download link in specific 'itag' ?

### ISSUE THREAD

**Issue by jf423** [fent/node-ytdl-core#156]
I am confused about how to do the filter of specific info.

i am doing like this :

`ytdl.getInfo('https://www.youtube.com/watch?v=pPkf7hylUuA', { filter: function(format) { return format.itag === '18'; } }, function(err, info){
    console.log(info);
});`

Instead, the log is still print the whole 'info.json' .

**Comment by TimeForANinja** [comment]
.getInfo is not supporting options.filter but .filterFormats(formats, filter) is getting exported

**Comment by fent** [comment]
Please look at the readme. `ytdl.chooseFormats()` can be used to select one format from `info.formats`. And itag can be filtered with the `quality` option.
