### ISSUE TITLE
Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by HcgRandon** [fent/node-ytdl-core#158]
Getting this error. Youtube updated their sig's

**Comment by HcgRandon** [comment]
Example of a failing getInfo:
https://www.youtube.com/watch?v=ayYpWwYZZwY

**Comment by Siriuo** [comment]
Also having the same issue here. I am guessing it has something to do with restrictions some youtube video's have.

Example video https://www.youtube.com/watch?v=OwJPPaEyqhI

**Comment by alexwohlbruck** [comment]
Getting the same problem with all videos. Any way to fix?

**Comment by HcgRandon** [comment]
https://github.com/fent/node-ytdl-core/blob/master/lib/sig.js#L145
https://github.com/fent/node-ytdl-core/blob/master/lib/sig.js#L146
are resulting in null, google changed their javascript. I don't have to fix this. I have work.

If anyone wants to attempt to debug the regexs are here:
https://github.com/fent/node-ytdl-core/blob/master/lib/sig.js#L104

**Comment by HcgRandon** [comment]
Keep an eye on, for possible fix on youtube-dl that will help us debug
https://github.com/rg3/youtube-dl/issues/13123

**Comment by CrimsonXV** [comment]
I've tried to run the tests locally, I think I tracked it down to the actionsObjRegexp and actionsFuncRegexp - I console.logged both and they returned null. Unfortunately I'm not good enough with RegExp to make a fix so maybe someone else could confirm and fix?

**Comment by sedmelluq** [comment]
In some of the scripts, one of the functions the regex extracts got the name `do` due to RNG. Since this is a keyword in Javascript, their minifier uses it in a a different way - it is defined like `"do": ` instead of `do: ` and accessed like `["do"]` instead of `.do`. This broke the regex.
