### ISSUE TITLE
Error: Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by ibexes** [fent/node-ytdl-core#160]
Honestly, I don't even know where to begin.
Error: Could not extract signature deciphering actions
    at /PATH/node_modules/node-ytdl-core/lib/sig.js:32:18
    at IncomingMessage.<anonymous> (/PATH/node_modules/node-ytdl-core/lib/request.js:43:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

from these (but not exclusively) videos:
https://www.youtube.com/watch?v=VxG5C4q_rEs
https://www.youtube.com/watch?v=GFQYaoiIFh8
https://www.youtube.com/watch?v=IOatp-OCw3E
https://www.youtube.com/watch?v=g8PrTzLaLHc
... more

These were all working a few days ago, has youtube changed something their end or something? I mean I'm running the thing from a UK server. I've tried to run it locally and the same issue occurs, but I'm able to open the said videos in browser. The issue persists on older versions of node-ytdl-core, and the current version.

Can't really give much more information that'd be useful from the top of my head.

**Comment by curz46** [comment]
Experiencing the same issue. I expect it's a change YouTube has made to the way it plays videos.

**Comment by ibexes** [comment]
That makes sense, it's able to play videos such as this https://www.youtube.com/watch?v=lSoKbOI8PwU, still.

**Comment by curz46** [comment]
Can you see a pattern?

**Comment by EdibleDerpy** [comment]
I have noticed the same issue just started today. Was working fine yesterday. I have a few videos that will still play but most of my song lists are spitting out errors. I see no pattern at this time.

**Comment by Korayementality** [comment]
Same issue here, however no videos seem to play at all.

**Comment by TinyMan** [comment]
#158 duplicate ? 

Check that you have v0.14.1

**Comment by EdibleDerpy** [comment]
This is not a version issue. This is a new change as of today or yesterday.

**Comment by ibexes** [comment]
Apologies, #158 duplicate indeed. 0.14.1 fixes it, I was just having trouble running it as I was missing a few dependencies on my server.

**Comment by VforVentordici** [comment]
Unfortunately, we have the same problem of: [#282](https://github.com/fent/node-ytdl-core/issues/282)
The error is located in sig.js file. The "exports.getTokens" function tries to assign _tokens_ value but the _exports.extractActions(body)_ function returns null...

Yt changed something and the _body_ will be different I guess, this generates the problem.
Does anyone know what _exports.extractActions(body)_ should return? We have to upgrade _exports.extractActions_ function.
