### ISSUE TITLE
Could not Extract Signature Deciphering Actions

### ISSUE THREAD

**Issue by FireController1847** [fent/node-ytdl-core#161]
Uh, just started getting TONS of these. Only a few videos are working ATM. 

![](https://img.visual-fire.com/hdqs1.png)

**Comment by fent** [comment]
Please check you have the latest version and this is not a dupe of https://github.com/fent/node-ytdl-core/issues/158

**Comment by FireController1847** [comment]
@fent I feel dumb for not updating. Thanks lol
