### ISSUE TITLE
Audio replacing

### ISSUE THREAD

**Issue by ayxos** [fent/node-ytdl-core#162]
Hi! Is there any way to replace the audio? i want to use a custom .mp3 file instead of the original audio. Is it possible?

**Comment by TinyMan** [comment]
You could do that with `ffmpeg`. See `fluent-ffmpeg` to do that with node. Just download the video ytdl then post-process it to replace the audio. 

Anyway it's not related to ytdl since it does not include any media processors, and aim to stay pure js

**Comment by fent** [comment]
Look at [pully](https://github.com/JimmyBoh/pully), it provides post-processing for ytdl-core, there is also an [example file](https://github.com/fent/node-ytdl-core/blob/master/example/ffmpeg.js).
