### ISSUE TITLE
Can't find video ID causes crash in program, can't handle error any other way.

### ISSUE THREAD

**Issue by Didey** [fent/node-ytdl-core#168]
If you try to use a audio stream in a discord bot, and then try to play a a video from a non-existent ID, the whole program crashes with no other way to handle the error. (.catch() doesn't work, ytdl() is not a promise).

This message also shows with an invalid video ID: 
events.js:163
      throw er; // Unhandled 'error' event

And I do handle an "error" event in the code, on the call to ytdl().

**Comment by fent** [comment]
From https://github.com/fent/node-ytdl-core#ytdlurl-options
>Returns a readable stream. 

Which can have an `error` event.
