### ISSUE TITLE
error when queuing more than 1 song

### ISSUE THREAD

**Issue by IWasAndrerstajn** [fent/node-ytdl-core#169]
I am trying to make a music bot with a playlist and here is my code
const vChannel = message.member.voiceChannel;
if(!vChannel) return message.reply("You are not in a voice channel. Please join one");
vChannel.join()
.then(connection => {
var stream;
if(message.guild.playlist) {
message.guild.playlist.push(args[1])
} else {
message.guild.playlist = [args[1]]
}
if(!vChannel.dispatcher){
message.channel.send("Next song");
stream = ytdl(message.guild.playlist.shift(), { filter: 'audioonly' })
const dispatcher = connection.playStream(stream);
message.guild.playlist;
}else{
dispatcher.on('end', () => vChannel.leave());
}
});
im using ytdl-core. and this is the output of the error

this.sockets.ws.sendPacket({
                        ^

TypeError: Cannot read property 'sendPacket' of null
    at VoiceConnection.setSpeaking

**Comment by fent** [comment]
Sorry. This is not related to ytdl-core, it looks like something you can ask about on the discord.js support server.
