### ISSUE TITLE
Key extraction errors

### ISSUE THREAD

**Issue by HcgRandon** [fent/node-ytdl-core#170]
I have these pop up in my logs every so often. Prob just a unique case, hopefully its helpful in some way. If you need more info please let me know I can try to get it

```
6/7/2017 2:26:09 PMCould not extract html5player key: https://www.youtube.com/yts/jsbin/player_ias-vflJx-lDV/en_US/base.js
```

**Comment by fent** [comment]
I see what the issue is, will fix in a bit.

Do you have the video id or url where this happens?
