### ISSUE TITLE
It only downloads a portion of long videos

### ISSUE THREAD

**Issue by jahtalab** [fent/node-ytdl-core#171]
I'm trying to download a video which is about 2 hours, but the module only downloads 28 minutes of it.

**Comment by fent** [comment]
I am able to download a video a bit over 2 hours, the 1080p format, and it downloads everything. On opening the file, I can play the whole video.

Is there a particular video where this happens? And what format did you try?

**Comment by jahtalab** [comment]
It seems to be working now, could have been a network issue, but with no exceptions!
