### ISSUE TITLE
ytdl-core will not install, and gives me a weird error.

### ISSUE THREAD

**Issue by OGNova** [fent/node-ytdl-core#172]
When installing ytdl-core, I get weird errors. I have linked a screenshot of the console when trying to install it, and the log that it gives me.

Screenshot: http://prntscr.com/fhmbak

Log: https://hastebin.com/uyojatuwoh.tex

I have no clue what's wrong, and also have no clue how to fix it. Any idea?

**Comment by fent** [comment]
That seems like an issue with npm. I'd ask them about it.

**Comment by OGNova** [comment]
Just opened an issue with them, thanks!
