### ISSUE TITLE
[Confirmed] IP-Grabber grabs IP when getting info/attempting to play a video.

### ISSUE THREAD

**Issue by FireController1847** [fent/node-ytdl-core#173]
**The Issue**
Currently under investigation, but currently I've gotten reports that users can get the ID of the process using YTDL-CORE by running an invalid YouTube link through the player. It will attempt to get it without checking first if it's a valid YT link, causing it to grab their IP.

**The Status**
I'm checking this as of the moment, but I wanted to make it aware for any others who would like to confirm/check it. I'll submit a PR to fix it if it's true.

I have officially confirmed that this WILL work. If you use Grabify to create a short link, and then add ?v="actual youtube video ID", it will successfully grab the player's IP. I'm now submitting a PR to fix this.

**Example Link**
_Warning, this WILL grab your IP if you go to this in a browser. If you don't trust me, then don't click it._
https://goo.gl/B7xaIV?v=eev8rSoDRbU

**Example Code**
```javascript
const yt = require("ytdl-core");
// Doesn't even need a player, just do this.
yt("https://goo.gl/B7xaIV?v=eev8rSoDRbU");
```

**Comment by fent** [comment]
But whenever a request is made, the host and path are gotten through constants, such as [on this line](https://github.com/fent/node-ytdl-core/blob/master/lib/info.js#L51).

**Comment by FireController1847** [comment]
That seems odd, as it still grabbed the IP?

**Comment by FireController1847** [comment]
Hmm. Possibly may have been a one time thing. I'll close this until I can get some further, investigation 😉
