### ISSUE TITLE
Downloads fail if #player-unavailable div is missing

### ISSUE THREAD

**Issue by NiklasGollenstede** [fent/node-ytdl-core#178]
YTDL seems to check if the #player-unavailable div is visible.
It does that by checking whether the div has the `hid` class, but that fails if the div is not present at all.

I ran into he problem with YTDL v0.14.2 packed with browserify running in Chrome 58.

I'd suggest that the "not visible" test is also passed if the element is not present at all, not only if it is hidden.

Prepending `(unavailableMsg || body.indexOf('<div id="player-unavailable"') !== -1) && ` to the test here does that:
https://github.com/fent/node-ytdl-core/blob/cad8e95c51aefb9084f34f53f30759410add86c5/lib/info.js#L58

**Comment by fent** [comment]
Do you have a link where this happens?

**Comment by NiklasGollenstede** [comment]
In my current test profile, it seems to happen for about 20% of the pages I attempt to load, seems to be random at every attempt and is not consistent per URL.

YouTube serves different versions of their site to users. I think that is done based on the user agent and saved in cookies. I don't send cookies with my requests, but the user agent is that of Chrome 58.
From the looks if it, I get the new version with custom elements from time to time:

Headers:
![image](https://user-images.githubusercontent.com/10552031/27035760-d6117fb0-4f82-11e7-8e99-03886205536b.png)

Response body:
[yt-response.txt](https://github.com/fent/node-ytdl-core/files/1068273/yt-response.txt)

**Comment by NiklasGollenstede** [comment]
That should do. Thanks!
