### ISSUE TITLE
Progress event not firing & error handling

### ISSUE THREAD

**Issue by AcevedoR** [fent/node-ytdl-core#179]
Hey, the 'progress' event does not seems to fire. (the 'data' does fire).
Could you make an example of error handling, I don't really understand the 'response' event (there is a lot of stuff in the object and I can't figure out what is relevant). I'm making a webapp where the user gives à YT link and the mp3 is stored on a server (for Roleplaying purposes :3), and I would want to display to the user a concise response.

Thank for the great work.
Regards.

**Comment by fent** [comment]
> Hey, the 'progress' event does not seems to fire. (the 'data' does fire).

How are you calling `ytdl`?

> Could you make an example of error handling

The returned object from `ytdl()` is a stream. It can emit an `error` like any other stream.
