### ISSUE TITLE
How to check stream progress?

### ISSUE THREAD

**Issue by camer0** [fent/node-ytdl-core#180]
I'm using this for a discord bot and I was wondering how you could capture the current time elapsed / total time in ytdl-core?

**Comment by fent** [comment]
For download progress, you can look at the [`progress` event](https://github.com/fent/node-ytdl-core#event-progress).

But it sounds like what you want is playback progress, that is something that you'd need your player to tell you. Looking at the discordjs docs, it looks like what you're looking for is [`StreamDispatcher#time`](https://discord.js.org/#/docs/main/stable/class/StreamDispatcher?scrollTo=time)
