### ISSUE TITLE
Error: status code: 503

### ISSUE THREAD

**Issue by SirDeadlystrike** [fent/node-ytdl-core#187]
Certain videos if you try to download them will trip this error
 `2017-07-07 20:50 -05:00: Error: Too many reconnects
    at doDownload (sanatized\node_modules\ytdl-core\lib\index.js:101:26)
    at PassThrough.onend (sanatized\node_modules\ytdl-core\lib\index.js:143:7)
    at emitNone (events.js:110:20)
    at PassThrough.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)`

This video is a example of one that will trip this error
> https://www.youtube.com/watch?v=C8iXS_94Fd0

**Comment by fent** [comment]
Spent a bit of time trying to figure this out. Only progress I made was that downloading the first few (2048) bytes of the video work, but any other ranges don't.

This only happens on the format with itag 22, which is the one selected by default since it's the highest quality. But all other formats do work without issues.

**Comment by Kashalls** [comment]
This isn't my video but it seems to happen on this video as well: https://youtu.be/Ulk8nMq7lFw

**Comment by FireController1847** [comment]
This issue doesn't seem to be happening anymore, For @gmedeadlystrike's URL, it caused a 503 error while @Kashalls's played just fine.

**Comment by Kashalls** [comment]
I found out this happened when it could not find any songs but found playlists instead.

**Comment by FireController1847** [comment]
@Kashalls What do you mean by "only finds playlists"? Are you referring to getInfo? Can I see an example of some code that causes the issue?

**Comment by fent** [comment]
Can also confirm it's not happening anymore. And the format 22 is not on the original link anymore either, and in other videos I could find it in, it's working fine.

Going to close this.

**Comment by gdoron** [comment]
@fent started to happen a lot.
All my requests fail if I'm using proxies, error 503, otherwise works perfectly.
I'm trying to debug and understand what has changed.
![image](https://user-images.githubusercontent.com/6141009/67936594-ba5ff480-fbd4-11e9-94d9-47593a94c29b.png)

**Comment by gdoron** [comment]
Removing `NODE_TLS_REJECT_UNAUTHORIZED=0` resolve it.
Not sure what's the deal behind it though.
