### ISSUE TITLE
Playing live

### ISSUE THREAD

**Issue by AegisDB** [fent/node-ytdl-core#188]
Hello, i've been all but literally smacking my head on the table over this for awhile now. I could never get YTDL-core to play live music, after having no luck elsewhere i decided to try once more.
Code:
```
let ytdl = require('ytdl-core');
message.guild.channels.get('331868457194881026').join()
.then(connect=>{
stream = ytdl('https://www.youtube.com/watch?v=7uXLkqT6Qqc', {quality: '92'})
connect.playStream(stream)
})``
```
I have an eval command, running that results in nothing, not even a second of play. I've run it by itself (no quality option) with every itag value 91/92/93/94/95, and with and without the' ' marks. The only way to get that to play anything is to put on the filter: 'audioonly' option which as stated elsewhere, only grabs about 1-2 seconds of video before cutting out (because it doesn't grab a live version)

Please tell me what i'm doing wrong.... i just don't understand why this isn't working....

**Comment by fent** [comment]
I tried 93, 94, 95 and they worked.

91 and 92 didn't however. Even if I try playing these two formats outside of discord.js, like on mpv, they don't seem to have any audio.

**Comment by fent** [comment]
How I tested was the [discord example](https://github.com/fent/node-ytdl-core/blob/master/example/discord.js). Filling in my bot token, the YouTube url, and setting the `quality` option to `95`, and deleting the `audioonly` filter.

**Comment by AegisDB** [comment]
It seems to be just my bot then, i have a test bot i use for testing, straight up copied the code over and it worked, i do not understand why it doesnt work straight through an eval command though, since an eval command is separate from the main process wouldn't it operate independently of it and therefore anything it does wont be affected?

Nevermind, i have something to go off of now, thanks, i know what DOES work and thereby i can fix my own problem... somehow...
