### ISSUE TITLE
Age confirm issue

### ISSUE THREAD

**Issue by icaliman** [fent/node-ytdl-core#19]
I got this error after a while:
```
500 Error: Error 150: Sign in to confirm your age
 at /var/nodejs/youtube/node_modules/ytdl-core/lib/info.js:47:16
 at Request._callback (/var/nodejs/youtube/node_modules/ytdl-core/lib/crequest.js:9:5)
 at Request.self.callback
```

**Comment by fent** [comment]
Do you have a video that gives this error? Does it only happen after a while because it looks like one of those messages you get for NSFW videos.

**Comment by jbergknoff** [comment]
Here's an example of a video with the issue: https://www.youtube.com/watch?v=otfd2UTrP_Q

**Comment by fent** [comment]
Can't find a way to scrape the video info

tried these pages
https://www.youtube.com/embed/otfd2UTrP_Q
http://www.youtube.com/get_video_info?hl=en_US&el=detailpage&video_id=otfd2UTrP_Q

The other option can be having the user login, by either giving some sort of credentials, or a cookie.

**Comment by jbergknoff** [comment]
It looks like rg3/youtube-dl has a workaround for the age gating that doesn't involve logging in: https://github.com/rg3/youtube-dl/blob/98998cded6e179b35055177f75fc921d99ee5938/youtube_dl/extractor/youtube.py#L828-L845

**Comment by andrewrk** [comment]
Another example: https://www.youtube.com/watch?v=rIqCiJKWx9I

**Comment by fent** [comment]
Thanks @jbergknoff

**Comment by andrewrk** [comment]
Nice fix! I'm really happy to depend on this module.

**Comment by fent** [comment]
Glad to hear :)

**Comment by icaliman** [comment]
Many thanks! :)

**Comment by ldenoue** [comment]
I still get this error today e.g. https://www.youtube.com/watch?v=Qxx14RCxblg
Is it possible to fix again?
