### ISSUE TITLE
Support for downloading captions

### ISSUE THREAD

**Issue by pietrop** [fent/node-ytdl-core#191]
Hey, Was wondering if this could provide support for downloading captions?
And what would it take to add that. 

Thanks

Pietro

**Comment by fent** [comment]
Could be something that's added in the future.

> And what would it take to add that.

Figuring out how.

**Comment by TimeForANinja** [comment]
i kinda is already provided
```js
require('ytdl-core').getInfo('Uy1Ds4qC-ig').then(d => {
	const player_resp = JSON.parse(d.player_response);
	const tracks = player_resp.captions.playerCaptionsTracklistRenderer.captionTracks
	console.log(tracks);
})```
that gives u the links to the captions and the display times

**Comment by fent** [comment]
Ah, it's that simple. Thanks for figuring that out.

I might add parsing the `player_response` for it, and either a bit to the readme about it or an example file.
