### ISSUE TITLE
Any way to search for videos? (ytsearch:)

### ISSUE THREAD

**Issue by SpicyDwarf** [fent/node-ytdl-core#194]

**Comment by fent** [comment]
Not from this module. The [Youtube API allows it](https://developers.google.com/youtube/v3/docs/search), I'd search for a module for that api or make the request yourself.

**Comment by alexmercerind** [comment]
https://github.com/alexmercerind/youtube-search-javascript I made this script to search for YouTube videos without the Youtube Data API.
