### ISSUE TITLE
This video is not available

### ISSUE THREAD

**Issue by AegisDB** [fent/node-ytdl-core#197]
| events.js:161
0|gaius2   |       throw er; // Unhandled 'error' event
0|gaius2   |       ^
0|gaius2   |
0|gaius2   | Error: This video is not available.
0|gaius2   |     at /home/buck/gaius/node_modules/ytdl-core/lib/info.js:61:25
0|gaius2   |     at IncomingMessage.<anonymous> (/home/buck/gaius/node_modules/miniget/lib/index.js:75:11)
0|gaius2   |     at emitNone (events.js:91:20)
0|gaius2   |     at IncomingMessage.emit (events.js:186:7)
0|gaius2   |     at endReadableNT (_stream_readable.js:974:12)
0|gaius2   |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
0|gaius2   |     at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)

Yeah i know you can't change the fact that the video can't be got by your program but at the same time is there not a way to make it so this doesn't crash my bot?
I tried putting a try catch around the entire thing but it still crashes the thing so it's obvious there's not a way (that i know) to check for an error during ytdl processing.

try {
                ytdl(connection.qlink[0], { filter: 'audioonly', quality: [249, 171, 140, 139] })
                    .pipe(fs.createWriteStream(connection.todelete))
                setTimeout(function () {
                    process(message, connection.todelete)
                }, 3000);
            }
            catch (err) { console.error(err.stack); }

Do you know of a way to catch this error so it doesn't absolutely annihilate my program, making it reboot?

PS. tried using the 'insert code' button on this all it does is just fuck it up.

Also should note that i'm taking in data and input from other users so i have no garuntees on what videos are submitted for processing nor do i really have a way to check every video, maybe is there something that the youtube data api returns that shows that ytdl won't be able to process it?

**Comment by fent** [comment]
The [stream api](nodejs.org/api/stream.html) can possibly emit an `error` event. Catch that and your program won't crash.

```js
ytdl(...)
  .on('error', (err) => do stuff with err....)
  .pipe(...)
```
