### ISSUE TITLE
Getting a strange error youtube-dl/ytdl-core

### ISSUE THREAD

**Issue by godleydemon** [fent/node-ytdl-core#198]
```javascript
[21:40:45] { Error: Command failed: /home/athena/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best --no-warnings https://r7---sn-q4f7snsk.googlevide
o.com/videoplayback?expire=1502091637&lmt=1500405114427482&mime=audio%2Fwebm&gir=yes&requiressl=yes&keepalive=yes&clen=5217877&source=youtube&signature=5AF0D
8A281B3906530DB2A766A77E1F7FC336EBA.68345327EFF6A2D68FE42DA18C956B90F99E8036&key=yt6&ei=FcWHWb3HCoHOuwXBxLGQDg&ipbits=0&id=o-AKcJF-Skg8f8fRU4PXGE-oRRGWOzfU76
h7Jvi4PRRdVf&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2C
expire&ms=au&itag=251&initcwndbps=1566250&dur=323.201&mv=m&mt=1502069977&pl=17&mn=sn-q4f7snsk&mm=31&ip=70.121.137.80&ratebypass=yes
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1956, in download
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 848, in process_ie_result
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 841, in process_ie_result
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1544, in process_video_result
IndexError: list index out of range

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/athena/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best --no-warnings https://r7---sn-q4f7snsk.googlevideo.com/videoplayback?expire=1502091637&lmt=1500405114427482&mime=audio%2Fwebm&gir=yes&requiressl=yes&keepalive=yes&clen=5217877&source=youtube&signature=5AF0D8A281B3906530DB2A766A77E1F7FC336EBA.68345327EFF6A2D68FE42DA18C956B90F99E8036&key=yt6&ei=FcWHWb3HCoHOuwXBxLGQDg&ipbits=0&id=o-AKcJF-Skg8f8fRU4PXGE-oRRGWOzfU76h7Jvi4PRRdVf&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ms=au&itag=251&initcwndbps=1566250&dur=323.201&mv=m&mt=1502069977&pl=17&mn=sn-q4f7snsk&mm=31&ip=70.121.137.80&ratebypass=yes' }
```

Not quite sure what it causing this, and not really sure what else to give you guys in the direction. As this error is bizarre to me.

getting this when trying to run straight through youtube-dl
https://hastebin.com/memizekuri.pl

**Comment by TimeForANinja** [comment]
Since this is not youtube-dl u should move to there git repository

**Comment by godleydemon** [comment]
I've been having a rough morning/afternoon, got a link to there repo I can post at?

**Comment by TimeForANinja** [comment]
Depends on  your implementation
https://github.com/przemyslawpluta/node-youtube-dl
Or
https://github.com/rg3/youtube-dl/

The second one looks more appropriate to me

**Comment by godleydemon** [comment]
Thanks Ninja, I'll go ahead and close this then, already posted over there at rg3 :)

**Comment by godleydemon** [comment]
welp, never mind, rg3 github was absolutely no help, and didn't even tell me what the damn issue was, or did, but it made no sense. Since the answer made absolutely zero sense, then they locked it so I can't ask anymore questions trying to clear it up. -.-

I have never had this issue before in trying to clear up an issue with a discord bot, it's absolutely insane to me. (sorry if I'm sounding frustrated, but I've been working on this problem for two days and I've been passed off to people during that entire time).

**Comment by fent** [comment]
Sorry to say, but I have to redirect you to another module again. This module, ytdl-core, does not use youtube-dl, or even python.

You're using this one:
https://github.com/przemyslawpluta/node-youtube-dl


But also, looking at the error, it's weird that `youtube-dl` is being called with a googlevideo.com URL. You usually give it a URL to YouTube, not the underlying video hosting server.

I don't know for sure, but this leads me to think it's an issue with the bot you're using. I worked on node-youtube-dl for a while and the above doesn't make sense, it would never call `youtube-dl` again with the URL that the `youtube-dl` program itself returned.

But, if you find the error is not from the bot, you should ask there.

**Comment by godleydemon** [comment]
so sorry to bother you @fent but I'm so frustrated with this. I went through and took out all of the code in my bot but the stuff pertaining to the music portions of it. Would you mind awfully to much, taking just a quick look to see if something is out of sorts?

https://hastebin.com/ipawehalas.js

**Comment by fent** [comment]
You're putting the `url` from `format.url` from the `YoutubeDL.getInfo()` function into a queue. Then calling `YoutubeDL` again with this url. Should be using the https library to download this video, and if it's been too long that the URL has expired, then you'd have to call `YoutubeDL` again with the YouTube URL or search term.

**Comment by godleydemon** [comment]
@fent I guess I'm a bit confused. The URL shouldn't expire in that short of time, and I'm able to access that url hours after it's been issued. I'm also having issues trying to pull that URL directly with the youtube-dl binary. So I guess I'm just really confused on what changed for me.

**Comment by godleydemon** [comment]
This is what I'm getting when running the binary directly
https://hastebin.com/zebiwaneqa.sql
