### ISSUE TITLE
Begin Option not working

### ISSUE THREAD

**Issue by kubsar** [fent/node-ytdl-core#200]
Hey!

I love the module and everything works perfectly but the begin option. I just can't seem to get it working. As I couldn't find similiar issues, I might think that it's my code. The video always starts playing at 0:00, no matter what time format I try to supply. I work with discord.js. Hope someone can help, thanks in advance!
```js
const tagID = message.author.tag.split('#', 2);

if (tagID[1] == '6133' || tagID[1] == '0219') {
	const [command, youtubeLink, beginTime] = Util.splitWithTail(message.content, " ", 2);
	const voiceChannel = message.member.voiceChannel;

	voiceChannel.join().then((connection) => {
		const stream = ytdl(youtubeLink, {
			filter : 'audioonly',
			begin : (beginTime === null) ? '0:00' : beginTime
		});
		const dispatcher = connection.playStream(stream);
		dispatcher.on('end', () => {
			message.delete();
			connection.disconnect();
		});
	}).catch((error) => {
		console.log("[ YT PLAYBACK ERROR ] " + error);
	});
}
```

**Comment by fent** [comment]
Is there a specific video it does not work with? We've found that it tends to not work with shorter videos (30s), or lower quality videos.

There's a note on the readme for the option
>This option may not work on super short (less than 30s) videos, and has to be at or above 6s. See #129

**Comment by kubsar** [comment]
Thanks for the reply! I tried a lot of videos. Long ones, short ones, hq / lq ones, tried to obey the 6s "bug" you mention in the readme, but it doesn't work with any video I try. I tried different params e.g. 1:23, 1m23s, 73800 (as in ms) and so on. Can't get it to function :S Tried to debug myself because I didn't wanna bother you, but as it is as of now you guys here are my last resort :>

**Comment by TinyMan** [comment]
I faced a similar problem, and finally understood the matter. You can follow the discussion in #129 and in #159 . I ended up creating [node-jamy](https://github.com/TinyMan/node-jamy) who can stream youtube's audio.

But the simplest solution, for you, is to use `ffmpeg` with `-ss` parameter. It will still download the entire video but start playing at the requested location.
