### ISSUE TITLE
Error handler was set twice in info.js

### ISSUE THREAD

**Issue by Deliaz** [fent/node-ytdl-core#208]
I am wondering why here an error handler was set twice? Is there a purpose for that or just a typo? 

**lib/info.js**
Lines 296 & 298
https://github.com/fent/node-ytdl-core/blob/79bbec359ab591f46204c14e6be4efb6d934aada/lib/info.js#L295-L300

**Comment by fent** [comment]
A mistake. Thanks for noticing.
