### ISSUE TITLE
Getting the total size / bytesTotal.

### ISSUE THREAD

**Issue by Aetheryx** [fent/node-ytdl-core#209]
Same question as #11. There doesn't seem to be a `format.size` anymore - what's the current equivalent?

**Comment by fent** [comment]
There's a [`progress` event](https://github.com/fent/node-ytdl-core#event-progress).

And here's an example that uses it
https://github.com/fent/node-ytdl-core/blob/master/example/progress.js

**Comment by Aetheryx** [comment]
My bad, should've looked into it more :x Thanks though!

**Comment by bitbytebit1** [comment]
When setting a Content-Length header the total value returned by the progress event, it reports the wrong size, if a song is normally 3:13 it is reported as being 3:32. Is there something missing?

**Comment by fent** [comment]
Content byte length is different than video/song play length. And there is an [`approxDurationMs`](https://github.com/fent/node-ytdl-core/blob/master/example/info.json#L23) property, but I don't think it's exposed in the returned formats.
