### ISSUE TITLE
Tests fail as of Jan 30, 2015

### ISSUE THREAD

**Issue by Thristhart** [fent/node-ytdl-core#21]
I presume youtube has changed something in the two days since the last commit, because the tests are now failing with a 403 error. Not all videos are 403-ing, but a lot are. 

Some that fail:
- https://www.youtube.com/watch?v=WLiuMkGCOC4
- https://www.youtube.com/watch?v=l9PxOanFjxQ

Some that do not fail:
- https://www.youtube.com/watch?v=-Tdu4uKSZ3M
- https://www.youtube.com/watch?v=_nabH71Bgyc

**Comment by Thristhart** [comment]
https://travis-ci.org/Thristhart/node-ytdl-core/builds/48943432 Here is a link to a failing Travis build. (The fork has no changes, just created to force travis to test)

**Comment by Cedriking** [comment]
Yep same here, same problem as I had before the latest commit.
Thank you.

**Comment by fent** [comment]
Fixed with https://github.com/fent/node-ytdl-core/commit/7f4e770919b8fdf2e3cbf006a2c244e02cc5f550
