### ISSUE TITLE
Error: Too many redirects (from miniget used by ytdl-core)

### ISSUE THREAD

**Issue by DevYukine** [fent/node-ytdl-core#212]
```
2|Senpai   | Error: Too many redirects
2|Senpai   |     at ClientRequest.<anonymous> (/root/Senpai-Bot/Senpai-Bot-Discord/node_modules/miniget/lib/index.js:59:19)
2|Senpai   |     at Object.onceWrapper (events.js:316:30)
2|Senpai   |     at emitOne (events.js:115:13)
2|Senpai   |     at ClientRequest.emit (events.js:210:7)
2|Senpai   |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
2|Senpai   |     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
2|Senpai   |     at TLSSocket.socketOnData (_http_client.js:454:20)
2|Senpai   |     at emitOne (events.js:115:13)
2|Senpai   |     at TLSSocket.emit (events.js:210:7)
2|Senpai   |     at addChunk (_stream_readable.js:266:12)
2|Senpai   |     at readableAddChunk (_stream_readable.js:253:11)
2|Senpai   |     at TLSSocket.Readable.push (_stream_readable.js:211:10)
2|Senpai   |     at TLSWrap.onread (net.js:585:20)
```

i get this error often in the last time and im not quit sure how to handle properly since i cant catch it property (seems to be thrown in the miniget lib or smth) and maybe you could tell me if its an network issue or something like that

**Comment by fent** [comment]
Looks similar to the error from #187, but that one is too many re*connects*. So possibly, this is a separate issue.

Do you have an example video where this happens?

**Comment by Dev-Yukine** [comment]
oh not at the moment, i will try to get one ASAP to help you investigate the issue :)

**Comment by jusola** [comment]
I got the same while testing, and it appears that if the video does not exist, this happens: 
 ```Error: Too many redirects
    at ClientRequest.<anonymous> (/home/juusolain/CordBot/node_modules/miniget/lib/index.js:59:19)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
 ```
This is probably the same thing

**Comment by Dev-Yukine** [comment]
oh yea that would make sense since you get rediricted if the video was claimed/deleted if i remember correct

**Comment by FireController1847** [comment]
Ahh it's happening still @fent pls fix kthx <3

**Comment by arjndr** [comment]
Yep, still happening sometimes.

**Comment by fent** [comment]
Are there video where this consistently happens?

**Comment by JimmyBoh** [comment]
My unit tests are now failing with this: https://www.youtube.com/watch?v=oVXg7Grp1W8

But I can override them with an environment variable and this worked: https://www.youtube.com/watch?v=OLxY0HDakRk

**Comment by mandazi** [comment]
It is happening with this video: https://www.youtube.com/watch?v=PimVw0LomLs

Using ytb2mp3: 
https://github.com/ytb2mp3/ytb2mp3/issues/2

**Comment by fent** [comment]
> It is happening with this video: https://www.youtube.com/watch?v=PimVw0LomLs

Ok I'm able to replicate with itag 22 of this. Will investigate.



> Using ytb2mp3:
> [ytb2mp3/ytb2mp3#2](https://github.com/ytb2mp3/ytb2mp3/issues/2)

This is using an outdated version of ytdl-core btw. You can see in the `package-lock.json` file. The error still happens with the video above, but you should always be using the latest version or you might run into other errors.

**Comment by fent** [comment]
Going to keep this opened to remember to investigate video: https://www.youtube.com/watch?v=PimVw0LomLs

**Comment by mandazi** [comment]
Any updates on this?

**Comment by fent** [comment]
Been on a break for a while, will get back to it in a few weeks.

**Comment by ShawnAndrews** [comment]
I'm also encountering this error rather frequently. I don't believe its due to a video not existing because after my program has crashed and i attempt to get the video it will succeed. Its very random when this error occurs.

This is my error log:
`Error: Too many redirects
    at ClientRequest.httpLib.get (C:\Users\ShawnDesktop\Desktop\ConnectWithGamers\node_modules\miniget\lib\index.js:115:32)
    at Object.onceWrapper (events.js:285:13)
    at ClientRequest.emit (events.js:197:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
    at TLSSocket.socketOnData (_http_client.js:449:20)
    at TLSSocket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:98:12)
    at PassThrough.onerror (_stream_readable.js:717:7)
    at PassThrough.emit (events.js:197:13)
    at PassThrough.req.prependListener (C:\Users\ShawnDesktop\Desktop\ConnectWithGamers\node_modules\ytdl-core\lib\index.js:131:14)
    at PassThrough.emit (events.js:197:13)
    at ClientRequest.httpLib.get (C:\Users\ShawnDesktop\Desktop\ConnectWithGamers\node_modules\miniget\lib\index.js:115:18)
    at Object.onceWrapper (events.js:285:13)
    [... lines matching original stack trace ...]
    at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)`

Is there any way to catch this error to prevent my program from crashing? By the error log i thought i had to simply add an event handler callback for 'error' events like so:

`
const readable: any = ytdl(...).pipe(writable);
readable.on(`error`, (error: any) => {...handle error...});
`

But this doesn't seem to catch the emitted error.

**Comment by ShawnAndrews** [comment]
This 'Too many redirects' error seems to occur when multiple ytdl calls are being processed at the same time. If i download a single youtube video at a time i never get this, only when i download multiple videos without letting the previous one finish.

**Comment by EmerickH** [comment]
@ShawnAndrews I have this issue while downloading only one video at the same time

**Comment by Gabriel10Velloso** [comment]
The same error is also working with me.
Urls: 
https://www.youtube.com/watch?v=IbbtAy2jvLM 
https://www.youtube.com/watch?v=lwIIODceKyY

**Comment by suroh001** [comment]
yo wtf fix this shit already

**Comment by FireController1847** [comment]
Yeah that's how you ask open source software developers who do this as a hobby in their free time to fix something! Insult them! That seems like a great idea!

**Comment by danielboos1** [comment]
Any updates on this?

**Comment by danielboos1** [comment]
I found out if you requeue the same video and it will actually play, so maybe you can fix it by making it retry on this error

**Comment by gdoron** [comment]
Curious if people here are using proxies or not.
It only happens for me when I'm using a proxy.

**Comment by mh4ck** [comment]
> Curious if people here are using proxies or not.
> It only happens for me when I'm using a proxy.

And how you fix it with proxy?

**Comment by gdoron** [comment]
@mh4ck I didn't. 
Had I had the time I would fork ytdl to use request module instead of miniget, it is by far more robust.

**Comment by TimeForANinja** [comment]
we tried to stay away from request since it's a heavyweight at more then 200x the size of miniget

**Comment by jimbuck** [comment]
And apparently Request is also ["unmaintained" now](https://github.com/request/request/issues/3142). I highly recommend [Got](https://github.com/sindresorhus/got) as an alternative.

**Comment by Nieme** [comment]
Error: input stream: Too many redirects
    at ClientRequest.<anonymous> (/location_dont_matter/node_modules/ytdl-core/node_modules/miniget/dist/index.js:129:42)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:310:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)

**Comment by nasir03082409229** [comment]
I m also facing same error anyone have fix this issue?

**Comment by fent** [comment]
status update on this issue, I'm unable to download the following video

https://www.youtube.com/watch?v=PimVw0LomLs

however, this time there's no error, the download starts, only downloading around 500kb, then stalls

**Comment by primeartsXD** [comment]
this problem might be caused by the command !serverQueue, try changing the volume to 5 maybe that could help i guess

**Comment by Anastatis** [comment]
I had this issue and then it got solved when I went to **node_modules>miniget>dist>index.js and changed the value of maxRedirects on line 13 to a very big number.** This worked for me. I never got this error again. It should say maxRedirects: {number}. The default value was set at 3 for me. 

Try this out!

**Comment by Gymnophoria** [comment]
To implement the above suggestion by @Anastis without changing the miniget code (which will get overridden w/ npm updates), add the following to your ytdl options: `requestOptions: { maxRedirects: 10 }`. Change maxRedirects to any number you see fit, I haven't tested this much, although I wouldn't suggest making it too big as redirect loops do signal a broken page and will slow down both your client and YouTube. HTTP spec set the standard at 5 ([RFC 2616 section 10.3](https://www.ietf.org/rfc/rfc2616.txt)), which Chrome/Firefox and probably others follow, more than miniget's 2 default but still not "a very big number."
