### ISSUE TITLE
How to mitigate Cross-Origin Request Error when running in browser

### ISSUE THREAD

**Issue by scirahul** [fent/node-ytdl-core#213]
When I run this module in browser (using browserify) to get the video info I get following error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.youtube.com/watch?v=Pv0PAchVGCw&hl=en. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

How can this be mitigated?

**Comment by scirahul** [comment]
There are large number of browser plugins that already do this. I can try fixing this and make ytdl-core browserify compatible if you can guide me.

**Comment by fent** [comment]
Browser plugins have different permissions than a script included in your page with `<script>`.

If you're looking to create a webpage that uses ytdl-core, it would have to be through the backend.
