### ISSUE TITLE
How to stop or resume downloading | Playlist download

### ISSUE THREAD

**Issue by szmyks267** [fent/node-ytdl-core#214]
Is possible to stop and resume a download. node-ytdl-core support downloading playlists from YouTube?

**Comment by fent** [comment]
It uses an http request, you can throttle it however you want. And you can use the[range option](https://github.com/fent/node-ytdl-core#ytdlurl-options) to specify a byte range if you're reconnecting.

Downloading playlists is not supported.

**Comment by h-hub** [comment]
Hi, How to stop the download ? can you explain more ?

**Comment by TimeForANinja** [comment]
You should be able to call `.destroy()` on the stream returned by ytdl
