### ISSUE TITLE
Need help with importing util

### ISSUE THREAD

**Issue by JamesTiberiusKirk** [fent/node-ytdl-core#215]
Hi, noob here.

I need to import util so I can use the validateLink function. The documentation is a bit unclear for me. 
In the beginning I tried to simply do `const ytdl = require('ytdl-core')` with `ytdl.validateLink(url)`, that didn't work. Then, I tried to `const {util} = require('ytdl-core')` and `util.validateLink(url)`, which didn't work either.

What is the proper way to import util?
Thanks in advance!

**Comment by BrunoMoreira991** [comment]
Not your mistake, the readme clearly says `validateLink()` but apparently it's `validateId()` according to [this line](https://github.com/fent/node-ytdl-core/blob/master/lib/index.js#L32).

```js
const ytdl = require('ytdl-core')
ytdl.validateId(url);
```

@fent Either the readme or `index.js` should be updated accordingly.

**Comment by JamesTiberiusKirk** [comment]
This still doesn't seem to work for some reason. Keep getting the same error.
`Uncaught TypeError: ytdl.validateId is not a function`
And I am using it in the exact same way that you are.

**Comment by TimeForANinja** [comment]
guess that one is on me... gonna make a pr real quick
try updating ytdl-core @JamesTiberiusKirk
