### ISSUE TITLE
Getting Error: status code 403 for music videos

### ISSUE THREAD

**Issue by ajai-sandy** [fent/node-ytdl-core#218]
Hello there,
    First of all, thank you for providing this awesome plugin, I am developing an video streaming website which uses ytdl to get the download url. Recently I tried to stream chainsmokersVevo songs in my website, but all the videos in chainsmokers throed 403 (Forbidden) error.

My nodejs server is hosted in US region, and I used the download url to stream from India which all the videos gave me 403 error. When I tried to do the same in my localhost, to my amaze all the videos got played and none of them throed my 403 error.

Is there any restriction based on region? Say, both my server and client should originate from the same country ?

Is any proxy feature available, say I request from India in my browser, and I use a Indian proxy in my server to make a request to youtube using ytdl. By doing so, it would be like both request originated from the same country.

> P.S : I am using getInfo() to get the download url.

**Comment by TimeForANinja** [comment]
as far as i know the resolved youtube video streams are ip locked
therefor u'd have to serve the stream from your server
i'd wait for someone else to confirm/negate this thou

**Comment by fent** [comment]
^ That's correct.
