### ISSUE TITLE
Description not showing in info.json

### ISSUE THREAD

**Issue by mtt87** [fent/node-ytdl-core#22]
Is there a reason why the description field is not being retrieved?

:smile:

**Comment by fent** [comment]
It's not given by the URL that it gets the info from

https://github.com/fent/node-ytdl-core/blob/master/lib/info.js#L8

not even the `ytplayer.config` object has it. seems like the only way to get this would be to scrape the player page for it.

**Comment by mtt87** [comment]
Do you think if I build the scrape function it's going to be useful for somebody else?

Otherwise I'm thinking about using an optional method with the official API to retrieve all the information.

:smile:

**Comment by fent** [comment]
It might be, most people don't need the description though.

**Comment by fent** [comment]
This has been added in the latest release.
