### ISSUE TITLE
Captions no longer work as documented

### ISSUE THREAD

**Issue by FD-** [fent/node-ytdl-core#221]
I recently noticed that info.player_response doesn't seem to get reported anymore, so there's no way to get the captions from there.
This seems to be linked to a PR I submitted some time ago to fix the error message for videos that have to be purchased. The solution back then was to add the "&el=info" parameter to the request. However, it seems this leads to info.player_response not being included in the response.

**Comment by TimeForANinja** [comment]
just ran /examples/captions.js and it still returns them...

**Comment by FD-** [comment]
Right, sorry, I had modified the code and mixed up config.args.player_response and info.player_response. The latter is only reported if "&el=info" is not included in the request.
