### ISSUE TITLE
Does node-ytdl-core run non-free JavaScript?

### ISSUE THREAD

**Issue by hjek** [fent/node-ytdl-core#222]
According to RMS it is now impossible to view Youtube videos without running *non-free* JavaScript, even with **youtube-dl** since it uses a JS interpreter written in Python to run *non-free* JavaScript from Youtube. https://stallman.org/archives/2017-jul-oct.html#3_September_2017_(Youtube)

Does **node-ytdl-core** also run *non-free* JavaScript?

There are many ways of evaluating code in JavaScript, so it is not possible to just grep through the code in this repo, which is why I am asking.
https://stackoverflow.com/questions/28377412/block-eval-new-function

Thanks

**Comment by fent** [comment]
Eval is not used anywhere. If you were wondering about signature extraction, which I believe is where youtube-dl uses the interpreter, ytdl-core uses [regular expressions](https://github.com/fent/node-ytdl-core/blob/master/lib/sig.js#L91-L129).

**Comment by hjek** [comment]
That's great that it's not running non-free code! I assume that from free software perspective extracting strings from JS code is considered the same as extracting strings from HTML.

Thanks for the good news!
