### ISSUE TITLE
Not working with short videos

### ISSUE THREAD

**Issue by coderminion** [fent/node-ytdl-core#233]
it is not working with short videos with http status code 404 

you can refer this video : https://www.youtube.com/watch?v=CdqYGVP_D6I

**Comment by coderminion** [comment]
@fent I am overviewing code. Do you have any idea what might be the problem?

**Comment by FireController1847** [comment]
@fent This seems to be fixed, as I just played it using my bot and it worked fine.

**Comment by fent** [comment]
🤔
