### ISSUE TITLE
File Size limit with quality 

### ISSUE THREAD

**Issue by usamamashkoor** [fent/node-ytdl-core#237]
Hi is their a way i can download YouTube videos like this 
Download 720p format with 250 MB File size Limit
if the file size is greater then 250MB then 
we download 480p format with 250 MB file size Limit
if the file size of 480p  is greater then 250MB then 
we download 360p format with 250 MB file size Limit

Thanks in advance.

**Comment by FireController1847** [comment]
@usamamashkoor You could check the size of the stream using FileSystem, although I'm not sure if this is supported by FileSystem at all.

**Comment by fent** [comment]
Not in an elegant way since the filesize is only known when a download begins.

Something like this could work

```js
const ytdl = require('ytdl-core');
const url = require('url');
const https = require('https');

var limit = 1024 * 1024 * 250;
var videoID = 'somevideoid';

ytdl.getInfo(videoID).then((info) => {
  var formats = info.formats.slice();
  function tryNextFormat() {
    var format = formats.shift();
    if (!format) {
      return; // No format found within the limit
    }
    var parsed = url.parse(format.url);
    parsed.method = 'HEAD'; // We only want headers to get the filesize
    https.request(parsed, (response) => {
      if (response.getHeader('content-length') > limit) {
        tryNextFormat();
      } else {
        ytdl.downloadFromInfo(info, { format });
      }
    });
  }
  tryNextFormat();
});
```

**Comment by usamamashkoor** [comment]
Hi @fent thanks for your reply i have tried your solution but it is giving me this error on the console.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
``` 

and i have also tried commenting the http request in the `function tryNextFormat`
and in the `function tryNextFormat `i am simply running this code 
`ytdl.downloadFromInfo(info, { format })`
but this downloadfrominfo function is also not downloading the video. 

Can you please help me on this and thanks again for your answer above.

**Comment by fent** [comment]
Are you getting the socket hang up error right away, or after some time? If the latter, maybe the request needs to be ended.



> and in the function tryNextFormati am simply running this code
> ytdl.downloadFromInfo(info, { format })
> but this downloadfrominfo function is also not downloading the video.

`ytdl.downloadFromInfo` returns a stream, forgot to stream that to something.

**Comment by usamamashkoor** [comment]
it gives me the error after 40 to 50 sec but before this condition where we are getting the file szie of video
`if (response.getHeader('content-length') > limit) { `
 i have added `console.log(response.getHeader('content-length'))   ` before the condition to see if we are getting the file size but before showing something on console we are getting the above error if we need to end the request then can you please let me know how we can end it.

and about `downloadFromInfo ` function is their a way we can directly write the stream to the amazon s3 bucket if please then please let me know thanks.
 
and Thanks again for replying me.

**Comment by fent** [comment]
Ah, so `.end()` had to be called on it.

```js
const ytdl  = require('..');
const url   = require('url');
const https = require('https');
const fs    = require('fs');

var limit = 1024 * 1024 * 250;
var videoID = 'somevideoid';

ytdl.getInfo(videoID).then((info) => {
  var formats = info.formats.slice();
  function tryNextFormat() {
    var format = formats.shift();
    if (!format) {
      console.log('No format foudn within the limit');
      return;
    }
    var parsed = url.parse(format.url);
    parsed.method = 'HEAD'; // We only want headers to get the filesize
    https.request(parsed, (response) => {
      console.log('format', response.headers);
      if (parseInt(response.headers['content-length']) <= limit) {
        console.log('Found a format within limit, downloading...');
        var output = `${__dirname}/output.${format.container}`;
        ytdl.downloadFromInfo(info, { format })
          .pipe(fs.createWriteStream(output));
      } else {
        tryNextFormat();
      }
    }).end();
  }
  tryNextFormat();
});
```

**Comment by usamamashkoor** [comment]
Thanks again @fent . @fent is their a way i can directly download you tube video to amazon s3 bucket. ?

**Comment by fent** [comment]
Use something like [this module](https://www.npmjs.com/package/fstream-s3)

I'm not really familiar with it but it looks decent from the readme.

**Comment by usamamashkoor** [comment]
Thanks.
