### ISSUE TITLE
Options question

### ISSUE THREAD

**Issue by szarouski** [fent/node-ytdl-core#238]
Hi, I wonder if ytdl-core supports following options:
    [
      '-f', 'bestaudio', '-x', '--audio-format', 'mp3', '--audio-quality', '0',
      '--ffmpeg-location', path.join(__dirname, 'ffmpeg-20171016-7480f23-win64-static', 'bin'),
      '--embed-thumbnail', '-o', path.join(__dirname, 'music', '%(title)s-%(id)s.%(ext)s')]

I guess I can drop -o as I can pipe where I need to, but how about others?
Thank you.

**Comment by fent** [comment]
You're looking for [node-youtube-dl](https://github.com/przemyslawpluta/node-youtube-dl), this is ytdl-core, a JavaScript only implementation.

**Comment by szarouski** [comment]
Oh, I see. Thank you.
