### ISSUE TITLE
Set range end to end of video

### ISSUE THREAD

**Issue by CodeBitt** [fent/node-ytdl-core#240]
Is there a way to set the `range` option's `end` property so that it will go to the end of the video? I tried setting it to `undefined` but it did not work.

**Comment by fent** [comment]
If you don't give a `range.end` it will download to the end of the video? Although, `undefined` would make it behave the same way. How did you verify the video did not download to the very end?
 Can I see your code?

**Comment by CodeBitt** [comment]
It seems to be working but I have another issue where the server will not return a range for anything past the half way point. I will get back to you after more testing.

**Comment by CodeBitt** [comment]
Nevermind, this is not an issue
