### ISSUE TITLE
Convert to OGG

### ISSUE THREAD

**Issue by CodeBitt** [fent/node-ytdl-core#241]
Is there a way to convert a video's audio to an OGG for the readstream, instead of an m4a? The m4a file tye causes problems in most browsers when being streamed.

**Comment by fent** [comment]
Either filter by filetype, although ogg isn't a type available from the format lists. But maybe mp4 would work for you?

```js
ytdl(id, { filter: (format) => format.container === 'mp4' })
```

or convert to your desired type via ffmpeg

https://github.com/fent/node-ytdl-core/blob/master/example/ffmpeg.js
