### ISSUE TITLE
playing videos/audio from raspberry pi 3b fails, whilst working perfectly on windows.

### ISSUE THREAD

**Issue by olvrb** [fent/node-ytdl-core#242]
I have my discord bot with this:

```js
            var stream = ytdl(url);
            var voiceChannel = message.member.voiceChannel;
            voiceChannel.join().then(connection => {
                console.log("joined channel and playing video");
                const dispatcher = connection.playStream(stream);
                dispatcher.on("end", end => {
                    console.log("left channel");
                    voiceChannel.leave();
                });
            }).catch(err => console.log(err));
```
(url is the user input)
And it runs prefectly on Windows 10 Version 1703 (OS Build 15063.674). 

When i try to run it on my Raspberry Pi 3b, however, it joins the channel, and instantly leaves. Here's the output from console i get from the pi:

``` 
Bot has started, with 106 users, in 44 channels of 3 guilds.
joined channel and playing video
left channel
Now playing "Ultimate Best of 20Syl / 2011-2015 / HQ Audio quality (1080p)"
```

**Comment by fent** [comment]
Could the dispatcher be emitting an `error`?

**Comment by olvrb** [comment]
I have all dependencies installed and listen in package.json, and am using the exact same files on my windows machine as on my pi. [This](https://github.com/hydrabolt/discord.js/issues/1387) issue describes pretty much the same thing.

**Comment by fent** [comment]
What about the possible `error` event from `dispatcher`, is that logged? What about errors from `stream`?

**Comment by olvrb** [comment]
I found out that the version of FFMPEG i had didn't support Raspbian. FFMPEG itself doesn't actually support Raspbian.
