### ISSUE TITLE
Begin not working 

### ISSUE THREAD

**Issue by git-santosh** [fent/node-ytdl-core#243]
below code is not working 
```
 let url = 'http://www.youtube.com/watch?v=WKsjaOqDXgg';
 let video = ytdl(url,{begin:2});
 //let video = ytdl(url,{begin:'00:02:00.000'});
// let video = ytdl(url,{begin:'2ms'});
 video.pipe(fs.createWriteStream('video2.mp4'));
```

I have given try on passing different parameters on begin option but neither of them is not working for me

**Comment by fent** [comment]
The begin option is unreliable

from readme
>This option may not work on super short (less than 30s) videos, and has to be at or above 6s, see #129. It may also not work for some formats, see #219.
