### ISSUE TITLE
Finding if a download is incomplete or not.

### ISSUE THREAD

**Issue by sebasgarcep** [fent/node-ytdl-core#244]
I have an use case where I need to resume a download that is halfway through and already saved to disk. The problem is that the download may have also finished. If I send a start range for an already finished video, the request returns a message saying the following: `Status code: 400`, but nothing else. What I want is an error that is more descriptive, allowing me to confidently tell whether the 400 error is due to attempting to download a finished video, or for another reason.

**Comment by TimeForANinja** [comment]
U can do a request with method "HEAD" to the same url to get the content size and compare that with the size of the file.
It'd consider it better to track the download progress in the first place with a database or ending the filename with sth like ".part" and renaming when done.

**Comment by sebasgarcep** [comment]
The renaming scheme might be useful. Thanks @TimeForANinja!
