### ISSUE TITLE
Fetching subtitles

### ISSUE THREAD

**Issue by esphen** [fent/node-ytdl-core#245]
Hi,

Sorry if I'm being daft, but I can't seem to find any way to fetch the subtitle tracks of a video using this library. Is this currently possible?

**Comment by TimeForANinja** [comment]
This should still work https://github.com/fent/node-ytdl-core/blob/master/example/captions.js

**Comment by esphen** [comment]
I was indeed me that was being daft. Didn't see you had an examples directory.

Confirmed that this still works, thanks!
