### ISSUE TITLE
Give me and any tutorial 

### ISSUE THREAD

**Issue by CShehan** [fent/node-ytdl-core#246]
give me any tutorial ytdl-core use in my site

**Comment by fent** [comment]
There are some examples in the readme and in the [examples folder](https://github.com/fent/node-ytdl-core/tree/master/example)

**Comment by CShehan** [comment]
how to get video links? I'm new to js please give me any sample code

Thanks

**Comment by bubundas17** [comment]
You should have some basic knowledge of Nodejs In order to make it work. Go And learn the basics of Nodejs first.
