### ISSUE TITLE
Get total content length of video

### ISSUE THREAD

**Issue by owen-mills** [fent/node-ytdl-core#247]
Is there a way to get the total bytelength of the video requested regardless of the range or how much is already downloaded? I can only figure out how to get the total amount of bytes requested with the range, but I want to get the total byte length of the actual full file.

**Comment by fent** [comment]
That information is not included in a ranged request. But you can get it with an additional request.

```js
const ytdl = require('ytdl');
const urlLib = require('url');
const https = require('https');

const video = ytdl(url, { range: { start: 0, end: 1000 } });
video.on('info', (info, format) => {
  var parsed = urlLib.parse(format.url);
  parsed.method = 'HEAD';
  https.request(parsed, (res) => {
    console.log('total length:', res.headers['content-length']);
  }).end();
});
```

I've considered adding this as a property of each `format`, but it would require a request for each. There are a few other niceties I've thought of including, such as subtitles. I'll think about it more.

**Comment by owen-mills** [comment]
Thank you, you're a hero!

**Comment by owen-mills** [comment]
I have a slightly-related question. What will happen if the `end` range goes over the max video length?

**Comment by fent** [comment]
It'll only download as much as there is, and the `content-length` will not be bigger than the content.

**Comment by dushanranasinghe** [comment]
Will it return the content-length of both video and audio streams combined? 

```
          streams.video = ytdl(id, { quality: videoFormat.itag });
          streams.audio = ytdl(id, { quality: "highestaudio" });
```

If it doesn't, how can I get the content-length for this?

**Comment by TimeForANinja** [comment]
first of all: please do not comment in long-time closed issues - just open a new one
for your problem: you have 2 seperate streams and there is no combining done
means you can get the content-length from video using
```js
streams.video.on('info', (info, format) => {
  console.log(`video has a size of ${format.contentLength} bytes`)
})
```
and the content length of audio using
```js
streams.audio.on('info', (info, format) => {
  console.log(`audio has a size of ${format.contentLength} bytes`)
})
```
