### ISSUE TITLE
Unable to open audioonly downloaded file with vlc

### ISSUE THREAD

**Issue by AUTplayed** [fent/node-ytdl-core#248]
Hi, so I'm downloading the audio of a video via 

`ytdlCore("https://www.youtube.com/watch?v=zBoCdHX_Gtw",{filter:"audioonly"}).pipe(fs.createWriteStream("test.mp3");` 

However I am unable to open the _test.mp3_ file via vlc media player. I tried opening it via the Windows pre-installed player Groove (_shudders_) and it works! Then I changed the file extension from mp3 to mp4 and suddenly vlc was able to play the file. 

I'm not sure if this is an issue with vlc or with ytdl-core because vlc is able to open any mp3 files without any issues other than those downloaded via ytdl-core...

Thanks in advance!

**Comment by fent** [comment]
YouTube no longer has mp3 formats, not any I've seen lately anyway.Typically for audio formats, the container will be mp4, webm, and m4a.

The format object emitted from the [info event](https://github.com/fent/node-ytdl-core#event-info), has a `container` property you can use if you're trying to save the file somewhere. 

```js
var stream = ytdlCore(videoURL);
stream.on('info', (info, format) => {
  stream.pipe(fs.createWriteStream(`test.${format.container}`);
});
```

However, if you're only using ytdl-core to immediately save videos onto disk, consider [ytdl](https://github.com/fent/node-ytdl) which is a cli program that does just that.
