### ISSUE TITLE
Can this repo be run in browser with something like browserify?

### ISSUE THREAD

**Issue by red010182** [fent/node-ytdl-core#25]
According to browserify official page: "Browserify lets you require('modules') in the browser by bundling up all of your dependencies."

Just wondering if ytdl-core can run on browser side without server?

**Comment by fent** [comment]
I'm sure it can as all its dependencies are in pure javascript. And as far as I remember, any module that doesn't require anything to be built or to run external binaries will work with browserify.

But I have never tried.
