### ISSUE TITLE
add method to get dash manifest url

### ISSUE THREAD

**Issue by sheddup** [fent/node-ytdl-core#251]

**Comment by sheddup** [comment]
Thanks 👍

**Comment by sheddup** [comment]
Tried using this today, I don't see any dash/hls manifest in the getInfo response.  
Am I doing this wrong?

```
const ytdl = require('ytdl-core');

ytdl.getInfo("y9W7ZzlX9co").then(response => console.log(response)); //no manifests in this response
```

**Comment by fent** [comment]
Some videos don't have a manifest. If they do, it would be on some of these 3 properties: https://github.com/fent/node-ytdl-core/blob/master/typings/index.d.ts#L181-L183

**Comment by sheddup** [comment]
In the tests, this video id returns a manifest  https://github.com/fent/node-ytdl-core/blob/master/test/info-test.js#L16  
But with the code I posted above no manifest gets returned
