### ISSUE TITLE
Package not working in React Native project

### ISSUE THREAD

**Issue by ajai-sandy** [fent/node-ytdl-core#256]
Hi, I have installed your npm package in my react native project and added an import syntax, after doing so I got issue saying it's not able to import and the error message was pointed toward importing the package inside ReactNative. Is your package supported by React Native if not kindly let me know what to be done to make it work? Thanks.

<img width="320" alt="screen shot 2018-01-08 at 11 12 55 pm" src="https://user-images.githubusercontent.com/6812847/34684432-1590dd0a-f4cb-11e7-880f-45265e035a4a.png">

**Comment by fent** [comment]
I'm not too familiar with using React Native, or the es6 importing syntax. Perhaps trying the suggestion in the error would help?

**Comment by ajai-sandy** [comment]
Hi @fent ,
  I am trying to fetch only the downloadable video URLs, could you help me how to do that by pointing out in your code. I am thinking of creating a react-native npm package specific to my app.
Will definitely give you the credits once the package is developed.

**Comment by fent** [comment]
You can use [`ytdl.getInfo()`](https://github.com/fent/node-ytdl-core#ytdlgetinfourl-options-callbackerr-info) to get a list of formats, which contain a url

**Comment by insraq** [comment]
It does not work "AS IS" in React Native as this package requires Node runtime features that are missing in React Native. However, you can patch it yourself to make it work (and disable some of the features). I have a heavily patched version here that you can refer to. https://github.com/insraq/tubefm/tree/master/app/ytdl

**Comment by fent** [comment]
What specifically did you change above?

I'd like to ideally make this library available in more environments

**Comment by ajai-sandy** [comment]
@insraq I installed ur app in my mobile, gettting "TypeError:Network request failed" error, tried ur web ui as well but for some reason that is also not working. Kindly check on it. Will try ur code today and let you know how it works.

**Comment by insraq** [comment]
@fent Lots of polyfills. The basically the network request library need to be monkey patched. Also some API works differently. I will try to make an PR if I've got more time.

**Comment by insraq** [comment]
@ajai-sandy Have you do the `adb reverse` trick?

**Comment by ajai-sandy** [comment]
@insraq  I found the release build apk in the directory and installed that on my device, will try to clone your project and run it.

**Comment by acatarineu** [comment]
You can create a ```rn-cli.config.js``` file in your react native project root to map some of these node modules that are not available in react native. The following config works for node-ytdl-core:
```js
module.exports = {
  extraNodeModules: {
    fs: require.resolve('./_empty'),
    stream: require.resolve('stream-browserify'),
    http: require.resolve('stream-http'),
    https: require.resolve('https-browserify'),
    path: require.resolve('path-browserify'),
    buffer: require.resolve('buffer'),
  },
};
```
You just need to install these modules (stream-http, etc.). Also for this setup you need to create an empty file ```_empty.js``` in project root: it's used to fix the ```require('fs')``` errors but without providing a real implementation, to make sure that ```fs``` node module is not actually used.

One more thing, recently there was a small change that breaks it on react-native, we made a PR for that: https://github.com/fent/node-ytdl-core/pull/290

**Comment by ajai-sandy** [comment]
@acatarineu Thanks for the info, will try this today and let you know how it goes. Can you suggest me a video player in RN which I could use that would support the url generated by node-ytdl-core.

Like this : `https://r3---sn-n4v7sn7y.googlevideo.com/videoplayback?requiressl=yes&mt=1517929632&expire=1517951352&ratebypass=yes&pl=17&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ipbits=0&ei=GMV5WpOEBdSr-QOp2LOIDQ&ip=13.64.65.74&key=yt6&lmt=1517927989292326&itag=22&source=youtube&mv=m&fvip=3&ms=au%2Conr&signature=AFF6D142A23B438C22977B52CE82A5D434A7193E.BA4DE0AEE0DD118375B6F4C679EB8E3B8D17F671&mm=31%2C26&mn=sn-n4v7sn7y%2Csn-vgqsknes&id=o-ANreTWkCqXuec43UuIgOmLYGP8W8PqerEYwxsUE7UOhm&mime=video%2Fmp4&initcwndbps=25840000&dur=5002.065`

**Comment by acatarineu** [comment]
Sorry, we just need the links to download the files, can't help you there...

**Comment by ajai-sandy** [comment]
Hi @acatarineu,
I tried as per you suggested, but when I am building the project getting the following error

```bundling failed: Error: Unable to resolve module `util` from `/Users/ajai/Projects/demo/node_modules/ytdl-core/lib/index.js`: Module does not exist in the module map```

Have added the files, installed the npm packages and changed the lib code as per [#290](https://github.com/fent/node-ytdl-core/pull/290)

kindly find below screenshot for reference.

<img width="655" alt="screen shot 2018-02-15 at 9 56 18 pm" src="https://user-images.githubusercontent.com/6812847/36267909-20059e18-129b-11e8-8579-5cd942d08e45.png">

**Comment by alex-cliqz** [comment]
Did you try importing directly the function? ```import getInfo from 'ytdl-core/lib/info'```

**Comment by ajai-sandy** [comment]
@alex-cliqz I was importing like the following `import ytdl from 'ytdl-core';` now when I changed to  `import getInfo from 'ytdl-core/lib/info'` I am still getting the same issue

```error: bundling failed: Error: Unable to resolve module `url` from `/Users/ajai/Projects/demo/node_modules/ytdl-core/lib/info.js`: Module does not exist in the module map```

**Comment by fent** [comment]
Still getting this error?

**Comment by matt-way** [comment]
I am also still having a lot of problems getting this working with react-native. While the issue is clearly related to RN and native node module compatibility, the bigger issue I think is the design of the library. I can imagine that this was a lot of work, and I'm grateful, but you could definitely improve your code to avoid problems like this in the future.

I think the biggest suggestion is to not build giant single functions that tie a lot of functionality together. If you made lots of smaller functions that had definite purpose, then the code would be a lot easier to understand and modify, as well as modules being able to easily be swapped out if necessary (in this case).

**Comment by Bartozzz** [comment]
You can use the [`node-libs-react-native`](https://github.com/parshap/node-libs-react-native/) helper to map Node.js modules to their browser equivalents, like so:

```bash
$ npm install --save node-libs-react-native 
```

…then, create a file named `rn-cli.config.js` at the root of your project and paste the following code:

```javascript
module.exports = {
  resolver: {
    extraNodeModules: require("node-libs-react-native")
  }
};
```

However, it seems like [`node-ytdl-core`](https://github.com/fent/node-ytdl-core) is still incompatible. I guess it will be very hard to make it work outside Node.js' env.

```
req.prependListener is not a function. (In 'req.prependListener(event, function (arg) {
  stream.emit(event, arg);
})', 'req.prependListener' is undefined)

<unknown>
    index.js:130:24
downloadFromInfoCallback
    index.js:129:12
<unknown>
    index.js:23:29
<unknown>
    info.js:373:17
<unknown>
    info.js:240:19
```

**Comment by fent** [comment]
`prependListener` was added in node v6. Not sure if react-native only operates with a certain node version, or if you can choose to compile with whichever node version, but if you can, you should upgrade your node.

**Comment by AbelTesfaye** [comment]
I just finished publishing this to npm, I think you guys could find it handy: 

https://github.com/AbelTesfaye/react-native-ytdl

I've tried to keep everything as close to the original version as I can. 
Let me know if any part of the source code could be improved in any way. Cheers!

**Comment by benkaiser** [comment]
For anyone else facing issues using the re-packaged version above from @AbelTesfaye , I made a fork of node-ytdl, stripped a bunch of dependencies and got the raw basics of getting format urls (minus dash urls) working on my fork.
https://github.com/benkaiser/node-ytdl-core

**Comment by AbelTesfaye** [comment]
Hi @benkaiser ,

The library is updated now, there shouldn't be any issues anymore.

**Comment by benkaiser** [comment]
@AbelTesfaye awesome stuff! Here I was sweating trying to make my fork work when I could have just pinged you! :joy:

Thanks!

**Comment by benkaiser** [comment]
Hey @AbelTesfaye I'm hitting "This video is unavailable" on half of the videos I try and play. Mind rebasing your branch and see if that's a fix?

**Comment by benkaiser** [comment]
@AbelTesfaye my guess is it's this commit we really need:
https://github.com/fent/node-ytdl-core/commit/eb1491f5f70302a2b11005041aa9cd0f4a53ef08

**Comment by AbelTesfaye** [comment]
Hi @benkaiser,

I've been working the library, I think its fixed now. Before I publish it though, I need to test it. 

Could you please send me a YouTube link that's making this error?

**Comment by benkaiser** [comment]
@AbelTesfaye yeah this is one of them:

https://www.youtube.com/watch?v=LEQE3c_QJes

For me it's like half of the videos I have in my music library.

**Comment by benkaiser** [comment]
@AbelTesfaye I manually applied the patch myself too and appears to be working. In case your changes differ much, here is my PR:

https://github.com/AbelTesfaye/react-native-ytdl/pull/15

**Comment by AbelTesfaye** [comment]
Cool! thanks for the patches @benkaiser. They've both been merged!
