### ISSUE TITLE
util.filterFormats does not work

### ISSUE THREAD

**Issue by HelloWorld017** [fent/node-ytdl-core#261]
When I use #260, it raises a new bug "No formats found with custom filter".
It is raised because `audioBitrate` in formats is renamed to just `bitrate`.

So, if you want to distinguish between audio and video, you should use type property.

There are examples of type property.
```
audio/webm; codecs="vorbis"
audio/webm; codecs="opus"
audio/mp4; codecs="mp4a.40.2"
video/webm; codecs="vp9"
video/mp4; codecs="avc1.640028"
video/mp4; codecs="avc1.42001E"

video/3gpp; codecs="mp4.20.3, mp4a.40.2"
video/webm; codecs="vp8.0, vorbis"
video/mp4; codecs="avc1.64001F, mp4a.40.2"
```

**Comment by HelloWorld017** [comment]
Oops, it was my mistake for not finding json properly. There was audioBitrate. Sorry for invalid issue. Have a nice day!

**Comment by fent** [comment]
No problem. Was just about to look into this.
