### ISSUE TITLE
Youtube livestream stops randomly. Plays live stream for 10 minutes and ends while livestream is still ongoing

### ISSUE THREAD

**Issue by gohjoseph** [fent/node-ytdl-core#263]
The livestream does not end immediately, the livestream would play for 10 minutes and randomly end without any error. When the video is a livestream, I wouldn't provide any `options` parameter to `ytdl` so therefore it would play with video and audio (Just that discord.js only uses the audio from the stream)

I don't think this is a duplicate of #231. I do not get any request path errors and neither did I specify `audioonly` in my filter settings. This should be a different issue. Creating new issue because I can't reopen #255 since its not a dupe of #231.

It could be a side effect of the stream lagging behind the actual version. (Since youtube only stores the last 2 hours of the livestream and the stream starting behind 2 hours) See #157. 

Live stream used: https://www.youtube.com/watch?v=sKIbH-gXmX0

**Comment by fent** [comment]
Sorry about before.

Will require more investigation/debugging on my side, it might take a bit for me to get to it.

**Comment by FireController1847** [comment]
This is due to the way m3u8stream works with YouTube. I've made a PR on m3u8stream that should fix this along with allowing the fact that it'll start at the latest point in the stream.

**Comment by FireController1847** [comment]
@fent Don't forget to close this one, seems your comma after closes didn't wanna work 😝

**Comment by fent** [comment]
Need to learn that closing syntax
