### ISSUE TITLE
Error: This video is unavailable

### ISSUE THREAD

**Issue by guoxiangke** [fent/node-ytdl-core#264]
Hi , I use lambda & ytdl-core to download youtue video, before works, but today it's says: This video is unavailable, someone can help?

> START RequestId: 94030d1f-f5ab-11e7-ba0a-f54bb8cbd17d Version: $LATEST
> 2018-01-10T02:11:37.427Z	94030d1f-f5ab-11e7-ba0a-f54bb8cbd17d	downloading: http://www.youtube.com/watch?v=DD6xMdNTl48
> 2018-01-10T02:11:37.927Z	94030d1f-f5ab-11e7-ba0a-f54bb8cbd17d	Error: This video is unavailable
> at err (/var/task/node_modules/ytdl-core/lib/info.js:220:16)
> at IncomingMessage.res.on (/var/task/node_modules/miniget/lib/index.js:75:11)
> at emitNone (events.js:91:20)
> at IncomingMessage.emit (events.js:185:7)
> at endReadableNT (_stream_readable.js:974:12)
> at _combinedTickCallback (internal/process/next_tick.js:80:11)
> at process._tickDomainCallback (internal/process/next_tick.js:128:9)
> END RequestId: 94030d1f-f5ab-11e7-ba0a-f54bb8cbd17d

**Comment by fent** [comment]
Hi, this error was identified yesterday and a new version with a fix has been published. Please update ytdl-core.

    npm update ytdl-core

**Comment by FireController1847** [comment]
I can confirm it's fixed in latest version. (This bug was spamming the f*ck out of my bot, glad it got fixed soon xD)
