### ISSUE TITLE
"Error: This video is unavailable" on every video

### ISSUE THREAD

**Issue by Daspharion** [fent/node-ytdl-core#268]
Pretty much what title says.

**Comment by RealBlackB1RD** [comment]
Working perfect for me !
But its stop support playlists :(

(node:78320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: resource youtube#playlistListResponse not found

**Comment by fent** [comment]
Hi. This was fixed a few days ago, please update to latest version

    npm update ytdl-core

**Comment by Daspharion** [comment]
O thanks
