### ISSUE TITLE
Video starting time

### ISSUE THREAD

**Issue by danielmeng07** [fent/node-ytdl-core#27]
I'd like to snap a thumbnail of the video at, say 3.2s. Downloading the entire video is slightly overkill... I was wondering if I can specify a start and end time, so when I do use ffmpeg, it'll just be on the first frame.

**Comment by fent** [comment]
The only thing for that right now is the `range` option

https://github.com/fent/node-ytdl-core#ytdlurl-options

but that's only for specifying file ranges, for pausing and continuing incomplete downloads. It doesn't create a new video file with the given range so it might not be readable by ffmpeg.

If you want an acceptable thumbnail of the video, you can find it with [ytdl.getInfo](https://github.com/fent/node-ytdl-core#ytdlgetinfourl-options-callbackerr-info). If you want a thumbnail from a specific point in the video without downloading the entire video, that's not doable right now. :/

**Comment by danielmeng07** [comment]
I see. Thanks for reply. Is it theoretically possible to get a thumbnail from a specific point in time without needing to download the entire thing?

**Comment by fent** [comment]
I don't know. There might be a video format that has a marker for the start of a frame, allowing you to read the next frame if you downloaded a video starting at halfway, and the starting byte was inbetween a frame.

But I don't know much about video codecs to be able to say with certainty. And I'm not sure how youtube can do this but it seems to be able to.
