### ISSUE TITLE
Livestream Audio

### ISSUE THREAD

**Issue by ItzPike** [fent/node-ytdl-core#271]
The livestream played when executed, with the following script joins the voice channel, and then plays 5 seconds of audio from the livestream, and then just leaves
```
const ytdl = require('ytdl-core');
const streamOptions = { seek: 0, volume: 1 };

const stream = ytdl('https://www.youtube.com/watch?v=XAWgeLF9EVQ', { filter : 'audioonly' });
const dispatcher = connection.playStream(stream, streamOptions);
  })
  .catch(console.error);`
```

Any ideas on why it is doing that?

**Comment by fent** [comment]
Likely due to https://github.com/fent/node-ytdl-core/issues/231

**Comment by ItzPike** [comment]
I was looking on that towards the beginning of my issue before posting, but didn't find anything that would resolve it as of now.

I was thinking it may be a different issue, than as posted in #231

**Comment by fent** [comment]
It's slightly different because you're not getting an error thrown. But I'm pretty sure the same issue, DASH streams not being supported, is causing it.

I'll update the other issue to include this.
