### ISSUE TITLE
Downloading long videos. To much time.

### ISSUE THREAD

**Issue by DonikaV** [fent/node-ytdl-core#276]
Hi, i can`t understand what i am doing wrong. If it is long video - it could be downloaded after huge time. 

Maybe i am doing something wrong. Thanks for help.

```ts
import * as ytdl from 'ytdl-core';
import * as fs from 'fs';
import * as path from 'path';
import * as ffmpeg from 'fluent-ffmpeg';
import { Request, Response } from 'express';
import FileController from "../controllers/FileController";

const saveFolder = path.join(__dirname, '../public/uploads');
const downloader: any = ytdl;
export default function DownloadFromYoutube(req: Request, res: Response, url: string, fileName: string, preferredFormat: any, bitrate: string) {
    // making sure that the destination folder exists
    if (!fs.existsSync(saveFolder)) {
        fs.mkdirSync(saveFolder);
    }
    if (!downloader.validateID(url)) {
        return res.status(500).json({ error: 'That is not youtube URL.' });
    }
    const sockets = require('../bin/socket').sockets();
    const io = require('../bin/socket').io();

    preferredFormat = preferredFormat === 'mp4' ? 'video' : 'audioonly';
    const filePath = path.join(saveFolder, fileName);

    downloader.getInfo(url, (err, info: any) => {
        if (err) {
            res.status(500).json({ error: 'Some trouble with download. Try again.' });
        }
        const data = info;
        const download = downloader(url, {filter: preferredFormat, quality: 'highest'});
        // we have to convert some messy audio-format to mp3
        if (preferredFormat === 'audioonly') {
            // YOU NEED TO MAKE SURE FFMPEG IS INSTALLED ON YOUR ENVIRONMENT https://www.ffmpeg.org/
            ffmpeg(download).toFormat('mp3').audioBitrate(bitrate || 192).save(filePath).on('error', console.error);
        } else {
            download.pipe(fs.createWriteStream(filePath));
        }

        let maxPerc = 0;
        download.on('progress', (chunkLength, downloaded, total) => {
            // get sockets by videoid (url === videoid)
            const socket = io.sockets.to(sockets[url]);
            const percentageDownloaded = Math.floor(downloaded / total * 100);
            maxPerc = Math.max(maxPerc, percentageDownloaded);
            // emit percent event
            if (socket) socket.emit('percent', maxPerc);
        });

        download.on('end', () => {
            FileController.save(data)
                .then((file) => {
                    res.json(file);
                })
                .catch(error => res.status(500).json({error}));
        });
    });
}
```

I set timeout on server to 0. Because sometimes u get 500 error

**Comment by FireController1847** [comment]
If you're actually downloading videos, it might be better to use [YouTube DL](https://github.com/przemyslawpluta/node-youtube-dl), but in the rare case you need to use this to download it, it will take a large amount of time to download as it's streaming it directly from the video. This means for an hour long video, it will take an hour. For a 5 minute long video, it will take 5 minutes.

**Comment by DonikaV** [comment]
So my internet connection is 80mb ... And I now one website that can give me mp3 from YouTube in few minutes. I am trying to do something like this and sometimes I need wait about 10 or more minutes:(

**Comment by fent** [comment]
It might be the ffmpeg conversion. I know those can take a while. You might have noticed that the `progress` event fires several times at first, as much as there's buffer from `highWaterMark` from the ytdl stream. And then it slows down to the rate of ffmpeg.

**Comment by DonikaV** [comment]
Yes. Sometimes in the beginning I see some strange behavior of progress bar. 
So what can I do to resolve this? 
Thanks.

**Comment by fent** [comment]
If the file is being converted to mp3, I can see how that would take a while for a long video. There might be some quality/codec settings on ffmpeg you could adjust to try to speed this up.

To confirm this is what's happening, you can try the [cli version of ytdl](https://github.com/fent/node-ytdl), and compare the speed at which it downloads the same video.

**Comment by DonikaV** [comment]
@fent i tested cli and it works x10 faster than my app.... maybe i am doing something wrong
