### ISSUE TITLE
Audio Stream Ending Early

### ISSUE THREAD

**Issue by person4268** [fent/node-ytdl-core#277]
I am using this in a Discord bot that plays music, and I have not been able to get it to output any sound. 
This is what I currently have:
`
```
function ytdap(msg, args) {
    const ytdl = require('ytdl-core');
    console.log(args[1]); // https://www.youtube.com/watch?v=dQw4w9WgXcQ
    var stream = ytdl(args[1], { filter: 'audioonly' });
    var dispatc= Vchannelconnection.playStream(stream);
    dispatc.on('end', () => {
        leave();
        msg.channel.send("Stream Ended");
    });

}
```
I play a 10 minute Youtube video and I get stream ended after a couple of seconds. It was working a while back and I wasn't sure to put this issue in discord.js or this. 
`

**Comment by FireController1847** [comment]
The end event on Discord.js emits a reason on why it's ended. Can you log that reason and report back to me please?

**Comment by Kaezar** [comment]
I think I am having the same issue as person4268, and the logged reason from the 'end' event is undefined. I should also note that the 'start', 'debug', and 'error' events have not been emitted at all when I've been testing.

**Comment by person4268** [comment]
end is undefined for me, I'm going to attempt updating with NPM right now.

**Comment by person4268** [comment]
UPDATE: Updating ytdl-core within Visual Studio reports nothing. It says I'm on version 0.18.7. This is what my Visual Studio says under NPM packages
![image](https://user-images.githubusercontent.com/28717044/37434113-e0fa11d4-27b4-11e8-966d-3dbbf2d14714.png)

**Comment by fent** [comment]
You should update to the latest version, which right now is v0.20.3

YouTube changes their site all the time, so older versions may not work at all

**Comment by person4268** [comment]
Doing `npm uninstall ytdl-core` and `npm install ytdl-core` updated it. Doing just `npm install` did not update the package

**Comment by person4268** [comment]
I got it working, by reinstalling the package, which updated it. Thank you for helping.
