### ISSUE TITLE
Does streaming a video w/o ads (using this module) break YouTube's ToS? Does that mean we can't use this module in production products?

### ISSUE THREAD

**Issue by FireController1847** [fent/node-ytdl-core#278]
I decided to rephrase my question as it's completely different than my original intention. The title basically explains all, so not much more I need to say.

OLD:
```
Is it possible to retrieve the appropriate ad-videos that play before a YouTube video? I don't want to be streaming videos w/o supporting the correct creators with a request. I know that this module retrieves directly from the page, but does YouTube event support an API that will count all "streams" of a video as views? Is it even possible to make this module have all videos played count as a "view"? Would we have to use the IFrame API and only extract the audio from it for it to count as a view? I'm asking these here because they all relate to this module and if it accepts views / ads.

Overall, here's my question: Does streaming a video w/o ads (using this module) break YouTube's ToS? Does that mean we can't use this module in production products?
```

**Comment by fent** [comment]
There are some ad related fields on the `info` object: https://github.com/fent/node-ytdl-core/blob/master/example/info.json

I haven't messed around with them though.

As for the view count, just did a quick test with an obscure video with 1 view. Download it with ytdl-core doesn't increase the view count, but playing it in other browsers where I was signed out of my account does increase it.

Might be worth figuring out how that's done.

**Comment by FireController1847** [comment]
For the viewcount thing, I've learned that the IFrame API doesn't even increase viewcount. I don't think it's possible.

["Note: A playback only counts toward a video's official view count if it is initiated via a native play button in the player."](https://stackoverflow.com/questions/13456288/does-youtube-api-play-function-trigger-a-view-count)

**Comment by fent** [comment]
That's interesting. Then not sure if it's worth figuring out how to force the view to count if youtube is very against it.

**Comment by FireController1847** [comment]
🤔
