### ISSUE TITLE
Videos not working anymore

### ISSUE THREAD

**Issue by Cedriking** [fent/node-ytdl-core#28]
Hello,
I'm currently unavailable to see any video that I was searching with YTDL, and when I click the link I receive this video link: https://www.youtube.com/watch?v=UKY3scPIMd8

Something saying that the device is not supported?

Thank you for your time and help :-)

**Comment by fent** [comment]
Just ran tests, they passed. What video did you try with? Click what link?

**Comment by Cedriking** [comment]
YTDL is working fine, my bad, It's the youtube feed api that now show as the first item that video in a request.

Thank you :D
