### ISSUE TITLE
Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by HcgRandon** [fent/node-ytdl-core#282]
Looks like youtube changed sig stuff again. Not had a chance to investigate yet. Just reporting

Run tests to see error.
![image](https://user-images.githubusercontent.com/6123135/35918977-97276b7c-0be1-11e8-8053-28744192f753.png)

**Comment by MJunghenn** [comment]
Same here, 

is there anywhere a HowTo to change the signature?

**Comment by HcgRandon** [comment]
@fent pinging you in case you don't have notifs on. I'm not really familiar with youtube's sig bs so I prob wont be able to provide a patch this time around.

**Comment by HcgRandon** [comment]
The issue appears to come from line 157:
`var objResult = actionsObjRegexp.exec(body);`

objResult returns null. Looking to see if I can rewrite the regex

**Comment by HcgRandon** [comment]
Sadly I'm not familiar enough with the youtube js to debug this in a timely fashion. I don't believe I will be able to solve this in a timely manor. It would likely be better for us to wait on fent.

**Comment by HcgRandon** [comment]
And there he is. Thanks fent!

**Comment by MJunghenn** [comment]
Thanky, you will increase the version for it? Otherway npm update will not take effect or? @fent

**Comment by fent** [comment]
New version published
