### ISSUE TITLE
Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by martinbrennan** [fent/node-ytdl-core#284]
Hi I started seeing this error a short time ago. I am using ytd-core in a project that has not changed. This morning it worked - this afternoon I get this error. I am not sure how to run Mocha - I will try and investigate but I thought I'd raise it in case its a Youtube website change.
Martin

**Comment by sub2u** [comment]
Yes i am also getting same issue issue is around extracting signature 

 var objResult = actionsObjRegexp.exec(body);

where ObjREgexp is /var ([a-zA-Z_\$][a-zA-Z_0-9]*)=\{((?:(?:(?:[a-zA-Z_\$][a-zA-Z_0-9]*|(?:'[^'\\]*(:?\\[\s\S][^'\\]*)*'|"[^"\\]*(:?\\[\s\S][^"\\]*)*")):function\(a\)\{(?:return )?a\.reverse\(\)\}|(?:[a-zA-Z_\$][a-zA-Z_0-9]*|(?:'[^'\\]*(:?\\[\s\S][^'\\]*)*'|"[^"\\]*(:?\\[\s\S][^"\\]*)*")):function\(a,b\)\{return a\.slice\(b\)\}|(?:[a-zA-Z_\$][a-zA-Z_0-9]*|(?:'[^'\\]*(:?\\[\s\S][^'\\]*)*'|"[^"\\]*(:?\\[\s\S][^"\\]*)*")):function\(a,b\)\{a\.splice\(0,b\)\}|(?:[a-zA-Z_\$][a-zA-Z_0-9]*|(?:'[^'\\]*(:?\\[\s\S][^'\\]*)*'|"[^"\\]*(:?\\[\s\S][^"\\]*)*")):function\(a,b\)\{var c=a\[0\];a\[0\]=a\[b%a\.length\];a\[b\]=c(?:;return a)?\}),?\r?\n?)+)\};/
Need to check what got changed

**Comment by sub2u** [comment]
pointing to latest code fixed the issue for me

"ytdl-core": "https://github.com/fent/node-ytdl-core"

is the my code change.

**Comment by sub2u** [comment]
@martinbrennan  It is already fixed in latest commit https://github.com/fent/node-ytdl-core/commit/18b3f22ca14b6ee61bc646fd8a2f2c943baa6709#diff-d4723a0b85728eb05d8e2158f24c490c

you can patch it by changing the package file to point to github link 

"ytdl-core": "https://github.com/fent/node-ytdl-core"

**Comment by martinbrennan** [comment]
Thanks sub2u - I just upgraded and yes it works - so thank you for pushing me in that direction. I was using an older version of ytdl-core because I was trying to avoid ES5 syntax - and that allowed me to browserify and use with IE (I'd substituted a proxy mechanism in minget so it did all work). With the latest ES5 syntax I'm restricted to Chrome and Edge. Martin
