### ISSUE TITLE
All Secured streams giving: Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by marufbd** [fent/node-ytdl-core#286]
Youtube probably changed signature for live streams, but non-secured other videos working fine

**Comment by Feathercrown** [comment]
happening for all videos for me.

**Comment by suyogdilipkale** [comment]
Same thing is happening with my code, when can we have fix?

**Comment by 009800** [comment]
Yeah same here (for all)

**Comment by TimeForANinja** [comment]
can you provide a example stream? can't replicate with latest version and all stream's i've found in the last 10 minutes

**Comment by devdutchy** [comment]
Updating to v0.20.1 will fix it.

**Comment by Feathercrown** [comment]
Still happening for me

**Comment by marufbd** [comment]
Sorry, It all works fine with version 0.20.1. Actually my old version suddenly broke and I got mixed up with upgrading.
