### ISSUE TITLE
getting an Error: Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by suyogdilipkale** [fent/node-ytdl-core#287]
Started getting an ERROR: **Could not extract signature deciphering actions.** 
Is anyone have fix for this?

**Comment by 009800** [comment]
Yup, me too.
I hope there is a fix soon :)

**Comment by usamamashkoor** [comment]
Same here..

**Comment by TimeForANinja** [comment]
hope u did already check that ur running latest version 0.20.1?

**Comment by usamamashkoor** [comment]
Thanks it has been fixed for me by updating to latest copy.

**Comment by 009800** [comment]
Hm yes I have 0.20.1... still getting this error.
I'll have a look again.

**Comment by marufbd** [comment]
Example live stream: https://www.youtube.com/watch?v=nVHt1_SWTZg
Example Video: https://www.youtube.com/watch?v=ISLo_mmLJVc

**Comment by fent** [comment]
Can't reproduce

Please make sure you've upgraded to the latest version

**Comment by Feathercrown** [comment]
Not even working for the example bot for me :/

**Comment by cwilczewski** [comment]
Not working for me as well. Not sure if this has anything to do with it but when i run "npm test" in the ytdl-core folder i get an error

> ytdl-core@0.20.1 test E:\disbot\node_modules\ytdl-core
> istanbul cover node_modules/.bin/_mocha -- -t 16000 test/*-test.js

'istanbul' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.

**Comment by BudimirDjordjevic** [comment]
I'm having the same problem

**Comment by arthurbelair** [comment]
Updating to the latest version fixed it for me! Thanks! 👍🏼

**Comment by BudimirDjordjevic** [comment]
Updating to 0.20.1 fixed the issue for me too, thank you! <3

**Comment by fent** [comment]
Is anyone who is using the latest version (v0.20.1) still getting this error?

**Comment by Feathercrown** [comment]
I still am

**Comment by cwilczewski** [comment]
Yes, on version 0.20.1 and still getting this error... I removed it and installed it again, same thing. Tried on multiple computers.

**Comment by Feathercrown** [comment]
Works for me, thanks for the fix!

**Comment by TBubba** [comment]
Have you uploaded the update to npm yet? Because it doesn't work if I download from npm, but it works if I download from here and slap it in node_modules.

**Comment by fent** [comment]
Yep, you can see that v0.20.1 is the latest release here

https://www.npmjs.com/package/ytdl-core

And you can see [the change](18b3f22ca14b6ee61bc646fd8a2f2c943baa6709) I made to fix this is there

https://npm.runkit.com/ytdl-core/lib/sig.js?t=1518791541719 (line 132)

How are you installing with npm, and what does the dependency for `ytdl-core` look like in your `package.json` file?

**Comment by TBubba** [comment]
It works now! 

I changed it from ``"ytdl-core": "^0.7.18"`` to ``"ytdl-core": "^0.20.1"`` and deleted the node_modules and ``node install``-ed. I guess I don't know what ``^`` does.

**Comment by fent** [comment]
@cwilczewski @Ovyerus have you tried the above?

**Comment by ShadowKitty42** [comment]
I have done all this and it's still not working for me.
![screenshot_1](https://user-images.githubusercontent.com/3394296/36605309-30091f3a-1875-11e8-8e3a-ce7c5beac828.png)

**Comment by sihyungkim** [comment]
I have ytdl-core@0.20.2..

But, streaming is not working.
**' Could not extract signature deciphering actions'**

**Not working URL**
https://www.youtube.com/watch?v=i0p1bmr0EmE
https://www.youtube.com/watch?v=cDq1vUwM21k
https://www.youtube.com/watch?v=lalMvFHC79g
https://www.youtube.com/watch?v=dDeewpPQOK0 

**Working URL**
https://www.youtube.com/watch?v=nZbUcmvW4TA
https://www.youtube.com/watch?v=1WAbRa6Tg04
