### ISSUE TITLE
Edited

### ISSUE THREAD

**Issue by jray** [fent/node-ytdl-core#29]
Is there anyway to know if a video has been edited? I didn't see anything from inspecting the info response.

**Comment by fent** [comment]
Edited how?

**Comment by jray** [comment]
Doesn't youtube allow users to go back and clip videos?

**Comment by fent** [comment]
I'm not aware of that, and not sure how youtube would let users know of it.

Don't think it does though.

**Comment by jray** [comment]
Cool. I knew it was a long shot - just thought I'd ask. Thanks for responding!
