### ISSUE TITLE
Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by Valenz68** [fent/node-ytdl-core#292]
As the title said I get "Could not extract signature deciphering actions" error
I tried with test file too.
Please help me 
Bot console : 
![1](https://user-images.githubusercontent.com/36960333/36849652-dd005336-1d64-11e8-9507-319b03bbf8e9.PNG)

Mocha test:
![2](https://user-images.githubusercontent.com/36960333/36849715-0625acf2-1d65-11e8-9de4-b2f9fec11866.PNG)

**Comment by fent** [comment]
Just ran the tests without error. Are you by chance running the latest version, v0.20.2?

**Comment by Valenz68** [comment]
Is version written in node_modules\ytdl-core\package.json ? if it is this one it says "version": "0.20.2"

**Comment by Valenz68** [comment]
Finally got it to work, I deleted all my node_modules folder and reinstalled only the needed ones, I just have sometimes problem with an error telling me that the song is copyrighted, do you know how to bypass that ?

**Comment by fent** [comment]
That's strange. I might have been that the version of ytdl-core that youtube-audio-stream had installed was outdated.

As for the other 'copyright' error, feel free to open up a separate issue, for categorical purposes. And include a link to the video.
