### ISSUE TITLE
All of a sudden

### ISSUE THREAD

**Issue by iPhreak2G** [fent/node-ytdl-core#293]
I have been getting this error since last night 3/1/2018 and have not been able to solve the issue through debugging. everything was working flawless with no changes the day before.

`Cannot read property 'playStream' of null`
[Picture](https://i.imgur.com/T4k2Qlx.png)

As I stated before nothing has changed in the source code or dependencies in several weeks yet I just all of a sudden started getting this error. Any help is appreciated.

**Comment by fent** [comment]
That looks to be related to the discord.js library, not ytdl-core.

There is [an example](https://github.com/fent/node-ytdl-core/blob/master/example/discord.js) on using both together.
