### ISSUE TITLE
What is fs?

### ISSUE THREAD

**Issue by elshobokshy** [fent/node-ytdl-core#297]
I'm trying to install this app in a vuejs project, but I have no idea what npm package is fs or where did it come from. You said to require it, but what is it?

**Comment by fent** [comment]
It's a node core module https://nodejs.org/api/fs.html

I'm pretty sure this library doesn't use it though

**Comment by itslukej** [comment]
You won't be able to use it in the browser due to youtube's Access-Control-Allow-Origin header
