### ISSUE TITLE
How to get notified when download finished?

### ISSUE THREAD

**Issue by shankqr** [fent/node-ytdl-core#298]
When completed the download is there a callback function or something to notify it is successful?

**Comment by fent** [comment]
ytdl-core returns a standard node stream, which emits an `end` event when finished.

**Comment by towfiqi** [comment]
@fent Can you kindly share a sample code? Thanks

**Comment by josephrocca** [comment]
The `finish` event worked for me (`end` didn't):
```js
ytdl(url).pipe(fs.createWriteStream("video.mp4")).on("finish", function() {
  console.log(`Finished!`);
});

// or:
const stream = ytdl(url);
stream.pipe(fs.createWriteStream("video.mp4"));
stream.on("finish", function() {
  console.log(`Finished!`);
});
```

**Comment by fent** [comment]
that's because `.pipe()` returns the destination stream, in this case, the writestream to `video.mp4`. writestreams have a different set of events, including 'finish`.

your first example should work. but the 2nd one is listening to the original read stream, which emits an `end` event

**Comment by josephrocca** [comment]
Oh, good to know, thanks! I didn't test the second one - I just assumed that the two snippets were the same. :|
