### ISSUE TITLE
getInfo Error: Result of expression 'body.includes' [undefined] is not a function. 

### ISSUE THREAD

**Issue by Harryk13** [fent/node-ytdl-core#299]
When do getInfo for some video I have mistake:
"TypeError: Result of expression 'body.includes' [undefined] is not a function." in info.js
This problem work with video where is unavailableMsg. I see it with video was needed get parameter &has_verified=1
Typeof body in this point is String and this has not method includes.

**Comment by fent** [comment]
Could you link the video where this happens?

**Comment by fent** [comment]
ytdl-core goes around the age limit. I'm not getting that error when I try it myself :/

**Comment by Harryk13** [comment]
I have this problem with all video with age limit. This problem started at 12th March, before I had not this problem.

**Comment by TimeForANinja** [comment]
are you running latest version?
the video you provided works for me

**Comment by Harryk13** [comment]
In last version it works
