### ISSUE TITLE
getInfo ignored all get params

### ISSUE THREAD

**Issue by Harryk13** [fent/node-ytdl-core#300]
Some of videos need get params to parse. All this params ignored in your function and we have mistake for this videos.

**Comment by fent** [comment]
What params? The options in the readme?

**Comment by Harryk13** [comment]
Url get params.  https://www.youtube.com/watch?v=Z9D1h5Lnzxk&has_verified=1

**Comment by fent** [comment]
What does the `has_verified` param do? I'm not familiar with it

**Comment by Harryk13** [comment]
This param confirmed your age for some video. When this video start you have a question about your age in youtube account.

**Comment by fent** [comment]
ytdl-core intends to go around the age limit

https://github.com/fent/node-ytdl-core/blob/master/test/irl-test.js#L10-L12

Passing the url params is not necessary.
