### ISSUE TITLE
Is it possible to 'preload' songs?

### ISSUE THREAD

**Issue by FireController1847** [fent/node-ytdl-core#306]
For example, when directly trying to stream a song sometimes it can be quite laggy. Is it possible to 'preload' a song before actually playing it without downloading a file, saving it, then deleting it after it's played once?

Or, another thing that would work for me, is it possible to get the stream of a song initially and then play it 10-15 seconds later so there's minimal lag?

**Comment by fent** [comment]
Use the `highWaterMark` option

```js
ytdl(url, {
  highWaterMark: 1024 * 1024 * 10 // 10 megabytes
})
```

It defaults to 16kb https://nodejs.org/api/stream.html#stream_constructor_new_stream_writable_options

**Comment by FireController1847** [comment]
I guess I'm a little confused with the documentation.. what exactly does that do?

**Comment by fent** [comment]
It's the internal buffer of the stream. The amount you specify is the amount you can write to it before it is consumed. In this case, the ytdl stream is being written to by the request for the video, and is being consumed by the audio player at the speed at which it's playing.

If you add the following to the discord.js example, you'll see that with the default `highWaterMark`, it'll print only a bit of progress little by little until the song ends. With the `highWaterMark` increased, progress will go to 100% way before the song finishes.

```js
        stream.on('progress', (d, total, length) => {
          console.log('progress', total / length);
        });
```

It's also possible that the laggyness is cased by the `audioonly` filter, as pointed at in #294.

**Comment by FireController1847** [comment]
Ah, I didn't realize 294 was an issue. Thanks for explaining, though! :)
