### ISSUE TITLE
Video is Unavailable (Audio Stream Creation)

### ISSUE THREAD

**Issue by SalmonSeasoning** [fent/node-ytdl-core#308]
**The Issue**
I'm having an issue acquiring the audio stream.
Probable Issue Source: [`ytdl(url, {filter:'audioonly'});` (LINE 10)](https://github.com/SalmonSeasoning/SalmonSounds/blob/master/actions/utils/youtube-api/basic.js)
What happens is the stream fails to be created due to the "video being unavailable".
This happens with every single YouTube video. The YouTube API 3 Key is valid and works, and everything
else also works as intended.
I have tried `npm update ytdl-core` and that hasn't fixed anything.
This could potentially be related to issue #307 but I don't have any evidence of that.
This is indeed a Discord Music Bot using the [Discord.js API](https://discord.js.org).

**Log**

> PS C:\Users\qualt\Documents\GitHub\SalmonSounds> node .
(node:12224) ExperimentalWarning: The http2 module is an experimental API.
Logged in as SalmonSounds#9003.
SalmonSounds bot is successfully up and running!
https://www.youtube.com/watch?v=atuFSv2bLa8
(node:12224) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: This video is unavailable
(node:12224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: This video is unavailable
    at C:\Users\qualt\Documents\GitHub\SalmonSounds\node_modules\ytdl-core\lib\info.js:208:16
    at IncomingMessage.res.on (C:\Users\qualt\Documents\GitHub\SalmonSounds\node_modules\miniget\lib\index.js:76:11)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Log Explanation**
Obviously, the bot is started as normal. "SalmonSounds bot is successfully up and running!"
Then I used the `!play` feature with the title "Gas Gas Gas". I had it log the YouTube
video URL if it was successfully acquired. "https://www.youtube.com/watch?v=atuFSv2bLa8"
Then the error "This video is unavailable" appears and kills the program. After some debugging, I've come to the conclusion the error starts after this line of code is ran: [`let _stream = new actions.yt_search.createStream(videoUrl)` (LINE 181)](https://github.com/SalmonSeasoning/SalmonSounds/blob/master/index.js) which runs `ytdl(url, {filter:'audioonly'});` as stated above.
**Small Snippets (For Convenience)**
[index.js](https://github.com/SalmonSeasoning/SalmonSounds/blob/master/index.js)
```	
(new actions.yt_search.search(url)).init().then(videoUrl => {
console.log(videoUrl || 'Does not exist..');
let _stream = new actions.yt_search.createStream(videoUrl);
// ...
});
```
[actions/utils/youtube-api/basic.js](https://github.com/SalmonSeasoning/SalmonSounds/blob/master/actions/utils/youtube-api/basic.js)
```
class createStream{
	constructor(url){
		this.url = url;
		this.stream = ytdl(url, {filter:'audioonly'});
	}
	get_stream(){
		return this.stream;
	}
	getInfo(){
		return ytdl.getInfo(this.url);
	}
}
```

**Comment by fent** [comment]
From the line number in the error stack, it's apparent that the latest version of ytdl-core is not installed, since there is no error with that message [in that line](https://github.com/fent/node-ytdl-core/blob/master/lib/info.js#L208)

Make sure you have the latest version by running

    npm install ytdl-core@latest

**Comment by SalmonSeasoning** [comment]
@fent I appreciate your reply. However, I still think there is an issue with the stream creation. Instead of playing the audio (which *should* happen if the stream were created correctly), it gives me another error. The only difference is that this error is not related due to the out-dated module.
> PS C:\Users\qualt\Documents\GitHub\SalmonSounds> node .
(node:9040) ExperimentalWarning: The http2 module is an experimental API.
Logged in as SalmonSounds#9003.
SalmonSounds bot is successfully up and running!
https://www.youtube.com/watch?v=atuFSv2bLa8
(node:9040) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: message is not defined
(node:9040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I will close this issue and reopen a new one when more information is acquired on my part, if it is found that the issue is indeed just regarding the module. In the meantime, the only thing I ask of you is that you just double check the code where you are creating the stream with `ytdl(string[url], object[filter])`.

Thanks for the reply. Have a good day!

**Comment by fent** [comment]
That doesn't look like a ytdl-core error. That looks like a reference error.
