### ISSUE TITLE
Error: "Cannot find module "ytdl-core""

### ISSUE THREAD

**Issue by FireFoxAssassin** [fent/node-ytdl-core#309]
I have done `npm install ytdl-core -g` before, however `const ytdl = require("ytdl-core")` doesn't work. Help would be appreciated.

**Comment by fent** [comment]
No need to install globally, remove the `-g` flag

**Comment by FireFoxAssassin** [comment]
It still doesn't work

**Comment by FireFoxAssassin** [comment]
Yes, a `ytdl-core` folder exists in the `node_modules` folder. The error specifically says:
`(node:7956) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1) Error: Cannot find module `ytdl-core`
(node:7956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by fent** [comment]
Well this is strange, don't think I've seen this before

Does running `npm ls ytdl-core` show a version installed in the folder?

Is the script you're running inside a folder that can travel up the directory tree, until it finds the `node_modules/ytdl-core/` directory?

Does running the command `node` and then running `require('ytdl-core')` inside of that prompt give an error?

Are you sure `ytdl-core` was the module installed and not the similar module `ytdl`? Sorry this question is a bit dumb, just checking all possibilities

**Comment by FireFoxAssassin** [comment]
1) Yes
![image](https://user-images.githubusercontent.com/21371722/38459958-87a31d2c-3aa8-11e8-8072-41036661b718.png),

2) I don't entirely understand what you mean, my directory to `node_modules` is `C:\Windows\System32\node_modules` whilst index.js is in `C:\Users\User\Documents\Visual Studio 2015\Discord Bots\BotBot`

3)
![image](https://user-images.githubusercontent.com/21371722/38460093-2f6d28a2-3aab-11e8-88d0-8492e2ad9fe6.png)

4) I accidentally installed both 4 hours ago

**Comment by fent** [comment]
> I don't entirely understand what you mean, my directory to node_modules is C:\Windows\System32\node_modules whilst index.js is in C:\Users\User\Documents\Visual Studio 2015\Discord Bots\BotBot

A script travels up directories until it can find a `node_modules` folder in one of those directories. In this case, it'll check

```
C:\Users\User\Documents\Visual Studio 2015\Discord Bots\BotBot\node_modules
C:\Users\User\Documents\Visual Studio 2015\Discord Bots\node_modules
C:\Users\User\Documents\Visual Studio 2015\node_modules
C:\Users\User\Documents\node_modules
C:\Users\User\node_modules
...etc
```

You need to install your node_modules in one of those folders where your script can find it. I don't know if it's standard in Windows to have modules in the System32 directory actually. I thought even global modules were installed in your user directory

**Comment by FireFoxAssassin** [comment]
Ah okay, I managed to fix to by putting the `node-modules` folder within the bot's directory. And honestly, I don't know how the folder ended up in System32. Anyway thanks for the help!
