### ISSUE TITLE
Age restricted video's not reporting error

### ISSUE THREAD

**Issue by LexHimself** [fent/node-ytdl-core#317]
Hi,

info.js
`      if (!body.includes('<div id="watch7-player-age-gate-content"')) {
        return callback(new Error(util.between(body,
          '<h1 id="unavailable-message" class="message">', '</h1>').trim()));
      }`

This piece of code causes an application to freeze since it does not get a response.

`      if (!body.includes('class="subreason style-scope ytd-player-error-message-renderer"')) {
        return callback(new Error(util.between(body,
          '<h1 id="unavailable-message" class="message">', '</h1>').trim()));
      }`

This resolves the issue, an error is thrown back, and i can use the application further. 

Would it be possible to research this further? My locale is NL.

**Comment by fent** [comment]
Age restricted videos don't throw an error. Their info is still retrieved

https://github.com/fent/node-ytdl-core/blob/master/test/irl-test.js#L10-L12

Can you clarify what you mean by your app freezing? Is no error or response given with age restricted videos? Is an error thrown but not caught?

Is there a video you have where this happens?

**Comment by fent** [comment]
Hi, just published a fixed for this, v0.20.4. Please update and see if this fixes it for you.

Nice app you have there btw :)
