### ISSUE TITLE
"npm install ytdl-core@latest" does not install v0.20.3

### ISSUE THREAD

**Issue by Some-Dood** [fent/node-ytdl-core#319]
I've been having troubles with my Discord music bot lately, and I finally found what's causing my problems. I caught the error in the console which says:

`Error: This video is unavailable.
    at request (C:\Users\Some-Dood\Desktop\DiscordBot\node_modules\ytdl-core\lib\info.js:64:25)
    at IncomingMessage.res.on (C:\Users\Some-Dood\Desktop\DiscordBot\node_modules\miniget\lib\index.js:76:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

I looked into the issue and found out that I was using an old version of the module, which was v0.20.2. Hoping that I could receive the latest update to fix my issues, I entered `npm install ytdl-core@latest` into my command line. For some reason, it does not download v0.20.3. Instead, it re-downloads the old version I already had installed.

Further investigation lead me to the [npmjs page of ytdl-core](https://www.npmjs.com/package/ytdl-core), which was outdated. The latest version listed was still v0.20.2. I only request that this be solved. Thanks!

*I will open a new issue if even the latest update fails to resolve my original issue.

**Comment by Some-Dood** [comment]
Thanks for being such a chill guy, man. I appreciate it.

Anyway, um, I couldn't really find an "available" video. Could you send me a video link you think could produce positive results? I'll tell you if it works.

**Comment by fent** [comment]
Well if you can view a video in your browser, and it's not private or paid, it should also be available through ytdl-core. If it's not, it's an error with ytdl-core.

If you need a video, this one works for me: https://www.youtube.com/watch?v=4VT72T2RgGM

**Comment by Some-Dood** [comment]
Unfortunately, I still receive the same error. My code can't be flawed because the only error thrown (and caught) happens to be that same error. I don't know what's wrong honestly. Could you give me a layman's breakdown on how the module interacts with YouTube to return the stream? Perhaps that way I could see if the problem lies with my computer or the module?

**Comment by fent** [comment]
The stack trace from the first error above suggests that it's coming from line 64, but that error is now at [line 225](https://github.com/fent/node-ytdl-core/blob/master/lib/info.js#L225)

This makes me suspicious that you might still be running an older version. Do you use a bot that depends on ytdl-core? It might be listing an old version on its `package.json`

**Comment by Some-Dood** [comment]
Okay, so here's the error log again if you need it. I tested my bot again just a few minutes ago, and this was the error. And yes, my bot does depend on ytdl-core. The `package.json` says that it depends on `"^0.20.3"` if that helps.

```
Error: This video is unavailable.
    at request (C:\Users\Some-Dood\Desktop\DiscordBot\node_modules\ytdl-core\lib\info.js:64:25)
    at IncomingMessage.res.on (C:\Users\Some-Dood\Desktop\DiscordBot\node_modules\miniget\lib\index.js:76:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by tarnpreetb123** [comment]
I have having this exact same issue running ytdl-core on version 0.20.2. However, when I run my discord.js bot from my local computer everything is fine and no error but when I run it on heroku I get the error.

> 2018-05-09T13:47:25.445469+00:00 app[worker.1]: Error: This video is unavailable
2018-05-09T13:47:25.445487+00:00 app[worker.1]:     at IncomingMessage.res.on (/app/node_modules/miniget/lib/index.js:75:11)
2018-05-09T13:47:25.445485+00:00 app[worker.1]:     at request (/app/node_modules/ytdl-core/lib/info.js:221:16)
2018-05-09T13:47:25.445493+00:00 app[worker.1]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-05-09T13:47:25.445489+00:00 app[worker.1]:     at emitNone (events.js:110:20)
2018-05-09T13:47:25.445490+00:00 app[worker.1]:     at IncomingMessage.emit (events.js:207:7)
2018-05-09T13:47:25.445492+00:00 app[worker.1]:     at endReadableNT (_stream_readable.js:1057:12)

**Comment by fent** [comment]
Could you run the following to check if there are more than one version of ytdl-core installed?

    find ./node_modules -type d -name ytdl-core

**Comment by fent** [comment]
Sorry, that command is for a unix machine. What does `npm ls ytdl-core` print?

**Comment by Some-Dood** [comment]
The fault's on me, man. No need to apologize. I should've told you my operating system from the start. It's Windows by the way.

`-- ytdl-core@0.20.3`

**Comment by fent** [comment]
I'm not sure what to do since you seem to have the latest version installed :/

Did this work for you before in some other computer, connection, environment, or with a different bot?

Does running some of the [examples](https://github.com/fent/node-ytdl-core/tree/master/example) work?

**Comment by Some-Dood** [comment]
I'm afraid it has never worked for me. I've been facing this trouble for months now, and it has gotten to the point that I needed to report on it. I thought the previous releases would fix it, but alas...

I shall run the examples now. By any chance, do you think this is a regional issue? Perhaps I couldn't stream the videos because of my region?

Oh, and I logged the StreamDispatcher's "end" event and it always returns `undefined` as the reason for closing the stream. Does that help you investigate into things?

**Comment by Some-Dood** [comment]
UPDATE: The example worked because I hard-coded all the variables. I'm looking into the situation now and reviewing my code. I feel like I mishandled the URL somewhere in between the lines. I have never been so happy to listen to the Rickroll my whole life. Thanks! I'll close the issue as soon as I resolve my code.

**Comment by Some-Dood** [comment]
ANOTHER UPDATE: I discovered something strange. For some reason, the module **only** works if I hard-code the URL parameter. YTDL **does** work if I hard-code the variable as in `let url = "some URL";` but it fails if I were to derive the URL from an array as in `ytdl(args[someIndex]);`. Why does that happen?

If it wasn't clear, let's say I had an array `args` that stored the arguments of the message/command by the user. YTDL does not work if one were to access the array's elements and use the returned string as the URL for the first parameter of `ytdl(url)` in such a way that it is `ytdl( args[someIndexWhereTheStringURLis] )`.

However, if I were to do this instead, it would work:
```JavaScript
let url = "some URL";
const stream = ytdl(url);
const dispatcher = connection.playStream(stream);
```

But then it would fail again if I do this:
```JavaScript
let url = args[someIndex]; // The line of code in error
const stream = ytdl(url);
const dispatcher = connection.playStream(stream);
```

It's very strange because if I log the returned string of `args[someIndex]` or `url`, they both return the same string. I'm not sure how the JavaScript engine works so could anyone help here?

**Comment by Some-Dood** [comment]
__**FINAL UPDATE**__
I finally got my code to work. You'll never believe what has been causing my errors. I'm so sorry. I'm embarrassed now. Part of the validation process of the messages require the whole string to be converted to lower case. With that said, I have been converting the whole YouTube link to lower case, which is very bad because video IDs are in Base64 (with a few extra symbols inserted by Google). Converting the URLs to lower case completely ruins the whole link.

Again, I'm sorry for the past week of troubleshooting. I'm just in awe on how I could've missed it. I'm closing this issue now. So many thanks for your help!

**Comment by fent** [comment]
That's pretty funny. And no worries, it happens to all of us. Glad you found the issue.
