### ISSUE TITLE
Any age-restriction or rating metadata?

### ISSUE THREAD

**Issue by cloewen8** [fent/node-ytdl-core#321]
I am trying to prevent users from playing videos that do not fit our community rules. I've searched through the data provided by getInfo and haven't found anything. Can I get this information through ytdl? Or do I need to get this information from another source? I am specifically looking for an mpaa rating, but can use other rating systems as needed.

**Comment by fent** [comment]
There isn't a property that's currently there. But this could be added since ytdl-core has different logic paths for age restricted content.
