### ISSUE TITLE
High RAM usage?

### ISSUE THREAD

**Issue by FireController1847** [fent/node-ytdl-core#323]
I don't see anyone else having this issue and it may be specific to my application, but I'm going to ask here just in case anyone else notices this aswell.

When you "stream" directly from a YouTube URL, does it store said video in RAM instead of directly streaming it? I get that it pulls from YouTube faster than playback will play the video, but if it continually does that won't that build up in RAM?

This has never been an issue for me until about a month ago. I noticed that once I had increased playback buffer (because we had lag issues), RAM usage got worse. Before I could play ~20 videos at a time before hitting barley 4G. Now I can only do about ~12 before I hit 12G (the manual limit).

Here's a test snippet if you guys would like to try it. This is untested so if I need to fix something lemme know:
```js
const yt = require('ytdl-core');
// Simulate a workload.
const videos = []; // Put 12-20 video links in here, make sure they're ~3 minute videos (songs). They can be longer but may give different results.
const streams = [];
for (let i = 0; i < videos.length; i++) {
  streams.push(yt(videos[i], { quality: 'highestaudio' });
}
```

**Comment by fent** [comment]
> When you "stream" directly from a YouTube URL, does it store said video in RAM instead of directly streaming it? I get that it pulls from YouTube faster than playback will play the video, but if it continually does that won't that build up in RAM?

The stream it gives is chunked, and stores some video data in memory up to a certain limit. You can give the `highWaterMark` option to ytdl to change this limit, it uses the default stream value

https://nodejs.org/api/stream.html#stream_constructor_new_stream_writable_options

After this limit is reached, it won't store get any more video data until some data in memory has been consumed.

> This has never been an issue for me until about a month ago. I noticed that once I had increased playback buffer

How are you doing this?

**Comment by FireController1847** [comment]
I'm really sorry about this, I just have so many issues understanding the `highWaterMark` option. What I meant by 'increasing the playback buffer' is increasing the highWaterMark.

I guess what I don't understand is, when the data in memory has been consumed is it removed? Because it doesn't seem like it. At this point, I've completely removed the highWaterMark option and I still have this issue.

A couple months ago, my bot could handle 45-50 streams at a time without consuming too much RAM on a 16 GB machine. Then, I tested out the 'highWaterMark' option and the 'highestaudio' option instead of 'audioonly'. Could the casue of this not be related to 'highWaterMark' and instead be an issue with 'highestaudio' vs 'audioonly'?

**Comment by fent** [comment]
> I guess what I don't understand is, when the data in memory has been consumed is it removed?

Yes

> Then, I tested out the 'highWaterMark' option and the 'highestaudio' option instead of 'audioonly'. Could the cause of this not be related to 'highWaterMark' and instead be an issue with 'highestaudio' vs 'audioonly'?

`highestaudio` does have much larger files, since often, they will also include a video. But even so, it should only be downloading as much as it needs, as it's being consumed by your bot. It does sound like there's a problem somewhere, but I'm not sure where.

**Comment by FireController1847** [comment]
Alright, well I'll close this and see if the issue persists with the next version of my bot. If it does, I'll reopen.

**Comment by FireController1847** [comment]
Okay, I'm not sure if this is a node issue but after doing node --inspect Client.js, every time a song plays the Audio Buffer gets larger and does not decrease in file size after the stream has been consumed. It can gather up to 50 MB in memory before the song ends and it drops.

This does _not_ happen using your progress.js example, oddly enough.
