### ISSUE TITLE
change var to es6 standard

### ISSUE THREAD

**Issue by rubs019** [fent/node-ytdl-core#324]
Maybe you have a reason I don't understand, but I'd like to replace "var" for const or let, depending on the situation, to meet the ES6 standard.
Let me know if this is of interest to you.

**Comment by fent** [comment]
I don't really have a good reason to keep `var`. At the time when updating to es6, I thought `var` could live alongside `const` and `let`, but it looks like it was meant to be replaced.

It is of interest to me 👍
