### ISSUE TITLE
Expected format is now incorrect

### ISSUE THREAD

**Issue by BaileyJM02** [fent/node-ytdl-core#326]
The expected format `/^[a-zA-Z0-9-_]{11}$/` is now incorrect for youtubes new algorithm. 

These links are all valid however not recognised in this package: 
- https://www.youtube.com/playlist?list=PLDIoUOhQQPlU2NpvlGKTsQRoCMHTUCLMf
- https://www.youtube.com/playlist?list=PLx0sYbCqOb8Q_CLZC2BdBSKEEB59BOPUM
- [etc..]

**Also**: 
A recommendation that, when searching the URL params, the `list` param is found first so it therefor downloads the playlist instead of the single video, example:
- https://www.youtube.com/watch?v=ffxKSjUwKdU&list=PLx0sYbCqOb8Q_CLZC2BdBSKEEB59BOPUM

**Comment by TimeForANinja** [comment]
There's the official yt api to resolve playlists

**Comment by BaileyJM02** [comment]
Is there anyway to edit the expected format on my bot?
So `/^[a-zA-Z0-9-_]{11}$/` => `/^[a-zA-Z0-9-_]{34}$/`?

**Comment by TimeForANinja** [comment]
That would not work for both, playlists and videos
Also you can't parse a Playlist like a video🤔
