### ISSUE TITLE
'audioonly' option not downloading properly

### ISSUE THREAD

**Issue by JiNama** [fent/node-ytdl-core#327]
When I specify to only download the audio and pipe it into a .mp3 file, the file's download gets stuck super early on into the download and never continues downloading.

`ytdl(text, {
        quality: 'highestaudio',
        filter: 'audioonly'
      }).pipe(fs.createWriteStream(path + "/" + title + '.mp3'));`

where 'text' is the url.

Downloading as a video works perfectly and so does downloading the entire video w/o the audioonly and saving as an mp3 but doing that still includes the video data in the file.

**Comment by fent** [comment]
I think that's short for "something useful"

Do you have a video link where this happens? Or is it happening for all? I've tried reproducing with the [progress example](https://github.com/fent/node-ytdl-core/blob/master/example/progress.js) by adding the `quality` and `filter` options, with no success.

The download slows down, but it doesn't completely stop. This is typical of the formats found with `audioonly`. See #294

**Comment by JiNama** [comment]
@fent okay so I let the download go for awhile and they do actually eventually download. I definitely should've done a progress check first. Sorry about that! Everything is working now.
