### ISSUE TITLE
discord.js music bot using ytdl having playback problem

### ISSUE THREAD

**Issue by KannaDev** [fent/node-ytdl-core#331]
I am making a discord music bot using the ytdl-core library. I also use node-opus and ffmpeg. So, the dependencies are not an issue. 
The bot loads the song fine, its the playback thats having problem. Here is the hastebin for my code: https://hastebin.com/dokoguqoqu.js

It successfully outputs Now Playing which means there are no errors. However right after the bot joins the voice channel it never plays the song instead a second after it joins it executes the dispatcher.on(end) command and outputs Finished Playing. 

The audio from the youtube video is loaded but never played.

**Comment by TimeForANinja** [comment]
Your use of ytdl getInfo is not needed since ytdl() fires an event with the same data - second you should start the ytdl stream by itself and listen for errors it throws - then use it to create the dispatcher

**Comment by fent** [comment]
Not able to replicate :/

Does this happen for any song for you?

**Comment by kanna6501** [comment]
@fent yes. I've tried different songs from different content creators. Still the same issue.

**Comment by fent** [comment]
There might be an error with the ytdl stream. Try something like

```js
  let stream = ytdl(url, { filter: 'audioonly' });
  stream.on('error', console.error);
  let dispatcher = await connection.playStream(stream)
```

and see if there is an error.

Normally, uncaught errors will be shown in the console. But the `connection.playStream()` function seems to swallow any error emitted by the stream.

**Comment by fent** [comment]
There's a reference error in the error listener, variables `e` and `error` don't match.

**Comment by kanna6501** [comment]
@fent that was just a typo in the comment.
```
.on("error", e => {
console.error(e);
message.channel.send(....);
}
```

Still same issue. Joins and Leaves.

**Comment by kanna6501** [comment]
it doesn't work if i use it with discord.

**Comment by fent** [comment]
As noted in #332 , the issue might be with using `ytdl.getInfo()` immediately followed by `ytdl()` on the same video. If you're getting the video info beforehand, you can use [`ytdl.downloadFromInfo()](https://github.com/fent/node-ytdl-core#ytdldownloadfrominfoinfo-options).

Could you try it and let me know if that works?

```js
let stream = ytdl.downloadFromInfo(info, {filter: 'audioonly'})
```

**Comment by kanna6501** [comment]
@fent That fixed the playback problem. Thank You!
