### ISSUE TITLE
NOT AN ISSUE: Downloading the songs is slow..

### ISSUE THREAD

**Issue by RazorApple** [fent/node-ytdl-core#335]
Why dont we stream them from youtube? I cant find an way to do this.. There should be an link to acess the music from an youtube video like https://youtube.com/wUHf8hf6h4.mp3
P.S. add an label called QUESCION
sorry for bad english

**Comment by TimeForANinja** [comment]
that link is dead for me...

**Comment by fent** [comment]
Some formats are slow, see https://github.com/fent/node-ytdl-core#limitations
Everything is downloaded from youtube
