### ISSUE TITLE
Every video unavailable

### ISSUE THREAD

**Issue by kironix** [fent/node-ytdl-core#337]
title. not sure what else to say so lmk if u need any other info.

**Comment by kironix** [comment]
Strange, i haven't changed the code since it worked. Here it is anyway:

```const ytdl = require("ytdl-core");```
...
```queue.push(args[0]);
    ytdl.getInfo(queue[0]).then((info) => {msg.channel.send("Added " + info.title + " to the queue")})
    if (!msg.guild.voiceConnection) {
      msg.member.voiceChannel.join().then( (connection) => { 
        play(connection, msg)
      })
    }```
...
```function play(connection, msg) {
  ytdl.getInfo(queue[0]).then(info => {
    msg.channel.send("Now playing **" + info.title + "**")
  })
  dispatcher = connection.playStream(ytdl(queue[0], {filter: "audioonly"}))
  queue.shift();
  dispatcher.on("end", function() {
    if (queue[0]) {
      play(connection, msg);
    } else {
      connection.disconnect();
    }
  })
}```

**Comment by Themayu** [comment]
I'm also having this issue. The error output is as follows:
```JS
> Error: This video is unavailable
    at /home/gamershy/Bot/FB-dev/node_modules/ytdl-core/lib/info.js:208:16
    at IncomingMessage.<anonymous> (/home/gamershy/Bot/FB-dev/node_modules/miniget/lib/index.js:75:11)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:440:23)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

and my testing code is as follows:
```JS
var url = "https://www.youtube.com/watch?v=-ukNDmmTOLM"; // #1 on Trending
var stream = ytdl(url).on("error", err => console.log(err.stack));
```

I have tried this with a great deal many videos, and all of them give the above error after a couple of seconds of waiting time.

**Comment by TheAkio** [comment]
Apperantly you can't play "Topic Videos" or something... I'm not sure what YouTube did this time but you might want to check if you can get YTDL to work with the following track. It doesn't work for us but most other videos work: https://www.youtube.com/watch?v=HGEAt1ORBlw

**Comment by FireController1847** [comment]
The song @TheAkio linked is working perfectly fine for me.

**Comment by FireController1847** [comment]
The song @TheAkio linked is working perfectly fine for me and the test code @Themayu posted works fine for me.

**Comment by TheAkio** [comment]
I guess we were using an older version of ytdl-core then. I tried again today after our dependencies were updated and it worked. Might be some slightly broken version the Issue Author used so it didn't work for him.

**Comment by kironix** [comment]
I have even reinstalled node and reinstalled every single npm module at their latest version. I am still getting this error. Please help.

**Comment by TheAkio** [comment]
I would try out the code from @Themayu and see if that works. Can't test it myself atm. Might be that you are pushing an incorrect item into your queue.

**Comment by kironix** [comment]
I dont understand that code honestly.

That said, if i comment out any `.getinfo` in my code i no longer get the error, but the bot still immediately disconnects from the VC without playing anything. i've logged the queue to the console and it is indeed a youtube url being passed to the play function

```
//main file

  if (command === ".play") {
    if (msg.channel.id !== "462448191716065280") {
      return msg.reply("Use music commands in the <#462448191716065280> channel!");
    }
    if (!msg.member.voiceChannel) {
      return msg.reply("Join a voice channel first!");
    }
    if (!args[0] || !ytdl.validateURL(args[0])) {
      return msg.reply("Provide a youtube URL!");
    }
    if (!msg.guild.voiceConnection) {
      msg.member.voiceChannel.join().then( (connection) => { 
        music.play(connection, msg, args[0])
      })
    }
  }

//music.js

module.exports = {


  play: async function(connection, msg, link) {
    if (link) queue.push(link);
    console.log(link);
    console.log(queue);
    dispatcher = connection.playStream(ytdl(queue[0], {filter: "audioonly"}));
    queue.shift();
    dispatcher.on("end", function() {
      if (queue[0]) {
        play(connection, msg);
      } else {
        connection.disconnect();
      }
    })  
  }
}
```

**Comment by kironix** [comment]
yes, link prints the link alone and queue prinkts ['link here']

**Comment by fent** [comment]
Will keep this opened.

What does the link look like? Do you have some logs?

**Comment by kironix** [comment]
```https://www.youtube.com/watch?v=ak4totbeuyu
[ 'https://www.youtube.com/watch?v=ak4totbeuyu' ]

```
this is all that was output from the code i posted above. after that, the bot leaves the voice channel.

**Comment by fent** [comment]
If you go to that link in your browser, it's not available: https://www.youtube.com/watch?v=ak4totbeuyu

Are you using `.toLowerCase()` on your links or messages?

**Comment by kironix** [comment]
I am very embarassed and very sorry. Total oversight >.<

Thanks a lot for your patience and help mr/mrs fent

**Comment by fent** [comment]
No problem. It's actually happened before.
