### ISSUE TITLE
ERROR: using proxy

### ISSUE THREAD

**Issue by stanJ** [fent/node-ytdl-core#341]
There are some errors when I use proxy, and I can watch video normally. code and error info as below:
```
let url = 'https://www.youtube.com/watch?v=P6UAyWjC6S0'
ytdl.getInfo(url, {
  requestOptions: {
    transform: (parsed) => {
      console.log(parsed)
      return {
        host: '127.0.0.1',
        port: 1080,
        path: '/' + parsed.href,
        headers: { Host: parsed.host },
      };
    },
  }
}, function (err, info) {
  if (err) {
    console.log(err)
  } else {
    console.log(info)
  }
})
```

>{ Error: write EPROTO 140735936611264:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:at WriteWrap.afterWrite [as oncomplete] (net.js:836:14) errno: 'EPROTO', code: 'EPROTO', syscall: 'write' }

**Comment by nival999** [comment]
@yarsky-tgz , can you give a quick description on how to get this to work?
