### ISSUE TITLE
How to use range with time ?

### ISSUE THREAD

**Issue by xchopin** [fent/node-ytdl-core#345]
Hi,

I've read the documentation and I saw an interesting function called range() ` range - A byte range in the form {start: INT, end: INT} that specifies part of the file to download. ie {start: 10355705, end: 12452856}. Note: this downloads a portion of the file, and not a separately spliced video`

How are you supposed to know the byte of a video at X seconds ? 

Thanks

**Comment by TimeForANinja** [comment]
```
begin - What time in the video to begin, supports formats 00:00:00.000, or 0ms, 0s, 0m, 0h, or number of milliseconds. Example: 1:30, 05:10.123, 10m30s. This option may not work on super short (less than 30s) videos, and has to be at or above 6s, see #129. It may also not work for some formats, see #219. For live videos, this also accepts a unix timestamp or Date, and defaults to Date.now().
```

**Comment by fent** [comment]
Unfortunately, `range` only works with bytes, not with video time. There is the `begin` option, but it's a bit unreliable. And there is no `end` option to complement it.

If you want a reliable way to splice a video with a given time range, you'll have to use something like ffmpeg.

**Comment by PhongVu07** [comment]
Hi @fent, it has been 4 years, is there an upgrade to this?
