### ISSUE TITLE
Youtube Music

### ISSUE THREAD

**Issue by Tylertron1998** [fent/node-ytdl-core#348]
Long shot, but any chance of using the youtube music api? There is a particular API youtube uses now for music, I'm not sure if you can figure it or not. Would be amazing if you could!

https://music.youtube.com/

**Comment by fent** [comment]
It looks like it's all playlists that are still hosted on main site youtube

So this
https://music.youtube.com/watch?v=mtLgabce8KQ&list=RDAMVMmtLgabce8KQ

Can still be watched/listened to at
https://www.youtube.com/watch?v=mtLgabce8KQ

If anything, I could  add the `music.youtube.com` domain to the list of acceptable inputs.

**Comment by Tylertron1998** [comment]
Ah, so the API is the same? I though that it would be nicer to use for people who only use ytdl-core for music, as (I'd imagine) the videos are stripped of the video and are just audio.

**Comment by Tylertron1998** [comment]
Ah, that seemed to be just the one video I watched on there, lol.
Is there no difference between the two?

**Comment by fent** [comment]
Briefly looking at the network requests, it looks like it uses the same endpoints as the other video pages. Including `/get_video_info`, html5player, and googlevideo.com
