### ISSUE TITLE
Exception thrown with .getAuthor and failed regex

### ISSUE THREAD

**Issue by kelyvin** [fent/node-ytdl-core#349]
Hi, 

I sometimes run into the following exception that is thrown when calling `.getInfo`. 

```
'TypeError: Cannot read property \'1\' of null',
     '    at Object.exports.getAuthor (/Users/Kelvin/Workspaces/app/node_modules/ytdl-core/lib/util.js:419:21)',
     '    at request (/Users/Kelvin/Workspaces/app/node_modules/ytdl-core/lib/info.js:52:20)',
     '    at IncomingMessage.res.on (/Users/Kelvin/Workspaces/app/node_modules/miniget/lib/index.js:76:11)',
     '    at emitNone (events.js:111:20)',
     '    at IncomingMessage.emit (events.js:208:7)',
     '    at endReadableNT (_stream_readable.js:1055:12)',
     '    at _combinedTickCallback (internal/process/next_tick.js:138:11)',
     '    at process._tickCallback (internal/process/next_tick.js:180:9)
```

This occurs in the following line https://github.com/fent/node-ytdl-core/blob/master/lib/util.js#L415 because `channelMatch` results in a `null` value. 

This seems to occur sporatically when fetching "author" data. I'm not sure if a potential better solution exists, but a quick non-breaking solution is to create a check to see if the regex returns a proper result, and if it doesn't, simply return an empty object for `author`. In its current state, the request is async so I cannot properly handle the exception when this occurs either. :(

Thanks for the help!

**Comment by kelyvin** [comment]
Looks like this is potentially solved with the following pull request: https://github.com/fent/node-ytdl-core/pull/340

**Comment by fent** [comment]
I should have asked what videos this happens on? Better solution is to look at those videos and see where the author info is on those pages.

**Comment by fent** [comment]
Will keep this opened until we find those videos and parse the author info properly.

**Comment by kelyvin** [comment]
It occurred on the first youtube link that I tried. The one I received the exception on was:
https://www.youtube.com/watch?v=elwTgpHlty0

It happens sporadically (i.e. sometimes the author metadata was returned, and sometimes it didn't). Didn't get a chance to see the payload that was being parsed.

**Comment by fent** [comment]
Are you passing any options to ytdl?

**Comment by kelyvin** [comment]
Nope no options. My code block was simply:

```javascript
return ytdl.getInfo(videoId)
    .then((info) => {
     ...
    })
```

**Comment by fent** [comment]
I'm finding that if I request the watch page through my browser, I get a different html structure than if I request it through node or the command line. Maybe it has to do with the `User-Agent` header, are you setting any headers for the requests?

**Comment by kelyvin** [comment]
I am not setting any headers for the request. My example code block is currently implemented in Node and the code block and gets called from a REST API endpoint. 

In its current state, the REST API is a `POST` endpoint, but solely acts as a pass-through with no additional modifications/options made to `ytdl.getInfo`; i.e. it does not take in any additional headers (besides the `content-type` header) and the request body expects a `videoId`. This video id will be passed into `ytdl.getInfo(videoId)` and the result of this promise gets passed back as the response of the API. 

Before the fix was made, this API request would hang from the exception and not respond due to the promise never resolving. It would happen maybe ~70% of the time, and the remaining 30% of the time, it would return the proper author metadata. Hope that helps!

**Comment by fent** [comment]
Thanks for the detailed response. So right now, you're not getting author info for most of the videos you query? When you next encounter one that doesn't have author info, do you mind sharing the url of the video? I've just had trouble replicating this :/

**Comment by kelyvin** [comment]
Have you tried the one I linked earlier? This one: 
https://www.youtube.com/watch?v=elwTgpHlty0

That is one where I only receive the author info sometimes.

**Comment by fent** [comment]
Oh sorry, forgot it was posted.

Ok, so I'm still unable to reproduce. Last resort, but do you mind diffing your version of ytdl-core with the following, then when it happens next, upload the page it saves?

```
diff --git a/lib/info.js b/lib/info.js
index 6c38ef6..0973d98 100644
--- a/lib/info.js
+++ b/lib/info.js
@@ -45,6 +45,7 @@ exports.getBasicInfo = (id, options, callback) => {
           '<h1 id="unavailable-message" class="message">', '</h1>').trim()));
       }
     }
+    require('fs').writeFileSync('./watch_page.html', body, 'utf8');
 
     // Parse out additional metadata from this page.
     const additional = {
```

**Comment by fent** [comment]
The newest ytdl-core version has some changes on how it extracts author info. Feel free to try it and lemme know if the problem persists.

**Comment by kelyvin** [comment]
Oh shoot I totally forgot to follow up on this. Huge apologies! I'll give it a try later today and let you know if I see if it the problem still exists. Thanks a bunch!

**Comment by kelyvin** [comment]
After running some tests, it seems like I no longer encounter this issue! Thanks a bunch for your help, I will close this ticket now.
