### ISSUE TITLE
Compatibility with browserify

### ISSUE THREAD

**Issue by mallendeo** [fent/node-ytdl-core#35]
Hi, I'm working in porting this to the browser so it can be used in PhoneGap.

Out of the box, "compiling" this with browserify doesn't work, it seems that it's a problem with the request module (see issue [#1737](https://github.com/request/request/issues/1737)), also the bundle size is around 2.3M.

[Here](https://github.com/mallendeo/node-ytdl-core) is my progress, the final bundle size is 422k uncompressed, 233k minified and ~65k gzipped.

The first test is failing (download).

**Comment by fent** [comment]
Good idea with minimizing the dependencies. I've applied a couple of your commits on here.

did removing the request dependency work?

**Comment by andrewrk** [comment]
+1 removing request dependency. The built-in http and https modules are actually pretty straightforward to use.

**Comment by andrewrk** [comment]
FWIW here's how I download files:

```js
var http = require('http');
var https = require('https');
var url = require('url');

exports.download = download;

var whichHttpLib = {
  'http:': http,
  'https:': https,
};

function download(urlString, cb) {
  var parsedUrl = url.parse(urlString);
  var httpLib = whichHttpLib[parsedUrl.protocol];
  if (!httpLib) return cb(new Error("Invalid URL"));

  parsedUrl.agent = false;
  parsedUrl.rejectUnauthorized = false;
  httpLib.get(parsedUrl, function(res) {
    cb(null, res);
  }).on('error', function(err) {
    cb(err, null);
  });
}
```

[source](https://github.com/andrewrk/groovebasin/blob/master/lib/download.js)

**Comment by mallendeo** [comment]
@fent at the moment everything works fine, I can get correct urls for every video. The only problem is the download (downloadFromInfoCallback).

**Comment by fent** [comment]
I just pushed a change that gets rid of a bunch of the deps. Pretty much like your current fork, idk if it'll be any better if downloading still doesn't work for you with the native node http(s) libraries.

**Comment by mallendeo** [comment]
Great! I'll work in the description regex
Downloading is not a problem, I'll use LocalStorage

Thanks
