### ISSUE TITLE
Error: Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by PKPear** [fent/node-ytdl-core#352]
So I simply downloaded ytdl-core, grabbed the usage example, which is:
**const ytdl = require('ytdl-core')**
**const fs = require('fs')**

**ytdl('http://www.youtube.com/watch?v=A02s8omM_hI')**
 **.pipe(fs.createWriteStream('video.flv'));**

then saved it as aaa.js, and ran it using 
**node aaa**
and I get an error which is

**Error: Could not extract signature deciphering actions**
    **at request (directory_removed_because_privacy_stuff\node_modules\ytdl-core\lib\sig.js:36:18)**
    **at IncomingMessage.res.on (directory_removed_because_privacy_stuff\node_modules\miniget\lib\index.js:76:11)**
    **at IncomingMessage.emit (events.js:164:20)**
    **at endReadableNT (_stream_readable.js:1054:12)**
    **at _combinedTickCallback (internal/process/next_tick.js:138:11)**
    **at process._tickCallback (internal/process/next_tick.js:180:9)**

I then do what the guide also says, and I do the mocha test, which returns:
 **Try downloading videos without mocking**
    **Regular video**
      **1) "before each" hook for "Request status code is not 403 Forbidden"**

  **0 passing (73ms)**
  **1 failing**

  **1) Try downloading videos without mocking**
       **"before each" hook for "Request status code is not 403 Forbidden":**
     **TypeError: Cannot read property 'clear' of undefined**
      **at Context.beforeEach (test.js:22:20)**
This is suggesting to me that the signature is undefined.

Any ideas on how to fix this?

Also sorry if this isn't helpful, this is my first time reporting an issue on GitHub

**Comment by fent** [comment]
What version of ytdl-core do you have? Make sure you're on the latest version

    npm install ytdl-core@latest

**Comment by PKPear** [comment]
Okay, I did that and it worked
Thanks for your help, sorry if I wasted your time or anything on my lack of knowledge about npm

**Comment by TimeForANinja** [comment]
Guess we should go for a issue template asking for general thinks like: OS, node Version, ytdl-core Version, Video if any, guide to reproduce the error if possible
and whether the user did try to reinstall ytdl-core at latest version

**Comment by fent** [comment]
> Guess we should go for a issue template asking for general thinks like: OS, node Version, ytdl-core Version, Video if any, guide to reproduce the error if possible
> and whether the user did try to reinstall ytdl-core at latest version

It's done :)
