### ISSUE TITLE
Any interest in a chat server?

### ISSUE THREAD

**Issue by fent** [fent/node-ytdl-core#353]
Not just for bug and usage support. But also for general discussion about the library, similar libraries, future plans, sharing related projects, etc.

Not sure if there's any interest at all, so thought I'd ask.

**Comment by gohjoseph** [comment]
I'd be interested

**Comment by DUFC-Liam** [comment]
Same, lol

**Comment by unknownguy2002** [comment]
A chat server? That sounds interesting. Maybe try using discord(Alot of discord bots use ytdl-core)

**Comment by HcgRandon** [comment]
@fent extremely interested, my 2 cents would be on using discord.

**Comment by ndr3w221** [comment]
Yea discord

**Comment by ndr3w221** [comment]
@fent I can help you with discord, just email me at kalaz.bb@gmail.com

**Comment by unknownguy2002** [comment]
@ndr3w221 I suppose you have discord? Whats your tag? Mine is unknownguy2002#4392

**Comment by fent** [comment]
Ok, I just created a discord server: https://discord.gg/S47e3N

I'll add a link to it on the readme in a bit

**Comment by unknownguy2002** [comment]
Server link broken.

**Comment by DUFC-Liam** [comment]
https://discord.gg/jYmAVMy - Perma link
