### ISSUE TITLE
Need a example of getting a stream from a Youtube live video

### ISSUE THREAD

**Issue by bahaa96** [fent/node-ytdl-core#356]
I saw a more than 25 issue about live streams could you implement a simple example to get a stream from a Youtube live video ?

**Comment by DUFC-Liam** [comment]
```
this.stream = ytdl(`https://www.youtube.com/watch?v=___________`, { begin: Date.now(), filter: "audioonly" });
this.dispatcher = this.connection.playStream(this.stream);
```
NOTICE: This has not been tested yet- I shall test if this works soon (i'll update once tested)
Source #355

**Comment by fent** [comment]
A good number of the examples will work with live streams.

The example in the readme will work too

```js
ytdl('http://www.youtube.com/watch?v=A02s8omM_hI')
  .pipe(fs.createWriteStream('video.flv'));
```

But there's no progress output on it, and it'll continue to write to a file as long as the stream is running.

'begin: Date.now()` is not needed, since it's the default for live streams.
