### ISSUE TITLE
Error 100

### ISSUE THREAD

**Issue by zohon** [fent/node-ytdl-core#36]
Error 100 for content associated with canceled account.
it trigger an error and stop the application
at gotConfig /ytld-core/lib/infos.js:130:21

you can try with https://www.youtube.com/watch?v=UarIvA7g4uc

**Comment by fent** [comment]
did you try going to that video page? seems like a legit error

**Comment by fent** [comment]
you might also be using an outdated version, there is no file named infos.js

**Comment by zohon** [comment]
yes the video has an error but is there a way to avoid the application stop when triggering an error ?

the file i talk about is https://github.com/fent/node-ytdl-core/blob/master/lib/info.js at line 130

thanks for the response.

**Comment by fent** [comment]
check if there is an error and do whatever you want with it

```js
var stream = ytdl(yrl);
stream.on('error', function(err) {
  // stuff
});
```

**Comment by zohon** [comment]
ok thanks a lot for the response

**Comment by zohon** [comment]
Ok found my problem.

when the stream go on error it doesn't stop the .pipe(fs.createWriteStream(base))

to correct it i just add 

var fsInfo = fs.createWriteStream(urlBase);
var stream = ytdl('https://www.youtube.com/watch?v='+id);

stream.on('readable', function() {
   if(!fsInfo.launch) {
      stream.pipe(fsInfo);
      fsInfo.launch = true;
  }
});
