### ISSUE TITLE
ytdl-core issue when trying to download specific video

### ISSUE THREAD

**Issue by DavidArgoPCHS** [fent/node-ytdl-core#361]
C:\Users\...\node_modules\ytdl-core\lib\util.js:393
    id: channelMatch[1],
                    ^

TypeError: Cannot read property '1' of null
    at Object.exports.getAuthor (C:\Users\...\node_modules\ytdl-core\lib\util.js:393:21)
    at request (C:\Users\...\node_modules\node_modules\ytdl-core\lib\info.js:70:20)
    at PassThrough.stream.on (C:\Users\...\node_modules\miniget\lib\index.js:155:30)
    at emitNone (events.js:111:20)
    at PassThrough.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

When I try to stream this specific video: https://www.youtube.com/watch?v=ObEJk4bAV8M

**Comment by Timeraa** [comment]
I tried downloading this video using this code:
```JS
ytdl("https://www.youtube.com/watch?v=ObEJk4bAV8M")
    .on("progress", (chunk, totalDownload, totalSize) => {
      console.log(totalDownload, totalSize)
    })
    .on("info", (info) => {
      console.log(info.title)
    })
```
And this is the only output i get
```
BackpackersXpress and the Disco Carriage: Citation Needed 5x03
1136 86985488
3184 86985488
7280 86985488
14788 86985488
31172 86985488
47556 86985488
```
It stops downloading the video at this point.

But if i use ytdl as a stream it works fine

What code did you use to download the video?

**Comment by DavidArgoPCHS** [comment]
.playStream(ytdl("https://www.youtube.com/watch?v=ObEJk4bAV8M", {
    filter: "audioonly"
   }));

**Comment by Timeraa** [comment]
Hm, i don't get this error whatsoever, are you extracting information of the video somewhere? What version are you using?

**Comment by Timeraa** [comment]
Don't overcomplicate yourself, get the video title by using [ytdl.getInfo()](https://github.com/fent/node-ytdl-core#ytdlgetinfourl-options-callbackerr-info) and then download the video by using [ytdl.downloadFromInfo()](https://github.com/fent/node-ytdl-core#ytdldownloadfrominfoinfo-options)

**Comment by fent** [comment]
Update your ytdl-core, the newest version is 0.25.2
