### ISSUE TITLE
Can't stream long videos

### ISSUE THREAD

**Issue by ticarex** [fent/node-ytdl-core#366]
I'm using discord.js and ytdl-core to create a youtube music bot, everything works fine, except when I try to stream a long video/audio.
After about 40~50 minutes playing, the stream suddenly stops.
If I save the video to a file and then use the file instead of the direct ytdl stream, the video plays correctly without stopping.

This will stop after about 40~50 minutes:
```javascript
// video is 3 hours long
voiceConnection.play( ytdl("https://www.youtube.com/watch?v=okRelz4a6a8", { filter: (format) => format.container === 'mp4' }) );
```

This works:
```javascript
// video is 3 hours long
ytdl("https://www.youtube.com/watch?v=okRelz4a6a8", { filter: (format) => format.container === 'mp4' })
    .pipe(fs.createWriteStream('video.mp4').on('finish', () => {
        voiceConnection.play('video.mp4');
    }));
```

Using ytdl-core 0.25.2 and discord.js#master

**Comment by fent** [comment]
It might be that the download is stopping halfway. With a download that lasts that long I wouldn't be surprised. Do you know what the error is that it prints when the stream stops?

Try increasing the `requestOptions.maxReconnects` option, which defaults to `5`. You might also wanna listen for the `reconnect` and `retry` events, to confirm that is what's happening.

**Comment by ticarex** [comment]
I did a quick test only listening for `error` events, before I went to sleep I left the bot playing a 24 hour video at my vps and when I woke up the video has stopped playing and caught this error message:

`{ Error: read ECONNRESET at TLSWrap.onread (net.js:599:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }`

I'm going to do another test, this time listening for the `reconnect` and `retry` events

**Comment by ticarex** [comment]
Actually, looks like the problem was my VPS, thanks for your time though!
