### ISSUE TITLE
Remove cheerio dependency

### ISSUE THREAD

**Issue by mallendeo** [fent/node-ytdl-core#37]
Hi, I managed to get this working for all the tests, also I tested it with other videos.
I'm aware that is not ok to parse HTML with regular expresions, but cheerio is used only once, so I made this regex.

```js
var entities = require('entities');

// get description from #eow-description
var regexString = '<div id="watch-description-text".*?>[\\n\\r\\s]*?'
                + '<p id="eow-description".*?>(.+?)<\/p>[\\n\\r\\s]*?'
                + '<\/div>';
var regex = new RegExp(regexString, 'igm');
var description = regex.exec(body.match(regex));
description = description ? entities.decodeHTML(description[1]) : '';
console.log(description);
```

**Comment by fent** [comment]
My fear is that this might break if something on the youtube watch page slightly changes, but I'm willing to try and see if it ever becomes a big issue.

Can you make this a PR?

**Comment by mallendeo** [comment]
Done.
