### ISSUE TITLE
Again getting 'Error: This video is unavailable'

### ISSUE THREAD

**Issue by KriskotooBG** [fent/node-ytdl-core#371]
I used the example codes to try and pipe a stream to a discord bot but everytime I try to run it no matter what YouTube video I use (I tried like 10 videos) I get this:

events.js:183
    throw er; // Unhandled 'error' event
    ^

Error: This video is unavailable.
    at request (bla bla/ytdl-core/lib/info.js:53:25)
    at PassThrough.stream.on(bla bla/miniget/lib/index.js:173:30)
    at emitNone (events.js:111:20)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

I am unpdated to the newest version (0.26.2) but can't figure out why it happens

The videos I tried

- Never gonna give you up (this is my test video for everything haha)
- Couple of my uploads (no music just a video of a tree a took) 
And some other random videos

**Comment by fent** [comment]
Are you still getting this? Youtube was down for the past hour or so, and testing just now, I'm not getting any video errors.

**Comment by KriskotooBG** [comment]
@fent unfortunately no I thought it was that but it isn't I tried it now but again no luck same error

Here is the code I used if it helps

var videoURL = 'https://youtube.com/watch?v=dQw4w9WgXcQ';

ytdl(videoURL)
   .on('error', function (err){
        console.log('ytdl err: ' + err)
    }); 
    .pipe(stream, {end: false});

**Comment by abdatta** [comment]
I am again getting this for the following video (and a few more):
```
require('ytdl-core')('https://www.youtube.com/watch?v=b4b1cMVZOUU');
```
Please reopen this issue and help.

**Comment by FD-** [comment]
I was just getting the same error, but I'm using a modified version of this library. Does the issue go away for you on repeated accesses to the same video?

**Comment by abdatta** [comment]
No, it doesn't. Although I haven't tried it for more than a few times (like 8-9 times).

**Comment by FD-** [comment]
Seems to be permanent for me now as well. It seems like fmt_list is not longer included in the server info response.

**Comment by gomikestrat** [comment]
I'm getting the same error as well
