### ISSUE TITLE
Small error in the typing file

### ISSUE THREAD

**Issue by TR3MIC** [fent/node-ytdl-core#376]
I was searching for something in the TypeScript typing file (index.d.ts) and I spotted an error at line 93: there is no type "int" in TypeScript. It should be "number".
```typescript
    ...
    media : {
        ...
        year?: int;
        ...
    },
    ...
```
It doesn't stop the compilation, but it's still not a valid TypeScript type. #

**Comment by fent** [comment]
Good catch. Thanks!
