### ISSUE TITLE
Age restricted videos return "Error: Could not find player config"

### ISSUE THREAD

**Issue by DougTy** [fent/node-ytdl-core#383]
Attempting to use ytdl-core for any age restricted video results in `Error: Could not find player config`
Non-age-restricted videos work fine.

Example:
https://www.youtube.com/watch?v=B3eAMGXFw1o

Usage:
```
const ytdl_core = require( 'ytdl-core' )
const url = "https://www.youtube.com/watch?v=B3eAMGXFw1o"
ytdl_core.getInfo( url, { filter: 'audioonly' }, ( err, info ) => { console.log( err, info ) })
```

Output:
```
Error: Could not find player config
    at gotConfig (./node_modules/ytdl-core/lib/info.js:115:21)
    at request (./node_modules/ytdl-core/lib/info.js:98:9)
    at IncomingMessage.res.on (./node_modules/miniget/lib/index.js:76:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
undefined
```

This used to work previously, so I think some update on Youtube's end messed something up.
Please let me know if any additional debug info is required.

**Comment by fent** [comment]
I'm unable to reproduce this. Tested the video linked, and ran the [irl-tests](https://github.com/fent/node-ytdl-core/blob/master/test/irl-test.js) without errors. Maybe you downgraded to an older version?

**Comment by DougTy** [comment]
Oops, you're right, I was stuck on an old version. The very first thing I tried was upgrading everything with yarn, but it held back ytdl-core for some reason. My apologies.
