### ISSUE TITLE
Store tokens

### ISSUE THREAD

**Issue by durimjusaj** [fent/node-ytdl-core#39]
What if we store tokens and reuse them I have modified sig to request only once for tokens till now it's working. May this cause any problem in the feature ?

P.S. I did this in my project cause i need to fetch multiple videos from youtube at once.

**Comment by fent** [comment]
Do you mean the html5player file? Yeah it would be possible to store either a memory or file cache for them.

**Comment by fent** [comment]
And yeah, storing the tokens, not the entire file.
