### ISSUE TITLE
Audio Quality (highestaudio enabled)

### ISSUE THREAD

**Issue by Vaerys42** [fent/node-ytdl-core#390]
Actually trying to make an audio player on a Discord bot, but i got horrible quality on some vids puts on param (like https://www.youtube.com/watch?v=vzfvgNOki6E)
I already have tried most of the solution offers here but with no result.

Here's my code line where i use ytdl-core :
```
dispatcher = msg.guild.voiceConnection.playStream(yt(url, {quality: 'highestaudio'}));
```
Thanks for help

**Comment by fent** [comment]
You can try downloading the music locally, then playing it in an audio player outside of discord, and see if the quality is fine. If so, the issue might be with the audio player for discord. I've heard of people preferring node-opus over opusscript due to the increase in quality and lower cpu usage.

**Comment by Vaerys42** [comment]
Dowloading seems be good, but even if i use node-opus i still got bad quality on some musics i tried

**Comment by FireController1847** [comment]
When you say "poor quality" what do you mean? Is it bad quality in every server region? Does it cut in and out? What's your internet speed? Does the same thing happen on a different computer, or different internet connection?

**Comment by Vaerys42** [comment]
Some songs got high saturation and i don't have any cut. I must have like 20mb/s on the internet so i don't think it come from the internet. And i tried on another computer but still got the same problem.

**Comment by FireController1847** [comment]
Is there any way you can provide an audio sample? Or, better yet, add me and let me hear? I'm `FireController1847#3577`

**Comment by FireController1847** [comment]
Seems like we got it fixed by using `filter: "audio"` instead of `quality: "highestaudio"`, feel free to close this issue.

**Comment by Vaerys42** [comment]
Yeah, i confirm. Thanks for help everyone
