### ISSUE TITLE
This video is unavailable error

### ISSUE THREAD

**Issue by FraWolf** [fent/node-ytdl-core#394]
Hi everyone! I was trying to add a video by a link but with every link I try it says: "Error: This video is unavailable.". I've the latest version of ytdl-core (0.28.3), and the error is in the 
let info = await ytdl.videoInfo("url").catch(err => { console.log(err) });

**Comment by FraWolf** [comment]
Ops, bad copy-paste, I was talking about 
let info = await ytdl.getInfo("url").catch(err => { console.log(err) });

**Comment by FraWolf** [comment]
- It happens with every video I try
- The script worked fine, a day I updated it and stopped working.. (I haven't modified that)
- The version is the latest (0.28.3)

**Comment by TimeForANinja** [comment]
did you try going back to a older ytdl-core version to see whether that fixes your problem?

**Comment by FraWolf** [comment]
Yes, but nothing, same error.

**Comment by TimeForANinja** [comment]
but i guess that's your problem


> [It is strongly advised you actually shell out a couple dollars a month and get an actual real VPS, due to the free nature of Glitch it has led to a high number of Glitch based IP's getting API banned by Discord due to abuse.](https://anidiots.guide/other-guides/hosting-on-glitch)

i'd bet google did the same

**Comment by FraWolf** [comment]
I've already a server, but with glitch my music bot works better, it's a very small server (1gb ram, 20gb ssd and 1 vcore)

**Comment by FraWolf** [comment]
But I have a problem only when I use link, if I search a song with keywords the bot found it and reproduce it.

**Comment by fent** [comment]
Does running your app locally or in another environment have it work?

**Comment by Stapleton** [comment]
I am getting the same issue, normal old household PC. No server or anything. Residential connection.
ytdl-core: 0.29.1
node: 11.6.0
npm: 6.5.0-next.0

**Comment by Stapleton** [comment]
Can confirm its happening on all of them for me. Even went all the way back to 0.20.2 and same issue.

**Comment by SpeedBoostDiscord** [comment]
Germany have a lot of issues with youtube videos, I'd host elsewhere. As for Ontario, it will just be specific videos probably

**Comment by Zargith** [comment]
Hello!
I've the same issue and I don't know why...
Yesterday it was working well but today not at all !
I got the last version of ytld-core and I'm sure that not come from my connection because I can acces like I want at internet.
I'm currently in France but I don't think it's the cause :/ (I say that because of reading other comments)

Personnaly I use ytdl-core for my Discord bot in JS

**Comment by Zargith** [comment]
Okay my bad!

That's because I was using toLowerCase method!
And I did that yesterday before to go bed that's why I didn't notice it earlier 😂

**Comment by npreiber** [comment]
So I have a question about handling this error within an application without terminating.  Whenever I get this error the program terminates rather than continuing to process videos. Is there anyway to prevent this. I've tried catching the exception in try-catch block.

**Comment by AdamKearn** [comment]
I am looking for a way to catch this error as well.     I don't want my code to terminate when this error is presented.

**Comment by fent** [comment]
you can catch this error by listening to the `error` event from the returned stream

```js
let stream = ytdl(url);
stream.on('error', err => {
  // handle it
});
```

do the following to catch uncaught errors, but it's strongly recommended to figure out where the error originates from so you can handle it properly

```js
process.on('uncaughtException', err => {
});
```
