### ISSUE TITLE
Error: status code 302  - Unhandled 'error' event

### ISSUE THREAD

**Issue by GautierThiriez** [fent/node-ytdl-core#40]
Hi, 
Sometimes i having error on download.

Here's the error : 
 ```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: status code 304
    at ClientRequest.<anonymous> (/Users/Gautier/Documents/heroku/thewok-youtube-dl/node_modules/ytdl-core/lib/index.js:64:16)
```
Here's my code : 
 ```
            console.log('Creating stream...');
            file = fs.createWriteStream(tempDir + mp4Title);
            ytdl.downloadFromInfo(info)
                .pipe(file)
                .on('error', function (error) {
                    console.log('Error : ', error);
                    return next(err);
                })
                .on('info', function (info) {
                    console.log('Info : ', info);
                })
                .on('format', function (format) {
                    console.log('format : ', format);
                })
                .on('close', function (data) {
                    convert.convertMP3(title, tempDir, function () {
                        callback(tempDir, mp3Title)
                    });

                });
 ```
I don't understand why .on('error') is not receiving anything ( .on('info') neither even when i don't have error and the download is ok.)

Thanks.

**Comment by fent** [comment]
`ReadableStream#pipe()` returns the stream being written to, which wouldn't have all of those events. You'd have to move pipe after all of the `.on()` calls if you wanna chain.

As for the error, I could have it only error out on 4xx status codes.

**Comment by GautierThiriez** [comment]
Okay, so how can i handle this error ? 
How to prevent a crash of the app without editing "node_modules/ytdl-core/lib/index.js:64:16" ?

Thank you for your help.

**Comment by fent** [comment]
Listen to the `error` event before piping, if you want to reference the original stream

**Comment by GautierThiriez** [comment]
aaaaah ! okay. Thanks. Sorry for this silly question.
