### ISSUE TITLE
no video id found?

### ISSUE THREAD

**Issue by ghostilyallure** [fent/node-ytdl-core#410]
```js
async run(msg, args, ops) {

      if(!msg.member.voiceChannel) return msg.reply('You must be in a voice channel.');
    
      if(msg.guild.me.voiceChannel) return msg.reply('I\'m already connected.');
    
      if(!args[0]) return msg.reply('You need to input a URL.');
    
      let validate = await ytdl.validateURL(args[0]);
    
      if(!validate) return msg.reply('Please input a **valid** URL.');
    
      let info = await ytdl.getInfo(args[0]);
    
      let connection = await msg.member.voiceChannel.join();
    
      let dispatcher = await connection.playStream(ytdl(args[0], {filter: 'audioonly'}));
      
      msg.channel.send(`Now playing: ${info.title}`);
  }
}
```
i would do %play(url) but it would always come back as no video id found, with every video i tried. i browsed the docs, tutorials, etc. i even tried an older version, AND the updated version. however, none would work. the bot would join just fine, but it wouldn't play any music. is there anything wrong?

**Comment by FireController1847** [comment]
Can you add a `console.log(args[0])` right before the `await ytdl.getInfo(args[0])` line and then respond with the output please?

**Comment by DrDarkfire** [comment]
(I just found this out myself) args is a character array, so if you just use args the whole url will be use, but args[0] will be h, args[1] will be t. So on and so forth. It is not capturing a string, but rather individual characters in the array.
