### ISSUE TITLE
dispatcher instantly ending when trying to play from youtube

### ISSUE THREAD

**Issue by PoorlyDefinedBehaviour** [fent/node-ytdl-core#411]
### I can play files from my computer, but not from youtube

function playPlaylist(connection, message) {
musicHandler = connection.playStream(ytdl(songs[0], {filter: "audioonly"}));

musicHandler.setVolume(volume);

musicHandler.on("error", error => {
console.log(error);
});

musicHandler.on("end", () => {
songs.shift();
if (songs[0] !== undefined) {
playPlaylist(connection, message);
} else {
message.reply("Playlist is empty");
connection.disconnect();
isPlaying = false;
musicHandler = undefined;
}
});
}

**Comment by fent** [comment]
Are you getting any specific error?

**Comment by PoorlyDefinedBehaviour** [comment]
> Are you getting any specific error?

No errors, it just stops instatly.

**Comment by PoorlyDefinedBehaviour** [comment]
worked around it:

ytdl([songs].toString(), { filter: "audioonly" })
    .pipe(fs.createWriteStream("song.mp3"))
    .on("error", error => {
      console.log(error);
    })

const dirname = __dirname.replace(/\\/g, "/");

connection.playFile(`${dirname}/song.mp3`);

**Comment by TimeForANinja** [comment]
instead of doing `` `${__dirname.replace(/\/g, "/")}/song.mp3` `` you should absolutely use `require('path').resolve(__dirname, 'song.mp3')`

**Comment by PoorlyDefinedBehaviour** [comment]
> instead of doing `` `${__dirname.replace(/\/g, "/")}/song.mp3` `` you should absolutely use `require('path').resolve(__dirname, 'song.mp3')`

Thanks for letting me know, but how is it better?

**Comment by TimeForANinja** [comment]
The hole purpose of that function is to merge file/dir names
