### ISSUE TITLE
possibiltiy to load more related videos?

### ISSUE THREAD

**Issue by joek85** [fent/node-ytdl-core#418]
hello, i would like to ask if there is a way to load more related videos.
when i get infos for a video i get 11 videos and 1 playlist item "YouTube Mix", how to simulate a click to the "Load More" button so it can fetch the rest related videos?
or maybe is there a way do achieve that?
thank you.

**Comment by fent** [comment]
Get its link from the related videos and call `ytdl()` on it.

```js
ytdl(info.related_videos[0].id)
```

**Comment by FireController1847** [comment]
Oh yeah, I forgot about that. I guess I could have answered the question lol

**Comment by joek85** [comment]
hey, i think you got me wrong, let me explain,
`ytdl.getInfo(videourl + id, function getInfo(err, info) `

i get response like this

`related_videos: 
   [ { session_data: 'itct=CBkQvU4YACITCIKnk_2s4uACFRXtUQodc-ABFij4HTIJZW5kc2NyZWVuSPu6uY-589GwvwE%3D',
       short_view_count_text: '1.5M views',
       author: 'Suprafive Music',
       length_seconds: '236',
       iurlhq: 'https://i.ytimg.com/vi/ZqdPQdhwn6A/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDwr8TmKU_ehuFKffHG91seFlkngg',
       title: 'Andrea ft. Mario Joy - Miss California (Suprafive Remix)',
       endscreen_autoplay_session_data: 'playnext=1&itct=CBoQ4ZIBIhMIgqeT_azi4AIVFe1RCh1z4AEWKPgdMgxyZWxhdGVkLWF1dG9I-7q5j7nz0bC_AQ%3D%3D&autonav=1',
       iurlmq: 'https://i.ytimg.com/vi/ZqdPQdhwn6A/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDwr8TmKU_ehuFKffHG91seFlkngg',
       id: 'ZqdPQdhwn6A' },
     { session_data: 'itct=CBgQvk4YASITCIKnk_2s4uACFRXtUQodc-ABFij4HTIJZW5kc2NyZWVuSPu6uY-589GwvwE%3D',
       list: 'RDv2FHm5HuXXs',
       playlist_iurlmq: 'https://i.ytimg.com/vi/v2FHm5HuXXs/mqdefault.jpg',
       playlist_length: '0',
       playlist_title: 'Mix - Kanita - S\'jemi Ne (N.O.A.H Remix)',
       video_id: 'ZqdPQdhwn6A',
       playlist_iurlhq: 'https://i.ytimg.com/vi/v2FHm5HuXXs/hqdefault.jpg',
       thumbnail_ids: 'ZqdPQdhwn6A' },
     { session_data: 'itct=CBcQvU4YAiITCIKnk_2s4uACFRXtUQodc-ABFij4HTIJZW5kc2NyZWVuSPu6uY-589GwvwE%3D',
       short_view_count_text: '8.3M views',
       author: 'Capital T',
       length_seconds: '235',
       iurlhq: 'https://i.ytimg.com/vi/9p3W7bi_d4Y/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAnnB3wgQvW10dsdmJpTacFjhQe6w',
       title: 'Capital T - Kujtime (Prod. BO Beatz)',
       iurlmq: 'https://i.ytimg.com/vi/9p3W7bi_d4Y/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAnnB3wgQvW10dsdmJpTacFjhQe6w',
       id: '9p3W7bi_d4Y' },`
the related_videos array is about 11 items, this is normal behavior on youtube, now you notice on youtube in the "Up Next" section there is "SHOW MORE" button which fetches more related videos and add them to the "div list".
so i'm wondering if you can simulate the click so more related videos will be added to the "related_videos" array, unless you are fetching the mobile version of youtube page and i'm not sure if that button exists on that page.
hope it is clear now, thank you.

**Comment by fent** [comment]
Ah, that would take a bit more time to investigate how it works and implement it. I'll label this.

**Comment by joek85** [comment]
thank you, what do suggest to do about the issue? close it or leave it open until feature will be implemented?

**Comment by fent** [comment]
Leave it open until it's implemented

**Comment by fent** [comment]
after thinking about this a bit more, this feels out of scope to this project. it would require an additional request to get more videos, they aren't loaded with the rest of a video's metadata. it would be like loading comments, or replies to a comment, out of scope.
