### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by sunny-lan** [fent/node-ytdl-core#420]
Add that `.destroy()` should be called in order to cleanly terminate a stream which has not ended.

**Comment by RevenantEverest** [comment]
Can you elaborate more on this?

**Comment by sunny-lan** [comment]
For example, when trying download an ongoing livestream, if the user wants to terminate downloading without corrupting the partially downloaded video file.

```js
const stream = ytdl(stream_url);
on('process_exit', () => stream.destroy());
```

**Comment by FireController1847** [comment]
It might also be noteworthy to state that certain container formats like MP4 do not handle streams being cut off like this well. In these situations, you'd have to use ffmpeg or whatever you're using to cut it off appropriately.
