### ISSUE TITLE
Downloading from node-ytdl-core in SAFARI is downloading a .download file WITH NO CONTENT TYPE

### ISSUE THREAD

**Issue by TransmissionsDev** [fent/node-ytdl-core#421]
Using express and ytdl-core I've been able to download mp3 versions of youtube videos for a radio like web-app I'm making. 

Unlike most examples I've seen, I'm not trying to download a video or mp3 directly to a machine, but instead, serve it to a browser over a link.

The only problem is when I try to download the mp3 with safari it starts downloading a .dms or .download file, not an mp3. It returns not content-type when downloading with curl. 

```javascript
const ytdl = require("ytdl-core");
const app = express();
const fs = require("fs");

app.use(cors());

app.listen(4000, () => {
  console.log("Server IS ON !!! At port 4000");
});

app.get("/radio/download", (req, res) => {
  var URL = req.query.URL;

  console.log("A download request was received!");

  ytdl(URL, {
    filter: "audioonly"
  }).pipe(res);
});
```

I'm not sure how to get safari to recognize this as a valid mp3 file and treat it like so. 

When I go to a link like `https://ia802508.us.archive.org/5/items/testmp3testfile/mpthreetest.mp3` (A test mp3 file hosted on Internet Archive) safari shows a nice mp3 player: ![a busy cat](https://i.imgur.com/bKwvMLx.png).

This doesn't happen with any mp3 downloaded using my express app.

**How can I attach the correct headers or what ever is necessary for Safari to treat my mp3s correctly?**

**Comment by fent** [comment]
I think you have to set a mime type for the response headers, which you can find on `format.type`, and you can get the format by listening to the `info` event from the stream that calling `ytdl()`returns.

I'm going to close this since this isn't a ytdl issue.
