### ISSUE TITLE
How do I know if a mp3 file is downloaded?

### ISSUE THREAD

**Issue by loox37** [fent/node-ytdl-core#427]
Hello fent!!
First of all, great library!
This isn't an issue, more like a question, but I didn't know where to ask it.

I have this line: `downloader(url, {filter: 'audioonly'}).pipe(fs.createWriteStream("test.mp3"));`

How do I know when the file is downloaded or not?

**Comment by fent** [comment]
ytdl-core returns a node readable stream, which emits an `end` event when it finishes, and an `error` if there was an error. youtube also does not have audio in mp3 format, if you really need mp3, you can use ffmpeg to convert it.

there are examples of these in the [examples folder](https://github.com/fent/node-ytdl-core/tree/master/example)
