### ISSUE TITLE
Is there way to get the info of the video that error'ed?

### ISSUE THREAD

**Issue by opsigor** [fent/node-ytdl-core#43]
Hi! I'm building an module to download the videos and convert them to mp3. I'm currently have an issue, because i'm downloading an entire playlist from youtube. 

Here is my code: 
```js
let streams = _vid.forEach((val) => {
    numVideos++;
    let _stream = ytdl(val, options);
    _stream
      .on('info', (info, format) => {
        fs.stat(path, (err, stats) => {
          if (err) {
            fs.mkdirSync(path);
          }
          self.emit('download', info.title);
          self.createSong(path, info.title, _stream, 192);
        });
      })
      .on('error', (err) => {
        self.emit('error', err);
        numVideos--;
      });
  })
``` 

This piece of code is inside of a forEach loop, and i was wondering if i could display the video that was errored to the user. For example, i'm brazilian and some videos are blocked on youtube on my country. When i try to download a video that is blocked, it throws:
``` 
[Error: Error 150: Este vídeo apresenta conteúdo de UMG, que o bloqueou no seu país com base nos direitos autorais.]
``` 
Is there i way that i could catch the name of the video?

Thanks!!!

**Comment by fent** [comment]
The 'info' event is now emitted before the download is attempted.

**Comment by fent** [comment]
Also, I'm wondering if there's a way around blocked videos. But I can't find one that is blocked in the US to test on.
