### ISSUE TITLE
How to get specific quality video downloaded ?

### ISSUE THREAD

**Issue by thidasapankaja** [fent/node-ytdl-core#430]
I'm implementing youtube video downloader as a hobby project. Here I need to download the selected quality video.

From this, I'm receiving the different qualities of the same video which contains both audio and video. 

```
app.get('/getVideo', (req, res) => {
    let { url } = req.query;
    let id = ytdl.getURLVideoID(url);
    ytdl.getInfo(id, (err, info) => {
        if (err) {
            console.log(err);
            throw err
        }
        else{
            let audioandvideo = ytdl.filterFormats(info.formats, 'audioandvideo');
            
            let data = {
                videos: audioandvideo,
                title: info.title
            };
            res.setHeader('Content-Type', 'application/json');
            res.setHeader('Access-Control-Allow-Origin','*');
            res.send(JSON.stringify(data));
        }             
    })
});
```

Here `audioandvideo` variable contains the array of video types/qualities in the given video. 
How can I get a specific one from that downloaded?

```
app.get('/downloadVideo', (req, res) => {
    console.log(req.query);
    let { url, title } = req.query;

    res.header('Content-Disposition', 'attachment; filename="video.mp4"');

    ytdl(url, {
        format: 'mp4'
        }).pipe(res);
})
```
I tried passing an URL of an object returns from `audioandvideo` in the first request, here. But I'm getting an error like this `Error: Not a YouTube domain`. How can I get this fixed ?

Any help would be appreciated ?

**Comment by SpeedBoostDiscord** [comment]
filter: (format) => ['251']
take a look at the list of itags that give audio

**Comment by thidasapankaja** [comment]
@SpeedBoostDiscord  Sorry, I didn't get you. From the first code block I mentioned, I'm receiving the list of videos with audios in different qualities and types. How can I select one of them and download it?

**Comment by BrunoMoreira99** [comment]
Instead of passing `'mp4'` in
```js
ytdl(url, {
    format: 'mp4'
}).pipe(res);
```
just pass the format object you want to download, this is explained in the readme:
> `format` - Primarily used to download specific video or audio streams. This can be a specific `format` object returned from `getInfo`.

which can be any of the formats returned by `ytdl.filterFormats` that you're using in the first code block.

**Comment by thidasapankaja** [comment]
Thanks @BrunoMoreira99 . It works, However, I find it a bit confusing to download the file with a get request. If you can please check this out (https://stackoverflow.com/questions/56306008/file-download-with-reactjs-doesnt-work-correctly-using-axios) and help me, it would be great

Thanks

**Comment by fent** [comment]
If you're picking from an itag, you can use [`ytdl.chooseFormat()`](https://github.com/fent/node-ytdl-core#ytdlchooseformatformats-options), no need to use `ytdl.filterFormats()` since you're picking from a chosen itag anyway

Not sure what you mean by redirects not working. If fetching a video results in a redirect, ytdl should handle going to the new url

**Comment by thidasapankaja** [comment]
@fent added the frontend code block for more clarification about the issue I'm facing

**Comment by fent** [comment]
why not use `window.location` and not axios? axios and other http libraries should really only be used if you're manipulating the data in any way. but if you're only saving it, there's no reason to since the browser can handle that.

**Comment by thidasapankaja** [comment]
@fent I need to host this. How can I host this and still use `window.location` ?

**Comment by BrunoMoreira99** [comment]
@thidasapankaja `window.location` doesn't need to be an absolute url. See https://stackoverflow.com/questions/1655065/redirecting-to-a-relative-url-in-javascript

**Comment by thidasapankaja** [comment]
Thanks @BrunoMoreira99 . Anyway got this fixed with axios by using `responseType: 'blob'` instead of `responseType: Blob`
