### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by rainbowdude6** [fent/node-ytdl-core#436]
im new to this and i got this error message 

(node:21156) DeprecationWarning: Collection#filterArray: use Collection#filter instead
(node:21156) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'queue' of undefined
    at /Users/jacobpaulin/ErrorBot/Commands/Music/join_channel.js:47:32
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:21156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

and here is my code 

const commando = require('discord.js-commando');
const YTDL = require('ytdl-core');

function Play(connection, message)
{
    var server = sersers[message.guild.id];
    server.dipatcher = connection.playStream(YTDL(server.queue[0], {filter: "audioonly"}));
    server.queue.shift();
    server.dipatcher.on("end", function(){
        if(server.queue[0])
        {
            Play(connection,message)
        }
        else
        {
            connection.disconnect
        }
    });
}

class JoinChannelCommand extends commando.Command
{
    constructor(client)
    {
        super(client,{
            name: 'join',
            group: 'music',
            memberName: 'join',
            description: "Joins the channel that the user is in"
        });
    }

    async run(message, args)
    {
        if(message.member.voiceChannel)
        {
            if(!message.guild.voiceConnection)
            {
                if(!servers[message.guild.id])
                {
                    servers[message.guild.is] = {queue: []}
                }
                message.member.voiceChannel.join()
                    .then(connection =>{
                        var server = servers[message.guild.id];
                        message.reply("Successfully Summoned");
                        server.queue.push(args);
                        Play(connection, message);
                    })
            }
        }
        else
        {
            message.reply("You must be in a voice channel to summon me")
        }
        
    }
}

module.exports = JoinChannelCommand;

**Comment by fent** [comment]
hi, the stack trace shows the error is coming from non ytdl-core
