### ISSUE TITLE
Cross-origin request blocked (I don't know if it's a mistake)

### ISSUE THREAD

**Issue by zandercodes** [fent/node-ytdl-core#438]
My problem is, when I create a SPA, I have the problem that I get an error in the browser from fetch with the message:

> Cross-origin request blocked: The same source rule prohibits reading the external resource on https://www.youtube.com/watch?v=34Na4j8AVgA&hl=en&bpctr=1562068323. (Reason: CORS attack failed)

Where is the problem?

Best regards
ZanderCodes

Sry for my bad english

**Comment by TheNozomi** [comment]
If you are using the library on the client-side, that's expected. The browser will not let you make requests to different domains (read: [Same-origin policy](https://en.wikipedia.org/wiki/Same-origin_policy)). One workaround for this is creating an endpoint on your Node.js server that can be used like a proxy (you request to your local server, your server requests to YT API, and streams the response back to your browser).

**Comment by zandercodes** [comment]
Oh, I'm so stupid 😄
Thanks for help
