### ISSUE TITLE
YTDL cant play videos that are claimed

### ISSUE THREAD

**Issue by silvinator** [fent/node-ytdl-core#439]
I want to play music like Umbrella - The baseballs, but the stream is terminated instantly and I get the error undefined (i tried it with a new bot but then it just didn't play or gave an error). But this just happens to things that have a copyright claim on it. Is there a solution to this?

**Comment by atomic-addison** [comment]
I have run into this issue as well recently, i noticed that some videos that i used to be able to access are no longer accessible via ytdl, however my own test video with no claim or copyright i could access just fine.

**Comment by silvinator** [comment]
ok, I guess it was much easier as I thought. Just update it with npm install ytdl-core@latest. I feel dumb right now

**Comment by atomic-addison** [comment]
I did it today and it didn't work at first, but that turned out to be an unrelated issue and everything works properly now. I can relate.

**Comment by silvinator** [comment]
Weel, it worked right now and now it stopped working as I tried to put it on my main project

**Comment by atomic-addison** [comment]
I also updated my ffmpeg, if you haven't done that yet, you may need to.

**Comment by fent** [comment]
make sure to install with `ytdl-core@latest`
