### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by zandercodes** [fent/node-ytdl-core#441]
When download video with high quality, has the video no audio.
I have seen that with [MediaStream](https://stackoverflow.com/questions/52768330/combine-audio-and-video-streams-into-one-file-with-mediarecorder), both streams are streamed together.

**Comment by fent** [comment]
ytdl-core focuses on only the formats provided by youtube. and to merge video and audio streams, we'd have to include ffmpeg in the dependencies.

if you'd like to do this yourself, look at https://github.com/fent/node-ytdl-core#handling-separate-streams
