### ISSUE TITLE
(Discord bot) Music stops playing instantly

### ISSUE THREAD

**Issue by Zentreax** [fent/node-ytdl-core#451]
Hey! 
So, for some weeks now my Bot behaves really weird.
It joins, but leaves instantly & clears the queue.
Thing is - it does this only with ~50% of videos, some work perfectly fine some not.
https://www.youtube.com/watch?v=3MGpFtwl6fQ This one doesnt work
https://www.youtube.com/watch?v=S3fqxnQbMOI This one works perfectly fine

Here's my play.js file: https://pastebin.com/FxxRNeWF

**Comment by fent** [comment]
Is there an error at all?

Both of those videos work for me. make sure you have the latest version of ydl-core, which you can check with `npm ls ytdl-core`.

**Comment by macdja38** [comment]
All ytdl-core does is get the source URL from youtube... Your discord library handles playing it. One thing I would look out for is making sure the discord library you are using supports following redirects or you make sure to resolve that yourself. But other then that their is nothing ytdl-core can really do to fix your discord bot.

**Comment by Zentreax** [comment]
> 
> 
> Is there an error at all?
> 
> Both of those videos work for me. make sure you have the latest version of ydl-core, which you can check with `npm ls ytdl-core`.

No error at all, if there was i wouldnt ask here ;)

**Comment by Zentreax** [comment]
Updated every package i need, still doesnt work (no error). Also my bot is hosted on heroku if that matters.

**Comment by Fobenga** [comment]
same problem, also with music bot hosted on heroku

**Comment by macdja38** [comment]
This... **really** isn't the place for this but... What discord library are you using to play the URLs you get from this library?

**Comment by Zentreax** [comment]
@macdja38 discordjs, i noticed even tho im updating & reinstalling all packages, heroku still (atleast shows) them outdated when running _npm outdated_, couldnt find any fix and/or reason why

**Comment by macdja38** [comment]
use `npm install package-name@version` to install a specific version of a package. `npm update` will only update minor releases automatically.`

**Comment by Zentreax** [comment]
@macdja38 i did try _npm i package@latest_

**Comment by ethanwritescode** [comment]
> It joins, but leaves instantly & clears the queue.

This is most likely a problem with your code, not ytdl. As mentioned by fent, himself both videos work fine. 

Also, another off-topic thing. Don't use Heroku to host your bot (the way node processes run are much different than if you just ran it via something like PM2). I'd highly recommend getting a VPS to host your bot instead, if you can afford it.

**Comment by Zentreax** [comment]
Fixed it, still using heroku. I had to change the Versions to latest manually in package.json.
