### ISSUE TITLE
Audio still not merged in Video Using Ffmpeg example code

### ISSUE THREAD

**Issue by MSZ991** [fent/node-ytdl-core#453]
### Before creating an issue, please try the following

- Are you on the latest version of ytdl-core? If you're using a bot or application that depends on ytdl-core, check if it has an old version listed as a dependency.
  - To check, run `npm ls ytdl-core`
  - To install the latest version, run `npm install ytdl-core@latest`
- Search the list of issues for a possible duplicate.
  - If there is a duplicate issue thread, but it's closed, only post in it if it's been active in the past month. Otherwise, creating a new issue thread is fine.
- If your question is about using the library for a specific use case, check out the [examples folder](https://github.com/fent/node-ytdl-core/tree/master/example).

### Otherwise, feel free to open an issue

Include the following if your issue is a bug

- If you're getting a specific error message, include the full stack trace
- If you're getting unexpected behavior without an error message
  - What should happen?
  - What happens instead?
- Include any relevant code around ytdl-core. You don't have to upload your entire program, small snippets are fine.
- If this error happens only on some videos, include a link or links to videos.

**Comment by MSZ991** [comment]
Hi Thank you for this wonderful project.I would like to say that audio is not merged in video, I have used the same video link you mentioned in example/ffmpeg but its audio stop working after 20 sec.Please look into this matter. Thank you so much.

**Comment by MSZ991** [comment]
@fent @maxogden @Rafer45  any clue?

**Comment by fent** [comment]
I just ran that file `example/ffmpeg.js`. it doesn't show much output, but after 2 to 3 minutes it finished. then i played the file it made, `output.mp4` and it has audio all the way through.

**Comment by adamwoo2444** [comment]
@fent  I also checked with multiple links but it did not work correctly audio was missing.
"https://www.youtube.com/watch?v=i6BB9m8oiCk" you can check with this also.

**Comment by fent** [comment]
that video works for me too.

hmm, so you're running the script, and when it finishes, play the video and there's no sound?

**Comment by MSZ991** [comment]
yes no sound after 20 seconds :(

**Comment by MSZ991** [comment]
<img width="1039" alt="Screen Shot 2019-07-21 at 6 57 51 PM" src="https://user-images.githubusercontent.com/14855029/61592206-7e86bd80-abe9-11e9-8144-fa6440dbab4a.png">
and no sound after 20 secs :( please look into this issue. I shall be very thankful to you.

**Comment by MSZ991** [comment]
`var url = 'https://www.youtube.com/watch?v=i6BB9m8oiCk';
   const audioOutput = path.resolve(__dirname, 'sound2.mp4');
   const mainOutput = path.resolve(__dirname, 'output3.mp4');
    console.log(url);
    console.log(audioOutput);
    console.log(mainOutput);
  ytdl1(url, { filter: format => {
   
    return format.container === 'm4a' && !format.encoding; } 
      
   })
    // Write audio to file since ffmpeg supports only one input stream.
    .pipe(fs.createWriteStream(audioOutput))
    .on('finish', () => {
      ffmpeg()
        .input(ytdl1(url, { filter: format => {
          return format.container === 'mp4' && !format.audioEncoding; } }))
        .videoCodec('copy')
        .input(audioOutput)
        .audioCodec('copy')
        .save(mainOutput)
        .on('error', console.error)
        .on('progress', progress => {
          process.stdout.cursorTo(0);
          process.stdout.clearLine(1);
          process.stdout.write(progress.timemark);
        }).on('end', () => {
          fs.unlink(audioOutput, err => {
            if(err) console.error(err);
            else console.log('\nfinished downloading');
          });
        });
    });
 `
I have not sound.mp4 and output.mp4 file in my dir, do i need to create them manually ?

**Comment by fent** [comment]
there's an error in your screenshot above

**Comment by MSZ991** [comment]
what kind of file it is sound.mp4 ? I have to create it manually ?

**Comment by adamwoo2444** [comment]
@fent can you tell it because im facing a same issue.

**Comment by adamwoo2444** [comment]
I think you have to put audio file from where you want to merge into video.

**Comment by MSZ991** [comment]
No!! it downloads audiofile(m4a) directly using ytdl and write it on audiofile .This is what I am wondering i have to create it manually ? @fent

**Comment by fent** [comment]
> it downloads audiofile(m4a) directly using ytdl and write it on audiofile

yes

**Comment by adamwoo2444** [comment]
> > it downloads audiofile(m4a) directly using ytdl and write it on audiofile
> 
> yes

so I have to create audiofile manually? what about the error ? @fent please answer.

**Comment by MSZ991** [comment]
> > > it downloads audiofile(m4a) directly using ytdl and write it on audiofile
> > 
> > 
> > yes
> 
> so I have to create audiofile manually? what about the error ? @fent please answer.

@fent let me know so that I can close this issue.

**Comment by fent** [comment]
the audio file is created from the code in the example
