### ISSUE TITLE
To much requests after latest YouTube update - Best Practise?

### ISSUE THREAD

**Issue by mh4ck** [fent/node-ytdl-core#460]
Hi, 

after the latest YouTube update it's important to lower the YouTube request amount per IP.
To "proxy" an mp4 file directly to the Client i'm using a code like this: 

```
ytdl.getInfo('...', (err, info) => {
if (info && info.title) {
        let filenameRegex = new RegExp(config.worker.filenameRegex, 'ig');
        let filename = info.title.replace(filenameRegex, '_') + '.mp4';
        // Now this line because it's to late to send it in ytdl 'info' event.
        res.setHeader('Content-disposition', 'attachment; filename=' + filename);
       let stream = ytdl('id...');
       stream.pipe(res);
}
});
```

The problem with this code is - we have 2 info requests in a short period (The wrapped one and the internal one in the ytdl method). 

My question is, is there a way to hand over the info object from the first "getInfo" call to the 'ytdl' method so that it is not necessary for the ytdl method to request it again?

**Comment by fent** [comment]
this is a common usage pattern, and ytdl is prepared for it. ytdl keeps an internal cache for `ytdl.getInfo()` calls, in case it's called on the same video too frequently, and for this case specifically.

there's a test for it [here](https://github.com/fent/node-ytdl-core/blob/778371d9d48d0c76fc888cc7ef1d4eed76f7cc66/test/info-test.js#L170-L194)
