### ISSUE TITLE
Unable to extract video Title .

### ISSUE THREAD

**Issue by adamwoo2444** [fent/node-ytdl-core#462]
### Before creating an issue, please try the following

- Are you on the latest version of ytdl-core? If you're using a bot or application that depends on ytdl-core, check if it has an old version listed as a dependency.
  - To check, run `npm ls ytdl-core`
  - To install the latest version, run `npm install ytdl-core@latest`
- Search the list of issues for a possible duplicate.
  - If there is a duplicate issue thread, but it's closed, only post in it if it's been active in the past month. Otherwise, creating a new issue thread is fine.
- If your question is about using the library for a specific use case, check out the [examples folder](https://github.com/fent/node-ytdl-core/tree/master/example).

### Otherwise, feel free to open an issue

Include the following if your issue is a bug

- If you're getting a specific error message, include the full stack trace
- If you're getting unexpected behavior without an error message
  - What should happen?
  - What happens instead?
- Include any relevant code around ytdl-core. You don't have to upload your entire program, small snippets are fine.
- If this error happens only on some videos, include a link or links to videos.

**Comment by adamwoo2444** [comment]
Youtube updated its code!!!! thats why we are not able to extract title please look into this matter ASAP.

**Comment by cloudrac3r** [comment]
I'm also having problems with this.

**Comment by ethanwritescode** [comment]
youtube-dl likely updated the way it extracts video data. getInfo() and getBasicInfo() don't return the correct parameters. However, downloading videos still seems to work fine.

**Comment by cloudrac3r** [comment]
Here is how Invidious, another YouTube video extractor, dealt with this change: https://github.com/omarroth/invidious/commit/ff5d79e3ee1d295e97e589e39ca09bd0a880c99f

Hopefully this can assist somebody in figuring out what to change.

**Comment by fent** [comment]
> As a reference, this is what was returned after testing getInfo() a few minutes ago.
> https://runkit.com/illuminati4life/5d3f9c789c2c2e001b245873

> Here is how Invidious, another YouTube video extractor, dealt with this change: [omarroth/invidious@ff5d79e](https://github.com/omarroth/invidious/commit/ff5d79e3ee1d295e97e589e39ca09bd0a880c99f)


thanks! these were helpful. will push a fix soon.
