### ISSUE TITLE
video_id is not in response from getInfo

### ISSUE THREAD

**Issue by cloudrac3r** [fent/node-ytdl-core#465]
- [x] I have ytdl-core 0.29.4, the latest version published to npm
- [x] I have checked for duplicate issues

Here's the code I'm using:

    const ytdl = require("ytdl-core")
    ytdl.getInfo("cFJSV2dj0ps").then(info => {
        console.log(info.video_id)
    })

It logs this:

    undefined

In [index.d.ts](https://github.com/fent/node-ytdl-core/blob/89149faacf5bc2d74d708e5a15fe3113073acf6a/typings/index.d.ts#L182), the type `videoInfo` is supposed to have a property named `video_id`, but the actual response does not have this property.

I have some old code that used to use the `video_id` property, but this code does not work anymore because the property seems to have vanished at some point.

Could you add `video_id` back, please?

**Comment by meneses-pt** [comment]
I can also add that there was also a property named `title` and now it also disappeared.

**Comment by matt2legit** [comment]
I had the same issue, but found it's nested in the object with a slightly different name:  `player_response.videoDetails.videoId`.  The title is also there too `player_response.videoDetails.title`

**Comment by cloudrac3r** [comment]
@meneses-pt — The title issue was fixed a couple of days ago. Update.

@matt2legit — thanks, I guess I'll use that for now.

**Comment by fent** [comment]
> I had the same issue, but found it's nested in the object with a slightly different name: `player_response.videoDetails.videoId`. The title is also there too `player_response.videoDetails.title`

yeah this. i'm going to add backwards compatibility for some properties that are no longer present in the root `info` object. but use `info.player_response.videoDetails` for more consistency in the future.
