### ISSUE TITLE
just audio

### ISSUE THREAD

**Issue by cybermarkus1** [fent/node-ytdl-core#47]
So, if i want to get just the audio of the video, how would it be?

ytdl('http://youtube/blabal', {filter: 'audio'}).pipe(fs.createWriteStream('audioVideo.mp3'));

Best and great job!

**Comment by fent** [comment]
"audio" for videos that contain audio, and it may contain video too.
"audioonly" for only audio and no video.

**Comment by loox37** [comment]
Hello fent!!
First of all, great library!
This isn't an issue, more like a question.

I have this line: `downloader(url, {filter: 'audioonly'}).pipe(fs.createWriteStream("test.mp3"));`

How do I know when the file is downloaded or not?
