### ISSUE TITLE
URL takes to Error 403

### ISSUE THREAD

**Issue by NeuronButter** [fent/node-ytdl-core#471]
Hi there! I'm new to this, I'm trying to retrieve a video URL with no audio, and this is the code I've tried:
```
ytdl.getInfo("https://www.youtube.com/watch?v=1N3vUlC5354")
    .then(res => response = res)
    .then(function () {
        console.log(response.formats[3].url); //Video
        console.log(response.formats[20].url); //Audio
    })
```
They output a link each, but visiting that link returns a 403 Error in the normal browser.
I've looked into the problem, and it's supposed to be 'IP locked', but I'm using the same IP address, as I'm running Node from my local machine + the browser on my local machine.
Why is this / am I doing something wrong?
Thanks

**Comment by fent** [comment]
does it work if you download these using ytdl?

**Comment by NeuronButter** [comment]
My main issue is I’m attempting to make a YouTube downloading proxy, where it gets the link and uploads that end file to Google Drive. Does that mean it wouldn’t work?

**Comment by fent** [comment]
ytdl returns a stream, you can download/upload that anywhere

**Comment by MicroDroid** [comment]
Had the same issue, just update library to latest version.

**Comment by Bkucera** [comment]
Urls can be restricted on more than just IP, see https://github.com/ytdl-org/youtube-dl/blob/master/README.md#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser

So could be because different cookies / UA header
