### ISSUE TITLE
Video Not Found 

### ISSUE THREAD

**Issue by NotII** [fent/node-ytdl-core#472]
Issue : 
      throw er; // Unhandled 'error' event
      ^

Error: This video is not available.
    at request (/var/www/html/server/node_modules/ytdl-core/lib/info.js:52:25)
    at PassThrough.stream.on (/var/www/html/server/node_modules/miniget/lib/index.js:195:30)
    at emitNone (events.js:111:20)
    at PassThrough.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Code :
`const express = require('express');
const cors = require('cors');
const ytdl = require('ytdl-core');
const app = express();
app.use(cors());
app.listen(4000, () => {
    console.log('MP4 Server @ port 4000');
});
app.get('/download', (req,res) => {
var URL = req.query.URL;
var stream = ytdl(URL);
stream.on('info', (info) => {
res.header('Content-Disposition', 'attachment; filename=' + info.title + '.mp4');
ytdl(URL, {
    format: 'mp4'
    }).pipe(res);
})});`
I suspect youtube may have blocked the server as the code works fine locally

**Comment by FrostiizGit** [comment]
I do have the same problem, I tried on my 3 servers. All of them have the errors.
However the error does not appear on the same links even if 2 of the servers are in the same data center.

**Comment by NotII** [comment]
I left it overnight and now it started working just wondering if it will happen again and if theres anyway to fix it

**Comment by fent** [comment]
do you have the video this happened on?

**Comment by NotII** [comment]
No specific video it was all I tried

**Comment by FrostiizGit** [comment]
Seems to be working fine again for me also. 
Here are some youtube links that failed last week:
[Nirvana - Smells Like Teen Spirit](https://www.youtube.com/watch?v=hTWKbfoikeg)
[The Clash - Topic](https://www.youtube.com/watch?v=M1Zz7QWbS-w)
[Helmut Fritz - Ca m'énerve](https://youtu.be/4mNDYWhRSaw)
However, they did not fail on all my servers even if some of them are located in the same data-center.
