### ISSUE TITLE
Are itag values fixed?

### ISSUE THREAD

**Issue by AssetKid** [fent/node-ytdl-core#474]
Hi,

Are the itag values fixed?

For example, will `313` always be 2160p webm? I did some tests with a few files and it does seem to be the case.

I am currently using the `getInfo` method to lookup the itag values for each desired quality then starting the download.

Hardcoding the itag values will speed up the entire process.

**Comment by omarroth** [comment]
Generally yes, see [here](https://github.com/ytdl-org/youtube-dl/blob/64b6a4e/youtube_dl/extractor/youtube.py#L413-L516) and [here](https://github.com/omarroth/invidious/blob/46577fb/src/invidious/videos.cr#L140-L248). In some cases it is unfortunately not possible to provide hardcoded values, (e.g. changing width depending on aspect ratio).

**Comment by AssetKid** [comment]
Aaah. Okay.

I think I will stick with the `getInfo` method for now.

Thank you.

**Comment by TimeForANinja** [comment]
🤔 i hope you are using `getInfo` together with `downloadFromInfo`
that way not hardcoding the itag shouldn't make that much of a speed difference
