### ISSUE TITLE
Can't play this video url with 720p60(itag 22) 

### ISSUE THREAD

**Issue by a26364177** [fent/node-ytdl-core#475]
https://www.youtube.com/watch?v=FPmybmCAFW8
Can't play this video url with 720p60(itag 22).

**Comment by fent** [comment]
yeah this is weird. I'm able to download it, but not play it. and I can play other formats too.

I wonder if the encoder on youtube messed up in the uploading process.

**Comment by fent** [comment]
dupe of #163
