### ISSUE TITLE
related_videos is always empty

### ISSUE THREAD

**Issue by cloudrac3r** [fent/node-ytdl-core#479]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/fent/node-ytdl-core/issues/479)

`related_videos` is always empty.

I'm using the latest version of ytdl-core, 0.29.5.

At some point earlier today, YouTube changed something on their end that means ytdl-core fails to find the data. This also affects the [Invidious](https://github.com/omarroth/invidious) project in exactly the same way.

Related video data is still available in the HTML, so just changing where you look for it should be enough to fix this.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#481 Fixed related videos returning empty array](https://issuehunt.io/r/fent/node-ytdl-core/pull/481)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/fent/node-ytdl-core/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by cloudrac3r** [comment]
Here is how Invidious fixed this: https://github.com/omarroth/invidious/commit/16056661ddf19b2e877dc772476a85c5bdccc41e

Related videos data now includes new fields for author ID, author thumbnails, and a precise view count.

**Comment by flaviotordini** [comment]
For me related_videos is always empty. Should I open a new bug? Can someone confirm?

By the way, a test could be added that check for related_videos results.
