### ISSUE TITLE
Example given about how pass video Info to ffmpeg

### ISSUE THREAD

**Issue by cybermarkus1** [fent/node-ytdl-core#48]
pls help

**Comment by fent** [comment]
Look at how [pull](https://github.com/JimmyBoh/pully/blob/master/lib/downloader.js) does it.

I might add a directory of examples or add more examples to the readme. So I'll keep this opened.

**Comment by cybermarkus1** [comment]
thank you!

**Comment by JimmyBoh** [comment]
Pully has be rewritten, [try this instead!](https://github.com/JimmyBoh/pully/blob/master/src/lib/download.ts)
