### ISSUE TITLE
Failing in several server regions

### ISSUE THREAD

**Issue by johann-lr** [fent/node-ytdl-core#489]
My discord client throws the error `TypeError: Cannot read property 'key' of undefined` in some cases. 
First I thought this might be an issue where I defined some wrong properties but after lots of testing, I realized another problem: It only happens if the discord server region is set to US or India (f.ex.), Europe works perfectly.

Do I have to specify a proxy for the core or what might be a problem..?

**Comment by fent** [comment]
do you hate a stack trace? what version are you using?

**Comment by johann-lr** [comment]
1. I am using the latest version of ytdl-core.
2. There's no stack trace available right now, the StreamDispatcher (that loads the stream using ytdl) only returns this string.

**Comment by fent** [comment]
a stack trace would be really helpful, I can't find the property `key` used in ytdl-core's code

**Comment by johann-lr** [comment]
I'm sry, could you help me to get one? I do not really know how to generate that output since I only get this simple string I mentioned above...

**Comment by fent** [comment]
it looks like it does give just a string
https://discord.js.org/#/docs/main/stable/class/StreamDispatcher?scrollTo=e-error

well that's annoying...

**Comment by TimeForANinja** [comment]
You could try creating a new Error the moment it fails and log it's stack - sometimes works for me
