### ISSUE TITLE
formats.forEach is not a function - version 0.7.0

### ISSUE THREAD

**Issue by anitgandhi** [fent/node-ytdl-core#49]
In version 0.7.0, in `sig.js` line 76, the code was changed from `info.formats.forEach` to `formats.forEach`. Now, sometimes when I run the getInfo function, I get the following exception that exits my script: `TypeError: formats.forEach is not a function`. 

Note that this does not occur with all YouTube URLs supplied, only some, though I'm not sure of any particular pattern.

**Comment by fent** [comment]
Do you have a url where this happens? I know the fix, but it would help if I used the video for testing.

**Comment by anitgandhi** [comment]
One time this url broke it: `https://www.youtube.com/watch?v=fHTJ7gYnQzc`.

But that url doesn't always break it.
