### ISSUE TITLE
download progress slows down with filter of audioonly

### ISSUE THREAD

**Issue by its-me-ilia** [fent/node-ytdl-core#490]
I am converting youtube video to mp3 and then letting user download it but if

     ytdl(url,{
          filter: 'audioonly'
      })
      .pipe(res)
there is audioonly filter it downloading progress slows down. for example it video is length of 4:15, mp4 downloads size of 3x MB in five-six seconds and if it is audioonly size of 5MB, it takes 10-15sec or more. how can i fix this? here is full code:

    ytdl.getInfo(url, (err,info)=>{
           res.header('Content-Disposition', 'attachment; filename="'+ transliterate(info.title) 
     +'.mp3"');
           ytdl(url,{
              filter: 'audioonly'
           })
           .pipe(res)
    })

**Comment by RocoGreen** [comment]
Use quality instead

**Comment by its-me-ilia** [comment]
@RocoGreen it still slows down progress

**Comment by RocoGreen** [comment]
@its-me-ilia Did you try a connexion test ? 
And what is the video your trying to download ?

**Comment by its-me-ilia** [comment]
@RocoGreen [https://www.youtube.com/watch?v=SDTZ7iX4vTQ&list=RDSDTZ7iX4vTQ&start_radio=1](Foster The People: Pumped Up Kicks (Official Video))

**Comment by RocoGreen** [comment]
@its-me-ilia Try with https://www.youtube.com/watch?v=SDTZ7iX4vTQ&list=RDSDTZ7iX4vTQ
Did you try a connection test ?

**Comment by its-me-ilia** [comment]
@RocoGreen It still does the same with link you provided, no need for connection test because it works same way in other devices

**Comment by fent** [comment]
rate limiting is done by youtube

**Comment by omarroth** [comment]
See @fent's comment in #294. Also related: nficano/pytube#247 and the linked issue ytdl-org/youtube-dl#15271.

It should be possible to bypass rate-limiting by downloading in chunks of <~10MB.

**Comment by fent** [comment]
> It should be possible to bypass rate-limiting by downloading in chunks of <~10MB.

is this true? I may be able to split it up within ytdl-core

**Comment by omarroth** [comment]
There's some more details in the linked issues, but in most cases I have found that chunking helps with download speeds.

The relevant code in youtube-dl is [here](https://github.com/ytdl-org/youtube-dl/blob/3089bc748c0fe72a0361bce3f5e2fbab25175236/youtube_dl/downloader/http.py#L189-L321), and [here](https://github.com/omarroth/invidious/blob/1085ca4/src/invidious.cr#L4959-L5041) for Invidious.

**Comment by its-me-ilia** [comment]
@omarroth can you show me the snippet how can i donwload in chunks?
