### ISSUE TITLE
This video is unavailable.

### ISSUE THREAD

**Issue by danrleydfl** [fent/node-ytdl-core#494]
- If you're getting a specific error message, include the full stack trace
![](https://i.imgur.com/foWOgEQ.png)
- Include any relevant code around ytdl-core. You don't have to upload your entire program, small snippets are fine.
```js
const dispatcher = await serverQueue.connection.playStream(ytdl(song.url, {
  filter: 'audioonly',
  quality: 'highestaudio',
  highWaterMark: 33554432
}), { seek: 0, volume: 1 })
```
- Environment

Node v10.16.3
ytdl-core v0.29.7
opusscript v0.0.7

#262, #264, #274 and #448

**Comment by fent** [comment]
did this happen for a specific video?

**Comment by gdoron** [comment]
Which video is it? Did you check it's available? In your country?

**Comment by danrleydfl** [comment]
@fent, @gdoron doesn't work for any videos

**Comment by danrleydfl** [comment]
@fent and @gdoron, I found a possible solution to this problem. When we call the 'getInfo' method, the http request is made, but the video id is lowercase when it should actually be normalized.
![](https://i.imgur.com/0VMtIi3.png)
![](https://i.imgur.com/zIQFArB.png)

**Comment by fent** [comment]
ytdl-core doesn't lowercase the video id. are you sure your code isn't lowercasing this from where it's getting the youtube id or url?
