### ISSUE TITLE
Can't use custom user-agent

### ISSUE THREAD

**Issue by gdoron** [fent/node-ytdl-core#495]
Hi @fent,

Currently the library doesn't support sending custom user-agent because of:
https://github.com/fent/node-ytdl-core/blob/4d5858e20ae29e2a7764f7d66d0916614a0174b8/lib/info.js#L40

And if you bypass it with `transform`, some data will be missing (like the author and relatedVideos).

This is because YouTube returns different kind of responses based on the user-agent header, if you don't send a user-agent, like the library currently does, YouTube returns data in format that suits every browser, including IE 6.

It also means, the library might break once YouTube drop support of old browsers like the above.

I can fix it, but it requires some work, so please let me know in advance if you want to merge such a thing and I'll implement it.

Best,
Doron Grinzaig

**Comment by fent** [comment]
> It also means, the library might break once YouTube drop support of old browsers like the above.

this is a worry of mine. not sure if the player config and any "additional" (author, description, media, etc) info is available on the new watch page. if the config is available, but additional info isn't, or harder to parse, that metadata should now available under `player_response.videoDetails`.

if the config isn't available, we could get it through the `embed` or `get_video_info` paths.

> I can fix it, but it requires some work, so please let me know in advance if you want to merge such a thing and I'll implement it.

that would be great

**Comment by gdoron** [comment]
@fent it will take me some time as I'm busy with other projects, but it's on my list.
Thanks!

**Comment by gdoron** [comment]
I'm quite overloaded with other tasks I need to do for work, so if someone else is willing to take it, it's up for grab.
Otherwise, it can take some time but as I said, it's on my list.

**Comment by fent** [comment]
there's a new api that people are using, when going to the `/watch` page with the `pbj=1` param, along with [these headers](https://github.com/fent/node-ytdl-core/pull/503/files), it'll return a json object.

I've yet to investigate it too much, but that's another viable option

**Comment by fent** [comment]
I have an implementation at https://github.com/fent/node-ytdl-core/tree/new-endpoint if you or anyone is interested in testing it out.

I still need to update the tests for it so it will be a while before it's merged to master

currently, this issue and https://github.com/fent/node-ytdl-core/issues/523 issues are the only issues it fixes

**Comment by gdoron** [comment]
Hi @fent , sorry for going AFK for so long... 
FYI: the change still doesn't allow sending custom user agent for YouTube.
I can't share why I need such an odd feature after all, why does it matter if the API works, but we need it...
