### ISSUE TITLE
Related Videos thumbnail url correction

### ISSUE THREAD

**Issue by joek85** [fent/node-ytdl-core#498]
`videos.push({
          id: details.videoId,
          title: details.title.simpleText,
          author: details.shortBylineText.runs[0].text,
          ucid: details.shortBylineText.runs[0].navigationEndpoint.browseEndpoint.browseId,
          author_thumbnail: details.channelThumbnail.thumbnails[0].url,
          short_view_count_text: shortViewCount.split(' ')[0],
          view_count: viewCount.replace(',', ''),
          length_seconds: Math.floor(parseTime.humanStr(details.lengthText.simpleText) / 1000)
        });`

author_thumbnail gives the channel thumbnail, instead we also need the video thumbnail, so i added this line

`video_thumbnail: details.thumbnail.thumbnails[0].url`
Thanks.

**Comment by TinyMan** [comment]
I'll make a PR for that after I test it :)

**Comment by joek85** [comment]
Thank you, i will close this issue, BTW how can i reach you in private?
