### ISSUE TITLE
ytdl (Web Version)

### ISSUE THREAD

**Issue by joek85** [fent/node-ytdl-core#506]
Hello, i would like to offer my project:
https://github.com/joek85/trooveo

Made using VueJs (Front-End) and Node (Back-End), Please check it out and help us improve it.
It is based heavily on ytdl in all variants.
If you feel that my post isn't belong to here, please feel free to let me know so i can remove it.
Enjoy!

**Comment by mh4ck** [comment]
This is for issues not for Promo!

**Comment by fent** [comment]
I'm not entirely against promos, but don't think this belongs here. there is a section in the readme about related projects, but that's more for other libraries that can help you complement using ytdl-core, and not projects built by ytdl-core so much.

and I would rather not update the readme each time there's a new project just to promote each other. plus, someone could always look at ytdl-core dependents at https://www.npmjs.com/package/ytdl-core

maybe a wiki page should be made for such a list?

@joek85 thank you for sharing, have you seen [invidious](https://github.com/omarroth/invidious)?

**Comment by joek85** [comment]
hello, a wiki page would be a good idea.
yes i tired invidious, looks promising.
