### ISSUE TITLE
Example on event?

### ISSUE THREAD

**Issue by NeuronButter** [fent/node-ytdl-core#511]
Can someone please explain how to listen for this event? I couldn't find an example on how this could be used: https://github.com/fent/node-ytdl-core#event-info

**Comment by fent** [comment]
it's emitted on the stream that ytdl returns

```js
let stream = ytdl(url);
stream.on('info', (info) => {
  // do stuff
});
```

**Comment by NeuronButter** [comment]
Thanks!
