### ISSUE TITLE
Convert To mp3

### ISSUE THREAD

**Issue by maxlanser** [fent/node-ytdl-core#514]
when i run `node example/conver_to_js` in console return message `Cannot find module 'fluent-ffmpeg'`

this package is not in the package.json file, I installed it manually, but that didn't help either

**Comment by MCannucci** [comment]
ytdl-core doesn't support video or sound processing. The example is showing how to use ytdl-core with an FFMPEG wrapper (fluent-ffmpeg).

Include FFMPEG in your environment's PATH or FFMPEG_PATH variables for the example to work
(as well as having the module fluent-ffmpeg installed)
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#prerequisites

**Comment by FireController1847** [comment]
Closing as I feel this is resolved. Feel free to re-open the issue if needed

**Comment by HemKal** [comment]
You need to set your response header like this
`res.attachment(`${title}.${fmt}`)`
