### ISSUE TITLE
What exactly is the point of html5player and how can it be used?

### ISSUE THREAD

**Issue by NeuronButter** [fent/node-ytdl-core#515]
Hi! I've been looking through some of the response data, and I came across an interesting .js file. From `ytdl(url, options).on('info', (args) => {console.log(args)})`, the second last item in the object is html5player. It refers to a base.js file. What is this, and how can I use that? (Just curious if it's similar to the YouTube Player, that's all)
![image](https://user-images.githubusercontent.com/33238007/69219855-dcdba100-0bc7-11ea-8298-477c9fe468c8.png)

**Comment by fent** [comment]
it's used by ytdl-core to decipher the signature that many videos have. the signature must be deciphered and included in video requests for the downloads to go through.

I don't know how you or other users can make use of it, there's a lot of metadata and properties in `info` that are included in case someone needs it

I have considered only including `info.player_response.videoDetails`, which contains more specific information about the video such as title, description, view counts, author, etc. but it would probably break a lot of workflows that depend on some obscure property

**Comment by NeuronButter** [comment]
Ah, makes sense. Thanks for that!
