### ISSUE TITLE
Set config --limit-rate 

### ISSUE THREAD

**Issue by brunoqs** [fent/node-ytdl-core#518]
Is there any way to set an config limit rate like youtube-dl?

**Comment by fent** [comment]
I don't see this option in the docs, do you mean `--limit-rate`?

**Comment by brunoqs** [comment]
Yes

**Comment by TimeForANinja** [comment]
It is not currently implemented.
Should be doable thou (for e.g. using miniget's transform option).

**Comment by fent** [comment]
ytdl-core returns a [readable stream](https://nodejs.org/api/stream.html#stream_class_stream_readable), it can be read as fast as your download speed, or slower.

here's a module that throttles reading a stream
https://www.npmjs.com/package/throttled-reader
