### ISSUE TITLE
m3u8stream Can not find module 'parse-time'

### ISSUE THREAD

**Issue by emeraldfactory** [fent/node-ytdl-core#519]
I downloaded the latest version of ytdl-core to integrate music playing in a custom bot I'm making for a friend. When i go to run the  the bot for testing i get this error in the console log when starting the bot. When I comment out the "require('ytdl-core')" the bot starts up and runs normally.

Error: Cannot find module 'm3u8stream/lib/parse-time'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\.....\node_modules\ytdl-core\lib\info-extras.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by Cannicide** [comment]
I am also getting this error when using version 1.0.0 of ytdl-core, "Error: Cannot find module 'm3u8stream/lib/parse-time'". I believe 'm3u8stream/lib/parse-time' is imported in ytdl-core's 'info-extras.js'.

**Comment by emeraldfactory** [comment]
Did this started when you updated to 1.0.0? Did an older version of YTDL worked for you in the past?

**Comment by Cannicide** [comment]
No, I tried using older versions and they gave me the same error.

**Comment by mdmrcglu** [comment]
cp ./ytdl/node_modules/m3u8stream/dist /ytdl/node_modules/m3u8stream/lib

**Comment by emeraldfactory** [comment]
I'm working on a window, what would be the command equivalent?

**Comment by nicholasbrokaw** [comment]
I saw that a pull request has been made to fix this change, and the solution looks good to me.

I think that what @mdmrcglu said should work in the command line, @emeraldfactory. What window are you working in?
> cp ./ytdl/node_modules/m3u8stream/dist /ytdl/node_modules/m3u8stream/lib

**Comment by emeraldfactory** [comment]
Sorry I meant to say working I'm in windows OS, I uninstalled and rolled back to an early version  of YTDL but no dice. I then copied the files from m3u8stream/dist to them3u8stream/lib as @mdmrcglu suggested and its now working. Thank you for the help.

**Comment by nicholasbrokaw** [comment]
Oh good!

**Comment by TimeForANinja** [comment]
For everyone finding this post or getting referenced: just update your dependencies

**Comment by DonikaV** [comment]
@TimeForANinja which dependencies? :)

**Comment by TimeForANinja** [comment]
At least ytdl-core
