### ISSUE TITLE
FFMPEG not found on heroku

### ISSUE THREAD

**Issue by simonvank98** [fent/node-ytdl-core#522]
![image](https://user-images.githubusercontent.com/39694777/69380820-9e231500-0cb3-11ea-96f6-dbfc8b6d4c2c.png)
I have a basic music bot for discord that uses the m3u8stream package, and locally it works, but whenever its trying to build on Heroku it gives me the error that FFMPEG can not be found.

I think this error is not the initial error, I suspect that ytdl-core still tries to find m3u8stream/lib/parse-time instead of the newly patched m3u8stream/dist/parse-time

anyone an idea? not sure what info to give more so ask me anything

**Comment by TimeForANinja** [comment]
my idea is it is finding m3u8stream's parse-time
obvious reason would be you do indeed not have ffmpeg installed or it's not in your env

**Comment by simonvank98** [comment]
![image](https://user-images.githubusercontent.com/39694777/69381692-a2e8c880-0cb5-11ea-9cc0-c41d2c772381.png)
I do have FFMPEG mentioned in the package.json thougt?

**Comment by fent** [comment]
can you run `ffmpeg` in the command line?

**Comment by simonvank98** [comment]
![image](https://user-images.githubusercontent.com/39694777/69387683-e0a21d00-0cc6-11ea-9bed-7559bda9d45a.png)
Yes I can, maybe the problem is in building the app/bot on heroku? build does succeed tho

> can you run `ffmpeg` in the command line?

**Comment by simonvank98** [comment]
![image](https://user-images.githubusercontent.com/39694777/69387823-54442a00-0cc7-11ea-84cb-31c983961fda.png)
Could it be that heroku still has the old node_modules where dist/lib is not yet updated?

**Comment by TimeForANinja** [comment]
a) the "ffmpeg" dependency is just another wrapper, not the binaries
b) did you run `ffmpeg` in your local terminal to show us it's installed on heroku?

**Comment by simonvank98** [comment]
@TimeForANinja Hi sorry I thought you meant running `ffmpeg ` local, I am not sure how to run `ffmpeg` on Heroku, do you maybe know how I can test that?

**Comment by TimeForANinja** [comment]
if i remember right there's a package like "ffmpeg-binaries" (or sth like that) that discord.js pushed which installs ffmpeg for you

**Comment by simonvank98** [comment]
@TimeForANinja I am not sure what you want me to check/how to do it, what was your question?

**Comment by TimeForANinja** [comment]
thought of this package: https://www.npmjs.com/package/ffmpeg-binaries
has been deprecated thou...

**Comment by simonvank98** [comment]
@TimeForANinja installed `ffmpeg-static`, because `ffmpeg-binaries` didn't work but no changes, issue still there

**Comment by fent** [comment]
you're still getting the same error? [prism-media docs](https://github.com/amishshah/prism-media#dependencies) say installing `ffmpeg-static` should work?

**Comment by simonvank98** [comment]
@fent Yes, I am stil getting the same error with `node-opus` and `ffmpeg-static` :(
this is my package.json 
![image](https://user-images.githubusercontent.com/39694777/69832352-0df24c00-122e-11ea-8559-d1b7b1fd511e.png) and this is still the error 
![image](https://user-images.githubusercontent.com/39694777/69832360-1f3b5880-122e-11ea-9253-efddcd4f278c.png)

**Comment by fent** [comment]
I don't know. I'd ask the prism-media people why it isn't detecting ffmpeg

**Comment by HershKirsh** [comment]
I think you need to  add a plug-in like
[THIS](https://elements.heroku.com/buildpacks/jonathanong/heroku-buildpack-ffmpeg-latest) to your heroku app

**Comment by simonvank98** [comment]
I've added the buildpack and that helped! thankyou @HershKirsh

**Comment by Morrouh** [comment]
> @simonvank98 I think you need to add a plug-in like
> [THIS](https://elements.heroku.com/buildpacks/jonathanong/heroku-buildpack-ffmpeg-latest) to your heroku app

it's working for me too. Thank you so much!

**Comment by macedonga** [comment]
Try using https://github.com/kontentcore/heroku-buildpack-ffmpeg

**Comment by vkaelin** [comment]
Another option: https://www.npmjs.com/package/ffmpeg-static

**Comment by gitpierpy** [comment]
Yes, static build, then adjust PATH adding ffmpeg position in Heroku:  "Settings>Config Vars". Works fine for me. This avoids absolute ffmpeg path  in your code
