### ISSUE TITLE
"Proxy with auth" example not working.

### ISSUE THREAD

**Issue by mh4ck** [fent/node-ytdl-core#524]
Hi, i tried the proxy with auth example and got a **400 Bad Request** response. 
Then i changed the `path: parsed.href` to `path: parsed.path` now i get the error **To many redirects** does anybody else got it to work?

Here is a test Proxy if smbd. want to test.
{"host":"217.29.63.224","port":"10798","user":"SgpHms","pass":"6QQu3N"}

**Comment by fent** [comment]
can you get the above working with the `http` module, without ytdl-core? I get an auth error with the following, is this an http proxy?

```js
const http = require('http');
const { parse } = require('url');

let url = 'https://www.youtube.com/watch?v=iTg1bV2vks8';
let parsed = parse(url);
let username = 'SgpHms';
let password = '6QQu3N';
let auth = 'Basic ' + Buffer.from(username + ':' + password).toString('base64');

console.log('requesting...');
let useProxy = true;
http.get(useProxy ? {
  host: '217.29.63.224',
  port: 10798,
  path: parsed.path,
  headers: {
    Host: parsed.host,
    Authorization: auth,
  },
} : parsed, (res) => {
  console.log('got res', res.statusCode);
  res.setEncoding('utf8')
  res.on('data', (chunk) => {
    console.log('downloaded', chunk);
  });
});
```

I got most of the code from https://stackoverflow.com/a/3905553/157629

**Comment by RocoGreen** [comment]
Use `Proxy-Authorization` instead :

```js
const http = require('http');
const { parse } = require('url');

let url = 'https://www.youtube.com/watch?v=iTg1bV2vks8';
let parsed = parse(url);
let username = 'SgpHms';
let password = '6QQu3N';
let auth = 'Basic ' + Buffer.from(username + ':' + password).toString('base64');

console.log('requesting...');
let useProxy = true;
http.get(useProxy ? {
  host: '217.29.63.224',
  port: 10798,
  path: parsed.path,
  headers: {
    Host: parsed.host,
    "Proxy-Authorization": auth,
  },
} : parsed, (res) => {
  console.log('got res', res.statusCode);
  res.setEncoding('utf8')
  res.on('data', (chunk) => {
    console.log('downloaded', chunk);
  });
});
```

**Comment by fent** [comment]
if I remove `protocol` from the proxy_with_auth example, it works. with `protocol` set to always be "http:", I get a `too many redirects` error because youtube keeps trying to redirect to the https version of the site

**Comment by DELUUXE** [comment]
when removing the ``protocol: 'http'`` i am receiving the following error

```
Error: write EPROTO 26768:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:openssl\ssl\record\ssl3_record.c:252:
at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:66:16)
```

**Comment by fent** [comment]
I'm getting that too with a proxy from proxyorbit. I also tried using [http-proxy-agent](https://www.npmjs.com/package/http-proxy-agent) and got a `Status Code: 502` error.

**Comment by mh4ck** [comment]
And why you closed it then. I also tried a lot of things - but came up to switch over to "request" module. Found no other way to get it work.

**Comment by fent** [comment]
The proxy you have in your OP does work for me with the example, after removing `protocol`

**Comment by DELUUXE** [comment]
> I'm getting that too with a proxy from proxyorbit. I also tried using [http-proxy-agent](https://www.npmjs.com/package/http-proxy-agent) and got a `Status Code: 502` error.

seems like ill be trying to find a different proxy provider, sorry for bothering 😓

**Comment by fent** [comment]
ah, so I tried using [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent) instead, since ytdl-core makes https requests, and it worked.

```js
const ytdl = require('..');
const Agent = require('https-proxy-agent');

const proxy = 'http://xxx.xxx.xxx.xxx:xxxx';
const agent = new Agent(proxy);
const stream = ytdl('https://www.youtube.com/watch?v=2UBFIhS1YBk', {
  requestOptions: { agent }
});

console.log('Starting Download');

stream.on('data', (chunk) => {
  console.log('downloaded', chunk.length);
});

stream.on('end', () => {
  console.log('Finished');
});
```

I can update the examples to show usage with https-proxy-agent instead of using `requestOptions.transform` since handling proxies can be complicated, and there are many types. so better to leave it up to another optional module to handle it.

**Comment by DonikaV** [comment]
`{"error":{},"level":"error","message":"uncaughtException: The \"msecs\" argument must be of type number. Received type object\nTypeError [ERR_INVALID_ARG_TYPE]: The \"msecs\" argument must be of type number. Received type object\n    at validateNumber (internal/validators.js:130:11)\n    at validateTimerDuration (internal/timers.js:146:3)\n    at TLSSocket.Socket.setTimeout (net.js:407:11)\n    at setRequestSocket (_http_agent.js:361:10)\n    at handleSocketCreation_Inner (_http_agent.js:349:7)\n    at oncreate (_http_agent.js:224:5)\n    at Agent.createSocket (_http_agent.js:229:5)\n    at Agent.addRequest (_http_agent.js:185:10)\n    at new ClientRequest (_http_client.js:249:16)\n    at Object.request (https.js:289:10)\n    at Object.request (/Users/donika/Sites/mp3-ytb/node_modules/agent-base/patch-core.js:25:22)\n    at Object.https.get (/Users/donika/Sites/mp3-ytb/node_modules/agent-base/patch-core.js:48:21)\n    at doDownload (/Users/donika/Sites/mp3-ytb/node_modules/miniget/dist/index.js:110:25)\n    at process._tickCallback (internal/process/next_tick.js:61:11)","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"msecs\" argument must be of type number. Received type object\n    at validateNumber (internal/validators.js:130:11)\n    at validateTimerDuration (internal/timers.js:146:3)\n    at TLSSocket.Socket.setTimeout (net.js:407:11)\n    at setRequestSocket (_http_agent.js:361:10)\n    at handleSocketCreation_Inner (_http_agent.js:349:7)\n    at oncreate (_http_agent.js:224:5)\n    at Agent.createSocket (_http_agent.js:229:5)\n    at Agent.addRequest (_http_agent.js:185:10)\n    at new ClientRequest (_http_client.js:249:16)\n    at Object.request (https.js:289:10)\n    at Object.request (/Users/donika/Sites/mp3-ytb/node_modules/agent-base/patch-core.js:25:22)\n    at Object.https.get (/Users/donika/Sites/mp3-ytb/node_modules/agent-base/patch-core.js:48:21)\n    at doDownload (/Users/donika/Sites/mp3-ytb/node_modules/miniget/dist/index.js:110:25)\n    at process._tickCallback (internal/process/next_tick.js:61:11)","exception":true,"date":"Sun Dec 08 2019 15:10:49 GMT+0100 (Central European Standard Time)","process":{"pid":28723,"uid":501,"gid":20,"cwd":"/Users/donika/Sites/mp3-ytb","execPath":"/usr/local/bin/node","version":"v10.16.0","argv":["/usr/local/bin/node","/Users/donika/Sites/mp3-ytb/bin/www"],"memoryUsage":{"rss":68464640,"heapTotal":33914880,"heapUsed":29027008,"external":18386835}},"os":{"loadavg":[2.609375,2.3408203125,2.32177734375],"uptime":324713},"trace":[{"column":11,"file":"internal/validators.js","function":"validateNumber","line":130,"method":null,"native":false},{"column":3,"file":"internal/timers.js","function":"validateTimerDuration","line":146,"method":null,"native":false},{"column":11,"file":"net.js","function":"TLSSocket.Socket.setTimeout","line":407,"method":"setTimeout","native":false},{"column":10,"file":"_http_agent.js","function":"setRequestSocket","line":361,"method":null,"native":false},{"column":7,"file":"_http_agent.js","function":"handleSocketCreation_Inner","line":349,"method":null,"native":false},{"column":5,"file":"_http_agent.js","function":"oncreate","line":224,"method":null,"native":false},{"column":5,"file":"_http_agent.js","function":"Agent.createSocket","line":229,"method":"createSocket","native":false},{"column":10,"file":"_http_agent.js","function":"Agent.addRequest","line":185,"method":"addRequest","native":false},{"column":16,"file":"_http_client.js","function":"new ClientRequest","line":249,"method":null,"native":false},{"column":10,"file":"https.js","function":"Object.request","line":289,"method":"request","native":false},{"column":22,"file":"/Users/donika/Sites/mp3-ytb/node_modules/agent-base/patch-core.js","function":"Object.request","line":25,"method":"request","native":false},{"column":21,"file":"/Users/donika/Sites/mp3-ytb/node_modules/agent-base/patch-core.js","function":"Object.https.get","line":48,"method":"get","native":false},{"column":25,"file":"/Users/donika/Sites/mp3-ytb/node_modules/miniget/dist/index.js","function":"doDownload","line":110,"method":null,"native":false},{"column":11,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":61,"method":"_tickCallback","native":false}]}
`
:(

**Comment by DonikaV** [comment]
```
{ Error: connect EHOSTUNREACH 0.0.254.209:80 - Local (192.168.88.247:61174)
    at internalConnect (net.js:881:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1028:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '0.0.254.209',
  port: 80 }

```

**Comment by mh4ck** [comment]
> ah, so I tried using [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent) instead, since ytdl-core makes https requests, and it worked.
> 
> ```js
> const ytdl = require('..');
> const Agent = require('https-proxy-agent');
> 
> const proxy = 'http://xxx.xxx.xxx.xxx:xxxx';
> const agent = new Agent(proxy);
> const stream = ytdl('https://www.youtube.com/watch?v=2UBFIhS1YBk', {
>   requestOptions: { agent }
> });
> 
> console.log('Starting Download');
> 
> stream.on('data', (chunk) => {
>   console.log('downloaded', chunk.length);
> });
> 
> stream.on('end', () => {
>   console.log('Finished');
> });
> ```
> 
> I can update the examples to show usage with https-proxy-agent instead of using `requestOptions.transform` since handling proxies can be complicated, and there are many types. so better to leave it up to another optional module to handle it.

You not using the Authentication in your example.

**Comment by mh4ck** [comment]
> ah, so I tried using [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent) instead, since ytdl-core makes https requests, and it worked.
> 
> ```js
> const ytdl = require('..');
> const Agent = require('https-proxy-agent');
> 
> const proxy = 'http://xxx.xxx.xxx.xxx:xxxx';
> const agent = new Agent(proxy);
> const stream = ytdl('https://www.youtube.com/watch?v=2UBFIhS1YBk', {
>   requestOptions: { agent }
> });
> 
> console.log('Starting Download');
> 
> stream.on('data', (chunk) => {
>   console.log('downloaded', chunk.length);
> });
> 
> stream.on('end', () => {
>   console.log('Finished');
> });
> ```
> 
> I can update the examples to show usage with https-proxy-agent instead of using `requestOptions.transform` since handling proxies can be complicated, and there are many types. so better to leave it up to another optional module to handle it.

How to add Authorization to this example?

**Comment by DonikaV** [comment]
@mh4ck I tried this
https://github.com/TooTallNate/node-https-proxy-agent/issues/12#issuecomment-216098644 but not working for me

**Comment by mh4ck** [comment]
> @mh4ck I tried this
> [TooTallNate/node-https-proxy-agent#12 (comment)](https://github.com/TooTallNate/node-https-proxy-agent/issues/12#issuecomment-216098644) but not working for me

And if you use "Authentication" instead of "Proxy-Authentication" ?

**Comment by DonikaV** [comment]
at internalConnect (net.js:881:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1028:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '0.0.254.209',
  port: 80 }

**Comment by DonikaV** [comment]
```
const agent = new Agent({
    host: "45.89.191.120",
    port: "65233",
    headers: {
        username,
        password,
    },
});

Error: Status code: 407
    at ClientRequest.httpLib.get (/Users/donika/Sites/mp3-ytb/node_modules/miniget/dist/index.js:128:27)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:198:13)
    at Socket.Readable.read (_stream_readable.js:491:10)
    at flow (_stream_readable.js:957:34)
    at resume_ (_stream_readable.js:938:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by DonikaV** [comment]
If i try to use some free proxy without auth
```

getInfo(videoId, {
          requestOptions: {
            transform: (parsed) => {
              return {
                host: '41.213.13.154',
                port: 4145,
                path: parsed.href,
                headers: { Host: parsed.host },
              };
            },
          },
        })
```

{ Error: connect ECONNREFUSED 41.213.13.154:4145
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '41.213.13.154',
  port: 4145 }

**Comment by fent** [comment]
`headers` doesn't take username/password, look at the https-proxy-agent issue that was linked. and you probably still need https-proxy-agent for proxies without auth

**Comment by DonikaV** [comment]
Just fot first proxy from google https://free-proxy-list.net/
```ts
const agent = new Agent("8.209.83.91:3128");
getInfo(videoId, {
          requestOptions: { agent },
        }).then(function successCallback(response) {
          res.json(response).end();
          convertAndDownload(userBitrate, response, res, socket, fileName);
      }, function errorCallback(response) {
          console.log(response);
          res.status(500).json({error: errMsg});
      });
```

 Error: connect EHOSTUNREACH 0.0.12.56:80 - Local (192.168.88.247:63344)
    at internalConnect (net.js:881:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1028:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '0.0.12.56',
  port: 80 }

**Comment by fent** [comment]
I just tried a couple of random proxies from there, took a few minutes to start up but eventually it did start downloading.

```js
const ytdl = require('..');
const Agent = require('https-proxy-agent');

const host = '177.54.130.149';
const port = '59044';
const proxy = `http://${host}:${port}`;
const agent = new Agent(proxy);
const stream = ytdl('https://www.youtube.com/watch?v=2UBFIhS1YBk', {
  requestOptions: { agent }
});

console.log('Starting Download');

stream.on('data', (chunk) => {
  console.log('downloaded', chunk.length);
});

stream.on('end', () => {
  console.log('Finished');
});

```

I noticed that the ones that don't support https give an error, even if I try using the request module just to make sure

```js
const request = require('request');

const url = 'https://www.youtube.com/watch?v=2UBFIhS1YBk';
const host = '188.226.141.127';
const port = '3128';
const proxy = `http://${host}:${port}`;

request({ url, proxy }, (err, res) => {
  if (err) throw err;
  console.log('got res', res.statusCode);
});
```

**Comment by DonikaV** [comment]
@fent Yes, true, after couple of minutes it start download. But what i can do if i have 'premium' pfoxies from service? Where i need use login and password?

**Comment by fent** [comment]
did you try https://github.com/TooTallNate/node-https-proxy-agent/issues/12#issuecomment-216098644

**Comment by DonikaV** [comment]
yes, hundreds of times, all variants
