### ISSUE TITLE
how to add an end , so last bit of the video is not downloaded

### ISSUE THREAD

**Issue by arcovoltaico** [fent/node-ytdl-core#525]
I can see there's an option for setting a **start** point
 , so the file won't contain the previous seconds.
Is there a way to do the same trimming the end?
I can't see an "**end**" option ... any workaround?
Cheers

**Comment by mh4ck** [comment]
Maybe just set the length?

**Comment by fent** [comment]
there's no `end` option. I've been wanting to investigate how to do it and to find an alternative to `begin` since it's unreliable https://github.com/fent/node-ytdl-core/issues/357
