### ISSUE TITLE
filter: 'audioonly' does not work on v1.0.2

### ISSUE THREAD

**Issue by mahhov** [fent/node-ytdl-core#529]
Was using an older version in the morning (0.27), and `ytdl(<id>, {filter: 'audioonly'})` worked fine. I updated to version 1.0.2, and now I get `No formats found`.

From what I can tell, this is the relevant code: 
`fn = (format) => !format.bitrate && format.audioBitrate;`
https://github.com/fent/node-ytdl-core/blob/df7c80b03c4e59a602bb77f2a43535d3041f77c1/lib/util.js#L188

Here are console.logs of the available formats for a particular video:

```
const ytdl = require('ytdl-core');
ytdl.getInfo('QvtjAoFBmVg', (err, info) =>
    console.log(JSON.stringify(info.formats)));
```

Version 0.27, note the last 4 formats have `bitrate: null`:
https://gist.github.com/mahhov/632f869350ebb5a6dab64ce7715ea449

Version 1.0.2, note that now all 23 formats have a bitrate:
https://gist.github.com/mahhov/5cfa8ae7c9853f3d2cdb99fe1dabf954

**Comment by RocoGreen** [comment]
`bitrate` is `null` if it's a audio format but `audioBitrate` not.
I dunno but the line you refered is correct so something isn't right
And please, can you send me the video url ?

**Comment by mahhov** [comment]
For this one example at least, checking 
`format.mimeType.startsWith('audio') && format.audioBitrate` or `!format.qualityLabel && format.audioBitrate` would both work, but I'm not sure if that's valid for all videos.

**Comment by RocoGreen** [comment]
I checked with an another video but fent verification is correct but something isn't right

**Comment by mahhov** [comment]
The video ID is in my snippet, `QvtjAoFBmVg`. 
> bitrate is null if it's a audio format 
It has 23 formats available, the last 4 are audio-only but have non-`null` `bitrate` with v1.0.2, as seen in my 2nd JSON gist.

**Comment by RocoGreen** [comment]
Problem noticed, some audio formats contains `bitrate` value, i will try an another verification

**Comment by RocoGreen** [comment]
So the fix is: 
`fn = (format) => !format.qualityLabel && format.audioBitrate`
