### ISSUE TITLE
We're "breaking records" guys!!!

### ISSUE THREAD

**Issue by danrleydfl** [fent/node-ytdl-core#533]
Ytdl-core looks like a scratched disc (repeating parts of the song)
This occurs in this song:
https://youtu.be/ptkw2rPhAuM

**Comment by fent** [comment]
I wasn't able to reproduce. how are you downloading the video?

**Comment by danrleydfl** [comment]
{filter: 'audioonly', quality: 'lowest'}

**Comment by fent** [comment]
unable to reproduce. I've now listened to this song 3 times, good song though.

**Comment by 22preich** [comment]
I had this! I fixed it tho following the stuff they said in #405 . Basically `{filter: 'audioonly', quality: "highestaudio", highWaterMark: 1<<25}`.
