### ISSUE TITLE
Question: It save any data on hdd? For example .mp3 files?

### ISSUE THREAD

**Issue by baxandrei** [fent/node-ytdl-core#534]
It save any data on hdd? For example .mp3 files?

**Comment by fent** [comment]
it uses a [node stream](https://nodejs.org/api/stream.html#stream_class_stream_readable) to read the video sequentially chunk by chunk into memory. you can save it to a file or play it or do whatever with it.

if you need to save it in mp3 format, look in the examples folder for that specific use case.
