### ISSUE TITLE
Error: No such format found: 141

### ISSUE THREAD

**Issue by Amenocy** [fent/node-ytdl-core#54]
hi , 
1-i set quality such your example but give an error
ytdl(link, { quality: 141 }).pipe(res);
Error: No such format found: 141
, 
2- how i can send file to user(pipe) with size and file name with correct format ?
 tank you .

**Comment by fent** [comment]
If you really want that particular format, it might not always be available. `quality` is optional, and can be other values: https://github.com/fent/node-ytdl-core#ytdlurl-options

**Comment by Amenocy** [comment]
okay , i do it in 2 step  , get info and download
