### ISSUE TITLE
No sound on some Youtube URL

### ISSUE THREAD

**Issue by arcovoltaico** [fent/node-ytdl-core#542]
My code works with 99,99% of youtube videos. But on some cases, i.e.: `location='Z0blBD6_nfg'`
the downloaded video has no audio. If I download that video with the mac app 4K Video Downloader the audio is ok, so hopefully there's a way to sort it out...  Thanks for your nice work and help.

```
  const location=  'Z0blBD6_nfg';
  const url = 'https://www.youtube.com/watch?v=' + location;

            ytdl.getInfo(url, { quality: 'highest' }, function(err, info) {
                const stream = ytdl.downloadFromInfo(info, {
                    quality: 'highest',
                    requestOptions: { maxRedirects: 5 }
                })
                    .pipe(file);
            });
```

**Comment by fent** [comment]
some formats contain no sound. try using `filter: 'audioandvideo'` in the options

**Comment by arcovoltaico** [comment]
As long as I can find, there's no 'audioandvideo´option any more : 
```
     filter?: 'video' | 'videoonly' | 'audio' | 'audioonly' | ((format: videoFormat) => boolean);
```

**Comment by fent** [comment]
ok, I just published a fix for the types issue, the 'audioandvideo' filtering option should be there now

**Comment by Gr3gorywolf** [comment]
I guess that the problem isnt the filter because i looked into the videoinfos output and all the videos have `audioformat: null`  except one 360p video

**Comment by oliverschwendener** [comment]
Same issue here. Can't see the "audioandvideo" option in index.d.ts:

https://github.com/fent/node-ytdl-core/blob/44bf980713a5d875c4bcb288dfc386ad98bc7282/typings/index.d.ts#L5-L20

**Comment by fent** [comment]
update to latest, [v1.0.4](https://github.com/fent/node-ytdl-core/releases/tag/v1.0.4) had typings updated

**Comment by oliverschwendener** [comment]
I am using the latest version (v1.0.5) but can't find it in neither v1.0.5 nor v1.0.4. Commit message says

```
fix: types now have `filter: 'audioandvideo'`"
```

but there is no such option in index.d.ts. See here:

https://github.com/fent/node-ytdl-core/blob/44bf980713a5d875c4bcb288dfc386ad98bc7282/typings/index.d.ts#L5-L7

Am I doing something wrong?

**Comment by TimeForANinja** [comment]
nope, you're not doing anything wrong... guess fent forgot to add the `audioandvideo` option after moving the Filters

**Comment by fent** [comment]
oh crap I did

**Comment by fent** [comment]
new version published

**Comment by arcovoltaico** [comment]
Thanks, so any ideas on how to circumvent this edge case? I did found another id with the same issue ...  NfljhBjGoA8

**Comment by arcovoltaico** [comment]
It works like a charm, thanks peeps!

**Comment by Taha-Chaudhry** [comment]
Not working for me...

**Comment by Taha-Chaudhry** [comment]
It seems that it doesn't work when I select the 1080p quality, or set quality to 299

**Comment by Piliponful** [comment]
great lib bro, thanks
