### ISSUE TITLE
ytdl-core crash discord bot

### ISSUE THREAD

**Issue by LWJerri** [fent/node-ytdl-core#545]
![Снимок](https://user-images.githubusercontent.com/50290430/71382847-712f8e00-25e2-11ea-93e6-fc0076f7a71e.PNG)

Crash witch i'm typing url https://www.youtube.com/watch?v=KAdleD1XU3g and maybe such links are still somewhere else

**Comment by Asaduji** [comment]
I recommend you to properly catch errors to avoid your bot crashing
