### ISSUE TITLE
Streams not playing Apple

### ISSUE THREAD

**Issue by dayjur** [fent/node-ytdl-core#549]
Hi,
Can get stream link for videos no issue but only streams with format codes 18,22,37 only play,other just buffer for ever on Apple devices like Mac, Apple tv etc.

**Comment by fent** [comment]
how are you using this on apple tv?

**Comment by dayjur** [comment]
I play the stream using Unity and AVPro asset, I try opening the stream returned in safari browser open but does not play seems also with audio stream not play only itag 18,22 and 37 play
Seems like apple google blocking certain streams or something over on android for example exo player will play streams right away but on some there was a 30 seocnd delay before playing on media player.

**Comment by fent** [comment]
sorry I don't understand. are you calling ytdl-core from unity, then giving the url to your browser?

**Comment by dayjur** [comment]
Correct I call ytdl from Unity, and pass the stream link to AVPro after not playing I copied link to a browser and browser stuck too

**Comment by dayjur** [comment]
U can prob replicate get a stream link for itag 137 and try playing on mac safari browser

**Comment by fent** [comment]
the itag 137 is of [DASH format](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP). it may not be supported by appletv, or even directly by your browser. ytdl-core uses [m3u8stream](https://github.com/fent/node-m3u8stream) to play such formats

**Comment by dayjur** [comment]
Yes that is the case no apple devices I use will play direct link from 137 have to use non adaptive stream
