### ISSUE TITLE
Error: Could not extract html5player key after upgrading to 0.7.5

### ISSUE THREAD

**Issue by mhlavacka** [fent/node-ytdl-core#55]
W20151109-20:51:03.154(-5)? (STDERR) could not extract html5player key: //s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js

I tried to use previous versions but got the same error.

**Comment by esafirm** [comment]
Got the same issue, i think it's not related to 0.7.5 version. Same error on the CLI too.
 
could not extract html5player key: //s.ytimg.com/yts/jsbin/player-id_ID-vflA4yxG-/base.js
[Error: Input stream error: Could not extract signature deciphering actions]

**Comment by Amenocy** [comment]
same error in my app.

**Comment by anitgandhi** [comment]
Possibly related: 

I'm getting this error for any YouTube URL: `[Error: Could not extract signature deciphering actions]`. 

Sorry if this isn't actually related. I'll make a new issue if that's the case.

**Comment by thuongvu** [comment]
Like @anitgandhi, I'm getting `Error: Could not extract signature deciphering actions` on any YT video.  It worked fine about an hour ago.

**Comment by fent** [comment]
Weird that some of you are getting the "could not extract key" error, the current regular expression for it should work for the URLs given.

https://regex101.com/r/rM3wN8/1

However, I'm getting the "Could not extract signature deciphering actions" error for these files too.

**Comment by rubenbarreiro** [comment]
worked now for me. thx!

Just out of curiosity, was this because a youtube update or something? because I had the same issue in a previous version(0.5.1)

**Comment by fent** [comment]
Yes, there were slight changes to the base.js file, althought I should have been checking for those things beforehand too.

Always use the latest version for this.

**Comment by esafirm** [comment]
Thank you sir!

On Tue, Nov 10, 2015 at 8:43 PM, Roly Fentanes <notifications@github.com>
wrote:

> Yes, there were slight changes to the base.js file, althought I should
> have been checking for those things beforehand too.
>
> Always use the latest version for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fent/node-ytdl-core/issues/55#issuecomment-155422170>.
>



-- 
Best Regards,
Esa Firman.

*Mobile App Developer*
http://about.me/EsaFirm

**Comment by Priyanshu348** [comment]
How to fix the issue

**Comment by Archeelux** [comment]
> How to fix the issue

update

**Comment by TheRobertoLab** [comment]
I have same issue with version 1.0.7 react-native-ytdl

<img width="240" alt="image" src="https://user-images.githubusercontent.com/57195360/80311166-01225600-87d6-11ea-95ff-0bbb8cdc3a68.png">
