### ISSUE TITLE
Higher quality live stream

### ISSUE THREAD

**Issue by v0v0v** [fent/node-ytdl-core#551]
I want to download 1080p live videos, but I can't find live 1080p video / audio+video itag. The highest video quality I found is 480p.

**Comment by fent** [comment]
what video? are you searching through `info.formats`?

**Comment by v0v0v** [comment]
I searched through `filter: format => { if(format.live) console.log(format) }`

**Comment by fent** [comment]
is this happening on a specific video? are you on latest ytdl-core?

**Comment by v0v0v** [comment]
It's happening on every live stream. Yes, I'm on latest 1.0.6

**Comment by fent** [comment]
I just tried it on a random livestream I found on https://youtube.com/live

```
itag container quality codecs      bitrate  audio bitrate
94   ts        480p    H.264, aac  781.25KB 128KB
93   ts        360p    H.264, aac  488.28KB 128KB
92   ts        240p    H.264, aac  146.48KB 48KB
91   ts        144p    H.264, aac  97.66KB  48KB
299  mp4       1080p60 avc1.64002a 5.52MB
137  mp4       1080p   avc1.640028 4.15MB
298  mp4       720p60  avc1.4d4020 3.32MB
136  mp4       720p    avc1.4d401f 2.22MB
135  mp4       480p    avc1.4d401f 1.12MB
134  mp4       360p    avc1.4d401e 630.86KB
133  mp4       240p    avc1.4d4015 251.95KB
160  mp4       144p    avc1.42c00b 121.09KB
140  mp4               mp4a.40.2            128KB
139  mp4               aac                  48KB
300
301
386  mp4               unknown
387  mp4               unknown
en
```

note the 720p and 1080p streams. also, not all livestreams will have an HD format, you can double check by going to their youtube page.

(the `en` format at the bottom appears to be a separate issue)

**Comment by v0v0v** [comment]
It is downloading only last 3-4s of live stream and the process exits, but I need to download it live, like with 91-94 itags. Livestreams I'm trying to download are 1080p60 on youtube page.

**Comment by fent** [comment]
ok. I can replicate this with 1080p streams. will investigate.
