### ISSUE TITLE
TypeError  @ m3u8stream/dist/m3u8-parser.js

### ISSUE THREAD

**Issue by gklasen** [fent/node-ytdl-core#552]
I get the following image when trying to import ytdl-core.

Versions are:

m3u8stream@0.6.4
 ytdl-core@1.0.6

![image](https://user-images.githubusercontent.com/17546555/72435261-f0595180-379d-11ea-9e65-4008504c7cb0.png)

**Comment by TimeForANinja** [comment]
Not sure about your environment but check whether `require('stream').Writable` is defined

**Comment by fent** [comment]
dupe of https://github.com/fent/node-ytdl-core/issues/531
