### ISSUE TITLE
Begin appears to suddenly work when filter is not set to "audioonly"

### ISSUE THREAD

**Issue by Bottinator22** [fent/node-ytdl-core#554]
I'm using the website Glitch to make my Discord bots. So, I've got a bot here meant to play a very specific sound from a very specific video. So, I've tried begin with filter: audioonly and it has not worked. However, when I removed filter: audioonly, suddenly, it works. Just letting you know in case you didn't.

**Comment by Bottinator22** [comment]
Still inconsistent tho

**Comment by fent** [comment]
`begin` is very inconsitent and unreliable with what formats or videos it works on. using a filter will get you different formats that may or may not work better with `begin`. there's a small note about it on the readme.
