### ISSUE TITLE
Does not work on videos that are both unembeddable and age restricted

### ISSUE THREAD

**Issue by fent** [fent/node-ytdl-core#555]
https://www.youtube.com/watch?v=QTSNPAsnOK4

the current error is:

    Watch this video on YouTube. Playback on other websites has been disabled by the video owner

although attempts to circumvent this, even through the `pbj=1` param, will result in a new error:

    Sign in to confirm your age

videos that are age restricted are currently fetched through the embed endpoint. but in this case, we can't. feel free to suggest or try other methods.

EDIT as of 2020-10-21:
no error when getting info, but there will be no formats
error when trying to download: "This video is unavailable"

**Comment by fent** [comment]
age restricted videos are also not working anymore as of 16 days ago

https://github.com/fent/node-ytdl-core/actions

**Comment by theassyrian** [comment]
have you guys tried the .netrc --netrc flag to login like Gymnophoria said its age restricted and forces you to login

**Comment by fent** [comment]
what is the `.netrc --netrc` flag? ytdl-core does support cookies, which would fix this. but ideally we'd like to bypass having to login

**Comment by fent** [comment]
closed with https://github.com/fent/node-ytdl-core/commit/c0f7e41a75a410fa2bf10e8bce1b79935fe62ab6

all age restricted videos are no longer embeddable

**Comment by 89z** [comment]
You can use this:

~~~
POST /youtubei/v1/player HTTP/1.1
Host: www.youtube.com

{
 "context": {
  "client": {
   "clientName": "TVHTML5_SIMPLY_EMBEDDED_PLAYER",
   "clientVersion": "2.0"
  }
 },
 "videoId": "QTSNPAsnOK4"
}
~~~
