### ISSUE TITLE
AudioEncoding is NaN for AAC audio

### ISSUE THREAD

**Issue by Taconut** [fent/node-ytdl-core#56]
Hi! I just updated to v0.7.6 and I noticed that some AAC audio streams have NaN listed as their audio encoding. They're also missing the "type" and "clen" headers as well. Sorry to ruin your 0 open issue status, but this issue is breaking my program, since I need the MIME type and Content Length.

**Comment by fent** [comment]
How are you trying to access these headers? The stream returned is not an actual http request stream, but a passthrough stream that gets piped the contents from the request.

https://github.com/fent/node-ytdl-core/blob/master/lib/index.js#L93

If you're trying to access more from the request, you can listen to the `response` event for it.

**Comment by fent** [comment]
I'm not seeing where `audioEncoding` isn't listed on formats that don't have audio. Can you provide a video link where this happens?

`type` and `clen` are sometimes not there, I think it's due to getting formats from different locations.

**Comment by Taconut** [comment]
Unfortunately (or fortunately, depending on how you look at it), the exact same test code I ran earlier is no longer showing NaN anywhere. I'm going to go ahead and assume this is on google's end, with revamping youtube music and whatnot.

However, if I make a request to any url (id=pY2YlB61uBU, for example), the highest audio-only format (aac256) returns the following:

| key                   | value |
| -------------------  | ----- |
| itag                   | 141 |
| container          | mp4 |
| audioEncoding | aac |
| audioBitrate      | 256 |
| url                     | [omitted due to length] |

The Rest of the options are either null or missing.

**Comment by fent** [comment]
Not sure where I can get the other properties. Could maybe fill out `type` from the other attributes though.
