### ISSUE TITLE
using ytdl-core on client

### ISSUE THREAD

**Issue by Hesesses** [fent/node-ytdl-core#561]
Hello everyone, I just found this plugin and after few tests I am wondering how I could get links to youtube video files.

For example when using this code i'm getting CORS error. 
```
ytdl.getInfo(videoID, (err, info) => {
  if (err) throw err;
  let format = ytdl.chooseFormat(info.formats, { quality: '134' });
  if (format) {
    console.log('Format found!');
  }
});
```
Could it be possible to add option to specify proxy server url?
For example `ytdl.getInfo(videoID, {VIDEO_URL: 'my-url'}, (err, info) => {`
and my-url acts as proxy to `https://www.youtube.com/watch?v=` 

If I have understood correctly, then i wouldnt get CORS errors and hopefully `ytdl.getInfo` returns all formats and links to the video files.

What do you think?

**Comment by Roki100** [comment]
you can use proxy https://github.com/fent/node-ytdl-core/blob/master/example/proxy.js

**Comment by Hesesses** [comment]
Thanks for answer, i mean that you could replace the VIDEO_URL with your own url 
`const VIDEO_URL = 'https://www.youtube.com/watch?v=';`

**Comment by TimeForANinja** [comment]
@Hesesses if you're still struggling it would be helpful to further explain you're problem (maybe some example code?) - else this should be closed 😉
