### ISSUE TITLE
Weird glitching in the middle of the track when playing with a discord.js bot.

### ISSUE THREAD

**Issue by NorteX-dev** [fent/node-ytdl-core#563]
Hi.
I have a problem with ytdl-core and discord.js, which is:
The discord.js bot starts playing the stream like normal, works great, quality is ok.
The problem is when you listen to the song a little bit longer, the bot just glitches out and starts jumping around the track.
It's really hard to describe it with words, so here is an example:
https://www.youtube.com/watch?v=8rL4JX3oxKI
Where it ends, it doesn't fire the "error' or "end" events, nor prints out an error. (i made a typo in that video at the end, it DOES NOT.)

**Comment by Roki100** [comment]
try setting higher `highWaterMark` maybe?
