### ISSUE TITLE
Get HD and Full HD video 

### ISSUE THREAD

**Issue by krisnguyen95** [fent/node-ytdl-core#565]
I am using this library to get streaming links of videos but I only get one video with sound quality of 360p. I have reviewed some issues but I still don't know how to get higher quality videos. Please help me.

**Comment by fent** [comment]
look at the quality option

https://github.com/fent/node-ytdl-core#ytdlurl-options

https://github.com/fent/node-ytdl-core#handling-separate-streams

**Comment by krisnguyen95** [comment]
If I download video and audio, then merge them into an output file and save it to the source code.Then using that file to stream to the mobile app will take about 10 seconds.If the video quality is higher then it will take more time and if the number of users is large, the videos must be saved before playing, it will be very RAM consuming. It is not a good experience for the user. Please help me. Thanks

**Comment by TimeForANinja** [comment]
The solution is to not route the streams through your server, make it client sided

If that doesn't you might look into ffmpeg's ability to handle streams for input & output which would make saving before merging as well as fully saving before streaming absent

I really feel like that feature is overseen... Might do an example for that if I can find the time

**Comment by berkon** [comment]
@TimeForANinja I have a similar issue like mentioned at the top. I can't download a video in Full-HD WITH sound. Even though the video plays in Full-HD in the browser. Maximum I'm getting is 720p with sound. Any idea what I'm doing wrong?

**Comment by berkon** [comment]
Just found the answer here: https://github.com/fent/node-ytdl-core#handling-separate-streams

**Comment by azickri** [comment]
@berkon, you found a 720P video with audio? Can you tell me how that work?

**Comment by berkon** [comment]
@azickri, this his how I'm doing it in Electron. You have to rename the file to .js. Because Github does not accept .js files
[renderer.txt](https://github.com/fent/node-ytdl-core/files/9940881/renderer.txt)

**Comment by azickri** [comment]
@berkon, this is in client side? Because i see DOM manipulation

**Comment by berkon** [comment]
Corect! This runs as the renderer process in Electron.
