### ISSUE TITLE
Firefox is blocking manifest requests for only some videos

### ISSUE THREAD

**Issue by MicroDroid** [fent/node-ytdl-core#566]
I am the developer of [this](https://addons.mozilla.org/en-US/firefox/addon/youtube-download-button/) extension, and recently [this issue](https://github.com/MicroDroid/youtube-download-button/issues/5) has been reopened. Firefox apparently is blocking manifest requests for **some** videos with the following in the console:

![image](https://user-images.githubusercontent.com/8523135/74132353-0d434200-4bef-11ea-8736-685b220a6d36.png)

- Searching for the error, it looks like Firefox has this stuff implemented long ago already. 
- I have already tried updating to latest library version.
- Execution isn't even reaching the `.then()` of my code, so it's not an error in the handler.

Here's a video that breaks it: https://www.youtube.com/watch?v=hYcxkzm6y_E

**Comment by fent** [comment]
I'm not that familiar with firefox extensions, but for chrome extensions, some domains require extra permissions in the manifest. try adding it in your [manifest here](https://github.com/MicroDroid/youtube-download-button/blob/master/src/manifest.json#L19-L22).

**Comment by MicroDroid** [comment]
@fent Do you have a full list of what I need to add?

**Comment by fent** [comment]
try adding "https://manifest.googlevideo.com" and see if that fixes it. you might also need "https://*.googlevideo.com" if downloading gives an error too.

**Comment by TimeForANinja** [comment]
might try to set the `referer` header to `https://www.youtube.com/`
