### ISSUE TITLE
Return Like / Dislike Count from getInfo()

### ISSUE THREAD

**Issue by PrestonN** [fent/node-ytdl-core#569]
Hello!

It would be helpful if the getInfo() function returned the like / dislike count for a given video.  I would like to display the count in my application when a user tries to view a video.

Thanks in advance!

**Comment by TimeForANinja** [comment]
Check out #266

**Comment by PrestonN** [comment]
I took some time to try to see if this was mentioned before but I guess I didn't see that.  The average rating doesn't help much with my use case though and I'd rather have the specific like / dislike count.  My use case is that I'd like to display them when a user watches a video using [FreeTube](https://github.com/FreeTubeApp/FreeTube).
