### ISSUE TITLE
Can I use my YouTube API token for requests?

### ISSUE THREAD

**Issue by im1x** [fent/node-ytdl-core#570]
Hi. I experimented with node-ytdl-core for several days and it seems I have reached the API limits.
Now when I execute example\get_info.js I get no results and no errors. I did an investigation and found that [**this line**](https://github.com/fent/node-ytdl-core/blob/99284abc4341fd8490a8f83ac1442bf02672a4d8/lib/info.js#L38) receives a response with code 429 (Too Many Requests).

So, I have a question. Is it possible to use my YouTube API token for these requests to be able to make more requests? I mean, is this possible at all or does this part of the API not support tokens?

I use node-ytdl-core v1.0.7.

P.S. I know that I can use proxies, but this solution is not good for me.

**Comment by fent** [comment]
not currently supported, and I don't know if an API response would properly replace some of the requests.

**Comment by Roki100** [comment]
from what ive heard and tested passing account cookies 'bypasses' 429 and allows to do requests even on banned ips but miniget seems to not like cookie headers and ytdl just 'freezes', you can do some experimenting and maybe you will get it working, which will be better solution than using api in my opinion

**Comment by im1x** [comment]
> from what ive heard and tested passing account cookies 'bypasses' 429 and allows to do requests even on banned ips but miniget(module for doing requests which ytdl uses) seems to not like cookie headers and ytdl just 'freezes', you can do some experimenting and maybe you will get it working, which will be better solution than using api in my opinion

Yes you are right. I have already experimented and adding cookies really helps. This solution looks good, but so far I have not found a way to easily get cookies (for the test, I just took cookies from the browser). In order to receive cookies, I must be authorized, and for this, I suppose, I need to use the API. Maybe you know an easy way to get cookies?
