### ISSUE TITLE
Long links in videoInfo.descriptions are not usable and captions are also missing

### ISSUE THREAD

**Issue by Aasim-A** [fent/node-ytdl-core#571]
Hi, I was using ytdl on javascript and didn't care about types, but recently I switched to typescript and found out that the only description provided in the type definitions is:
```videoInfo.description```, but the problem with that is that youtube makes long links abbreviated in it, so I looked in the ```getInfo``` response and found that there is another version of the description which has full links, it is under
```videoInfo.player_response.microformat.playerMicroformatRenderer.description.simpleText```.
Also ```videoInfo.player_response.captions``` are not included in the type definition.

I'm wondering, is there a reason not to include full response types in the type definitions? since it's returning the full data anyways.

Keep up the good work!

**Comment by TimeForANinja** [comment]
The response you get from ytdl is mostly api data directly from YouTube which we don't control, high chance YouTube just changed there endpoint after the definitions were written

**Comment by Aasim-A** [comment]
Ok then, I'll make a PR to update the current type definitions
