### ISSUE TITLE
Event are no more triggered

### ISSUE THREAD

**Issue by Splinteer** [fent/node-ytdl-core#578]
Hello,

Everything was working great since the last update from m3u...
But now no event are triggered. Here is my code:
```
const opts = {
    filter: 'audioonly',
    quality: 'highestaudio',
    requestOptions: {
      agent
    }
  }
const audio = ytdl(req.params.id, opts)

audio.on('info', (info) => {
  console.log('info', info)
})

audio.on('response', (res) => {
  console.log('res', res)
})

audio.on('progress', (num, num2, num3) => {
  console.log('progress', num, num2, num3)
})

audio.on('error', (err) => {
  console.error('error', err)
})
```

**Comment by fent** [comment]
> Everything was working great since the last update from m3u...

which update was that? what version are you on now?

**Comment by Splinteer** [comment]
I have the last one.
But I badly expressed myself. It's not since the last update that the event are not triggered.
Everything were working with the last one. Just now it's not working

**Comment by Splinteer** [comment]
I have the last one.
But I badly expressed myself. It's not since the last update that the event are not triggered.
Everything were working with the last one. Just now it's not working.

Everything is working now. I don't know why, didn't change anything
