### ISSUE TITLE
Error: Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by NNickey** [fent/node-ytdl-core#58]
```events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Could not extract signature deciphering actions
    at C:\Users\Administrator\Desktop\lll\node_modules\ytdl-core\lib\sig.js:48:11
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Desktop\lll\node_modules\ytdl-core\lib\request.js:34:9)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)```

**Comment by koriwi** [comment]
Same for me since today

**Comment by R4wizard** [comment]
This has started happening for me too since today. Any video, always the same error.

**Comment by R4wizard** [comment]
Thanks for the rapid fix!

**Comment by R4wizard** [comment]
This has started happening again today.
-shakes fist at YouTube-

**Comment by R4wizard** [comment]
This appears to have been caused by an added newline character in the youtube output. I've patched this on my fork and added a pull request https://github.com/fent/node-ytdl-core/pull/60

**Comment by fent** [comment]
New version published. Thanks @R4wizard for taking care of this!

**Comment by R4wizard** [comment]
If you have any time available, could you possibly describe what it is we are actually retreiving from these pages? I'd like to have a look and see if there is something I can do to make this process more dynamic.

**Comment by fent** [comment]
Sure. Which pages specifically?

**Comment by R4wizard** [comment]
I think the signature deciphering page would be a good place to start, then we can try to avoid this somewhat regular issue.

**Comment by fent** [comment]
Hope this helps

https://github.com/fent/node-ytdl-core/blob/master/lib/sig.js#L239
