### ISSUE TITLE
{ filter: "videoonly" } doesn't work with getinfo() , getbasicinfo()  and filterFormats()

### ISSUE THREAD

**Issue by iii8iii** [fent/node-ytdl-core#582]
### Before creating an issue, please try the following

- Are you on the latest version of ytdl-core? If you're using a bot or application that depends on ytdl-core, check if it has an old version listed as a dependency.
  - To check, run `npm ls ytdl-core`
`ytdl-core@2.0.0`
  - To install the latest version, run `npm install ytdl-core@latest`
- Search the list of issues for a possible duplicate.
  - If there is a duplicate issue thread, but it's closed, only post in it if it's been active in the past month. Otherwise, creating a new issue thread is fine.
- If your question is about using the library for a specific use case, check out the [examples folder](https://github.com/fent/node-ytdl-core/tree/master/example).

### Otherwise, feel free to open an issue

Include the following if your issue is a bug

- If you're getting a specific error message, include the full stack trace
- If you're getting unexpected behavior without an error message
  - What should happen?
`get info about 'videoonly'`
  - What happens instead?
`get links with audio and video`
- Include any relevant code around ytdl-core. You don't have to upload your entire program, small snippets are fine.
`ytdl.getInfo('5UrwkoxLrws', { filter: "videoonly" }, (err, info) => {
                    if (err) throw err;
                    res( info.formats)
                });`
- If this error happens only on some videos, include a link or links to videos.
`One of the URLs I get:`
[url with video and audio](https://r6---sn-4g5e6nl6.googlevideo.com/videoplayback?expire=1582976244&ei=lPhZXsDyOI3x7gPBwoiwBg&ip=80.240.31.227&id=o-AL893dKAI8I33pinwpNJH2sMzdhXruQwDEykxUAOGqb0&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-4g5e6nl6%2Csn-5hnekn7s&ms=au%2Conr&mv=m&mvi=5&pl=24&initcwndbps=2611250&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=2655.016&lmt=1581322328527252&mt=1582954535&fvip=2&fexp=23842630%2C23882513&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ADKhkGMwRQIgX0xvodSShAVXhdxq-jRSwbbsFnI-p1VLlT9w53lzhewCIQCufEibJ06kJld-EENbtzEd9RSa-7ne2Fl0HmYwVgFhEA%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRQIhAKiMH5ArrzthP-0UPFUto7ucy38wL3aG_-4U2qfbRyojAiBdzdpz5--8Mt6ePKlnwRceXQl_s0c0-taoZtLtcilyPQ%3D%3D) this URL would be temporary, you can run the code yourself get check all URLs you get

**Comment by iii8iii** [comment]
btw, what version node js does ytdl need actually? I use ytdl-core@2.0.0 in GCP GAE standard environment which supports node js 10, but the codes can't run while everything is found in my window with node js 12.

**Comment by fent** [comment]
I'm getting itag 299 when I run `ytdl --filter vidoeonly [VIDEO_ID]` on a random video. itag 299 has video only, no audio.

ytdl-core works with node >= 10

**Comment by iii8iii** [comment]
@fent  what I mean is that when I run codes as follow:
`ytdl.getInfo('5UrwkoxLrws', { filter: "videoonly" }, (err, info) => { 
if (err) throw err; 
console.log (info.formats);
 })`
I find that info.formats is an array, and it contains some fromats which have video and audio when I open its URL in browser

I will try again later, but not now for network problems. Thanks for reply

**Comment by fent** [comment]
oh, `filter` is used when downloading a video, not when getting a video's info. `info.formats` will always have all of the formats. if you'd like to filter them, you can do `ytdl.filterFormats(info.formats, 'videoonly')`

I'll keep this opened since the typings file is misleading

**Comment by iii8iii** [comment]
> ytdl.getBasicInfo('X15Kgksl59Y', (err, info) => {
                    if (err) throw err;
                    let videoFormats = ytdl.filterFormats(info.formats, 'videoonly');
                    console.log(videoFormats);
                });

codes above get itag: 18 which has video and audio
it seems like that there is a bug in funtion hasAudio (`const hasAudio = format => !!format.audioBitrate;`) in util.js
Infomaiton about itage18 below:

> {
    "itag": 18,
    "url": "https://r4---sn-4g5ednsk.googlevideo.com/videoplayback?expire=1583145770&ei=yo5cXqTzD4fpgAeFqJXQAg&ip=80.240.31.227&id=o-ANUS711oEyLhqiEvt6HPrEmG4o3FBdJlOU8wkUxNqBQW&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-4g5ednsk%2Csn-4g5e6nld&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=1128750&vprv=1&mime=video%2Fmp4&gir=yes&clen=264586667&ratebypass=yes&dur=3825.441&lmt=1548120050967717&mt=1583124085&fvip=4&fexp=23842630&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ADKhkGMwRAIgfSJXJjOXLpKkv_8ysqLZbiDct6h2-8TFoBbqVrqmgU0CIA2NBBrhvncmC9zUbMHfvf9AIMExdHgT3wpwKogCDAKi&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRQIgFd3j2VwDPIng8uzqQO5upageOGKgn8npfyhUvz1yGYECIQCcsHxsevclaWfvl5Sy5gB0z-UFakfrJ5hStykt78NWFg%3D%3D",
    "mimeType": "video/mp4; codecs=\"avc1.42001E, mp4a.40.2\"",
    "bitrate": 553393,
    "width": 640,
    "height": 360,
    "lastModified": "1548120050967717",
    "contentLength": "264586667",
    "quality": "medium",
    "qualityLabel": "360p",
    "projectionType": "RECTANGULAR",
    "averageBitrate": 553320,
    "audioQuality": "AUDIO_QUALITY_LOW",
    "approxDurationMs": "3825441",
    "audioSampleRate": "44100",
    "audioChannels": 2
  },

it doesn't contain `audioBitrate`, but it contains auduio

**Comment by fent** [comment]
ah I see. yeah that looks wrong. we should use a more reliable property
to check for audio.
