### ISSUE TITLE
URL validation

### ISSUE THREAD

**Issue by Zerefdev** [fent/node-ytdl-core#583]
Hello, 

Is it normal that both 
`ytdl.validateURL(https://www.youtube.com/watch?v=n33VS5bq03o)`
and 
`ytdl.validateURL(https://www.youtube.com/wartwzwerwer)`
Return true?

same goes for returning the ID ytdl.getURLVideoID(url), it returns whatever (**>11 characters**) after **youtube.com/** if there is no **watch?v=**

I am using the latest Nodejs LTS and Discordjs 11.6.1

**Comment by fent** [comment]
good catch. there are some youtube urls that have the id in the path, such as `youtu.be/ID`, `youtube.com/embed/ID`, and `youtube.com/v/ID`. but it shouldn't be matching `youtube.com/ID`
