### ISSUE TITLE
{ Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 sec onds.

### ISSUE THREAD

**Issue by TripleZer000** [fent/node-ytdl-core#588]
I am using https://gabrieltanner.org/blog/dicord-music-bot and my bot connects but it doesn't seem to have any audio to input to voice. 
LOG BELOW
Ready!
{ Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 sec
onds.
    at VoiceConnection.authenticateFailed (/home/runner/WhorBot/node_modules
/discord.js/src/client/voice/VoiceConnection.js:304:26)
    at connectTimeout.client.setTimeout (/home/runner/WhorBot/node_modules/d
iscord.js/src/client/voice/VoiceConnection.js:325:61)
    at Timeout.setTimeout (/home/runner/WhorBot/node_modules/discord.js/src/
client/BaseClient.js:83:7)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) [Symbol(code)]: 'VOICE_CONNECT
ION_TIMEOUT' }
(node:1437) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send a
n empty message    at RequestHandler.execute (/home/runner/WhorBot/node_modules/discord.js/
src/rest/RequestHandler.js:170:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. T
his error originated either by throwing inside of an async function without
a catch block, or by rejecting a promise which was not handled with .catch()
. (rejection id: 1)
(node:1437) [DEP0018] DeprecationWarning: Unhandled promise rejections are d
eprecated. In the future, promise rejections that are not handled will termi
nate the Node.js process with a non-zero exit code.

**Comment by kyletuite** [comment]
This is not a ytdl-core issue. This is an issue with Discord.js, and it's likely the guide you're following is not up to date with the most recent release of Discord.js (stable branch is now 12.0.2, previously 11.0).; there have been a lot of syntax changes, and a few dependency changes. I would recommend opening an issue [here](https://github.com/discordjs/discord.js), and joining the official Discord.js Discord server, where you can receive general help with the library.
