### ISSUE TITLE
The 'size' property in the 'format' object is missing

### ISSUE THREAD

**Issue by orielz** [fent/node-ytdl-core#59]
I`m listenning to the 'info' event using

```javascript
obj.on('info', function(info, format) { 
        format.size // Is missing
});
```

Until now i got the property 'size' which was in 'format' object, i think that the property is missing after upgrade to the latest version

**Comment by andrewrk** [comment]
See https://github.com/fent/node-ytdl-core/issues/57#issuecomment-157846975

**Comment by orielz** [comment]
Thanks.

**Comment by usamamashkoor** [comment]
@orielz can you please let us know how did you get the file size before downloading it.?

**Comment by fent** [comment]
You can use the [progress event](https://github.com/fent/node-ytdl-core#event-progress) to get the size.
