### ISSUE TITLE
discord.js bot not playing audio

### ISSUE THREAD

**Issue by CostDeathYT** [fent/node-ytdl-core#590]
My code: https://hastebin.com/varigayufo.js
The bot joins the voice channel and leaves triggering the songStream.on("end") function as if the audio was done playing and I'm not sure why this happens. The issue is not the search function as I have tested it with a plain URL and it didn't work either. I have also tested various videos and therefore concluded the issue isn't a specific video either. Any idea what could be happening?

**Comment by fent** [comment]
the call to ytdl-core is a string 🤔 

```js
let songUrl = "YTDL(\"https://www.youtube.com/watch?v=" + video.id + "\", { filter: \'audioonly\' })";
```
