### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hansputera** [fent/node-ytdl-core#592]
Could not extract html5player key: https://www.youtube.com/s/player/9b926fb0/player_ias.vflset/en_US/base.js

How to fix it?

**Comment by mahhov** [comment]
I've also encountered this error and just ignored it. It seems to be not-constant, i.e. it will go away if you retry.

**Comment by mh4ck** [comment]
Duplicate of this: https://github.com/fent/node-ytdl-core/issues/591

**Comment by fent** [comment]
closed by new version
