### ISSUE TITLE
Stream becomes glitchy after playing for a short amount of time

### ISSUE THREAD

**Issue by Helperbot3** [fent/node-ytdl-core#596]
Here is a snippet of my code (with @discord.js/opus)
`
                if(msg.channel.type !== 'text'){break}
                const voiceChannel = msg.member.voice.channel
                if(!voiceChannel){return msg.channel.send("Please join a voice channel first")}
                if(!(args[1].includes("https://www.youtube.com/watch?v="))){return msg.channel.send("Please give a full YouTube link to play")}
                voiceChannel.join().then(connection => {
                    const stream = ytdl(args[1], {filter: 'audioonly'})
                    const dispatcher = connection.play(stream);
                    dispatcher.setBitrate(32) // so it doesn't take a bunch of network. (so i can enjoy my friggin netflix)
                    dispatcher.on('end', () => {
                        voiceChannel.leave()
                        return
                    })
                    dispatcher.on('error', () => {
                        voiceChannel.leave()
                        return
                    })
                    dispatcher.on('start', () => {
                        msg.channel.send("Started playing music")
                    })
                    bot.on("message", msg => {
                        if(msg.content == ".pause"){
                            dispatcher.pause()
                            msg.channel.send("Paused music")
                        }
                        if(msg.content == ".resume"){
                            dispatcher.resume()
                            msg.channel.send("Resumed music")
                        }
                        if(msg.content == ".stop"){
                            voiceChannel.leave()
                            var musicQueue = Array()
                            return msg.channel.send("Stopped music and cleared queue")
                        }
                    })
                })
            `

The code works perfectly for about 30 seconds. However, after a short time frame, the stream will repeat a part of the stream twice multiple times and then skip to the end prematurely (https://www.youtube.com/watch?v=7ljwjlHSS00 at 1:21). I honestly have no clue why the stream glitches like this after a short time. Sometimes the stream stops completely (https://www.youtube.com/watch?v=iQKQ0-mhEJE at 1:10)

Thanks for the help and thanks for this awesome node.js module!

**Comment by Helperbot3** [comment]
Editing issue: the code segment is incorrect and did not come across correctly

**Comment by Gymnophoria** [comment]
Use three tildes and the language to get a multiline code block:
\`\`\`js
console.log("Hello world!");
\`\`\`
becomes
```js
console.log("Hello world!");
```

That song (C2C - Delta) worked fine for me using ytdl-core v2.0.1 and d.js v12.0.2 on Debian Linux, but not on Windows - so I can reproduce the issue using my own code. However, this appears to be a discord.js issue, as I can use my bot to download an mp3 of the song, using ytdl-core on Windows, without issue (the output mp3 has the entire song). I've previously had this issue on all operating systems, but now it appears to be limited to Windows (well, I haven't tried it on macOS). You'll probably want to look at discord.js issue 3362.

**Comment by lumap** [comment]
I got the same error, but sometimes the music stops playing completely after1 to 3 minutes.

**Comment by Helperbot3** [comment]
discord.js issue per @Gymnophoria https://github.com/discordjs/discord.js/issues/3362

**Comment by Helperbot3** [comment]
Closed: This is not a problem with ytdl. This is a problem with the interaction between discord.js and node 10+. 

Again, for a possible fix, see https://github.com/discordjs/discord.js/issues/3362
