### ISSUE TITLE
Unlisted video  not working

### ISSUE THREAD

**Issue by mrqaidi** [fent/node-ytdl-core#601]
Hi

i was testing  unlisted video  i got  formats and data but   video url giving me HTTP ERROR 403

**Comment by mh4ck** [comment]
Hey maybe it will help you: I got the same problem  while using a proxy to request the info and downloading the video without proxy. Problem was that the proxy already got blacklisted and seems to generate wrong download links.

**Comment by mrqaidi** [comment]
@mh4ck  i dont use any proxy ! do i need one for unlisted video

**Comment by fent** [comment]
can you give the video link?

**Comment by mrqaidi** [comment]
> can you give the video link?

sent via email

**Comment by fent** [comment]
I'm able to download on my side

**Comment by mrqaidi** [comment]
> I'm able to download on my side

how can you share your codes bcoz i  get 403 error when trying to download

**Comment by fent** [comment]
I'm using [ytdl](https://github.com/fent/node-ytdl) to test

**Comment by mrqaidi** [comment]
@fent   i dont know why i am getting error 403  but this what i am using 
`let info = await ytdl.getInfo(id);			
`

**Comment by fent** [comment]
are you only calling `.getInfo()` and getting the error? usually, if we get that error, it's from trying to download the video

**Comment by mrqaidi** [comment]
yes i use getinfo() only and download url from formats

**Comment by richardabear** [comment]
Still encountering this issue today
