### ISSUE TITLE
Error: ffmpeg exited with code 69: Conversion failed!

### ISSUE THREAD

**Issue by medoror** [fent/node-ytdl-core#608]
Fluent-ffmpeg is no longer working with ytdl-core.  My code was working before but now impossible to save as mp3 or even stream audio using ffmpeg.

My code using one flow for downloading and ffmpeg processing is [here](https://github.com/medoror/audio_clipper_slackbot/blob/722c499bf17f9a70574c1541b5bd0f17c749341f/src/youtubeVideo.ts#L34)

My code using the [accepted example](https://github.com/fent/node-ytdl-core/blob/master/example/convert_to_mp3.js) is [here](https://github.com/medoror/audio_clipper_slackbot/blob/5f146294db224ab33cecc683596287b5f4fbdfb9/src/youtubeVideo.ts#L34)

both have the same issue below

```
events.js:173
      throw er; // Unhandled 'error' event
      ^
Error: ffmpeg exited with code 69: frame=    0 fps=0.0 q=0.0 Lsize=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
Conversion failed!
    at ChildProcess.<anonymous> (/Users/medoror/workspace/slackbot/audio_clipper/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:188:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
Emitted 'error' event at:
    at emitEnd (/Users/medoror/workspace/slackbot/audio_clipper/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at endCB (/Users/medoror/workspace/slackbot/audio_clipper/node_modules/fluent-ffmpeg/lib/processor.js:544:13)
    at handleExit (/Users/medoror/workspace/slackbot/audio_clipper/node_modules/fluent-ffmpeg/lib/processor.js:170:11)
    at ChildProcess.<anonymous> (/Users/medoror/workspace/slackbot/audio_clipper/node_modules/fluent-ffmpeg/lib/processor.js:182:11)
    at ChildProcess.emit (events.js:188:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

**Comment by fent** [comment]
I just ran the example without any issues, the mp3 plays fine too. maybe something in your environment changed? what is the error's message?

**Comment by medoror** [comment]
There error message is in the description.  What is weird is that even though ffmpeg throws an error to crash the program.  The program still manages to create an mp3 file.  This mp3 file has size but it doesn't seem to playable. Could this be related to my dependencies? Do my [package.json](https://github.com/medoror/audio_clipper_slackbot/blob/master/package.json) and [package-lock.json](https://github.com/medoror/audio_clipper_slackbot/blob/master/package-lock.json) files more or less match what you have in your example run?

**Comment by fent** [comment]
try installing ffmpeg directly instead of @ffmpeg-installer/ffmpeg. it might be that the version of ffmpeg that the node package has is too old.

**Comment by medoror** [comment]
so i uninstalled `@ffmpeg-installer/ffmpeg` and I installed `ffmpeg` version 4.2.2 on my local machine and it still didn't work (Same exact error).  The version information is below.  I'm stumped at why this is suddenly not working for me.  Any other thoughts?  My next guess is to confirm that ytdl is actually downloading video...

```
±  |master {2} U:3 ✗| → ffmpeg -version
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
built with Apple clang version 11.0.0 (clang-1100.0.33.17)
configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```

**Comment by medoror** [comment]
Do you have any comments on the way I am trying to extract audio from a [youtube video](https://github.com/medoror/audio_clipper_slackbot/blob/master/src/youtubeVideo.ts#L34-L63)? Is the filter object correct?

**Comment by fent** [comment]
there is no `format.resolution` anymore. try `format.qualityLabel`. maybe that's it, but I would think ffmpeg would be able to convert videos to mp3 too.

> My next guess is to confirm that ytdl is actually downloading video...

I'd try this, and try converting with ffmpeg through the command line and see if you get the same error.

**Comment by medoror** [comment]
Ahhh I see that `format.resolution` being replaced by `qualityLabel` [here](https://github.com/fent/node-ytdl-core/commit/eb1491f5f70302a2b11005041aa9cd0f4a53ef08).  I made that swap.  The video downloaded and was processed through ffmpeg but then there was no sound.  Seemed like the formats that were being chosen had `audioBitrate` values set to null.  So I ended up changing my filter function to the following which DID WORK

```
                        ytdl(this.link, {
                            filter: function (format) {
                                if (format.container === 'webm' && format.audioBitrate) {
                                    return true;
                                }
                            }
                        })
```
Feel free to close this issue. Thanks for your help and quick responses.  If you have an clarifying explanations about the logic for `chooseFormat` and what configurations are ideal for audio only downloads please share!

**Comment by fent** [comment]
np

the function looks looks. I would change it to a lambda for style purposes

```js
filter: format => format.container === 'webm' && format.audioBitrate
```
