### ISSUE TITLE
ytdl-core works in Firefox but not in Chrome

### ISSUE THREAD

**Issue by zandercodes** [fent/node-ytdl-core#613]
Version: 2.1.0

### What should happen?
The ytdl-core should display information about a video in the browser. This works fine under Firefox with Vue.js and Webpack.
Only Chrome gets a JSON Parsing Error.

### What happens instead?
Uncaught Error: Error parsing config: Unexpected token ; in JSON at position 87378

When I do this in JSON.stringify, I get an empty object.

What's the mistake?

Best regards
ZanderCodes

**Comment by fent** [comment]
that error was fixed recently. make sure you're on latest.

**Comment by zandercodes** [comment]
Is with current version 2.1.1 solved
