### ISSUE TITLE
YTDL with option audioonly do not render proper mp3 files

### ISSUE THREAD

**Issue by AlexisRieucau** [fent/node-ytdl-core#619]
### Before creating an issue, please try the following

- Are you on the latest version of ytdl-core? If you're using a bot or application that depends on ytdl-core, check if it has an old version listed as a dependency.
  - To check, run `npm ls ytdl-core`
  - To install the latest version, run `npm install ytdl-core@latest`
- Search the list of issues for a possible duplicate.
  - If there is a duplicate issue thread, but it's closed, only post in it if it's been active in the past month. Otherwise, creating a new issue thread is fine.
- If your question is about using the library for a specific use case, check out the [examples folder](https://github.com/fent/node-ytdl-core/tree/master/example).

### Otherwise, feel free to open an issue

Include the following if your issue is a bug

- If you're getting a specific error message, include the full stack trace
- If you're getting unexpected behavior without an error message
  - What should happen?
  - What happens instead?
- Include any relevant code around ytdl-core. You don't have to upload your entire program, small snippets are fine.
- If this error happens only on some videos, include a link or links to videos.

**Comment by AlexisRieucau** [comment]
Hi, I'm trying to extract a mp3 file from Youtube videos using ytdl() :`let audioStream = ytdl(videoUrl, { filter: 'audioonly' });`
It seems to behave correctly without any error until I try to listen to the mp3 generated and nothing is playing in my music reader.
If i put `audioandvideo` in the filters and save the file as mp4 it works correctly so I guess the problem might come from the `audioonly`.

**Comment by AlexisRieucau** [comment]
Forgot to mention that I'm using `fs.createWriteStream()` to create the mp3 file.
`audioStream.pipe(fs.createWriteStream(`${pathToVideo}.mp3`));`

**Comment by TimeForANinja** [comment]
try `.mkv`
not all `audioonly` is mp3

**Comment by AlexisRieucau** [comment]
Oh ok I don't really know much about these kind of things, seems like I'm gonna have to make some research to get what `opus` and `mp4a` implies. Anyway using `.mkv` solved my problem thx !
