### ISSUE TITLE
Error: could not extract signature deciphering actions

### ISSUE THREAD

**Issue by alekaizer** [fent/node-ytdl-core#62]
Hi guys,
I'm getting this error, I ran the examples as well, got the same error!

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Could not extract signature deciphering actions
    at /var/www/rep/rep/node_modules/youtube-mp3-downloader/node_modules/ytdl-core/lib/sig.js:48:11
    at IncomingMessage.<anonymous> (/var/www/rep/rep/node_modules/youtube-mp3-downloader/node_modules/ytdl-core/lib/request.js:34:9)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

What is the reason and how can I solve it? Thanks in advance

**Comment by fent** [comment]
Make sure you are using the latest version of ytdl-core.

**Comment by alekaizer** [comment]
Great!! :+1:  Nice, Merci !
