### ISSUE TITLE
D.js v12, randomly crashing from attempting to play a song?

### ISSUE THREAD

**Issue by sylqvq** [fent/node-ytdl-core#622]
I'm running a Discord.js bot (i'm sure you see that often here), which recently I wanted to add music functionality, so I did, and for the most part all works well, but every once in a while if a queue goes on long enough, the entire process crashes because of "The 'url' argument must be of type string. Recieved undefined." I've been trying to troubleshoot this for a while now, but I can't really figure out how to fix it, I've set the bot up to log the video ID playing next, and exactly what it logs is what is given to ytdl-core

![image](https://user-images.githubusercontent.com/57052622/81432682-fbf3ce00-9128-11ea-8648-43ea2c0c37d2.png)

Again, the bot works completely fine for the most part, it's just every so often it crashes the whole process, I'm assuming because it's not passing the URL properly? I've also tried putting the stream in a try block, but it doesn't catch errors at all, and instead just crashes the entire process still.

![image](https://user-images.githubusercontent.com/57052622/81432995-7b819d00-9129-11ea-83ed-e2cc26174abe.png)
^ I've even made sure that what's given to ytdl-core is a string, and it passes every time

![image](https://user-images.githubusercontent.com/57052622/81433023-876d5f00-9129-11ea-9451-d6498475082c.png)
^ _More relevant code_

Any help is appreciated!

**Comment by fent** [comment]
that error was just fixed yesterday. make sure you're on latest.

**Comment by sylqvq** [comment]
I updated it, and tested it right before posting this.

**Comment by fent** [comment]
do you mind logging the `format` with the following

```js
ytdlDispatch = ytdl(...)
ytdlDispatch.on('info', (info, format) => {
    if (!format.url) {
        console.log(info.video_id, format);
    }
});
```

it would help me debug since I'm having difficulty reproducing this

**Comment by sylqvq** [comment]
Sure thing, do I send a response if another error happens?

**Comment by sylqvq** [comment]
Assuming that's supposed to log when something goes wrong, when I attempted it again the same error happened, without any details from that event
![image](https://user-images.githubusercontent.com/57052622/81450466-1db07d80-9148-11ea-8a87-6f24d90051de.png)

**Comment by sylqvq** [comment]
This is what I get w/ that. (sorry for only screenshots, this is through VNC)

![image](https://user-images.githubusercontent.com/57052622/81451085-51d86e00-9149-11ea-9d14-90cac4d847ff.png)

**Comment by fent** [comment]
if you run `npm ls ytdl-core` what does it show?

**Comment by sylqvq** [comment]
uhuh... must've been my package manager? i tried updating it earlier today just before writing this, odd, it showed 2.1.1

**Comment by sylqvq** [comment]
updated to 2.1.2, and everything was resolved, sorry for wasting your time lol

**Comment by fent** [comment]
no problem. I wonder what happened when updating earlier
