### ISSUE TITLE
Miniget throws uncatchable Error if filtered format does not have a URL

### ISSUE THREAD

**Issue by rezemble** [fent/node-ytdl-core#624]
In some cases, format responses may not contain URL fields.

This may happen for example when too many requests are made.

This will result in Miniget throwing an uncatchable error.

I've created a PR #623 to mitigate this issue, automatic tests don't pass anymore because filtering is now stricter.

**Comment by Fractum34254** [comment]
I have the exact same problem
Do you have a partially working solution (e.g. just requesting no format?).
Atm I request `{ quality: 'highestaudio', filter: 'audioonly' }`.
The only way for me to catch the error is via 
`process.on('uncaughtException', (err, origin) => { //handle });`

**Comment by fent** [comment]
this was fixed in latest release. the PR is more preventative, in case something like it happens again, the error would be catchable.
