### ISSUE TITLE
Videos with chapters?

### ISSUE THREAD

**Issue by Protected** [fent/node-ytdl-core#625]
Youtube videos can now have chapters. For example:

https://www.youtube.com/watch?v=BvyQ70PVI4s

youtube-dl -j gives me information on said chapters:

```js
{
    ...
    "chapters": [
        {
            "start_time": 0,
            "end_time": 46,
            "title": "Are you a Creator-focused YouTuber?"
        },
        {
            "start_time": 46,
            "end_time": 83,
            "title": "Recent Subs to 100% Launch"
        },
        {
            "start_time": 83,
            "end_time": 105,
            "title": "Sneak Peeks Coming Soon!"
        },
        {
            "start_time": 105,
            "end_time": 139,
            "title": "Video Chapters Experiment (iOs coming soon!)"
        },
        {
            "start_time": 139,
            "end_time": 203,
            "title": "Channel Memberships Highlighted Comments Experiment"
        },
        {
            "start_time": 203,
            "end_time": 223,
            "title": "Monetization of COVID-19 Content Launch"
        },
        {
            "start_time": 223,
            "end_time": 241,
            "title": "Giving Creator Expansion"
        },
        {
            "start_time": 241,
            "end_time": 322,
            "title": "Music Policy Directory Deprecation"
        },
        {
            "start_time": 322,
            "end_time": 397,
            "title": "Trivia Winner"
        },
        {
            "start_time": 397,
            "end_time": 471,
            "title": "Trivia"
        }
    ]
    ...
}
```

But as of now ytdl doesn't appear to do so. May I request this as an improvement for getInfo?

**Comment by Protected** [comment]
Oh, I should have watched this specific video (I retrieved it just now as an example). Apparently they're just parsing the video description. I can probably do that myself, although it would still be useful to have something guaranteed to mirror youtube's own behavior.

**Comment by ImUrX** [comment]
i saw youtube-dl and they fetch a json too now, is there any info on this?
youtube even has thumbnails for the chapters!
![thumbnails](https://i-want-to.2dgirls.date/2DhMZv.png)

**Comment by zardoy** [comment]
@fent Please can you reopen this issue as a feature request? It would be REALLY good to have `videoDetails.chapters` here

**Comment by fent** [comment]
sure, but this information is in the description like @Protected posted. so ytdl-core would simply parse the description and then add a `chapters` array to `videoDetails` with a structure similar to youtube-dl's

**Comment by Protected** [comment]
To be clear, since youtube themselves are displaying the chapters on the video's timeline, there must be an "official" set of rules for how chapters are detected and extracted from the description... Currently on my project I'm simply embedding youtube-dl to do this for me and trust that they're keeping up to date.

**Comment by zardoy** [comment]
@Protected Yeah, I'm using **youtube-dl** too, but I want to replace it in favor of this lib, because youtube-dl requires python to be installed on the end user machine. That's why I think it would be good to implement all youtube-dl features here e,g, auto-merge for high quality formats.
