### ISSUE TITLE
Can you add playing youtube videos as a stream in a vc?

### ISSUE THREAD

**Issue by babycreeper189** [fent/node-ytdl-core#626]
This would be very cool.

**Comment by fent** [comment]
vc?

**Comment by IF64** [comment]
that means voice channel and yes that would be extremely cool. I'm sure people are looking into that right now

**Comment by TimeForANinja** [comment]
as far as i know discord does not allow bot's to stream video via their api
besides it not being possible - it's a feature discord would have to implement and not ytdl-core

**Comment by babycreeper189** [comment]
alright, so we just need to wait for discord to add that

**Comment by TimeForANinja** [comment]
and after that you're discord api wrapper needs to implement it - ytdl-core is already capable of this
