### ISSUE TITLE
Error: rtmp protocol not supported

### ISSUE THREAD

**Issue by alekaizer** [fent/node-ytdl-core#63]
Getting this error on launch, I run

```
npm update ytdl-core
```

and relaunch again same error!

```
events.js:141
      throw er; // Unhandled 'error' event
       ^

Error: rtmp protocol not supported
     at Object.exports.chooseFormat (/var/www/xxxxxx/node_modules/ytdl-core/lib/util.js:150:12)
     at downloadFromInfoCallback (/var/www/xxxxxx/node_modules/ytdl-core/lib/index.js:42:21)
     at Immediate._onImmediate (/var/www/xxxxxx/node_modules/ytdl-core/lib/index.js:110:5)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by fent** [comment]
Yep. It's not currently supported. Back then the only rtmp module was one that used rtmpdump, which I didn't wanna use because I wanted to keep the module js only.

But now there's more so I may try to support this.

Can you post the video link this happened on?

**Comment by alekaizer** [comment]
sorry for the wait, been busy, the video link is 

https://www.youtube.com/watch?v=lTurfn7vvCk

I tried to play it with Chromium browser Version 47.0.2526.73 Ubuntu 14.04 (64-bit) on Ubuntu 14.04 didn't work but works on Firefox 43.0 Mozilla Firefox for Ubuntu canonical-1.0

Hope we will have the support soon

**Comment by fent** [comment]
Is there another video that uses the rtmp protocol? The video above no longer does so and downloads fine.
