### ISSUE TITLE
Error: Error parsing info: JSON.parse(...).reduce is not a function

### ISSUE THREAD

**Issue by javierlm** [fent/node-ytdl-core#632]
Hi!

I'm trying to use this module for developing a web extension. The problem appears when I use Webpack, the error code that appears on the browser is:

`Error: Error parsing info: JSON.parse(...).reduce is not a function`

If I use the module directly from Node, there's no error. The code that I use is so simple:

```javascript
    ytdl.getInfo(ids_array[i], (err, info) => {
      if (err) throw err;
      console.log(info);
    });
```

And the error is in this line:

```javascript
`info = JSON.parse(body).reduce((part, curr) => Object.assign(curr, part), {});
```

Have someone used this module with Webpack?

**Comment by fent** [comment]
since it's an extension, can you open up dev tools for the `background.html` and inspect the requests it makes? that request is supposed to return an array, that's why `.reduce` is used

is youtube in your `permissions` in `manifest.json`?

**Comment by javierlm** [comment]
> 
> 
> since it's an extension, can you open up dev tools for the `background.html` and inspect the requests it makes? that request is supposed to return an array, that's why `.reduce` is used
> 
> is youtube in your `permissions` in `manifest.json`?

I'm allowing all URLs on my manifest.json, for testing purposes.

I inspected the requests, and for my surprise the response is always a JSON like this:

`reload: now`

If I execute the code directly from Node, the response is correct, with a JSON that has a lot of fields.

**Comment by fent** [comment]
do its headers match the ones used [here](https://github.com/fent/node-ytdl-core/blob/master/lib/info.js#L33-L36)

if they don't match, you'll need to add them yourself with the `chrome.webRequest` API. I have an extension that uses ytdl-core, although an older version, and I had to do some tinkering to get my browser to change the `User-Agent` header

https://github.com/fent/chrome-veefeed/blob/447a9b395ce5d1e440fcb565485334d8da973e97/background/sources/videos/youtube.js#L8-L23

that should be updated for the new ytdl-core version, but the idea's the same.

**Comment by javierlm** [comment]
> 
> 
> do its headers match the ones used [here](https://github.com/fent/node-ytdl-core/blob/master/lib/info.js#L33-L36)
> 
> if they don't match, you'll need to add them yourself with the `chrome.webRequest` API. I have an extension that uses ytdl-core, although an older version, and I had to do some tinkering to get my browser to change the `User-Agent` header
> 
> https://github.com/fent/chrome-veefeed/blob/447a9b395ce5d1e440fcb565485334d8da973e97/background/sources/videos/youtube.js#L8-L23
> 
> that should be updated for the new ytdl-core version, but the idea's the same.

Yes, headers are correctly setted. I want to obtain specific video info (song, artist, and album), but I can't find the info like the CLI app. I suppose I need to obtain this data manually from the gigantic JSON that the URL gives me?

**Comment by MicroDroid** [comment]
I'm having this issue too. Indeed headers are present on the request and all requests apparently send back `{"reload": "now"}`

**Comment by javierlm** [comment]
Ok. I think I've found something about this issue. The problematic header is the "Cookie". If I use the following code in the webextension, the getInfo function works, and the request returns a complete JSON:
```javascript
browser.webRequest.onBeforeSendHeaders.addListener((details) => {
  let header = details.requestHeaders.find(h => h.name === 'Cookie');
  if (header) { header.value = ''; }
  return { requestHeaders: details.requestHeaders };
}, {
  urls: [
    'https://www.youtube.com/watch?v=*',
    'https://www.youtube.com/get_video_info*'
  ],
  types: ['xmlhttprequest'],
}, ['blocking', 'requestHeaders']);
```

It's similar to the one who @fent shared, the only change was the specific header that is causing problems. Probably this can be the solution to your extension @MicroDroid .

Without the given code:

![imagen](https://user-images.githubusercontent.com/34691743/83791365-9811e600-a691-11ea-96b9-8a24f34cde02.png)

With the fix:

![imagen](https://user-images.githubusercontent.com/34691743/83791600-e0c99f00-a691-11ea-8bd7-aa911096ccbc.png)

I don't know why it downloads a **base.js** script too, of more than 1MB.

@fent , is the media info(musical information in this case), in the information given by getInfo? The CLI gives this information too, but I'm a bit confused with the returned JSON.

**Comment by fent** [comment]
cool! I'm going to look into adding this to the library so that it works for extensions. what did you use to build it? last time I used rollup. wondering if it's best to put it in the library or in the build tool



> I don't know why it downloads a **base.js** script too, of more than 1MB.

that's normal. that script is used to decipher url signatures, which are needed to download videos.

**Comment by javierlm** [comment]
> 
> 
> cool! I'm going to look into adding this to the library so that it works for extensions. what did you use to build it? last time I used rollup. wondering if it's best to put it in the library or in the build tool

I've used webpack.

> > I don't know why it downloads a **base.js** script too, of more than 1MB.

> that's normal. that script is used to decipher url signatures, which are needed to download videos.

Ok.

But how about the media information for album, song and artists in music videos? How I can obtain that data like the CLI version of this library does?

**Comment by fent** [comment]
you can get those from `info`, those are located in `info.videoDetails.media`. the json returned from the endpoint is not what `getInfo` returns, the json gets processed and transformed by `getInfo`

**Comment by javierlm** [comment]
> 
> 
> you can get those from `info`, those are located in `info.videoDetails.media`. the json returned from the endpoint is not what `getInfo` returns, the json gets processed and transformed by `getInfo`

It's an empty object. Media has no data :/

**Comment by javierlm** [comment]
I update the used code, that works on Chrome and Firefox. The other code was only working on Firefox, due to some differences with Chrome:

```javascript
chrome.webRequest.onBeforeSendHeaders.addListener((details) => {
    let header = details.requestHeaders.find(h => h.name === 'Cookie');
    if (header) { header.value = ''; }
    return { requestHeaders: details.requestHeaders };
  }, {
    urls: [
      'https://www.youtube.com/watch?v=*',
      'https://www.youtube.com/get_video_info*'
    ],
    types: ['xmlhttprequest'],
  }, ['blocking', 'requestHeaders', 'extraHeaders']);
```

Chrome needs the extraHeaders too, for being able to modify the cookie header. The background script must be persistent too.

@fent , I will test again the library, because I think there's a regression with the media information. I will keep you updated.

**Comment by gdoron** [comment]
I get the same error, not from extensions but regular nodejs app.
Looking at it now to see what and why...

**Comment by gdoron** [comment]
My resolution was, not to override the headers when using a proxy, because it removes the headers mentioned above.

**Comment by MicroDroid** [comment]
My extension is dying :eyes:

**Comment by fent** [comment]
> My extension is dying 👀

does the fix above work for you?

**Comment by MicroDroid** [comment]
@fent Possibly, I haven't tried. Will the workaround be integrated within node-ytdl-core or not?

**Comment by fent** [comment]
it will. but I want to test it myself on an extension first.

I was also considering including only in a browser build file, but it looks like we all use different build tools. the OP of this issue uses webpack, I used rollup for my extension.

**Comment by MicroDroid** [comment]
Interesting. If you want it tested on an extension I could do that with mine and report back.
