### ISSUE TITLE
discord bot joins channel, light green but has no audio/sound

### ISSUE THREAD

**Issue by FeX5858** [fent/node-ytdl-core#640]
My problem:
After 2 weeks of working fine my bot only joins the channel, light up green but did not play any audio/sound or even disconnect if the song should have ended. So I tried mp3 files. They work. So issue is `ffmpeg`, `@discord/opus` or `ytdl`. I updated all of them, installed ffmpeg in systempath. Reinstalled all of them. Installed them to a new clean workspace. Nothing helped. Same issue, no errors. So i figured out that when i run the script and catch the ytdl path the bot has the following problem: `buffer: BufferList { length: 0 },`.
That means there is no audio given from ytdl-core. How could I fix it?
To add: The dispatcher finish event does not work as a result of this too.
```js
function testing(voicecc, message) {

                    const streamstream = ytdl("https://www.youtube.com/watch?v=iU9bc6LmX8k", { filter: 'audioonly'})

                var dispatcher = voicecc.playStream(streamstream);

                if(dispatcher) {
                    console.log("dispatcher exist")
                }

                dispatcher.on("finish", () => {
                    voicecc.disconnect();
                    console.log("disconected")
                });

                dispatcher.on("speaking", () => {
                    console.log("i try to speak")
                });

                dispatcher.on('error', error => {console.log(error)});

                console.log(streamstream)

                }

                const voicecc = await message.member.voiceChannel.join()

                if(voicecc) {
                    console.log("joined a voicechannel")
                }

                testing(voicecc, message)
```
package.json
```json
"dependencies": {
    "@discordjs/opus": "^0.3.2",
    "colors": "^1.4.0",
    "discord.js": "^11.6.4",
    "file-system": "^2.2.2",
    "ms": "^2.1.2",
    "simple-youtube-api": "^5.2.1",
    "yt-search": "^1.1.2",
    "ytdl-core": "^2.1.5"
```

**Comment by Roki100** [comment]
can you try doing
```npm i ytdl -g
ytdl https://www.youtube.com/watch?v=iU9bc6LmX8k --print-url
```
will it output direct url or error?

**Comment by FeX5858** [comment]
@Roki100 it fires:
`ytdl : Die Benennung "ytdl" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms 
erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den 
Vorgang.
In Zeile:1 Zeichen:1
+ ytdl https://www.youtube.com/watch?v=iU9bc6LmX8k --print-url
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (ytdl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 `

**Comment by Roki100** [comment]
@FeX5858 did you install it with
`npm i ytdl -g` tho?

**Comment by FeX5858** [comment]
@Roki100 No. I will try it out

**Comment by FeX5858** [comment]
@Roki100 Ok. I did it and now your code fires : Status code: 429
Mine dispatcher code do the same as before.

**Comment by FeX5858** [comment]
@Roki100 Ok. I tried it out and got the `Status Code: 429` Error. That means too many requests. But how could i fix this issues which only appears with `ytdl` / `ytdl-core`

**Comment by Roki100** [comment]
> @Roki100 Ok. I tried it out and got the `Status Code: 429` Error. That means too many requests. But how could i fix this issues which only appears with `ytdl` / `ytdl-core`

429 cant be fixed, use proxy or just do not make any request for few days

**Comment by JMTK** [comment]
I'm also getting this but only on `ytdl-core-discord` which makes me think it's related to the ffmpeg settings or the Opus demux. I also updated the internal version of `ytdl-core-discord` to `3.0.0` and it's still happening. I would say this issue should be moved there.

**Comment by FeX5858** [comment]
@JMTK Its a simple problem. If u get this error u are "softbanned" from youtube. So ur IP. You could enter youtube with every device except of ytdl-core or sth like this. You just have to wait. After 4 days know, my bit is working like before. Like nothing happened.
