### ISSUE TITLE
ytdl-core + ytpl doesn't finish the download of most songs from the playlist.

### ISSUE THREAD

**Issue by IcyTower1337** [fent/node-ytdl-core#642]
Couldn't find a similar issue, so I'm making a new one. I've made this small program:

```js
const ytdl = require('ytdl-core');
const ytpl = require('ytpl');
const fs = require('fs');
const prompt = require('prompt-sync')();
var playlistURL, playlistID;
var validPlaylistID = false;
do
{
    var playlistURL = prompt('Youtube Playlist URL: ');
    ytpl.getPlaylistID(playlistURL, function(err, result) {
        if(!err) validPlaylistID = true;
        playlistID = result;
    });

    if(!validPlaylistID) console.log("Invalid Playlist URL.");
}
while(!validPlaylistID);
console.log(playlistID);


    ytpl(playlistID, function(err,playlist){
        console.log('Playlist Name: '+ playlist.title);
        for(var i=0;i<playlist.items.length;i++){
            var element = playlist.items[i];
            var name = element.title;
            var video = ytdl(element.url_simple,{quality: 'highestaudio', filter: 'audioonly', highWaterMark: 1024 * 1024 * 10})
            video.pipe(fs.createWriteStream('./downloads/'+name+'.mp3'));
            video.on('response', function(res) {
                var totalSize = res.headers['content-length'];
                var dataRead = 0;
                res.on('data', function(data) {
                  dataRead += data.length;
                  var percent = dataRead / totalSize;
                  process.stdout.cursorTo(0);
                  process.stdout.clearLine(1);
                  process.stdout.write(element.title +' @ ');
                  process.stdout.write((percent * 100).toFixed(2) + '% ');
                });
                res.on('end', function() {
                  process.stdout.write('\n');
                });
              });
        };
    });

/* 
    ytdl-core + ytpl Youtube Playlist Downloader
    made by IcyTower1337
*/
```

Now I've gotten the program to download every video on the playlist, but not every file plays...
the files have size, but not all files play, for example:
https://www.youtube.com/playlist?list=PL2xx-aV24fyC7Oht2GxkgTc9aAUXeNN3z
that playlist downloads every file "correctly" as you can see here:
![image](https://user-images.githubusercontent.com/25158289/83461573-fa37d480-a460-11ea-8546-a424324fa3c1.png)
but only "Brennan Heart & Jonathan Mendelsohn - Be Here Now (Official Video).mp3" actually plays audio, the other ones don't even open, they just finish instantly.
I'm not sure why exactly this is hapening, and at this point I've changed my for loop from `playlist.items.forEach()` to `for element in playlist.items` and the one I've posted and neither have worked.
Here's the output:
```
Youtube Playlist URL: https://www.youtube.com/playlist?list=PL2xx-aV24fyC7Oht2GxkgTc9aAUXeNN3z
PL2xx-aV24fyC7Oht2GxkgTc9aAUXeNN3z
Playlist Name: Music2
3LAU - Star Crossed (Official Video) @ 100.00%
3LAU - Star Crossed (Official Video) @ 100.00%
3LAU - Star Crossed (Official Video) @ 100.00%
3LAU - Star Crossed (Official Video) @ 100.00%
3LAU - Star Crossed (Official Video) @ 100.00%

D:\Coding\nodejs\ytdlplaylist\playlistdownloader>
```
Aditionally the output shows the same name for every song even though I'm using the for to iterate through the songs in the playlist but that isn't as big of an issue.

Any and all help is welcomed, thank you for the time.

**Comment by fent** [comment]
> Now I've gotten the program to download every video on the playlist, but not every file plays...
> the files have size, but not all files play, for example:
> https://www.youtube.com/playlist?list=PL2xx-aV24fyC7Oht2GxkgTc9aAUXeNN3z
> that playlist downloads every file "correctly" as you can see here:
> ![image](https://user-images.githubusercontent.com/25158289/83461573-fa37d480-a460-11ea-8546-a424324fa3c1.png)
> but only "Brennan Heart & Jonathan Mendelsohn - Be Here Now (Official Video).mp3" actually plays audio, the other ones don't even open, they just finish instantly.

audioonly formats are usually in mp4 or webm containers. try changing their extensions to those and see if they play. you can get the extension by looking at `format.mimeType`. (I might extract that from there and put it directly on the `format` object, in a future update)



> Aditionally the output shows the same name for every song even though I'm using the for to iterate through the songs in the playlist but that isn't as big of an issue.

pretty common js issue, one of the most common. basically, the same variable is being shared in the for loop for every single video, so the last video ends up overwriting the variable. to fix it, use `let` and `const`, don't use `var`

also, you should probably rate limit your downloads and not download every video from the playlist at the same time. otherwise, youtube servers will end up limiting the downloads themselves and could even ban your ip for some time. I made [this library](https://github.com/fent/timequeue.js) that can help with that, I'm sure there are others too if you search for `queue` or `async`

**Comment by IcyTower1337** [comment]
> audioonly formats are usually in mp4 or webm containers. try changing their extensions to those and see if they play. you can get the extension by looking at `format.mimeType`. (I might extract that from there and put it directly on the `format` object, in a future update)

This worked, but it's kind of annoying because .mp3 was the format I wanted in the end, but it's fine I can just add a ffmpeg converter or something else in the end. 

> pretty common js issue, one of the most common. basically, the same variable is being shared in the for loop for every single video, so the last video ends up overwriting the variable. to fix it, use `let` and `const`, don't use `var`

I rememeber my teacher saying something about `let` being better than var, but didn't pay eneugh attention to why, now I know, thanks for the knowledge!

> also, you should probably rate limit your downloads and not download every video from the playlist at the same time. otherwise, youtube servers will end up limiting the downloads themselves and could even ban your ip for some time. I made [this library](https://github.com/fent/timequeue.js) that can help with that, I'm sure there are others too if you search for `queue` or `async`

I will look into this, thanks for the heads up, and thanks for the help from above! I think closing this is fine now.

**Comment by fent** [comment]
> you can get the extension by looking at `format.mimeType`. (I might extract that from there and put it directly on the `format` object, in a future update)

sorry. forgot this is already available in `format.container`
