### ISSUE TITLE
Unable to download particular video Avicii Wake Me Up

### ISSUE THREAD

**Issue by kfwebdev** [fent/node-ytdl-core#646]
Using ytdl-core 2.1.5 in node.js and most videos download perfectly. For some reason this one results in a blank file.

https://www.youtube.com/watch?v=IcrbM1l_BoI

Anyone come across this type of issue? Initially I was filtering by audioonly but seems to be the same result without filter as well.

**Comment by fent** [comment]
I'm able to download and play it fine, even with audioonly

**Comment by kfwebdev** [comment]
Oh really? Interesting, maybe it's something in my download code then. I'll revisit my code again. I've been working with it for awhile and while other's have worked, I haven't been able to download this. Thank you for confirming it works for you.

**Comment by kfwebdev** [comment]
I should have mentioned this is going through an ffmpeg download stream into mp3 format. Maybe that's where the issue is happening.

**Comment by TheBlueKyanite** [comment]
I am having this issue as well; some videos fail to download.

**Comment by kfwebdev** [comment]
@TheBlueKyanite do you have a video id? I'll try it on my setup. Also are you using ffMpeg or straight ytdl to download?

**Comment by TheBlueKyanite** [comment]
iywaBOMvYLI is the id. I am using ytdl straight to download.

**Comment by kfwebdev** [comment]
@TheBlueKyanite that one seems to download for me. I'm passing it to ffMpeg as well. Are you using the latest ytdl?

This is my code.

`
let downloadStream = ytdl(jobData.url, {
				filter: 'audioonly',
				quality: 'highestaudio',
			})
			const convertStream = ffmpeg(downloadStream)
				.format('mp3')
`

**Comment by TheBlueKyanite** [comment]
Strange, I am using version 2.1.6

**Comment by MGPlayzYT** [comment]
Try updating the package to `3.1.1`. I used to have this issue but it was fixed after I updated.
