### ISSUE TITLE
Some videos shows http 403

### ISSUE THREAD

**Issue by batuhansahan** [fent/node-ytdl-core#653]
I cannot access some spesific videos(the url shows http 403 error) - i thought this was fixed on 2.1.2 but it occured again. anyone knows what is the problem. and how to solve the problem.

example video
[Maroon 5 - Girls Like you](https://www.youtube.com/watch?v=aJOTlE1K90k)

i tried every version but no help.

**Comment by fent** [comment]
works for me when I try it. are you using a ytdl-core wrapper like ytdl-core-discord? any other settings passed like proxy? latest is actually v3.1.1

**Comment by batuhansahan** [comment]
i tried 3 1 1 but still same
```
ytdl.getInfo(link, (err, info) => {
          if (err) throw err;
          let video = ytdl.filterFormats(info.formats, 'audioandvideo');
          })
```

**Comment by batuhansahan** [comment]
no im using this library, i tried 3.1.1 but still same, i am using with express js

if i use postman there is no error but if i request via Android Application to express js restfull api, its giving url but the url shows http 403.


Android React-native
```js
      fetch(`${VIDEO_API_SERVER}/v1/video/youtube`, {
        method: 'POST',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          link: url,
        }),
      })
```

Nodejs Backend
```js
  router.route('/youtube').post(async (req, res) => {
    const {link} = req.body;
      try {
        const info = await ytdl.getInfo(link);
        if (info) {
          let video = ytdl.filterFormats(info.formats, 'audioandvideo');
          if (video.length === 0) {
            video = ytdl.filterFormats(info.formats, 'videoonly');
          }
          return res.send({video: video[0].url});
    } catch ...
```

**Comment by batuhansahan** [comment]
@fent 
no im using this library, i tried 3.1.1 but still same, i am using with express js

if i use postman there is no error but if i request via Android Application to express js restfull api, its giving url but the url shows http 403.


Android React-native
```js
      fetch(`${VIDEO_API_SERVER}/v1/video/youtube`, {
        method: 'POST',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          link: url,
        }),
      })
```

Nodejs Backend
```js
  router.route('/youtube').post(async (req, res) => {
    const {link} = req.body;
      try {
        const info = await ytdl.getInfo(link);
        if (info) {
          let video = ytdl.filterFormats(info.formats, 'audioandvideo');
          if (video.length === 0) {
            video = ytdl.filterFormats(info.formats, 'videoonly');
          }
          return res.send({video: video[0].url});
    } catch ...
```

**Comment by fent** [comment]
yep, this is under [limitations](https://github.com/fent/node-ytdl-core#limitations)
