### ISSUE TITLE
error not playing music

### ISSUE THREAD

**Issue by GokseLW** [fent/node-ytdl-core#656]
![image](https://user-images.githubusercontent.com/57256097/85287210-9c653e00-b49c-11ea-81a1-946ff080b25b.png)

**Comment by Roki100** [comment]
Its not a ytdl issue.
This is caused by discord.js not being able to establish connection to discord voice websocket in 15 seconds.

**Comment by MGPlayzYT** [comment]
This is not `ytdl-core` related, try checking your code.

**Comment by Roki100** [comment]
> This is not `ytdl-core` related, try checking your code.

also not code related
it can be either discord voice server or his connection issue
