### ISSUE TITLE
Error: input stream: Video unavailable

### ISSUE THREAD

**Issue by ghost** [fent/node-ytdl-core#657]
I'm trying to make a Discord music bot but I keep getting this error:

```
Error: input stream: Video unavailable
    at Object.exports.playError (C:\Users\Administrator\Desktop\musicbot\node_modules\ytdl-core\lib\util.js:437:12)
    at downloadFromInfoCallback (C:\Users\Administrator\Desktop\musicbot\node_modules\ytdl-core\lib\index.js:63:18)
    at C:\Users\Administrator\Desktop\musicbot\node_modules\ytdl-core\lib\index.js:23:5
    at C:\Users\Administrator\Desktop\musicbot\node_modules\ytdl-core\lib\info.js:288:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

It seems to work with some other vids but not this idk why: https://www.youtube.com/watch?v=N70DRo8_WwA

Thanks in advance

**Comment by xLivex** [comment]
Probably the video is unavailable in your country or the country where are you trying to host the bot from

**Comment by ifaisalqz** [comment]
I keep getting the same error above, its seems youtube change something with the API or something like that, because yesterday I can run this youtube music [https://www.youtube.com/watch?v=ele2DMU49Jk] but today I can't

**Comment by fent** [comment]
it's possible that the uploader has made it unavailable in your country since yesterday

**Comment by ifaisalqz** [comment]
> it's possible that the uploader has made it unavailable in your country since yesterday

Yeah maybe, I have a VPS from contabo and it's in US washington, someone told me to avoid problem like this you have to install proxy in your machine is that correct? and how?, Thanks.

**Comment by xLivex** [comment]
> Yeah maybe, I have a VPS from contabo and it's in US washington, someone told me to avoid problem like this you have to install proxy in your machine is that correct? and how?, Thanks.

Yes, you should use a proxy
check the [example](https://github.com/fent/node-ytdl-core/blob/master/example/proxy.js)

**Comment by DieBrute** [comment]
using a proxy with your example compromises the use of got and provides a nice https proxy agent Error: input stream: connect ECONNREFUSED.

Through the documentation I read, there is a incompatibility between the two packages
