### ISSUE TITLE
Error codes are uncaught

### ISSUE THREAD

**Issue by SteamingMutt** [fent/node-ytdl-core#66]
When requesting videos that are non-existent, YouTube replies with, for example `error code 404`, those codes are uncaught so the script stops with uncaughtException errors.
http://pastebin.com/sjCRwmep

**Comment by fent** [comment]
The stream returned by ytdl can emit the "error" event, which you can listen to.

```js
var stream = ytdll(url);
stream.on('error', function(err) {
});
```

**Comment by SteamingMutt** [comment]
Yup, that works :+1:
