### ISSUE TITLE
Slow download for audio tracks

### ISSUE THREAD

**Issue by talhabalaj** [fent/node-ytdl-core#660]
ytdl-core downloads the audio too slow, while others like ytdl-org/youtube-dl#21301 is just fine. Please look into this issue

**Comment by fent** [comment]
are you linking to that youtube-dl issue, or to youtube-dl in general?

**Comment by talhabalaj** [comment]
> are you linking to that youtube-dl issue, or to youtube-dl in general?

Actually the issue, they had similar issue so i thought i should let u know. 

I did more research, I was able to fix this by using `node-fetch` and adding a range header like "bytes=0-". that just works like a magic. Maybe you need to tweak that for the default behavior for ytdl. 

And sorry for like very bad issue description.  
You may close the issue now.
