### ISSUE TITLE
How do add cookies?

### ISSUE THREAD

**Issue by harshmandan** [fent/node-ytdl-core#661]
How do I add cookies, extracted from chrome (cookies.txt). Also how do I verify that the cookies are working?

**Comment by fent** [comment]
```js
ytdl(url, {
  requestOptions: {
    headers: {
      Cookie: 'a=1;b=2'
    }
  }
});
```

**Comment by harshmandan** [comment]
request options is not available for ytdl.getInfo(). I just want the info but without cookies it just keeps getting 429s.
Also this is my cookie file extracted using cookie.txt:
```
# Netscape HTTP Cookie File
# This file is generated by youtube-dl.  Do not edit.

.youtube.com	TRUE	/	FALSE	1654506508	APISID	82OXkGHhjizKHEU788ABYZK3ldt_1iJREGF
.youtube.com	TRUE	/	FALSE	1654506508	HSID	AQSF-y0S124920fB-V
.youtube.com	TRUE	/	TRUE	1656309188	LOGIN_INFO	AFmmfakeIhAISq8GEaMYDK-9pLtzU-XelD8u_ag9SgoviuWLwOM94xAiEAoVloDwNyqwPzJmdontbeJnUOUKwjlD4i8YzSboOLkSU:QUQ3MjNmeldldnotrealnBLMVYwZ2MwSWQyd0w5ckpJeFVjcHse3895bHHFIdWV5NkQ5c3ZOa1pfVGRjMHhaSXFjMThISXAyWUtDcS1ycTFPcGRxRlB5U040UjlaRS1OanJ5NllNNzlwY1WbHlLN1QwZzhzVWdmmjsfdsmfexDreallfakeTk1uaGxLNXRJMndfQXBBS1Q5VXRxMmNBbmp3Q3l3T3N0LVQ2NHFKV1VrV1pZUnJhX3Aw
.youtube.com	TRUE	/	FALSE	1598837289	PREF	f1=50003330&hl=en
.youtube.com	TRUE	/	TRUE	1654506508	SAPISID	XYA2VbHdaaFgfIjRlbG-/AQYu_EU4y1UYVLi
.youtube.com	TRUE	/	FALSE	1654506508	SID	xwcpDXWS0JE#_AS9-j8fRH7cYVjq1Qcg2qm4BtBw2LNZYbyxDvoy9-fG7xJLfwsbLwvFFw.
.youtube.com	TRUE	/	FALSE	1625189290	SIDCC	AJi4QfFewsJzkmNG1zVRHAjxnX9E5vUkGICjqznmV6dOvEFUJAUddKx2k0VyfN7KTAUUa76DDE2MmpQ
.youtube.com	TRUE	/	TRUE	1654506508	SSID	AV6DESFFJSeMQKR8VFz
.youtube.com	TRUE	/	TRUE	1606986301	VISITOR_INFO1_LIVE	Ij_phQFFDDNlg
.youtube.com	TRUE	/	TRUE	0	YSC	45Ih-KFHE8
.youtube.com	TRUE	/	TRUE	1654506508	__Secure-3PAPISID	XYA24hYFOSHgfIHFJDRlbG-/AQYumG_EU4y1UYVLi
.youtube.com	TRUE	/	TRUE	1654506508	__Secure-3PSID	xwFHEJDmbK_AS9-j8fRH7cYVjq1Qcg223rjjHm4BtBw24LNZYbyxdYI32492GTqc6zxzrQZ8RXQ.
.youtube.com	TRUE	/	TRUE	1596265199	__Secure-APISID	82OXkGHhjizKHFHEYYvxC/ABYHFIEdt_123PREGF
.youtube.com	TRUE	/	TRUE	1596265199	__Secure-HSID	AQSF-ayr836fOIwmB-V
.youtube.com	TRUE	/	TRUE	1596265199	__Secure-SSID	AV6qMFRy38Uw0QKR8VFz
.youtube.com	TRUE	/	FALSE	0	s_gl	1d69aac621b2f9c0a25dade8234GHRyvdsdpeIAAABVUw==

```

So, according to your answer my cookie would be like this?
```
{Cookie: 'APISID: 82OXkGHhjizKHEU788ABYZK3ldt_1iJREGF; SAPISID:XYA2VbHdaaFgfIjRlbG-/AQYu_EU4y1UYVLi ..........'
```

**Comment by fent** [comment]
> request options is not available for ytdl.getInfo()

it is available, it takes similar options as calling `ytdl()`



> Also this is my cookie file extracted using cookie.txt:

I've edited your post. be careful about posting sensitive information, even cookies. someone could login to your account with that.



> So, according to your answer my cookie would be like this?

use `=` instead of `:`. and no spaces between key and value

**Comment by harshmandan** [comment]
I had already edited the cookie file before sharing it.

This is the screenshot of the params getInfo accepts. How do I put options in it?
![sc](https://i.imgur.com/vtqqy9e.png)

**Comment by harshmandan** [comment]
Okay! Thanks for the info but it still isn't working.
Now it throws this error:
```
Error: Error parsing info: JSON.parse(...).reduce is not a function
at exports.getBasicInfo (/home/live/node_modules/ytdl-core/lib/info.js:43:11)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Object.exports.<computed> [as getBasicInfo] (/home/live/node_modules/ytdl-core/lib/info.js:296:18)
at async exports.getFullInfo (/home/live/node_modules/ytdl-core/lib/info.js:187:14)
at async Object.exports.<computed> [as getFullInfo] (/home/live/node_modules/ytdl-core/lib/info.js:296:18)
```

I tried with this code:

```
ytdl.getInfo(req.body.vid, { requestOptions: 
                { 
                    headers: {
                        Cookie: 'APISID=secure;LOGIN_INFO=secure;PREF=f1=50000000&hl=en;SAPISID=secure;SID=secure;SIDCC=secure;SSID=secure;VISITOR_INFO1_LIVE=secure;__Secure-3PAPISID=sec;__Secure-3PSID=sec;__Secure-APISID=sec;__Secure-HSID=sec;__Secure-SSID=sec;s_gl=sec'
                    }
                }
            }, (err, info) => {
                      console.log(info);
            });
```

**Comment by fent** [comment]
try adding a space after each `;`. all examples i've seen of cookies have them like that

    key=value; another_key=another_value; more=stuff;

**Comment by harshmandan** [comment]
Still nothing. I logged the body in info.js at 43rd line. The body has this output:
```
{"reload":"now"}
```

**Comment by fent** [comment]
hmm, I'll have to investigate this. this was also noticed in this issue https://github.com/fent/node-ytdl-core/issues/632#issuecomment-639000789

**Comment by fent** [comment]
I tried using cookies myself, everything worked, didn't get `{"reload":"now"}`

**Comment by harshmandan** [comment]
Alright. I think I can tell you how to replicate this. I generated my cookie file using the cookie.txt extension in chrome.
Cleared cookies, logged in into youtube, extracted the cookie file using extension.

Then I generated this string:
```
APISID=sec; LOGIN_INFO=sec; PREF=f1=50000000&hl=en; SAPISID=sec; SID=sec; SIDCC=sec; SSID=sec; VISITOR_INFO1_LIVE=sec; __Secure-3PAPISID=sec; __Secure-3PSID=sec; __Secure-APISID=sec; __Secure-HSID=sec; __Secure-SSID=sec; s_gl=sec'
```
`sec` is where my secret keys go. 

Used these keys in my code as:

```
ytdl.getInfo(req.body.vid, { requestOptions: 
                { 
                    headers: {
                        Cookie: cookieString
                    }
                }
            }, (err, info) => {
                if (err) {
                    console.log(err);
                    return res.status(422).send({code:422, status:"err", err:err});
                }
                res.json({code:200, status:"success", info});
            });
```

When I run this code, its throws this error:
```
Error: Error parsing info: JSON.parse(...).reduce is not a function
at exports.getBasicInfo (/home/live/node_modules/ytdl-core/lib/info.js:43:11)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Object.exports.<computed> [as getBasicInfo] (/home/live/node_modules/ytdl-core/lib/info.js:296:18)
at async exports.getFullInfo (/home/live/node_modules/ytdl-core/lib/info.js:187:14)
at async Object.exports.<computed> [as getFullInfo] (/home/live/node_modules/ytdl-core/lib/info.js:296:18)
```

To verify the cookie file. I've used the ytdl command line utility and it works fine.

Can you verify if the cookies you used were obtained using the same process and/or are an youtube account's cookies?

Thanks!

**Comment by fent** [comment]
ok, I was able to replicate it by using the cookies.txt extension to extract cookies, and I did get a `{ "reload": "now" }` response. but I think that could have to do with giving a bad cookie header.

if I try the 2nd method you posted, I don't get an error and all the requests go through fine. but, I'm also not sure if I'm really logged in.

**Comment by harshmandan** [comment]
Okay! I can understand if the first method doesn't work. But I'm getting error with the second method as well.

Just to confirm if this is the procedure you followed.
 - Open Incognito/Private session.
 - Head to youtube and log in
 - You'll be redirected to youtube homepage.
 - Open dev tools and head to network tab.
 - Now refresh the page again.
 - Copy Cookie from REQUEST Header section from the first request (It should show up as www.youtube.com)
 - Use that header with YTDL

**Comment by fent** [comment]
I found a way, it needs the `x-youtube-identity-token` header. you can find this in the watch page's source if you search for `ID_TOKEN`. but I'll make a change so that ytdl-core looks for it if the cookie header is set

**Comment by mh4ck** [comment]
Even with the `x-youtube-identity-token` header i get the `parsedBody.reduce is not a function` error

I wrote a small nightmare.js script which extract the values from YouTube:

```
const Nightmare = require("nightmare");
const fs = require("fs");
const request = require("request");

const nightmare = Nightmare({
    show: true,
    height: 768,
    width: 1024
});

nightmare
.useragent("Chrome")
.goto("https://www.youtube.com/")
.wait('a[href*="accounts.google.com"]')
.click('a[href*="accounts.google.com"]')
.wait(10000)
.type('#Email', '[your email]')
.click('#next')
.wait(10000)
.type('input[type=password]', '[your password]' + '\u000d')
.wait(10000)
.useragent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36")
.goto("https://www.youtube.com/watch?v=AhaB4KEUGW0")
.wait('#avatar-btn')
.evaluate(() => {
    var ret = {cookie: document.cookie, cv: null};
    var cv_regex = /innertubeContextClientVersion":\"([^\"]+)/gm;
    var str = document.body.innerHTML;
    var m = cv_regex.exec(str);
    if(m && m[1]) {
        ret.cv = m[1];
    }

    var headHTML = document.head.innerHTML;
    var id_regex = /ID_TOKEN":\"([^\"]+)/gm;
    var idM = id_regex.exec(headHTML);
    if(idM && idM[1]) {
        ret.id = idM[1];
    }
    return ret;
})
.end()
.then((ret) => {
    let cookie = ret.cookie;
    console.log(cookie);
    let clientVersion = ret.cv;
    console.log(clientVersion);
    let idToken = ret.id;
    console.log(idToken);

    request.post("[send to your address where you need it]", {
        form: {
            cookie: cookie,
            clientVersion: clientVersion,
            idToken: idToken
        }
    },
    (err, resp, body) => {
        if(err) {
            console.log(err);
            return;
        }

        if(resp.statusCode != 200) {
            console.log("[Error]: Received status code: " + resp.statusCode);
            return;
        }

        console.log("[Info]: Cookie send successfull to Server!");
    });
})
.catch((err) => {
    console.log(err);
});
```

I'm sending now these headers to the info request
- cookie
- x-youtube-client-name
- x-youtube-client-version
- x-youtube-identity-token

And get the error "**Error parsing info: parsedBody.reduce is not a function**"

Am i doing smth. wrong? @fent

**Comment by fent** [comment]
> I'm sending now these headers to the info request
> 
> * cookie
> * x-youtube-client-name
> * x-youtube-client-version
> * x-youtube-identity-token

are you defining those yourself in the options to `getInfo`? or letting ytdl-core add them?

**Comment by mh4ck** [comment]
> > I'm sending now these headers to the info request
> > 
> > * cookie
> > * x-youtube-client-name
> > * x-youtube-client-version
> > * x-youtube-identity-token
> 
> are you defining those yourself in the options to `getInfo`? or letting ytdl-core add them?

I define them myself in the headers

**Comment by fent** [comment]
does the cookie work for you in your browser? are you using a proxy or a custom user-agent?

**Comment by mh4ck** [comment]
Yes it works in my browser, while login i'm usung the UA 'Chrome' otherway the login is not working. 

I'm using the script above to generate/read the header values. 

Then i set them in getInfo requestOptions...
