### ISSUE TITLE
new info format

### ISSUE THREAD

**Issue by samelie** [fent/node-ytdl-core#67]
From what I can tell they have removed _dashmpd_

Correct me if I am wrong, I do remember seeing the manifest url being loaded in the Network devtools. Not there anymore however. Great shame :(

I see what you do in the config parse, maybe you know another place it could be hiding?

**Comment by fent** [comment]
Dash URL is still there, at least on the irl-test.js videos. Were there any videos where it used to be but not anymore?

**Comment by samelie** [comment]
I tried getInfo with the url on the readme `'http://www.youtube.com/watch?v=A02s8omM_hI'`, nothing.
saw something about having to generate signatures. need to look further
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1466

**Comment by fent** [comment]
Getting info for that video, and downloading, both worked for me.

**Comment by samelie** [comment]
I get the info too, it seems they are removing the dashmpd from the config.
https://gist.github.com/samelie/3e81112d84dd42c2ce70

**Comment by samelie** [comment]
If anyone is interested the data from a dash representation can still be extracted without the dashmpd.
Using this method:
https://gist.github.com/samelie/48911ecb689856daa9a0
The index range can still be found in the videoinfo
