### ISSUE TITLE
Event: response dose not emit for a successful fecth

### ISSUE THREAD

**Issue by Dalanke** [fent/node-ytdl-core#671]
Hi,
I was trying to stream in audio only format and everything works fine. However, when I check with some videos, I found that I can successfully get them, but the `response` event won't emit. This only happens for certain videos.
The code I tested with are listed below:
```JavaScript
const ytdl = require('ytdl-core');
const fs = require('fs');

let stream = ytdl("https://www.youtube.com/watch?v=E8S2IHiuWZA", { range: { start: 0 , end: 1 }, filter: 'audioonly' });
stream.on('info', function (info, format) {
  console.log('Download started')
  console.log(info.videoDetails.title)
  //console.log(format);
})
stream.on('progress', function (length, downloaded, total) {
  //console.log(`length=${total}`);
});
stream.on('response', Ytbres => { 
  console.log(Ytbres.headers)
});


stream.pipe(fs.createWriteStream('myvideo_1.mp4'))
``` 

Any thoughts or suggestion would be grateful. Thanks!

**Comment by Aasim-A** [comment]
Hi there, this format of this link is `dashMPD`, and the download of that format is handled by a different module (`m3u8stream` also made by @fent ), to resolve your issue, that module needs to be modified to pass the `response` event to the video download stream.

**Comment by Dalanke** [comment]
> Hi there, this format of this link is `dashMPD`, and the download of that format is handled by a different module (`m3u8stream` also made by @fent ), to resolve your issue, that module needs to be modified to pass the `response` event to the video download stream.

Hi,
I tried to modify this module but now get multiple response. Any idea that I can get single response as the other links?
Here is what I have done:
```JavaScript
// modified in index.js of moudule m3u8stream

const requestQueue = new queue_1.default((segment, callback) => {
        let options = Object.assign({}, requestOptions);
        if (segment.range) {
            options.headers = Object.assign({}, options.headers, {
                Range: `bytes=${segment.range.start}-${segment.range.end}`,
            });
        }
        let req = miniget_1.default(url_1.resolve(playlistURL, segment.url), options);
        req.on('error', callback);
        // Here is what I have tried to pass out event
        req.prependListener('response', arg => {
            stream.emit('response', arg);
        });
        streamQueue.push(req, (err, size) => {
            downloaded += +size;
            stream.emit('progress', {
                num: ++segmentNumber,
                size: size,
                duration: segment.duration,
                url: segment.url,
            }, requestQueue.total, downloaded);
            callback();
        });
    }, { concurrency: chunkReadahead });
```

I am not quite sure if it is correct way, any idea is welcome. Thanks!

**Comment by Aasim-A** [comment]
In `dashMPD` format the download is segmented into multiple parts, that's why you're getting multiple response events called, if the information that you want is not dependant on the other parts of the video, you can make it fire off the event once. What data do you exactly need from the `response` event?

**Comment by Dalanke** [comment]
Thanks for your reply!
Actually I need the headers in `response`, I found out that the stream to client is not working if headers is missing. I tried to construct my own header but I found it is also hard to get the size of the download, so the `content-length` can not be set.
What I am doing is that I use the `<audio>` tag and set the `src` to my server like this:
```html
<audio controls id="player">
    <source src="http://localhost:3000/stream?id=pYyfKSf-VfA" >
    <p>Your browser doesn't support HTML5 audio.</p>
  </audio>
```
where the request is handled and return the stream by `stream.pipe(res)`, before streaming, the headers needs to be set correctly or audio control won't work. I set the header in this way:
```JavaScript
stream.on('response', Ytbres => {
      res.set(Ytbres.headers);
      res.status(Ytbres.statusCode);
    });
```
 a valid header should looks like:
```
HTTP/1.1 206 Partial Content
Content-Type: video/mp4
Expires: Fri, 24 Jul 2020 16:49:59 GMT
Cache-Control: private, max-age=21298
Date: Fri, 24 Jul 2020 16:49:59 GMT
Content-Length: 13437332
Connection: close
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
Content-Range: bytes 0-13437331/13437332
Last-Modified: Sun, 10 Nov 2019 11:01:18 GMT
alt-svc: h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
X-Powered-By: Express
Server: gvs 1.0
```
so I need the `Content-Length` and `Content-Range`. I also tried to see contentLength in `ytdl.videoFormat` for `info` event, but it is `undefine` in this format.

**Comment by fent** [comment]
`Content-Length` is not available in segmented formats. and the `range` option isn't supported either, I'll add a note about it on the readme.

if there's a way to get the size of a segmented format before downloading the whole thing, please let me know. the information isn't in the `format` object or in the headers. it may be in the playlist file, but I didn't see it last time I checked.

as for the `response` event, it might make sense to pass it through from m3u8stream even if it's fired multiple times. it won't fix your issue though.

**Comment by Dalanke** [comment]
> `Content-Length` is not available in segmented formats. and the `range` option isn't supported either, I'll add a note about it on the readme.
> 
> if there's a way to get the size of a segmented format before downloading the whole thing, please let me know. the information isn't in the `format` object or in the headers. it may be in the playlist file, but I didn't see it last time I checked.
> 
> as for the `response` event, it might make sense to pass it through from m3u8stream even if it's fired multiple times. it won't fix your issue though.

Thanks for your reply!
I have checked the url in `format` object, and found out it is a xml file for the download. There might be some useful information to get the size of segment.

Here is the `format` I got from the event
```
{
  mimeType: 'audio/webm; codecs="opus"',
  qualityLabel: null,
  bitrate: null,
  audioBitrate: 160,
  itag: 251,
  url: 'https://manifest.googlevideo.com/api/manifest/dash/expire/1595967899/ei/OzUgX57lHOSQ8gSejKfoCw/ip/100.17.39.169/id/a58c9f2927fe55f0/source/youtube/requiressl/yes/playback_host/r1---sn-8xgp1vo-cvne.googlevideo.com/mh/hT/mm/31%2C29/mn/sn-8xgp1vo-cvne%2Csn-ab5szn76/ms/au%2Crdu/mv/m/mvi/1/pl/16/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/2033750/vprv/1/mt/1595946153/fvip/1/keepalive/yes/fexp/23883098/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRgIhAJ8qp86Bx1zzabGETSfWkdnDBwPV7nBouiQEhQcnrro6AiEA1CQRgvJa9tpVLp4d8DwAX36TxhD2hTaC1X7jOlyoXQk%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhAO_NlHIe2GnfZGByLUtzJEM7NHBSEZRHYhLJZHgvEwjnAiArgbq5Bub-202wsQiYCfY8IDa9As2r_VopLCxaXU1XQw%3D%3D',
  hasVideo: false,
  hasAudio: true,
  container: 'webm',
  codecs: 'opus',
  videoCodec: null,
  audioCodec: 'opus',
  live: false,
  isHLS: false,
  isDashMPD: true
}
```
I copy the url into the browser and got a xml file,  and I searched the itag `251` found information below:
```
<Representation id="251" codecs="opus" audioSamplingRate="48000" startWithSAP="1" bandwidth="157096">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
        <BaseURL>https://r1---sn-8xgp1vo-cvne.googlevideo.com/videoplayback/expire/1595967899/ei/OzUgX57lHOSQ8gSejKfoCw/ip/100.17.39.169/id/a58c9f2927fe55f0/itag/251/source/youtube/requiressl/yes/mh/hT/mm/31,29/mn/sn-8xgp1vo-cvne,sn-ab5szn76/ms/au,rdu/mv/m/mvi/1/pl/16/initcwndbps/2033750/vprv/1/ratebypass/yes/mime/audio%2Fwebm/otfp/1/gir/yes/clen/5348750/lmt/1573383704226887/dur/319.321/mt/1595946153/fvip/1/keepalive/yes/fexp/23883098/sparams/expire,ei,ip,id,itag,source,requiressl,vprv,ratebypass,mime,otfp,gir,clen,lmt,dur/sig/AOq0QJ8wRQIgZ_xevg9Nx_eqMEZJIlBvkgqd3HVXB0PXDYnUiREUDRACIQDk2xkuwIRdnP3uYmumejMEYQQqHGRyZueFabTqVTz9fQ%3D%3D/lsparams/mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRQIgaQcOd9y3uO748pyeoxqTdYT4GFBgV6kAGU5EMbERW_8CIQC3vckGTPlP7Ks--Xf1-uvuFXCw9xKf7Tv-qya_9EadYQ%3D%3D/</BaseURL>
        <SegmentList>
          <Initialization sourceURL="range/0-265" />
          <SegmentURL media="range/807-171221" />
          <SegmentURL media="range/171222-339635" />
          <SegmentURL media="range/339636-527314" />
          <SegmentURL media="range/527315-705600" />
          <SegmentURL media="range/705601-870600" />
          <SegmentURL media="range/870601-1030560" />
          <SegmentURL media="range/1030561-1194251" />
          <SegmentURL media="range/1194252-1355445" />
          <SegmentURL media="range/1355446-1521133" />
          <SegmentURL media="range/1521134-1687063" />
          <SegmentURL media="range/1687064-1851699" />
          <SegmentURL media="range/1851700-2027935" />
          <SegmentURL media="range/2027936-2191331" />
          <SegmentURL media="range/2191332-2350987" />
          <SegmentURL media="range/2350988-2512404" />
          <SegmentURL media="range/2512405-2679671" />
          <SegmentURL media="range/2679672-2842714" />
          <SegmentURL media="range/2842715-3005844" />
          <SegmentURL media="range/3005845-3170895" />
          <SegmentURL media="range/3170896-3340524" />
          <SegmentURL media="range/3340525-3511526" />
          <SegmentURL media="range/3511527-3672478" />
          <SegmentURL media="range/3672479-3842445" />
          <SegmentURL media="range/3842446-4038815" />
          <SegmentURL media="range/4038816-4224777" />
          <SegmentURL media="range/4224778-4391509" />
          <SegmentURL media="range/4391510-4554415" />
          <SegmentURL media="range/4554416-4721623" />
          <SegmentURL media="range/4721624-4889038" />
          <SegmentURL media="range/4889039-5057392" />
          <SegmentURL media="range/5057393-5225411" />
          <SegmentURL media="range/5225412-5348749" />
        </SegmentList>
      </Representation>
```

I assume that we can get the whole size there. Any thoughts ?

**Comment by TimeForANinja** [comment]
just wanna point out that that doesn't work for `live` videos 🤔

**Comment by fent** [comment]
hmm yeah we could look in urls for a `/range[\/=](\d+)-(\d+)/` pattern

**Comment by Dalanke** [comment]
I have used `xml2js` library to parse the xml file and finally get the total size, but I am not sure that if every xml returned by url is in same structure. For the live videos, I think is reasonable not to provide `content-length`

Just attach my test code if you guys want to play with it

```JavaScript
var parseString = require('xml2js').parseString;
var http = require('https');

// get xml from url then parse it 
function xmlToJson(url, callback) {
  var req = http.get(url, function(res) {
    var xml = '';
    
    res.on('data', function(chunk) {
      xml += chunk;
    });

    res.on('error', function(e) {
      callback(e, null);
    }); 

    res.on('timeout', function(e) {
      callback(e, null);
    }); 

    res.on('end', function() {
      parseString(xml, function(err, result) {
        callback(null, result);
      });
    });
  });
}

var url = 'https://manifest.googlevideo.com/api/manifest/dash/expire/1595990076/ei/3IsgX5jEKMzYhwbGyb34Cw/ip/100.17.39.169/id/a58c9f2927fe55f0/source/youtube/requiressl/yes/playback_host/r1---sn-8xgp1vo-cvne.googlevideo.com/mh/hT/mm/31%2C29/mn/sn-8xgp1vo-cvne%2Csn-ab5l6ndy/ms/au%2Crdu/mv/m/mvi/1/pl/16/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1962500/vprv/1/mt/1595968355/fvip/1/keepalive/yes/fexp/23883098/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgYgkDIRelMDtdqaZw2yphzHUUpIRJOJPUCRL5cIkF-gcCIQCxB96ceqtnny054XwtVUP9QmOfPmilQECM_CUYHwfNnQ%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgX87iGnfP6-UZ7AQnU2dUmwWS1UBXd19QEAswdWfse2UCIQCCMIT2wXu6gp4MH2gh38y04y28PZOzTCOIvU1UyX8LPA%3D%3D'

xmlToJson(url, function(err, data) {
  if (err) {
    return console.err(err);
  }

 // handle data according to structure
  var adapt = data.MPD.Period[0].AdaptationSet
  adapt.forEach(element => {
    if(element['$'].mimeType == 'audio/webm') {
      var range = element.Representation[0].SegmentList[0].SegmentURL 
      var total = range[range.length - 1]['$'].media // output: range/5225412-5348749
      console.log(total.split('-')[1])
    }
  });
  // output: 5348749
})
```

**Comment by Dalanke** [comment]
A quick update, I found the content length from the `info` event.
By matching the itag, I got it from `info.player_response.streamingData.adaptiveFormats`

Here is the object it return:
```
{
  itag: 251,
  mimeType: 'audio/webm; codecs="opus"',
  bitrate: 157096,
  initRange: { start: '0', end: '265' },
  indexRange: { start: '266', end: '806' },
  lastModified: '1573383704226887',
  contentLength: '5348750',
  quality: 'tiny',
  projectionType: 'RECTANGULAR',
  averageBitrate: 134003,
  audioQuality: 'AUDIO_QUALITY_MEDIUM',
  approxDurationMs: '319321',
  audioSampleRate: '48000',
  audioChannels: 2,
  s: 'CAOq0QJ8wRAIgItnoVKjwnwj_HUVd5xNbpIFldZe6wqetKdx3b8jfulEAIFIeUzp6zC73gDCop8cgiw0UA8XXE4o4kD-LULWGKNHwNHw',
  sp: 'sig',
  url: 'https://r1---sn-8xgp1vo-cvne.googlevideo.com/videoplayback?expire=1596060395&ei=i54hX-OYBIvm8wTDlpzoDA&ip=100.17.39.169&id=o-AAg27MtiFPnacGBt_V0f_9yMwerw20jVhyMFouWQWDZl&itag=251&source=youtube&requiressl=yes&mh=hT&mm=31%2C29&mn=sn-8xgp1vo-cvne%2Csn-ab5szn76&ms=au%2Crdu&mv=m&mvi=1&pl=16&initcwndbps=2060000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=5348750&otfp=1&dur=319.321&lmt=1573383704226887&mt=1596038582&fvip=1&keepalive=yes&fexp=23883098&c=WEB&txp=2211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPqal2cLFhDfYxxz1E7wb7na0s976CfK4z2anuxSkGtNAiEArbDknE34gIXQcN_pkAPTJq_uUu4eZ0q6E3YG9DdXEWo%3D&ratebypass=yes&sig=AOq0QJ8wRAIgItnpVKjwnwj_HUVd5xNbpIFldZe6wqetKdx3b8jfulECIFIeUzo6zC73gDCop8cgiw0UA8XXE4o4kD-LULWGKNHw'
}
```
Also, from the `url` in this object, you can directly download the file you want, or use `https.get()` to get a readable stream in response.
Hope this helps

**Comment by fent** [comment]
cool find! didn't realize there are formats that have both a dashmpd playlist url and a regular video url. we could add a preference for ytdl to choose the direct url format, or to have both urls in one format.

**Comment by monzer15** [comment]
> I have used `xml2js` library to parse the xml file and finally get the total size, but I am not sure that if every xml returned by url is in same structure. For the live videos, I think is reasonable not to provide `content-length`
> 
> Just attach my test code if you guys want to play with it
> 
> ```js
> var parseString = require('xml2js').parseString;
> var http = require('https');
> 
> // get xml from url then parse it 
> function xmlToJson(url, callback) {
>   var req = http.get(url, function(res) {
>     var xml = '';
>     
>     res.on('data', function(chunk) {
>       xml += chunk;
>     });
> 
>     res.on('error', function(e) {
>       callback(e, null);
>     }); 
> 
>     res.on('timeout', function(e) {
>       callback(e, null);
>     }); 
> 
>     res.on('end', function() {
>       parseString(xml, function(err, result) {
>         callback(null, result);
>       });
>     });
>   });
> }
> 
> var url = 'https://manifest.googlevideo.com/api/manifest/dash/expire/1595990076/ei/3IsgX5jEKMzYhwbGyb34Cw/ip/100.17.39.169/id/a58c9f2927fe55f0/source/youtube/requiressl/yes/playback_host/r1---sn-8xgp1vo-cvne.googlevideo.com/mh/hT/mm/31%2C29/mn/sn-8xgp1vo-cvne%2Csn-ab5l6ndy/ms/au%2Crdu/mv/m/mvi/1/pl/16/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1962500/vprv/1/mt/1595968355/fvip/1/keepalive/yes/fexp/23883098/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgYgkDIRelMDtdqaZw2yphzHUUpIRJOJPUCRL5cIkF-gcCIQCxB96ceqtnny054XwtVUP9QmOfPmilQECM_CUYHwfNnQ%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgX87iGnfP6-UZ7AQnU2dUmwWS1UBXd19QEAswdWfse2UCIQCCMIT2wXu6gp4MH2gh38y04y28PZOzTCOIvU1UyX8LPA%3D%3D'
> 
> xmlToJson(url, function(err, data) {
>   if (err) {
>     return console.err(err);
>   }
> 
>  // handle data according to structure
>   var adapt = data.MPD.Period[0].AdaptationSet
>   adapt.forEach(element => {
>     if(element['$'].mimeType == 'audio/webm') {
>       var range = element.Representation[0].SegmentList[0].SegmentURL 
>       var total = range[range.length - 1]['$'].media // output: range/5225412-5348749
>       console.log(total.split('-')[1])
>     }
>   });
>   // output: 5348749
> })
> ```

hey there,

I tried this and it works!

well for itag 137 (mp4-1080p) mostly.
so it prints something weird on other itags instead of **range/num-num**

i get  **sq/num/dur/num**

any idea to overcome this?

**Comment by Dalanke** [comment]
> > I have used `xml2js` library to parse the xml file and finally get the total size, but I am not sure that if every xml returned by url is in same structure. For the live videos, I think is reasonable not to provide `content-length`
> > Just attach my test code if you guys want to play with it
> > ```js
> > var parseString = require('xml2js').parseString;
> > var http = require('https');
> > 
> > // get xml from url then parse it 
> > function xmlToJson(url, callback) {
> >   var req = http.get(url, function(res) {
> >     var xml = '';
> >     
> >     res.on('data', function(chunk) {
> >       xml += chunk;
> >     });
> > 
> >     res.on('error', function(e) {
> >       callback(e, null);
> >     }); 
> > 
> >     res.on('timeout', function(e) {
> >       callback(e, null);
> >     }); 
> > 
> >     res.on('end', function() {
> >       parseString(xml, function(err, result) {
> >         callback(null, result);
> >       });
> >     });
> >   });
> > }
> > 
> > var url = 'https://manifest.googlevideo.com/api/manifest/dash/expire/1595990076/ei/3IsgX5jEKMzYhwbGyb34Cw/ip/100.17.39.169/id/a58c9f2927fe55f0/source/youtube/requiressl/yes/playback_host/r1---sn-8xgp1vo-cvne.googlevideo.com/mh/hT/mm/31%2C29/mn/sn-8xgp1vo-cvne%2Csn-ab5l6ndy/ms/au%2Crdu/mv/m/mvi/1/pl/16/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1962500/vprv/1/mt/1595968355/fvip/1/keepalive/yes/fexp/23883098/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgYgkDIRelMDtdqaZw2yphzHUUpIRJOJPUCRL5cIkF-gcCIQCxB96ceqtnny054XwtVUP9QmOfPmilQECM_CUYHwfNnQ%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgX87iGnfP6-UZ7AQnU2dUmwWS1UBXd19QEAswdWfse2UCIQCCMIT2wXu6gp4MH2gh38y04y28PZOzTCOIvU1UyX8LPA%3D%3D'
> > 
> > xmlToJson(url, function(err, data) {
> >   if (err) {
> >     return console.err(err);
> >   }
> > 
> >  // handle data according to structure
> >   var adapt = data.MPD.Period[0].AdaptationSet
> >   adapt.forEach(element => {
> >     if(element['$'].mimeType == 'audio/webm') {
> >       var range = element.Representation[0].SegmentList[0].SegmentURL 
> >       var total = range[range.length - 1]['$'].media // output: range/5225412-5348749
> >       console.log(total.split('-')[1])
> >     }
> >   });
> >   // output: 5348749
> > })
> > ```
> 
> hey there,
> 
> I tried this and it works!
> 
> well for itag 137 (mp4-1080p) mostly.
> so it prints something weird on other itags instead of **range/num-num**
> 
> i get **sq/num/dur/num**
> 
> any idea to overcome this?
> 
> ```
> var adaptSets = data.MPD.Period[0].AdaptationSet
> 
>         adaptSets.forEach(element => {
>             element.Representation.forEach(rep => {
>                 if (rep['$'].id == format.itag) {
>                     var range = rep.SegmentList[0].SegmentURL
>                     var total = range[range.length - 1]['$'].media // output: range/5225412-5348749
>                     if (total.includes("range")) {
>                         const contentLength = total.split('-')[1]
>                         resolve(contentLength)
>                     }else{
>                         // here is the issue
>                        // output: sq/number/dur/time
>                         resolve(-1)
>                     }
>                 }  
>             })
>         });
> ```

You can try to play with `sq/num/dur/num` format to calculate the content length, all you need is some function parse this string. However I think the better idea is get what you want from the `info` event. The info event will return an object contains all kinds of information. Kindly refer to `README` and my reply in this issue

> A quick update, I found the content length from the `info` event.
> By matching the itag, I got it from `info.player_response.streamingData.adaptiveFormats`
> 
> Here is the object it return:
> 
> ```
> {
>   itag: 251,
>   mimeType: 'audio/webm; codecs="opus"',
>   bitrate: 157096,
>   initRange: { start: '0', end: '265' },
>   indexRange: { start: '266', end: '806' },
>   lastModified: '1573383704226887',
>   contentLength: '5348750',
>   quality: 'tiny',
>   projectionType: 'RECTANGULAR',
>   averageBitrate: 134003,
>   audioQuality: 'AUDIO_QUALITY_MEDIUM',
>   approxDurationMs: '319321',
>   audioSampleRate: '48000',
>   audioChannels: 2,
>   s: 'CAOq0QJ8wRAIgItnoVKjwnwj_HUVd5xNbpIFldZe6wqetKdx3b8jfulEAIFIeUzp6zC73gDCop8cgiw0UA8XXE4o4kD-LULWGKNHwNHw',
>   sp: 'sig',
>   url: 'https://r1---sn-8xgp1vo-cvne.googlevideo.com/videoplayback?expire=1596060395&ei=i54hX-OYBIvm8wTDlpzoDA&ip=100.17.39.169&id=o-AAg27MtiFPnacGBt_V0f_9yMwerw20jVhyMFouWQWDZl&itag=251&source=youtube&requiressl=yes&mh=hT&mm=31%2C29&mn=sn-8xgp1vo-cvne%2Csn-ab5szn76&ms=au%2Crdu&mv=m&mvi=1&pl=16&initcwndbps=2060000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=5348750&otfp=1&dur=319.321&lmt=1573383704226887&mt=1596038582&fvip=1&keepalive=yes&fexp=23883098&c=WEB&txp=2211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPqal2cLFhDfYxxz1E7wb7na0s976CfK4z2anuxSkGtNAiEArbDknE34gIXQcN_pkAPTJq_uUu4eZ0q6E3YG9DdXEWo%3D&ratebypass=yes&sig=AOq0QJ8wRAIgItnpVKjwnwj_HUVd5xNbpIFldZe6wqetKdx3b8jfulECIFIeUzo6zC73gDCop8cgiw0UA8XXE4o4kD-LULWGKNHw'
> }
> ```
> 
> Also, from the `url` in this object, you can directly download the file you want, or use `https.get()` to get a readable stream in response.
> Hope this helps

**Comment by fent** [comment]
is there a video where this would help? the ones i've tried, the `format` object already contains `contentLength`

**Comment by Dalanke** [comment]
Sorry for delayed response.
I think the video I mentioned at first on issue description (`https://www.youtube.com/watch?v=E8S2IHiuWZA`)  might help with this question.

**Comment by fent** [comment]
yep, that one has the `contentLength` in the format objects already, so it wouldn't benefit from this change. i'd like to find a video where parsing the urls in the dash manifest would get us new information

**Comment by Dalanke** [comment]
Actually, I have no idea why it changed. When I tested it, it's a `DashMPD` format.
It has been a while from the time point that I played with this issue, seems like you guys have done some great job and made few updates on it. I found my code no longer working.
I suggest look into all available format to see if there is DashMPD format available. Also you can contact @monzer15 to see if there is some working `DashMPD` link.

**Comment by fent** [comment]
ok, closing for now, but here is the diff in case this pops up again

```diff
diff --git a/lib/info.js b/lib/info.js
index fdf62f5..4b812b8 100644
--- a/lib/info.js
+++ b/lib/info.js
@@ -282,14 +282,14 @@ const getDashManifest = (url, options) => new Promise((resolve, reject) => {
   let formats = {};
   const parser = sax.parser(false);
   parser.onerror = reject;
-  let adaptationSet;
+  let adaptationSet, currFormat;
   parser.onopentag = node => {
     if (node.name === 'ADAPTATIONSET') {
       adaptationSet = node.attributes;
     } else if (node.name === 'REPRESENTATION') {
       const itag = parseInt(node.attributes.ID);
       if (!isNaN(itag)) {
-        formats[url] = Object.assign({
+        currFormat = formats[`${url}dash`] = Object.assign({
           itag, url,
           bitrate: parseInt(node.attributes.BANDWIDTH),
           mimeType: `${adaptationSet.MIMETYPE}; codecs="${node.attributes.CODECS}"`,
@@ -301,6 +301,16 @@ const getDashManifest = (url, options) => new Promise((resolve, reject) => {
           audioSampleRate: node.attributes.AUDIOSAMPLINGRATE,
         });
       }
+    } else if (node.name === 'INITIALIZATION') {
+      const range = /range\/(\d+)-(\d+)/.exec(node.attributes.SOURCEURL);
+      if (range) {
+        currFormat.initRange = { start: parseInt(range[0]), end: parseInt(range[1]) };
+      }
+    } else if (node.name === 'SEGMENTURL') {
+      const range = /range\/(\d+)-(\d+)/.exec(node.attributes.MEDIA);
+      if (range) {
+        currFormat.contentLength = parseInt(range[1]);
+      }
     }
   };
   parser.onend = () => { resolve(formats); };
```
