### ISSUE TITLE
ytdl delivers low speed and high cpu usage

### ISSUE THREAD

**Issue by hypo-thesis** [fent/node-ytdl-core#677]
### Before creating an issue, please try the following

version : "ytdl-core": "^3.2.0"

### Otherwise, feel free to open an issue

Include the following if your issue is a bug
```

    const video = ytdl(url, { filter: 'videoonly', quality: 'highestvideo' , preset: 'ultrafast' })
      .on('progress', (_, downloaded, total) => {
        tracker.video = { downloaded, total };
      });
```

This piece of code consumes 100% of the cpu and shows poor performance in downloading. A video with 3 mins goes up to 10 mins at 100% cpu of Intel Xeon W-2125 which is quite odd.

Any way I can limit the cpu and speed things up?

**Comment by fent** [comment]
`preset` is not a ytdl option, are you using another library with this option?

**Comment by hypo-thesis** [comment]
> `preset` is not a ytdl option, are you using another library with this option?

No I just added that from ctrl+space that it came up. I know this does nothing. I will edit my question if that is irrelevant.

**Comment by fent** [comment]
just checking.

>     const video = ytdl(url, { filter: 'videoonly', quality: 'highestvideo' , preset: 'ultrafast' })
>       .on('progress', (_, downloaded, total) => {
>         tracker.video = { downloaded, total };
>       });

anything else done with `video`? is it saved to a file? passed to discord/ffmpeg? part of your code looks like from the [ffmpeg example](https://github.com/fent/node-ytdl-core/blob/master/example/ffmpeg.js). if you're using ffmpeg, it will use up cpu when processing videos, and it will take more time than simply downloading.

otherwise, there was recently an update a few days ago that fixed slow speeds with `filter: 'audioonly'`. even though your `package.json` shows the latest version, are you using another library that has ytdl-core as a dependency? does `npm ls ytdl-core` show only one entry?

**Comment by hypo-thesis** [comment]
![ytdl](https://user-images.githubusercontent.com/28728305/88903447-66b23280-d25c-11ea-871c-a6a6e7bfdbf7.jpg)

Yes only the one version and nothing else is added.
It is saved to a file like this 

```
    audio.pipe(ffmpegProcess.stdio[3]);
    video.pipe(ffmpegProcess.stdio[4]);
    ffmpegProcess.stdio[5].pipe(fs.createWriteStream(`./${info.videoDetails.title}.mp4`))
```

Title being taken from `const info = await ytdl.getInfo(url)`

**Comment by TimeForANinja** [comment]
so you are using ffmpeg on the video
since it looks like you only wanna merge the two streams i hope changed to coding parameter to `-c copy` in the ffmpeg parameters (in the code that would be `'-c', 'copy'`)
if you keep using those `-c:a flac and -c:v libx265 -x265-params log-level=0` parameters it reencodes your video & audio which takes quite a lot of work since you fetch `highestvideo`

**Comment by nehege** [comment]
i think if you try this problem will be solved. Please notice us. 
```
      '-loglevel', '0', '-hide_banner',
      '-itsoffset', '3.0', '-i', 'pipe:3',
      '-i', 'pipe:4',
      '-c', 'copy',
      '-f', 'matroska', 'pipe:5',
    ], {
      windowsHide: true,
      stdio: [
        'inherit', 'inherit', 'inherit',
        'pipe', 'pipe', 'pipe',
      ],
```

**Comment by TimeForANinja** [comment]
not quite
* since you wanna save as mp4 we gotta change the `-f` flag
* if you don't want your audio/video to be out of sync you should remove that `-itsoffset`
```js
[
  '-loglevel', '0', '-hide_banner',
  '-i', 'pipe:3',
  '-i', 'pipe:4',
  '-c:', 'copy',
  '-f', 'mp4', 'pipe:5',
]
```

mb on using an example quite far away from reality

**Comment by fent** [comment]
> ```js
> ```js
> 
> ```
> 
> 
> mb on using an example quite far away from reality
> ```

maybe could use some comments on the ffmpeg options?

**Comment by hypo-thesis** [comment]
> not quite
> 
> * since you wanna save as mp4 we gotta change the `-f` flag
> * if you don't want your audio/video to be out of sync you should remove that `-itsoffset`
> 
> ```js
> [
>   '-loglevel', '0', '-hide_banner',
>   '-i', 'pipe:3',
>   '-i', 'pipe:4',
>   '-c:', 'copy',
>   '-f', 'mp4', 'pipe:5',
> ]
> ```
> 
> mb on using an example quite far away from reality

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:782:11)
    at Socket._write (net.js:794:8)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Socket.Writable.write (_stream_writable.js:303:10)
    at PassThrough.ondata (_stream_readable.js:712:22)
    at PassThrough.emit (events.js:315:20)
    at PassThrough.Readable.read (_stream_readable.js:512:10)
    at flow (_stream_readable.js:985:34)

I get this using `'-f', 'mp4', 'pipe:5',` but there seems to be no issue with` '-f', 'matroska', 'pipe:5',`

**Comment by TimeForANinja** [comment]
mp4 can't hold all encodings - that's why the reencoding breaks
so stick with `'-f', 'matroska', 'pipe:5'` but at least change your filename to end with `.mkv`

**Comment by hypo-thesis** [comment]
> mp4 can't hold all encodings - that's why the reencoding breaks
> so stick with `'-f', 'matroska', 'pipe:5'` but at least change your filename to end with `.mkv`

Yes sir. 

Thanks everyone basically I think I can close this issue now.
