### ISSUE TITLE
default best audio should be m4a

### ISSUE THREAD

**Issue by nagualcode** [fent/node-ytdl-core#680]
I believe default audio for best audio should be .m4a.
It is considered bad pratice to encode a lossy format to another. There is no need to perform mp3 compression from m4a, the youtube standard audio format, as most of the media player software can handle m4a audio.
Thank you.

**Comment by TimeForANinja** [comment]
no conversion between encodings is done in this library
youtube encoded both mp3 and m4a from the original video provided by the content creator
it doesn't matter which one you choose, it was only reencoded once by youtube

besides - the library should already [prefer mp4a](https://github.com/fent/node-ytdl-core/blob/master/lib/util.js#L6)

**Comment by nagualcode** [comment]
TIL youtube already provided a mp3 conversion.
Thank you.
