### ISSUE TITLE
The resources on the returned URL can't be found

### ISSUE THREAD

**Issue by winstonma** [fent/node-ytdl-core#682]
I deployed a [Netlify Function](https://www.netlify.com/products/functions/), purely using `ytdl-core`. This API just simply takes the youtube video ID and return the info of the best video (I only take the video URL). Here are the code:

```
const ytdl = require("ytdl-core");
 
/* export our lambda function as named "handler" export */
exports.handler = async (event, context) => {
  const videoID =
    event.queryStringParameters && event.queryStringParameters.videoID;

  return ytdl
    .getInfo(videoID)
    .then((info) => ({
      title: info.videoDetails.title,
      format: ytdl.chooseFormat(info.formats, { quality: "highest" }),
    }))
    .then((data) => ({
      statusCode: 200,
      headers: { "content-type": "application/json" },
      body: JSON.stringify(data),
    }))
    .catch((error) => ({
      statusCode: error.statusCode || 500,
      body: JSON.stringify({
        error: error.message,
      }),
    }));
};
```

The `video.format.url` returns the URL of the best video.

Example 1: Please run the following URL on the browser
https://5f2c22f110dbc800088c5b6b--goalaheadltd.netlify.app/.netlify/functions/getVideoDownloadURL?videoID=0ADQauuOJto
returns me the MP4 url. Then I pasted the `video.format.url` of the API response on the browser and I can watch the video in the browser.

However I just uploaded a video on youtube and tried to use the created API to get the Video URL: https://5f2c22f110dbc800088c5b6b--goalaheadltd.netlify.app/.netlify/functions/getVideoDownloadURL?videoID=MD0k4MbVEfc
I copied the URL onto the browser but it said the resources is not available (no video).

Thanks for the help.

**Comment by fent** [comment]
just tried those two urls and they both returned a working url from youtube. i'm guessing sometimes the video won't immediately work and you'll have to retry.

and keep in mind that some videos, such as livestreams, use a playlist file with links to segments of the video. if you go to that file, your browser will download the playlist, not the video. ytdl-core uses [m3u8stream](https://github.com/fent/node-m3u8stream) to download these.

**Comment by winstonma** [comment]
Thanks for the reply

I could confirm both videos are not livestream.

Also I just obtained the video URL from the second API call and paste it onto my browser, and I saw this
![image](https://user-images.githubusercontent.com/1215090/89594398-40a41800-d884-11ea-8874-6160d2b44a05.png).

In addition, when I tried the second API call on my PC it also returns a working URL, it returns a different and non-working URL once it is deployed.

**Comment by winstonma** [comment]
I just connect my PC with a US VPN and now I can play the Video.

Hmm... so is Youtube video region specific?

**Comment by fent** [comment]
> I just connect my PC with a US VPN and now I can play the Video. Hmm... so is Youtube video region specific?

download urls are limited to the same ip. I'm surprised sometimes it works, it shows that we don't understand the exact boundaries for these limits



> May I ask another question? Is it possible that I can put the `ytdl-core` on the browser side so the user would generate the video URL from their browser instead of making an API call from the server, which is in US?

it'll only work from an extension. otherwise, you'll get CORS errors.

**Comment by winstonma** [comment]
Thanks for the reply. If the API is IP specific then API calling method would not work for me.

Seems I need to go for the CORS way, are there any resource I can take a look?

**Comment by fent** [comment]
I have an extension that uses this library https://github.com/fent/chrome-veefeed

just make sure to add `youtube.com` to permissions in `manifest.json`

**Comment by winstonma** [comment]
Thanks @fent. I have a bit clearer picture of the Youtube API limitation.

For the CORS solution I will take a look

Thanks again for your time

**Comment by fent** [comment]
no problem!

feel free to close the issue if you have no more questions

**Comment by winstonma** [comment]
Reading [youtube.js](https://github.com/fent/chrome-veefeed/blob/master/background/sources/videos/youtube.js) but I am not really sure about how the code get though the CORS problem.

@fent I may need some light from you

**Comment by fent** [comment]
add permissions to `manifest.json`

**Comment by winstonma** [comment]
@fent I am still having CORS problem. And I am still confused.

### Background
I am building a website that need to grab the MP4 URL of the youtube video. Currently I setup an API function on my server and the browser would call the server and collect the MP4 URL. Because of the access problem mentioned above, I would like to put your code onto frontend, so the browser would directly ask youtube server (using ytdl-core) but I faced CORS problem.

I read your code and it is for Chrome addon, I am confused because in my project there is no `manifest.json` or something similar?

Would like to seek some light from you.
