### ISSUE TITLE
Error parsing info: Cookie header used in request but...

### ISSUE THREAD

**Issue by mh4ck** [fent/node-ytdl-core#684]
Hi, i'm trying to receive the video info with ".getInfo" and a cookie. 

I'm using the latest Chrome to browse a YouTube video.
Then i open the developer console, get my token by reading "document.cookie" via console.
Then i open the website source code and searching for "ID_TOKEN", get only 1 result (in <head> area) wich i copy. 

Then i use my test code to receive the info and get the error: 

```
Error: Error parsing info: Cookie header used in request, but unable to retrieve video metadata
    at exports.getBasicInfo (/Users/.../Documents/GitHub/yt2mp3-worker/node_modules/ytdl-core/lib/info.js:75:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Map.getOrSet (/Users/.../Documents/GitHub/yt2mp3-worker/node_modules/ytdl-core/lib/cache.js:24:19)
    at async exports.getInfo (/Users/.../Documents/GitHub/yt2mp3-worker/node_modules/ytdl-core/lib/info.js:216:14)
    at async Map.getOrSet (/Users/.../Documents/GitHub/yt2mp3-worker/node_modules/ytdl-core/lib/cache.js:24:19)
```

So my code (Censored my Cookie and ID_Token):

```
const ytdl = require("ytdl-core");
const cookieString = "APISID=xxxx; SAPISID=xxxx; __Secure-3PAPISID=xxxx; CONSENT=xxxx; wide=1; _gcl_au=xxx; PREF=al=xx&f6=80; SIDCC=xxxxx";
const idToken = "QUFFLUhqa0NO....VXVKb1pQbVVyOHNoQXw=";

ytdl.getInfo("https://www.youtube.com/watch?v=hbzSc-FiMF8", {
    requestOptions: {
        headers: {
            "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36", //Already tested with and without user agent - no changes to the error.
            cookie: cookieString,
            'x-youtube-identity-token': idToken
        }
    }
}).then((info) => {
    console.log(info.videoDetails.title);
}).catch((err) => {
    console.log(err);
}); 
``` 

I already added a console.log(body) to ytdl-core/lib/info.js to see what YouTube sends back.

The response body: 
```
{"reload":"now"}
```

**Forgot to add:** 
The same error appears for me by just using ytdl

```
const ytdl = require("ytdl-core");
const fs = require("fs");
const cookieString = "APISID=xxxx; SAPISID=xxxx; __Secure-3PAPISID=xxxx; CONSENT=xxxx; wide=1; _gcl_au=xxx; PREF=al=de&f6=80; SIDCC=xxxxx";
const idToken = "QUFFLUhqa0NO....VXVKb1pQbVVyOHNoQXw=";

let videoStream = fs.createWriteStream("video");

ytdl("https://www.youtube.com/watch?v=hbzSc-FiMF8", {
    requestOptions: {
        headers: {
            cookie: cookieString,
            'x-youtube-identity-token': idToken
        }
    }
}).pipe(videoStream)
```

**Comment by fent** [comment]
have you tried without adding `x-youtube-identity-token`?



> const cookieString = "APISID=xxxx; SAPISID=xxxx; __Secure-3PAPISID=xxxx; CONSENT=xxxx; wide=1; _gcl_au=xxx; PREF=al=de&f6=80; SIDCC=xxxxx";

do you pick out certain values to include in the cookie string? or pasting the entire string?

are you running the script in the same ip as your browser?

**Comment by mh4ck** [comment]
> have you tried without adding `x-youtube-identity-token`?
> 
> > const cookieString = "APISID=xxxx; SAPISID=xxxx; __Secure-3PAPISID=xxxx; CONSENT=xxxx; wide=1; _gcl_au=xxx; PREF=al=de&f6=80; SIDCC=xxxxx";
> 
> do you pick out certain values to include in the cookie string? or pasting the entire string?
> 
> are you running the script in the same ip as your browser?

It's the complete cookie like it is in Chrome haven't modified it. 

No haven't tried it without the idToken will try it and update it here. 

And no it's a different IP do you all use the same ip? 😅 That would be not possible for me i have a 'few' server where it runs.

**Comment by fent** [comment]
just tested with different IPs and it still worked for me. so that's not the issue.

**Comment by mh4ck** [comment]
Mh, can i ask where you from or which ips you tested? Maybe there are some features depending on the GEO that block the process. I tested Germany and Russia but with German language...

**Comment by fent** [comment]
I tested using VPNs in LA and NY

**Comment by mh4ck** [comment]
No changes if i login with firefox and use the cookie.

Do you have an idea which parts i can log to find a solution?
I'm completely out of ideas.

**Comment by mh4ck** [comment]
**Update:** 

Found the solution but not the reason. 
`document.cookie` prints a different cookie into the console but another cookie is sent to the get_video_info request.

**Comment by fent** [comment]
ah, I should update the instructions for getting cookie in the example

**Comment by WaqasIbrahim** [comment]
@fent Some `httponly` cookies are sent with the request which you can't read with `document.cookie`.

**Comment by fent** [comment]
> Found the solution but not the reason.
> `document.cookie` prints a different cookie into the console but another cookie is sent to the get_video_info request.
so does this work for you now? can the issue be closed?
