### ISSUE TITLE
Wrong information under ReadMe:Limitations

### ISSUE THREAD

**Issue by mh4ck** [fent/node-ytdl-core#687]
Hi, i just recognized that there is written: "**Generated download links are valid for 6 hours, for the same IP address.**" but they are also valid for any other IP Address. 

I'm using it that way that i request the videoInfo on one server which also handles my proxies (it requests the info with a proxy) and send it to other server which download it with their own IP. It works.

**Comment by fent** [comment]
yep, I've seen this work too. will change.
