### ISSUE TITLE
Domain restricted embed video

### ISSUE THREAD

**Issue by rubenbarreiro** [fent/node-ytdl-core#69]
Hello there, been using the module for a while and it's awesome so far, but now I hit a wall with the following:

While trying to get a video with explicit content the module does a workaround with an embed url, that's what I understand so far(please correct me if I'm wrong here) but then that video has a domain restriction so the embed strategy fails.

So I'm doing this(pretty normal)
1. `ytdl.getInfo(url ...`: no error here, and I got the video itags info and everything else
2. `ytdl(url ...`: `[Error: status code 403]`

This is the video https://www.youtube.com/watch?v=B3eAMGXFw1o (awful song btw) 

I tried some things like using `Referer` in the headers(like [here](http://stackoverflow.com/questions/13407482/youtube-embed-gives-restricted-from-playback-on-certain-sites-error-despite-ap#answer-35568163)), but no luck.

As far as I could see the `403` happens in `/videoplayback` request.      

If is there any more info I can provide please say so.

Thanks for your time.

PS: I'm running latest version `0.7.13` and just happens with the video above, I had not tested it with a video with similar configuration. I ran `mocha test` and all tests passed, just to see if I had some strange network setup

**Comment by fent** [comment]
Tried playing the video from https://www.youtube.com/embed/B3eAMGXFw1o and getting 403s in the Network tab. Could this be a temporary Youtube error?

Here's another age restricted video that works fine https://www.youtube.com/embed/otfd2UTrP_Q

**Comment by rubenbarreiro** [comment]
Hi there and thanks for your response.

I'm facing that problem from around a month so I don't think is network related. I'm able to load the player but when I try to play it this is what I got.

![screen shot 2016-03-31 at 6 33 59 pm](https://cloud.githubusercontent.com/assets/10094801/14186754/663b0812-f76f-11e5-8d9d-aa5bed960c08.png)

Now, the video you provided plays just fine.   

So the problem is the combination of: 
 - explicit content video which causes the module to have to use the embed url 
 - and the video being domain restricted for embed use

**Comment by fent** [comment]
Hmm, it doesn't work for me if I follow it from here :/

**Comment by rubenbarreiro** [comment]
ok, very weird. and if you try the w3schools link? does not work either?

**Comment by fent** [comment]
It doesn't work either with w3schools.

**Comment by rubenbarreiro** [comment]
well, just checked again and seems working for me.

![screen shot 2016-04-02 at 5 33 36 pm](https://cloud.githubusercontent.com/assets/10094801/14228008/2bd9f7a6-f8f9-11e5-8a8a-e2de92980ad0.png)

It will be very useful if someone else can try this too so we could make sure that the domain restriction thing is working

**Comment by Luke0129** [comment]
Its working just fine for me
![image](https://cloud.githubusercontent.com/assets/16747705/14249149/9c9a3f34-fa78-11e5-9b53-c59db2a5a2be.png)

**Comment by TimeForANinja** [comment]
think i found a fix... at least worked for this one video
all i did is i added `sts: '17186'` to the query params of the get_video_info url in https://github.com/fent/node-ytdl-core/blob/master/lib/info.js#L87
that variable can also be found in the yt.setConfig(Line10 for me) and also in the base.js(Line 6641 for me)
hope it also works for u...

**Comment by fent** [comment]
It does work for me! O_O

Thank you very much!
