### ISSUE TITLE
stream progress is incorrect when format is dash mdp 

### ISSUE THREAD

**Issue by monzer15** [fent/node-ytdl-core#691]
I tried to download a video with separate streams (video-only, audio-only), but the progress seems incorrect, it returns kb's size in both streams, then I tried getting the content length from HTTP request header also no luck, it returns the same thing

link:  https://www.youtube.com/watch?v=yeYiuUONO9I

any idea how to manage dash mpd formats content length?

**Comment by fent** [comment]
see https://github.com/fent/node-ytdl-core/issues/546#issuecomment-676827185

going to adjust readme to reflect this

**Comment by monzer15** [comment]
> see [#546 (comment)](https://github.com/fent/node-ytdl-core/issues/546#issuecomment-676827185)
> 
> going to adjust readme to reflect this

sorry I didn't see it until now, thank you
