### ISSUE TITLE
Is there a way to get VTT subtitles file?  

### ISSUE THREAD

**Issue by Aparus** [fent/node-ytdl-core#692]
I have seen this issue https://github.com/fent/node-ytdl-core/issues/245
And got files with captions... but they are all XML. 

![Screenshot from 2020-08-25 18-16-21](https://user-images.githubusercontent.com/1222611/91192878-229d3b00-e6ff-11ea-991c-e48f517584a4.png)

Python youtube-dl allows to list different formats of subtitles 
`youtube-dl --list-subs --skip-download https://www.youtube.com/watch?v=CEQTo9usai4`
```
Available subtitles for CEQTo9usai4:
Language formats
en       vtt, ttml, srv3, srv2, srv1
```
And by default downloads in VTT format:
`youtube-dl --write-subs --skip-download https://www.youtube.com/watch?v=CEQTo9usai4`

**Is there a way to get VTT file with node-ytdl-core?**

**Comment by fent** [comment]
check the [captions.js](https://github.com/fent/node-ytdl-core/blob/master/example/captions.js) example

**Comment by Aparus** [comment]
> check the [captions.js](https://github.com/fent/node-ytdl-core/blob/master/example/captions.js) example

I did! There is XML files, how I wrote above.

**Comment by fent** [comment]
I just updated the `captions.js` example. basically it adds `&fmt=vtt` to the url

**Comment by Aparus** [comment]
> I just updated the `captions.js` example. basically it adds `&fmt=vtt` to the url

It works. Thank you!!! :-)
