### ISSUE TITLE
How to transform function ytdl to async

### ISSUE THREAD

**Issue by dimeks** [fent/node-ytdl-core#698]
How to transform function ytdl to async ?

  ytdl(URL, {
    format: 'mp4'
    }).pipe(res);

**Comment by isuckatprogram** [comment]
probably create like a function that returns a promise and resolves the promise when done if you really want this.

**Comment by TimeForANinja** [comment]
ytdl in its current implementation is already asynchronous

besides that i am unable to come up with valid reasons to make ytdl an async function and return the whole downloaded file - that will probably end up in a memory exception and counter the elemental stream-driven design of nodejs
