### ISSUE TITLE
Error 429 & Error 402: How to change Network Interface

### ISSUE THREAD

**Issue by MJunghenn** [fent/node-ytdl-core#70]
Is there any possibility to change the outgoing IP/Net. Interface?

I hotfixed that by editing request.js - adding "parsed.localAddress = 'xxx:xxx:xxx:xxx';" above the get request.

**Comment by fent** [comment]
Options used to be passable to the request method, maybe that should come back.

https://github.com/fent/node-ytdl-core/tree/62231cfc351f6c144d7dba0009c5a0a139056bcf#ytdlurl-options
