### ISSUE TITLE
 ERROR TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by Niraj456** [fent/node-ytdl-core#701]
used in
`const fs = require('fs');
const ytdl = require('ytdl-core');

ytdl('http://www.youtube.com/watch?v=A02s8omM_hI')
  .pipe(fs.createWriteStream('video.mp4'));`

Error
![image](https://user-images.githubusercontent.com/60421503/92347443-b999c800-f0ed-11ea-929b-83879ce8ac92.png)

**Comment by fent** [comment]
stack trace is pointing to `home-home-module-es2015.js`, a compiled file
