### ISSUE TITLE
Error parsing info: Unexpected token < in JSON at position 5

### ISSUE THREAD

**Issue by meoyawn** [fent/node-ytdl-core#702]
Version: 3.2.2

Started getting this recently here:

https://github.com/fent/node-ytdl-core/blob/79f2be2c294f18c3bbfdfbb8ecc42b6582e646a3/lib/info.js#L62-L75

I see there's no status code check, so it might be a `5xx` html from the server

Retrying helps with it, but thinking a good error message might help here. Will we need to patch https://github.com/fent/node-miniget to achieve this?

Thanks

**Comment by fent** [comment]
miniget will throw if status code is not 4xx or 5xx

are you using a cookie? using ytdl-core in a browser?

**Comment by meoyawn** [comment]
oh, I get it now. I'm compiling for Cloudflare Workers and replaced `miniget` with a `fetch` based implementation

I see that `miniget` retries on `429` and `503`, will do the same

thanks much!
