### ISSUE TITLE
Getting CORS issue when integrating in ionic app integration

### ISSUE THREAD

**Issue by raviyadav5951** [fent/node-ytdl-core#703]
Integrated the ytdl-core into react component but when calling ytdl.getInfo. CORS issue is shown on console.

**Comment by fent** [comment]
ytdl-core gets CORS errors when used from a browser. not sure how ionic uses libraries, is there a setting for giving more permissions to some requests?

**Comment by raviyadav5951** [comment]
@fent ionic renders the app on webview.
![image](https://user-images.githubusercontent.com/8953891/92628025-d569bd80-f2e9-11ea-813f-30fb1cb8c2e6.png)

**Comment by fent** [comment]
@Simsalabina, @burhankaraman since you opened/commented on issue https://github.com/fent/node-ytdl-core/issues/336, did you run into any CORS issues?
