### ISSUE TITLE
Invalid URL: Undefined for specific format

### ISSUE THREAD

**Issue by sukovec** [fent/node-ytdl-core#704]
Hello. 

Calling ytdl with some video ends with error. Specifically it happens when trying to download some itags from [this video](https://www.youtube.com/watch?v=ZOFu0ySOuBk). I'm passing just URL and whole format object downloaded by getBasicInfo the default export function of this library. 

I'm using following code:
```
        console.log(`Calling yt(url, { format: format })`);
        console.log(`url = "${url}"`);
        console.log("format:", format);
        let str = yt(url, { format: format });

        str.on("error", (err) => { console.error("Error downloading from jutub:", err) });
```

Full output (with format json) can be found [here](https://nopaste.xyz/?6c7b5c61121422bc#3ASArPoNe2cmRgWDm8xFM9anYsvFTzTQhcLnXtdNTewy), stacktrace is here:
```
Error downloading from jutub: Error: Invalid URL: undefined
    at doDownload (/home/suk/proj/avc-web-meter/node_modules/miniget/dist/index.js:108:34)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

```

```
$ npm ls ytdl-core
avc-web-meter@1.0.0 /home/suk/proj/avc-web-meter
└── ytdl-core@3.2.2

$ node --version
v14.9.0
```

**Comment by fent** [comment]
you'll have to call `getInfo` and not `getBasicInfo` if you intend to use formats to download

**Comment by sukovec** [comment]
True, thanks. I expected that the only "itag" could be necessary for this. Now it works.
