### ISSUE TITLE
I don't need a stream (Questions regarding chunked loading)

### ISSUE THREAD

**Issue by max-scopp** [fent/node-ytdl-core#706]
Hi, great library.

I'm sorting a youtube link by certain criterias:

```js
  getBestTrack(info: ytdl.videoInfo) {
    const audioFormats = ytdl.filterFormats(info.formats, 'audio');

    const candidates = ytdl.filterFormats(audioFormats, (format) => {
      const notLowAudio = format.audioQuality !== "AUDIO_QUALITY_LOW";
      const notMono = format.audioChannels > 1;
      return notMono && notLowAudio;
    });

    const prioritizedCandidates = candidates.sort((a, b) => {
      const aSample = parseInt(a.audioSampleRate, 10);
      const bSample = parseInt(b.audioSampleRate, 10);
      return (aSample > bSample) ? 1 : 0
    });

    const [bestMatch] = prioritizedCandidates;

    return bestMatch;
  }
```

Which will result in one `videoFormat`.
Eventually, I'm reading the `url` property and create my own stream.

If I use that URL in my browser, I can listen to the whole song.
However, if I'm using the exact same link for discord to stream, it does not fully stream the song.

If I look into [this file](https://github.com/fent/node-ytdl-core/blob/6b051d81e06041d918569d1fa020007f524b3265/lib/index.js#L133) I see that internally there is some logic to apply the chunking, using the header `Range`.

Can you elaborate how the logic works/is intended?
Is this a restriction from youtube itself?
Can I set a complete Range of the song and therefor avoid the chunked loading?

**Comment by TimeForANinja** [comment]
> Can you elaborate how the logic works/is intended?

[you can set a start and optional end range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range)
if youtube ends a request before we got the full file we just do another request with the range starting where the previous request stopped

> Is this a restriction from youtube itself?

most webservers end sockets that are open for too long

> Can I set a complete Range of the song and therefor avoid the chunked loading?

setting no range is the same as setting a complete range
you ether need to read faster from youtube (and therefor cache a lot of data) or use range to chunk the requests
chunking requests on the other side may result in being rate limited
