### ISSUE TITLE
song is being skipped

### ISSUE THREAD

**Issue by IslandRhythms** [fent/node-ytdl-core#710]
Hello,
I recently moved my bot from my machine to a raspberry pi 3b+. However there is a very annoying error that is specific to the raspberry pi. When I use the play command and run this function which is called from an async function, 

```
function play(guild, song) {
console.log(song);
  const serverQueue = queue.get(guild.id);
  if (!song) {
    serverQueue.voiceChannel.leave();
    queue.delete(guild.id);
    return;
  }
  const dispatcher = serverQueue.connection
    .play(
      ytdl(song.url, {
        quality: "highestaudio",
        highWaterMark: 1 << 25,
        filter: "audioonly",
      })
    )
    .on("finish", () => {
      if (!queue.repeat) serverQueue.songs.shift();
      if (queue.continue && serverQueue.songs.length === 0)
        serverQueue.songs.push(serverQueue.backup);
      play(guild, serverQueue.songs[0]);
    })
    .on("error", (error) => console.error(error));
  dispatcher.setVolumeLogarithmic(serverQueue.volume / 5);
  serverQueue.textChannel.send(`Start playing: **${song.title}**`);
}
```

the bot calls it again without having played a song. I know this is specific to the raspberry pi because on my local machine when I test it I do not have this problem. The console log will show the details of the song and then the next print will be an undefined which is when the bot has left already. I am receiving no error messages what so ever. The bot will show the Start playing message however.

Please let me know if you need to see more code.

**Comment by fent** [comment]
does the `finish` event fire on the first song? does the 2nd song play fine?

**Comment by IslandRhythms** [comment]
it skips everything. I think it might be a binding issue with opus so I think ytdl isn't the problem

**Comment by ixfloma** [comment]
this is probably audio encoding problem, the audio library (like opus) didn't recognize any audio in stream, there's certain youtube video that do something like this. try by creating actual file with mp4 extensions and read it to play
