### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by fbagjug** [fent/node-ytdl-core#714]
Hello, I'm experiencing an issue that has come from nowhere and randomly started happening, I'm currently on ytdl-core 3.3.0.

This is the error: 
```
TypeError: Cannot read property 'full' of undefined
    at Function.ytdl.downloadFromInfo (D:\jsbotgit\jsbot\node_modules\ytdl-core\lib\index.js:199:13)
    at play (D:\jsbotgit\jsbot\app.js:2322:61)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
It says on line 2322 which is `const dispatcher = connection.play(ytdl.downloadFromInfo(songInfo, {begin: begin}));`
`begin` is a parameter which is by default set to 0. I'm not too sure why or where this error has randomly come from.

**Comment by fent** [comment]
make sure `songInfo` is defined

**Comment by fbagjug** [comment]
`songInfo` is set from song.info which uses `await ytdl.getInfo(ytlink);`

**Comment by fbagjug** [comment]
Never mind, I found it. Thanks anyways :D
