### ISSUE TITLE
filter. audio vs audioonly

### ISSUE THREAD

**Issue by m-ilk** [fent/node-ytdl-core#715]
hey fent,
    i have a question about filter. what is the difference between audio and audioonly? 
    is it gonna affect the download speed?
    is audioonly file size smaller than audio file?

**Comment by Roki100** [comment]
audio selects a format that __includes__ audio, and audioonly selects a format that has only audio w/o video, and no it should not affect download speed as chunking exist.
Audioonly file should be smaller than audio file that includes video

**Comment by m-ilk** [comment]
@Roki100  thanks! i tried to download a few videos using audio and audioonly. the file size are significant smaller when using audioonly. however, the download time took way much longer. it took approximate  10 times longer to download the exact same video. do you know the reason why it took longer to download?

**Comment by fent** [comment]
download speeds for audioonly were recently fixed. make sure you're on latest.
