### ISSUE TITLE
Player Config not found every so often

### ISSUE THREAD

**Issue by fbagjug** [fent/node-ytdl-core#716]
Hello, I'm on the latest version of YTDL-Core which is v3.3.0. I have saw other people open issues about this but my issue isn't exactly the same, my issue is that randomly it will say "Player config not found" but if I re-request it then it works fine. The fact it doesn't have a consistency makes it more annoying and harder to debug, just wondering if anyone researched this?

**Comment by WeebHiroyuki** [comment]
I can reproduce this issue.

**Comment by fent** [comment]
any videos this happens on?

**Comment by WaqasIbrahim** [comment]
https://www.youtube.com/watch?v=8qu2TOR0b_o
https://www.youtube.com/watch?v=EUq-tNlCo7s
https://www.youtube.com/watch?v=IPX5U5iprTA
https://www.youtube.com/watch?v=K5yRqt8QFcI
https://www.youtube.com/watch?v=f3Lmx2Atkuo

All of these are music videos btw.

**Comment by WeebHiroyuki** [comment]
For me, it just happened randomly.

**Comment by fbagjug** [comment]
> any videos this happens on?

Sorry for the late reply, when I was debugging this for you I got limited by the 429 error so had to wait. But for me it seems random. It had happened a few times on the same song but just then I tried to play it again and it was fine for me so yeah it's just random.
