### ISSUE TITLE
 TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-disposition"]

### ISSUE THREAD

**Issue by dimeks** [fent/node-ytdl-core#718]
i tryind download this video https://www.youtube.com/watch?v=gdZLi9oWNZg and i get the error TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-disposition"]

my code

res.header('Content-Disposition', attachment; filename=${info.videoDetails.title}.mp3);

**Comment by fent** [comment]
sorry but this is unrelated to ytdl-core, so closing.

but the error has to do with the string passed to the header.

**Comment by HemKal** [comment]
You need to implement this

`encodeURI(info.player_response.videoDetails.title);`
