### ISSUE TITLE
[Error: could not find `player config`]

### ISSUE THREAD

**Issue by MJunghenn** [fent/node-ytdl-core#72]
This comes up on downloading: 

[Error: could not find `player config`]

ExampleID: ybFAS3LUXIo
Another one: eEWYwQR9jPE

**Comment by MJunghenn** [comment]
It's because the video is blocked by GEMA or deleted by user..

**Comment by fent** [comment]
Seems to be happening with age restricted videos.

**Comment by fent** [comment]
Yeah, something in the embed page changed, has been fixed.
