### ISSUE TITLE
Bug: Error during playback

### ISSUE THREAD

**Issue by bartixen** [fent/node-ytdl-core#720]
Describe the bug
`The error is that everything works great on my computer, but on vps I get this error with the song, e.g. https://www.youtube.com/watch?v=SXFS1-BEtaQ The problem is with ytdl-core and ytdl-core-discord`

Works on: `VPS` | `1 CORE` | `2 GB RAM`

Node.js version: `v12.19.0`

Debian version: `4.9.228-1`

Additional information & screenshots
![95331501-6365a380-08aa-11eb-9b69-4feef6851255](https://user-images.githubusercontent.com/48735544/95429312-7fb91d00-094a-11eb-8b1d-3bf7e1635e2e.png)

**Comment by Asaduji** [comment]
This is not ytdl-core related, open an issue at https://github.com/amishshah/ytdl-core-discord instead

**Comment by fent** [comment]
hmm, I looked [`ytdl-core-discord/index.js`](https://github.com/amishshah/ytdl-core-discord/blob/5471076dc217dfdc10dc0991ceea8ecec2359fee/index.js), it will throw this when it finds no audio formats. I don't know how that would happen though, the above video works for me locally and has several audio formats. can you add more logging to narrow this down in case it's a ytdl-core bug? logging for the video id and `info.formats` would be good.

**Comment by bartixen** [comment]
For me, everything works locally only on vps no. It cannot be the fault  of ytdl-core only ffmpeg, which does not want to play in a given format, I think and I will add that in all the bots I tested there is this error with some movies, so something may not be installed on vps

**Comment by dylanjames-js** [comment]
I’m having the same issue and the ytdl-core-discord repo has been deleted :(

**Comment by fent** [comment]
since this is support for another library, and that library is no longer supported (i'm assuming), closing
