### ISSUE TITLE
Await ytdl.getInfo

### ISSUE THREAD

**Issue by Marly212** [fent/node-ytdl-core#721]
Hey Guys,

I have a Question that i dont Understand.

![grafik](https://user-images.githubusercontent.com/42452096/95438525-b1d07c00-0956-11eb-8085-e2a9a3abaebc.png)

Thats the way I call my own Function and pass the url.

![grafik](https://user-images.githubusercontent.com/42452096/95438858-286d7980-0957-11eb-85ed-da252afbe6ec.png)

And here is the beginning of the Download Function, as you can see at the bottom Iam getting the videoInfo with ytdl.getInfo.
Its all working and iam getting the Info, but my Problem is when its at the ytdl.getInfo Point it starts the function, skippes to the end of the YTDownload function (myOwn), goes on with the rest of the Code and THEN jumps back into the Info function where I get my Title.

I tried to understand how async, await and Promise works and i thought i got the Hang of it but I dont understand it.

How can I tell my Programm to await the ytdl.getInfo(url) function before doing other stuff?

**Comment by fent** [comment]
call your function with `await`

```js
await YTDownload(url)
```

you can also `await` the call to `ytdl.getInfo`

**Comment by Marly212** [comment]
> 
> 
> call your function with `await`
> 
> ```js
> await YTDownload(url)
> ```
> 
> you can also `await` the call to `ytdl.getInfo`

Hey,

i tried to await the call to ytdl.getInfo(url)

![grafik](https://user-images.githubusercontent.com/42452096/95453021-70e26280-096a-11eb-8190-1b970b176326.png)

![grafik](https://user-images.githubusercontent.com/42452096/95453071-8192d880-096a-11eb-8256-89c542cc4465.png)

But Iam getting this error

**Comment by TimeForANinja** [comment]
yep, you can only await async functions 😉 

a few more tips:
* calling validateID after getVideoID makes no real sense
* for usecases like this im a big fan of doing the following:
  * call ytdl.getInfo and wait for its response
  * take the title or other information you need
  * then use [https://github.com/fent/node-ytdl-core#ytdldownloadfrominfoinfo-options](ytdl.downloadFromInfo) with the information you gained from ytdl.getInfo
since the default ytdl(id) method already does a call to getInfo you lower your requests to youtube
alternative would be to use the info event which gets emitted by the stream from ytdl(id)

**Comment by Marly212** [comment]
> 
> 
> yep, you can only await async functions 😉
> 
> a few more tips:
> 
>     * calling validateID after getVideoID makes no real sense
> 
>     * for usecases like this im a big fan of doing the following:
>       
>       * call ytdl.getInfo and wait for its response
>       * take the title or other information you need
>       * then use [https://github.com/fent/node-ytdl-core#ytdldownloadfrominfoinfo-options](ytdl.downloadFromInfo) with the information you gained from ytdl.getInfo
>         since the default ytdl(id) method already does a call to getInfo you lower your requests to youtube
>         alternative would be to use the info event which gets emitted by the stream from ytdl(id)

Hey,
thanks for the Tips.

I made a little test Programm for you to help me understand what I am doing wrong:

![grafik](https://user-images.githubusercontent.com/42452096/95465466-785e3780-097b-11eb-966b-831e35a26fca.png)


![grafik](https://user-images.githubusercontent.com/42452096/95465483-7eecaf00-097b-11eb-9d54-fdf782109e49.png)

The first Picture shows my test.js Programm where I simply call my YTDownload function.
My Programm runs like the Numbers are showing:
1. First it calls the Download Function with the Link (I used the first Link I found)
2. Then it "starts" the getInfo function which is awaited
3. Then it jumps back and logs "Skipped"
4. After 3-4 seks its jumps into the respons and gets me the Title.

**Comment by TimeForANinja** [comment]
that step 3 is what it's supposed to do
since ytdl waits for its request to reach youtube and be answered nodejs continues executing code that's below

**Comment by Marly212** [comment]
Ok so I need to look into nodejs more, thanks for the help.

**Comment by Marly212** [comment]
> 
> 
> yep, you can only await async functions 😉
> 
> a few more tips:
> 
>     * calling validateID after getVideoID makes no real sense
> 
>     * for usecases like this im a big fan of doing the following:
>       
>       * call ytdl.getInfo and wait for its response
>       * take the title or other information you need
>       * then use [https://github.com/fent/node-ytdl-core#ytdldownloadfrominfoinfo-options](ytdl.downloadFromInfo) with the information you gained from ytdl.getInfo
>         since the default ytdl(id) method already does a call to getInfo you lower your requests to youtube
>         alternative would be to use the info event which gets emitted by the stream from ytdl(id)

Hey,
Iam sorry to bother you again but do I just need to pass the "info" which I get from ytdl.getInfo into the ytdl.downloadFromInfo?

**Comment by TimeForANinja** [comment]
From the README :

__ytdl.downloadFromInfo(info, options)__
Once you have received metadata from a video with the ytdl.getInfo function, you may pass that information along with other options to this function.

**Comment by Marly212** [comment]
So I pass the Information in downloadFromInfo with my Options and then? 
My Question is what I need to do after I pass the Information because this alone isn't Downloading the File.

**Comment by TimeForANinja** [comment]
`ytdl.downloadFromInfo(xxx)` returns a stream identical to `ytdl(xxx)`
so you can do sth like this
```js
const fs = require('fs');
const ytdl = require('ytdl-core');
const info = await ytdl.getInfo(url);
const stream = ytdl.downloadFromInfo(info);
stream.pipe(fs.createWriteStream('out.mp4'));
```

**Comment by Marly212** [comment]
Can I write the file as an mp3 file? Is it an mp3 file then? 
Or do I need to convert the mp4 file to an mp3 file with the help of FFmpeg?

**Comment by TimeForANinja** [comment]
the object in info should contain the mime-type 😉

**Comment by mr-tiwari-ji** [comment]
I created this function - 

  async function downloadYouTube(ytLink){
    console.log(ytLink)
    const videoInfo = await ytdl.getInfo(ytLink);
    console.log(videoInfo)
    const audioFormat = ytdl.chooseFormat(videoInfo.formats, { filter: 'audioonly' });
    console.log(audioFormat)
  
    if (!audioFormat) {
      throw new Error('No audio format found for the video.');
    }
  
    const audioPath = `../music/tmp/${videoInfo.videoDetails.title}.mp3`;
  
    if (fs.existsSync(audioPath) && !promptExistsAction()) {
      return null;
    }
  
    const audioStream = ytdl(ytLink, { quality: audioFormat.itag });
  
    return new Promise((resolve, reject) => {
      audioStream.pipe(fs.createWriteStream(audioPath));
      audioStream.on('end', () => resolve(audioPath));
      audioStream.on('error', reject);
    });
  };


when i run this i am getting error - 
Console --> 
https://www.youtube.com/watch?v=0mCVpUDCkEk
(1/1) Downloading 'Shubh - Still Rollin'...
https://www.youtube.com/watch?v=0mCVpUDCkEk
evalmachine.<anonymous>:426
Ama=function(a,b,c,d){var e=null;switch(b){case "JSON":try{var f=c.responseText}catch(h){throw d=Error("Error reading responseText"),d.params=a,oC(d),h;}a=c.getResponseHeader("Content-Type")||"";f&&0<=a.indexOf("json")&&(")]};Ila(ncode);
                                                                                                                                                       
                                                                      ^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at new Script (node:vm:94:7)
    at exports.decipherFormats (C:\Users\OneDrive\Documents\ Full Project\ Music Library\node_modules\ytdl-core\lib\sig.js:116:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async exports.getInfo (C:\Users\OneDrive\Documents\ Project\ Music Library\node_modules\ytdl-core\lib\info.js:401:17)
