### ISSUE TITLE
how to download mp3 using ffmpeg-static

### ISSUE THREAD

**Issue by hypo-thesis** [fent/node-ytdl-core#722]
I see in the sample the author has used 'ffmpeg-fluent' to download mp3 but I was wondering if there is any way to use 'ffmpeg-static' that is already used for high quality videos to be used as a means to download or convert to mp3.

If you give a short sample code I can follow and modify.

**Comment by TimeForANinja** [comment]
check the ffmpeg example 😉 

besides that ffmpeg-static and fluent-ffmpeg serve different purposes
ffmpeg-static provides the ffmpeg binairy while fluent-ffmpeg tries to provide an interface to the binairy inside the nodejs language
