### ISSUE TITLE
Header option 

### ISSUE THREAD

**Issue by fdciabdul** [fent/node-ytdl-core#724]
how to use header option like

'x-youtube-client-version': '2.20180222'
'x-youtube-client-name': '1',
'x-client-data': '' 

or pobably custom User-Agent ?

i was try like this one 
```javascript
ytdl.getInfo(url , 
      { requestOptions: {
      headers: {
      'cookie': cookie,
      'x-youtube-client-version': '2.20180222',
      'x-youtube-client-name': '1',
      'x-client-data': '' 
    },
  },
})
```

but that's error , or something wrong ?

**Comment by fent** [comment]
that looks good. what was the error?

**Comment by fdciabdul** [comment]
> that looks good. what was the error?

oof , apparently i forgot bout the commas xD
