### ISSUE TITLE
"Unexpected token ) in JSON" for some videos

### ISSUE THREAD

**Issue by WaqasIbrahim** [fent/node-ytdl-core#727]
For some videos `jsonEndpointURL` returns this response.

```
)]}'
{"reload":"now"}
```

**Comment by fent** [comment]
can you post the videos where this happens? and does it happen consistently with those videos or only sometimes?

**Comment by WaqasIbrahim** [comment]
> can you post the videos where this happens? and does it happen consistently with those videos or only sometimes?

I tested this a bit yesterday and it just happens randomly, there are no specific videos.

**Comment by WaqasIbrahim** [comment]
@fent This fix creates another problem. I already tested it. Now getting this error: Error parsing info: Cookie header used in request, but unable to find YouTube identity token
```js
let match = watchPageBody.match(/(["'])ID_TOKEN\1[:,]\s?"([^"]+)"/);
```
This match is not working.

**Comment by fent** [comment]
> **Update**: I have examined the source of `watchPageBody` and there is no `ID_TOKEN`.
> 
> **Update 2**: `watchPageBody` source has all the video data, we should not just rely on json endpoint. There should be a fallback to the old method. [youtube-dl](https://github.com/ytdl-org/youtube-dl) still uses old extraction method.

yeah... might be worth to go back, or at least fall back in case of cookies
