### ISSUE TITLE
Errors not bubbling correctly

### ISSUE THREAD

**Issue by MikeDev96** [fent/node-ytdl-core#730]
Some errors never make it out of ytdl.

I've tried wrapping the ytdl() call in a try/catch & I've tried adding an error event to the stream, neither of which fire.

The particular errors in these issues are uncatchable: https://github.com/fent/node-ytdl-core/issues/729 & https://github.com/fent/node-ytdl-core/issues/727

**Comment by fent** [comment]
`ytdl()` returns a stream, not a promise. so any errors can't be captured with a `try catch`. adding a listener to the `error` event should do it. how are you adding it?

make sure to not add it to another stream accidentally like in the example below, a pattern i've seen before

```js
ytdl(id).pipe(fs.createWriteStream('output.mp4')).on('error', err => {
  // this listens on the write stream, not on the ytdl stream
});
```

**Comment by MikeDev96** [comment]
Never mind, it's an issue with discord-ytdl-core. This is why I shouldn't code at 1am. Sorry for wasting your time.
