### ISSUE TITLE
Problems with ytdl-core

### ISSUE THREAD

**Issue by DavidsonVeniali** [fent/node-ytdl-core#731]
I'm using ytdl-core for a bot on Discord and all the videos that put so much to play the music receive this error in the terminal:

![discord](https://user-images.githubusercontent.com/49105234/96354052-6d588500-10a8-11eb-9985-b3438bf4d5f9.png)

Can you help me?

**Comment by fent** [comment]
there's a `ReferenceError` there. is that the issue?

**Comment by kira0x1** [comment]
I only get this occasionally and when I check the link provided, either the video is removed or its restricted by country.
So make sure your links work first.

**Comment by dragonDScript** [comment]
This is a typo. connection is the correct variable

**Comment by dragonDScript** [comment]
Oh, and this (YTDL) will be deprecated soon due to legal reasons, but there are other packages available.

**Comment by TimeForANinja** [comment]
> Oh, and this (YTDL) will be deprecated soon due to legal reasons, but there are other packages available.

boy you know sth even the devs don't know

**Comment by wolf-yuan-6115** [comment]
> Oh, and this (YTDL) will be deprecated soon due to legal reasons, but there are other packages available.

no

**Comment by Hazmi35** [comment]
> Oh, and this (YTDL) will be deprecated soon due to legal reasons, but there are other packages available.

that's youtube-dl, and it's actually reinstated, proof: https://github.com/ytdl-org/youtube-dl and https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/, and, ytdl-core with youtube-dl it's not that related, I'm not saying it's impossible, though
