### ISSUE TITLE
Seeking issue in mp4 format

### ISSUE THREAD

**Issue by hypo-thesis** [fent/node-ytdl-core#733]
I got some seeking issues with the converted file. my FFMPG settings are :  

```
const ffmpegProcess = cp.spawn(ffmpeg, [
                '-loglevel', '0', '-hide_banner',
                '-progress', 'pipe:3',
                '-itsoffset', '0.0', '-i', 'pipe:4',
                '-i', 'pipe:5',
                '-c:v', 'libx265', '-crf', '16' , '-c', 'copy',
                '-f', 'matroska', 'pipe:6',
            ], {
                windowsHide: true,
                stdio: [
                    /* Standard: stdin, stdout, stderr */
                    'inherit', 'inherit', 'inherit',
                    /* Custom: pipe:3, pipe:4, pipe:5, pipe:6 */
                    'pipe', 'pipe', 'pipe', 'pipe',
                ],
```

When I change to `'-c:a' `I still have the same issue. `'-crf' '24`' and `'18'` also makes the same problem for me. How do I handle the seeking issue?

edit: I just checked .mkv and that one is not seekable as well.

**Comment by TimeForANinja** [comment]
🤔 looks more like a ffmpeg-parameter issue than a ytdl-core problem
the stderr looks normal?

**Comment by fent** [comment]
> 🤔 looks more like a ffmpeg-parameter issue than a ytdl-core problem

even so, these parameters look like they were copied from the ffmpeg example

**Comment by hypo-thesis** [comment]
> > 🤔 looks more like a ffmpeg-parameter issue than a ytdl-core problem
> 
> even so, these parameters look like they were copied from the ffmpeg example

They are from the example. I do not know why I cannot seek through any of the downloaded videos. I have to check stderr and get back to you guys.

**Comment by hypo-thesis** [comment]
I changed the code the example as is and I cannot seek with the example either. 

```
ffmpegProcess = cp.spawn(ffmpeg, [
  // Remove ffmpeg's console spamming
  '-loglevel', '0', '-hide_banner',
  // Redirect/enable progress messages
  '-progress', 'pipe:3',
  // 3 second audio offset
  '-itsoffset', '3.0', '-i', 'pipe:4',
  '-i', 'pipe:5',
  // Rescale the video
  '-vf', 'scale=320:240',
  // Choose some fancy codes
  '-c:v', 'libx265', '-x265-params', 'log-level=0',
  '-c:a', 'flac',
  // Define output container
  '-f', 'matroska', 'pipe:6',
```

my FFmpeg version is : _ffmpeg version 4.3-2~18.04

libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100_

Can someone check the example for me? I think Youtube is acting up? I am not sure how to bring the seeking back as I tried it on multiple devices and computers.

**Comment by hypo-thesis** [comment]
```
ffmpeg version 4.3.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'pipe:4':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    creation_time   : 2020-01-14T10:10:18.000000Z
  Duration: 00:00:59.98, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 21 kb/s (default)
    Metadata:
      creation_time   : 2020-01-14T10:10:18.000000Z
      handler_name    : ISO Media file produced by Google Inc.
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'pipe:5':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6avc1mp41
    creation_time   : 2020-01-14T10:10:34.000000Z
  Duration: 00:00:59.92, start: 0.000000, bitrate: N/A
    Stream #1:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 46 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2020-01-14T10:10:34.000000Z
      handler_name    : ISO Media file produced by Google Inc.
Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 0, only the last option '-c copy' will be used.
Output #0, matroska, to 'pipe:6':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    encoder         : Lavf58.45.100
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 46 kb/s, 25 fps, 25 tbr, 1k tbn, 12800 tbc (default)
    Metadata:
      creation_time   : 2020-01-14T10:10:34.000000Z
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(eng): Audio: aac (LC) ([255][0][0][0] / 0x00FF), 44100 Hz, stereo, fltp, 21 kb/s (default)
    Metadata:
      creation_time   : 2020-01-14T10:10:18.000000Z
      handler_name    : ISO Media file produced by Google Inc.
Stream mapping:
  Stream #1:0 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5fab9c0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5f9dc80] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
frame=  225 fps=0.0 q=-1.0 size=     961kB time=00:00:08.92 bitrate= 882.4kbits/frame=  454 fps=449 q=-1.0 size=    1897kB time=00:00:18.08 bitrate= 859.4kbits/frame=  678 fps=447 q=-1.0 size=    3004kB time=00:00:27.05 bitrate= 909.6kbits/frame=  906 fps=449 q=-1.0 size=    3919kB time=00:00:36.16 bitrate= 887.9kbits/frame= 1135 fps=450 q=-1.0 size=    4432kB time=00:00:45.32 bitrate= 801.1kbits/frame= 1359 fps=448 q=-1.0 size=    4781kB time=00:00:54.28 bitrate= 721.5kbits/frame= 1498 fps=450 q=-1.0 Lsize=    5191kB time=00:00:59.95 bitrate= 709.3kbits/s speed=  18x    
video:4223kB audio:937kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.606663%
done

```

the complete log.

**Comment by hypo-thesis** [comment]
_General
Complete name                            : F:\ONE MINUTE OF PURE SATISFACTION   Compilation 1135_3.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso6/iso2/avc1/mp41)
File size                                : 2.93 MiB
Duration                                 : 59 s 981 ms
Overall bit rate                         : 410 kb/s
Writing application                      : Lavf58.45.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 3 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 59 s 920 ms
Bit rate                                 : 309 kb/s
Width                                    : 854 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.030
Stream size                              : 2.21 MiB (75%)
Title                                    : ISO Media file produced by Google Inc.
Writing library                          : x264 core 155 r2901 7d0ff22
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : Opus
Codec ID                                 : Opus
Duration                                 : 59 s 981 ms
Bit rate                                 : 97.4 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 713 KiB (24%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1_


Video data which is not seekable.

**Comment by hypo-thesis** [comment]
I used the following settings to overcome this:

`'-c:v', 'libx265', '-crf', '18', '-c', 'copy' , '-movflags', 'frag_keyframe+empty_moov', `
`  '-f', 'mp4', 'pipe:5',`

mp4 was not seekable without these tag.

**Comment by TimeForANinja** [comment]
Might be worth updating the example
You agree @fent?

**Comment by fent** [comment]
yeah. but it'd be nice if i could find documentation for these options >_<

https://ffmpeg.org/ffmpeg.html

**Comment by TimeForANinja** [comment]
it's a container option: https://ffmpeg.org/ffmpeg-formats.html#Options-9

**Comment by TimeForANinja** [comment]
on the other side...
i just ran the example as-is and i am able to seek the out.mkv using vlc

**Comment by fent** [comment]
how about the `'-crf', '18'` option?

**Comment by TimeForANinja** [comment]
thats just a quality setting
shouldn't change keyframes but lemme try

**Comment by TimeForANinja** [comment]
did remove that rescale `'-vf', 'scale=320:240',` and added the `'-crf', '18',`
boy cpu-based h265 is slow...
20 min encoding for 1min 40sec of video
but even thou the encode is not finished i can already seek with vlc just fine

@hypo-thesis what was your filename / extension
