### ISSUE TITLE
Could not find player config

### ISSUE THREAD

**Issue by jennasisis** [fent/node-ytdl-core#735]
Hello, after a few songs being played, I will occasionally get this error.

- If you're getting a specific error message, include the full stack trace

![image](https://user-images.githubusercontent.com/26691026/96823249-10d3cd80-13fa-11eb-935d-a6bcc2a9e4eb.png)

- Include any relevant code around ytdl-core. You don't have to upload your entire program, small snippets are fine.

All I am doing is just the standard `ytdl(url)` and piping the stream into a discord bot.

I've tried to attach an `error` listener to the ytdl stream that is returned from `ytdl(url)`, but that does not seem to catch it. What's interesting is that the error message says it's an unhandled rejection, yet the documentation doesn't indicate that what is being returned is a Promise. Should I use `ytdl(url).catch()` instead?

**Comment by fent** [comment]
`ytdl()` returns a stream, not a promise. it's weird that it says unhandled rejection, although it does use promises within and attempts to catch any errors and export them using the `error` event.

how is the `error` listener attached?

**Comment by jennasisis** [comment]
(pardon the formatting as i am currently on mobile)

```js
const stream = ytdl(url);

// ReadableStream has the error event, right? I listen to it here
stream.on('error', console.error);
```

**Comment by fent** [comment]
so I added this line to `getInfo` in  `lib/info.js`

```js
  throw Error('an errors that is always thrown');
```

then ran the following
```js
const video = ytdl(url);
video.on('error', err => {
  console.log('caught!');
});
```

and when ran, it does print "caught!"

**Comment by OORDINARY12** [comment]
happen with me too

**Comment by BlazeIsClone** [comment]
Im getting the same error as well randomly.  `error: Could not find player config`
But after a minute the code starts working again.

**Comment by jennasisis** [comment]
>```throw Error('an errors that is always thrown');```

This [throws](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw) an unhandled exception, not an uncaught rejection, which is the error I was getting.
Either way it seems you have fixed it in the commit. Thanks :)
