### ISSUE TITLE
Error parsing info: Cookie header used in request, but unable to find YouTube identity token

### ISSUE THREAD

**Issue by alansyahdwi** [fent/node-ytdl-core#737]
I got this error when playing a song after update ytdl-core to latest version. It happened randomly.

![Screenshot_377](https://user-images.githubusercontent.com/63584768/96836192-d22c2a80-146e-11eb-9d06-aae714b005dd.png)

**Comment by fent** [comment]
dupe https://github.com/fent/node-ytdl-core/issues/736
