### ISSUE TITLE
Input Stream: This video is unavailable

### ISSUE THREAD

**Issue by OORDINARY12** [fent/node-ytdl-core#739]
happend when searching vidode's title

`Error: input stream: This video is unavailable

    at downloadFromInfoCallback (C:\Users\Administrator\Desktop\dc\node_modules\ytdl-core\lib\index.js:76:26)

    at C:\Users\Administrator\Desktop\dc\node_modules\ytdl-core\lib\index.js:18:5

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (internal/process/task_queues.js:97:5)
`

**Comment by addict67** [comment]
This error happens mostly when the video is private or region restricted -> #658

**Comment by fent** [comment]
are you getting this for a specific video? usually, the error is more specific, it should say something like "private" or "not available in this region".

**Comment by arcovoltaico** [comment]
I'm in London testing with this A.Cooper video:  **jXZcJojTucg**  . It fails 2 in 3 times. So not a very consistent error. ```
This video is unavailable
    at downloadFromInfoCallback 
```
 Also curious why 

  ```
try {
            const stream = ytdl.downloadFromInfo(info, downloadOptions).pipe(file);
          } catch (e) {}
```

does not catch the error.

**Comment by fent** [comment]
> Also curious why
> 
> ```
> try {
>           const stream = ytdl.downloadFromInfo(info, downloadOptions).pipe(file);
>         } catch (e) {}
> ```
> 
> does not catch the error.

ytdl returns a stream, streams are not promises, they emit an `error` event
