### ISSUE TITLE
Prepare for DMCA request

### ISSUE THREAD

**Issue by mh4ck** [fent/node-ytdl-core#742]
Hey it's not directly an issue of the code but a subject we should solve. 

It seems that the RIAA will take down all youtube downloader software on GitHub so we should prepare for a DMCA request and start over to other platforms or build a website so that this repo is not lost when it's hit.

Source: https://torrentfreak.com/riaa-takes-down-popular-open-source-youtube-dl-software-201024/

**Comment by danbulant** [comment]
Pretty sure moving to other platforms won't really help - they can send takedowns to NPM and then even if the code isn't lost, it will be much harder to use and will (probably) be illegal to share, so it would be needed to either move to some sketchy site that doesn't respect DMCA (in which case, they can send DMCA to google so it won't be searchable) or setup a website (in which case the hosting may receive DMCA request).

**Comment by GunnerBasil** [comment]
This may or may not help: https://www.websiteplanet.com/blog/dmca-ignored-countries/

**Comment by snbugz** [comment]
Does this potentially have anything to do with the add-on not being able to "batch download"? Seems to happen only with RIAA related content.

**Comment by mh4ck** [comment]
I already have some experiences with dmca requests and the best solution was in the past to use russian servers. The russian only follow the russian law and also dmca requests out of the country. 

So it's not bulletproof but they need to take more actions than on Europe or US Services/Hoster.

Maybe it's an idea to host a 'git' server there.

**Comment by theodesp** [comment]
> will take down all youtube downloader  software on GitHub ...

How definite is this?

**Comment by ARitz-Cracker** [comment]
I'm sure #741 should be enough for now, no?

**Comment by mh4ck** [comment]
> I'm sure #741 should be enough for now, no?

For sure not, it's not allowed to bypass YouTube video encryption / decipher the signature. There is a new Topic for DMCA requests with the name "Anticircumvention".

Take a look here: https://www.lumendatabase.org/notices/search?utf8=%E2%9C%93&topic_facet=Anticircumvention+%28DMCA%29

**Comment by download13** [comment]
Does the DMCA takedown/response system allow takedowns of "Anticircumvention software" though?

I was under the impression that the takedowns had to refer to specific copyrighted material. The anticircumvention thing was just another part of the law that explicitly made DRM RE illegal.

**Comment by TimeForANinja** [comment]
Just wanna throw this in here:
a) It was a DMCA request against the by far biggest and best known library. Other Libraries may not be in direct danger / be able to fly under the radar. I mean they didnt even go the way of removing youtube-dl from most package repositories...
Also - i haven not directly talked to fent but i don't see him (or may i even say us) move the library to some other primary host as long as we're possible to host it here - so for now i'd say keep calm
b) The point the DMCA focusses on the most is that they not only support downloading copyrighted material but actively advertise they can & even demonstrate it in there examples - we don't do any of that, maybe adding a big disclaimer into the readme would be a good next step thou
d) There is a huge discussion if the DMCA is even valid. youtube-dl had some big users who e.g. worked in the archiving business and you bet they checked if they were permitted to use it. I even read people arguing that what youtube does can't even be described as drm - and indeed they show no sign off closing the gap to the drm of some industry giants like e.g. netflix

**Comment by SugarD-x** [comment]
TimeForANinja brings up some good points. Unfortunately I hate to mention this one because it is not good news, but it seems ytdl-core-discord was also taken down in the mess. While they do have a fairly large presence, they are a smaller one similar to node-ytdl-core as far as I'm aware.

In terms of preparation, having local backups is a good idea in case things get erased and the takedown notices are reversed. (I'm not sure how GitHub handles this on their end). Many companies are indeed upset and getting involved in the legal battle now, so all we can really do right now is just prepare for the worst and hope for the best.

The RIAA really created a massive mess with this incident, and it may set legal precedent for moving forward in the future of the internet. I hope it isn't in their favor, as that would protect us from some future takedowns. If it is, we may be looking at a very bleak outcome.

**Comment by fent** [comment]
if you're worried about this, [join the discord](https://discord.gg/KepExUM). if anything happens, we can continue to discuss there.
