### ISSUE TITLE
Filter hasAudio not working

### ISSUE THREAD

**Issue by arcovoltaico** [fent/node-ytdl-core#743]
I'm using the version 3.4.2.
While I debug the code after executing this:
```
const options = {
        quality: 'highest',
        filter: format => format.hasAudio === false && format.hasVideo == true
      };

      ytdl.getInfo(url,options)
```

the formats on utils.js L93 contains values with hasAudio = true.  What should I change in the code?

On the version 2 I  was using this successfully:
```
const options = {
        quality: 'highest',
        filter: 'audioandvideo'
      };
```

Thanks so much

**Comment by fent** [comment]
what formats do you get and what do you expect to get?

**Comment by arcovoltaico** [comment]
It was just a check for being sure the filter was working. My final code would be` format.hasAudio === true && format.hasVideo == true.`  Setting format.hasAudio as false I was expecting that the array of formats would contain the ones with hasAudio= false, but not the case. So I wonder if I have a syntax error on the filter.

**Comment by TimeForANinja** [comment]
`ytdl.getInfo(xxx)` does not filter the formats / support quality and filter parameter
that's a parameter `ytdl(xxx)` or `ytdl.downloadFromInfo(xxx)` support

if you want to filter results of `ytdl.getInfo(xxx)` you can use https://github.com/fent/node-ytdl-core#ytdlchooseformatformats-options which we also use internally

**Comment by arcovoltaico** [comment]
I was following the options typing. I think it should be changed then?
 function getInfo(url: string, options?: downloadOptions): Promise<videoInfo>;

**Comment by TimeForANinja** [comment]
that's the point i'd call it a bug 😅

**Comment by fent** [comment]
yep, i've already updated the readme to reflect that. need to update typings too.
