### ISSUE TITLE
"Unexpected token (" at async function

### ISSUE THREAD

**Issue by mh4ck** [fent/node-ytdl-core#744]
Hi, with the update to the latest version i get the following error: 

```
.../node_modules/ytdl-core/lib/info.js:30
exports.getBasicInfo = async(id, options) => {
SyntaxError: Unexpected token (
```
Shouldn't there be a space between the arrow function and the ( ? Or what's the error?

Details:
running node v15.0.1

**Comment by fent** [comment]
not getting this when i run with node v15

**Comment by mh4ck** [comment]
Sorry, found out there was an error in my forever configuration after updating nvm...
