### ISSUE TITLE
Error: input stream: Could not find player config

### ISSUE THREAD

**Issue by amitojsingh366** [fent/node-ytdl-core#745]
I keep encountering the error `Error: input stream: Could not find player config` and it occurs randomly at random intervals on random videos. Its very annoying cuz when it starts it will continue to happen.

**Comment by Asaduji** [comment]
dupe of #738, update to latest and try again

**Comment by amitojsingh366** [comment]
Using latest ytdl-core still same issue....

**Comment by TimeForANinja** [comment]
let us keep discussion in #738

**Comment by amitojsingh366** [comment]
A bit more info about the system:
#29~18.04.1-Ubuntu SMP Tue Oct 6 17:14:23 UTC 2020 (x86_64).
I also get the error when I test run the code on my MacBook Air with macOS 10.15.7 (19H2). But it is less frequent on the Mac

**Comment by fent** [comment]
are you using ytdl-core-discord?

**Comment by amitojsingh366** [comment]
No i'm using just `ytdl-core` on version 3.4.2

**Comment by amitojsingh366** [comment]
Ok so `ytdl-core v4.0.0` fixes the errors. Thanks a lot!

**Comment by fent** [comment]
it was fixed in v3.4.2

**Comment by amitojsingh366** [comment]
Yes im aware of that but maybe as I've been using your library from a long time the previous versions were cached somehow by npm and v4.0 somehow fixed it.
Thanks anyways and keep up the good work!

**Comment by amitojsingh366** [comment]
Update: the previous error docent come at all but now its rare but I get the error `Error: input stream: Error parsing info: Unable to retrieve video metadata` occurred only 2x till now

**Comment by fent** [comment]
yep, i've seen it a few times. ytdl-core retries the request if this happens, usually that fixes it.

i'll have to have it retry it a few more times with backoff

**Comment by amitojsingh366** [comment]
Oh ok. 
I guess this issue is solved
