### ISSUE TITLE
Download URLs from ytdl.getInfo say "Access denied" when opened

### ISSUE THREAD

**Issue by chrisr11** [fent/node-ytdl-core#747]
Hi,

I am using the ytdl.getInfo() method to get the direct download link of all the available video formats. When I open any of the downloads links in the browser, it says "Access to r6---sn-vgqskn7z.googlevideo.com was denied".

Why is this happening? Also, I noticed that the **ip** is set to **0.0.0.0** in all the download links.

- Here's the video's link: https://www.youtube.com/watch?v=1La4QzGeaaQ
- Here's a download link for 720p resolution: https://r6---sn-vgqskn7z.googlevideo.com/videoplayback?expire=1603681698&ei=QumVX6bLKYHgNuPks9AF&ip=0.0.0.0&id=o-ANdGsUYPEbvLGtIepQEiSHL4KybI8TtIEVkMmDand4N-&itag=22&source=youtube&requiressl=yes&mh=-I&mm=31%2C26&mn=sn-vgqskn7z%2Csn-tt1e7n7k&ms=au%2Conr&mv=m&mvi=6&pl=22&initcwndbps=3918750&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=337.757&lmt=1599799121311872&mt=1603659992&fvip=6&c=WEB&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgfPA8xK2_eMSX6dM0Bgp2ZVAel0wUPra8HWwabmye-S8CIFThGxughWAan58pgWiBtaKaHLU6pwowdzfqzuHG4qaF&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKNUO8rfWfFvYL7G46M2rcRlkBDBPoZMuDGkW4QqnPmXAiBYnv8YqYkP_yIwJEVeaB9nlYm0x4Gvh4x8T0MdHk6LxQ%3D%3D

**Comment by TimeForANinja** [comment]
a https request does not only contain the path information
most important besides the url are headers

so don't expect the urls out of ytdl formats to work out-of-the-boy in your browser

**Comment by chrisr11** [comment]
So what can I do to make the download URLs to work?

**Comment by chrisr11** [comment]
Nevermind, issue resolved.

**Comment by TimeForANinja** [comment]
> So what can I do to make the download URLs to work?

use the whole ytdl library 🤷 

but nice you found your own way 👍
