### ISSUE TITLE
formats is empty

### ISSUE THREAD

**Issue by daoquangphuong** [fent/node-ytdl-core#754]
ytdl-core v4

after running this code
```js
const ytdlCore = require('ytdl-core');

const main = async () => {
    const info =  await ytdlCore.getInfo('https://www.youtube.com/watch?v=rButbqDqAe8');
    console.log(info.formats)
}

main().catch(console.error)
```
I get info.formats = []
```
[]
```

**Comment by Roki100** [comment]
it mostly happens when the video is not available in your region

**Comment by daoquangphuong** [comment]
that's weird cause I still can view this video from my browser.

![Uploading Screen Shot 2020-10-28 at 15.12.15.png…]()

**Comment by Roki100** [comment]
I cant see the image but I am not sure then.
I don't get formats mostly when the video is not available in the region my server is in

**Comment by daoquangphuong** [comment]
sorry for the image.
@Roki100 
I got empty formats when I was running the code above in my computer. and I can play the youtube link that was used in the code

```https://www.youtube.com/watch?v=rButbqDqAe8```

**Comment by daoquangphuong** [comment]
https://github.com/fent/node-ytdl-core/blob/c5290635a5035bdf81cfebc8c0de67ca56f8ba14/lib/info.js#L116

i clone your code and fix it by add this line
```
  info.player.args.player_response = info.player.args.player_response || info.playerResponse;
```
to
```
info.html5player = info.html5player || (info.player && info.player.assets && info.player.assets.js);
  info.player.args.player_response = info.player.args.player_response || info.playerResponse;
  return gotConfig(id, options, info, body);
```

**Comment by fent** [comment]
thanks for the above tip on how to fix

going to mark this as dupe since #750 exists
