### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined [BUG AND SUPPORT]

### ISSUE THREAD

**Issue by Beast-0001** [fent/node-ytdl-core#756]
0|arrow  | TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
0|arrow  |     at validateString (internal/validators.js:107:11)
0|arrow  |     at Url.parse (url.js:155:3)
0|arrow  |     at Object.urlParse [as parse] (url.js:150:13)
0|arrow  |     at Object.exports.getURLVideoID (/var/www/Bots/Arrow/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/util.js:254:22)
0|arrow  |     at Object.exports.getVideoID (/var/www/Bots/Arrow/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/util.js:287:20)
0|arrow  |     at Object.exports.<computed> [as getFullInfo] (/var/www/Bots/Arrow/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:291:19)
0|arrow  |     at Function.exports.<computed> [as getInfo] (/var/www/Bots/Arrow/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:287:29)
0|arrow  |     at /var/www/Bots/Arrow/node_modules/ytdl-core-discord/index.js:24:8
0|arrow  |     at new Promise (<anonymous>)
0|arrow  |     at download (/var/www/Bots/Arrow/node_modules/ytdl-core-discord/index.js:23:9)
0|arrow  |     at play (/var/www/Bots/Arrow/Arrow/include/play.js:15:23)
0|arrow  |     at Object.execute (/var/www/Bots/Arrow/Arrow/commands/music/play.js:98:6)
0|arrow  |     at processTicksAndRejections (internal/process/task_queues.js:88:5)
0|arrow  | Error [VOICE_PLAY_INTERFACE_BAD_TYPE]: Unknown stream type
0|arrow  |     at VoiceConnection.play (/var/www/Bots/Arrow/node_modules/discord.js/src/client/voice/util/PlayInterface.js:84:11)
0|arrow  |     at play (/var/www/Bots/Arrow/Arrow/include/play.js:32:5)
0|arrow  |     at processTicksAndRejections (internal/process/task_queues.js:88:5) {
0|arrow  |   [Symbol(code)]: 'VOICE_PLAY_INTERFACE_BAD_TYPE'
0|arrow  | }

Been saying that since I updated it to V4.0.0

**Comment by JasperSurmont** [comment]
V4.0.0 has been working for me. Care to include some code?

**Comment by Beast-0001** [comment]
Sure

**Comment by Beast-0001** [comment]
Here's the command: `/*global require module*/
const { play } = require("../../include/play");
const ytdl = require("ytdl-core");
const YouTubeAPI = require("simple-youtube-api");
const youtube = new YouTubeAPI("REEEEEEEEEEEE");
const Discord = require("discord.js");
module.exports = {
	name: "play",
	description: "Play Music from Youtube",
	aliases: [],
	usage: "<Wanted song URL or name>",
	display: true,
	type: "music",
	execute: async function(client, message, args, prefix) {
		try {
			const { channel } = message.member.voice;

			if (!args.length) return message.reply("Usage: " + prefix + "play <YouTube URL | Video Name>").catch(console.error);
			if (message.mentions.users.first() || message.content.includes("<@")) return message.channel.send("I can't play a role or user!");
			if (!channel) return message.reply("You need to join a voice channel first!").catch(console.error);

			const permissions = channel.permissionsFor(message.client.user);
			if (!permissions.has("CONNECT"))
				return message.reply("Cannot connect to voice channel, missing permissions");
			if (!permissions.has("SPEAK"))
				return message.reply("I cannot speak in this voice channel, make sure I have the proper permissions!");

			const search = args.join(" ");
			const videoPattern = /^(https?:\/\/)?(www\.)?(youtube\.com|youtu\.?be)\/.+$/gi;
			const playlistPattern = /^.*(youtu.be\/|list=)([^#&?]*).*/gi;
			const url = args[0];
			const urlValid = videoPattern.test(args[0]);

			// Start the playlist if playlist url was provided
			if (!videoPattern.test(args[0]) && playlistPattern.test(args[0])) {
				return message.client.commands.get("playlist").execute(message, args);
			}

			const serverQueue = message.client.queue.get(message.guild.id);
			const queueConstruct = {
				textChannel: message.channel,
				channel,
				connection: null,
				songs: [],
				loop: false,
				volume: 100,
				playing: true
			};

			let songInfo = null;
			let song = null;

			if (urlValid) {
				try {
					songInfo = await ytdl.getInfo(url);
					song = {
						title: songInfo.title,
						url: songInfo.video_url,
						duration: songInfo.length_seconds
					};
				} catch (error) {
					if (error.message.includes("copyright")) {
						return message
							.reply("⛔ The video could not be played due to copyright protection ⛔")
							.catch(console.error);
					} else {
						console.error(error);
					}
				}
			} else {
				try {
					const results = await youtube.searchVideos(search, 1);
					songInfo = await ytdl.getInfo(results[0].url);
					song = {
						title: songInfo.title,
						url: songInfo.video_url,
						duration: songInfo.length_seconds
					};
				} catch (error) {
					console.error(error);
				}
			}

			if (serverQueue) {
				serverQueue.songs.push(song);
				return message.channel
					.send(new Discord.MessageEmbed().setDescription(`✅ **${song.title}** has been added to the queue by ${message.author}`))
					.catch(console.error);
			} else {
				queueConstruct.songs.push(song);
			}

			if (!serverQueue) message.client.queue.set(message.guild.id, queueConstruct);

			if (!serverQueue) {
				try {
					queueConstruct.connection = await channel.join();
					play(queueConstruct.songs[0], message);
				} catch (error) {
					console.error(`Could not join voice channel: ${error} Try again later; If this error continues, DM thebeastatfnbr#3142`);
					message.client.queue.delete(message.guild.id);
					await channel.leave();
					return message.channel.send(`Could not join the channel: ${error} Try again later; If this error continues, DM thebeastatfnbr#3142`).catch(console.error);
				}
			}
		} catch (err) { console.log(err); }
	}
};
`

**Comment by paul-hanneforth** [comment]
This happens to me aswell!

**Comment by Beast-0001** [comment]
Yeah, it's happening since last week and since I upgraded to V4

**Comment by error434** [comment]
I'm having the same issue as well

**Comment by fent** [comment]
> Yeah, it's happening since last week and since I upgraded to V4

make sure you really are on latest. that stack trace shows a file that no longer exists, showing that you're on an outdated version. you're also using ytdl-core-discord, which is no longer maintained and likely uses an older version too.

**Comment by Beast-0001** [comment]
I installed ytdl-core@latest and uninstalled ytdl-core-discord.
Same error

**Comment by Beast-0001** [comment]
wait seems to be different: `0|arrow  | TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
0|arrow  |     at validateString (internal/validators.js:107:11)
0|arrow  |     at Url.parse (url.js:155:3)
0|arrow  |     at Object.urlParse [as parse] (url.js:150:13)
0|arrow  |     at Object.exports.getURLVideoID (/var/www/Bots/Arrow/node_modules/ytdl-core/lib/url-utils.js:30:22)
0|arrow  |     at Object.exports.getVideoID (/var/www/Bots/Arrow/node_modules/ytdl-core/lib/url-utils.js:63:20)
0|arrow  |     at Function.exports.<computed> [as getInfo] (/var/www/Bots/Arrow/node_modules/ytdl-core/lib/info.js:312:23)
0|arrow  |     at ytdl (/var/www/Bots/Arrow/node_modules/ytdl-core/lib/index.js:19:8)
0|arrow  |     at play (/var/www/Bots/Arrow/Arrow/include/play.js:15:23)
0|arrow  |     at Object.execute (/var/www/Bots/Arrow/Arrow/commands/music/play.js:98:6)
0|arrow  |     at processTicksAndRejections (internal/process/task_queues.js:88:5)
0|arrow  | Error [VOICE_PLAY_INTERFACE_BAD_TYPE]: Unknown stream type
0|arrow  |     at VoiceConnection.play (/var/www/Bots/Arrow/node_modules/discord.js/src/client/voice/util/PlayInterface.js:84:11)
0|arrow  |     at play (/var/www/Bots/Arrow/Arrow/include/play.js:32:5)
0|arrow  |     at Object.execute (/var/www/Bots/Arrow/Arrow/commands/music/play.js:98:6)
0|arrow  |     at processTicksAndRejections (internal/process/task_queues.js:88:5) {
0|arrow  |   [Symbol(code)]: 'VOICE_PLAY_INTERFACE_BAD_TYPE'
0|arrow  | }`

**Comment by Beast-0001** [comment]
And `0|arrow  | Error: Error parsing info: Unable to retrieve video metadata
0|arrow  |     at getWatchPage (/var/www/Bots/Arrow/node_modules/ytdl-core/lib/info.js:77:13)
0|arrow  |     at processTicksAndRejections (internal/process/task_queues.js:88:5)
0|arrow  |     at async exports.getBasicInfo (/var/www/Bots/Arrow/node_modules/ytdl-core/lib/info.js:86:22)
0|arrow  |     at async Map.getOrSet (/var/www/Bots/Arrow/node_modules/ytdl-core/lib/cache.js:24:19)
0|arrow  |     at async exports.getInfo (/var/www/Bots/Arrow/node_modules/ytdl-core/lib/info.js:210:14)
0|arrow  |     at async Map.getOrSet (/var/www/Bots/Arrow/node_modules/ytdl-core/lib/cache.js:24:19)
0|arrow  |     at async Object.execute (/var/www/Bots/Arrow/Arrow/commands/music/play.js:73:17)`

**Comment by fent** [comment]
the first error is from giving `undefined` to ytdl.

the second error can be tracked at https://github.com/fent/node-ytdl-core/issues/751

**Comment by Beast-0001** [comment]
Ok

**Comment by Beast-0001** [comment]
I still don't understand why it's returning `undefined`

**Comment by fent** [comment]
passing it an `undefined` url i would guess? i would debug your code around the call to ytdl

**Comment by Datura359** [comment]
I believe what is happening here is that the response we're getting back from YouTube has changed.  

From your code: 
`				songInfo = await ytdl.getInfo(url);
				song = {
					title: songInfo.title,
					url: songInfo.video_url,
					duration: songInfo.length_seconds
				};`

songInfo.video_url is no longer valid.
songInfo.videoDetails.video_url  will provide that information.  Many other variables in the response have also changed.

**Comment by Beast-0001** [comment]
ah ok

**Comment by fent** [comment]
closing this in favor of #751
