### ISSUE TITLE
TypeError: Cannot read property 'setVolumeLogarithmic' of null

### ISSUE THREAD

**Issue by weblol200** [fent/node-ytdl-core#763]
For an unknown reason, this error occurs and the bot crashes. Fix possible?
![изображение](https://user-images.githubusercontent.com/48912672/97804859-1d0e2500-1c5b-11eb-862a-5b92b7080087.png)

**Comment by fent** [comment]
likely a discordjs issue since this function does not exist within ytdl-core

**Comment by North-West-Wind** [comment]
You probably didn't initialize a dispatcher. Go read the [docs of Discord.js](discord.js.org).

This is not related to `ytdl-core`
