### ISSUE TITLE
ytdl.getInfo isn't firing the callback.

### ISSUE THREAD

**Issue by SpEaGs** [fent/node-ytdl-core#764]
I'm not sure specifically what is happening here, as I'm not getting any error output whatsoever, and I've already confirmed that my args are correct. Here's the code in question (truncated the callback a bit to make it more readable since none of it is getting called anyway):
```javascript
    let errcount = 0;
    log('get_yt_info calling getInfo.');
    ytdl.getInfo(url, (error, info) => {
        if (error) {
            logErr(`Error ( ${url} ): ${error}`);
            if (errcount < 3) {
                errcount++;
                log(`Retrying...`);
                setTimeout(() => {
                    get_yt_info(url, msg, status);
                }, 1 * 1000);
            }
            return;
        }
        log('get_yt_info got info.')
        errcount=0;
    });
```
For reference: url is just a generic youtube watch link (i.e. `https://www.youtube.com/watch?v=v1uSlrukwHY`).
As I said above, nothing inside the callback function passed to `ytdl.getInfo()` is getting called, and there are no errors thrown. 

I'm running `ytdl-core@4.0.2`

**Comment by Peppy8651** [comment]
I believe that they removed support for callbacks a few updates back. It probably should work with promises like
 `const info = await ytdl.getInfo(url);`
