### ISSUE TITLE
Unable to retrieve video metadata

### ISSUE THREAD

**Issue by deebah** [fent/node-ytdl-core#766]
Every once in a while, when trying to download a youtube video, it will give me this error: 
`Error parsing info: Unable to retrieve video metadata`

And here is the code for downloading:
`ytdl(url, {quality: 'highestaudio', highWaterMark: 1 << 25});`

Any ideas about what could be happening or how I could fix it?

**Comment by Gymnophoria** [comment]
Version 4.0.3 theoretically fixes this - try updating and see if the issue persists.

**Comment by GabFLAB** [comment]
Update to version 4.0.3 of ytdl-core, why not? Also,  #751
