### ISSUE TITLE
Not all video URLs actually exist

### ISSUE THREAD

**Issue by avi12** [fent/node-ytdl-core#771]
I discovered an issue on YouTube's end, which needs to be accounted in this module.
For some video IDs, the YouTube endpoint returns video URLs that don't actually exist.
For example, for [this video](https://www.youtube.com/watch?v=VVgENTnk_qU), the endpoint returns [this](https://r4---sn-nhpax-ua8r.googlevideo.com/videoplayback?expire=1604968774&ei=5oypX805poPp2w_oubWoCQ&ip=83.130.29.241&id=o-AEghQQX4G_aOfQdubrY_m7oba2GRzci8fnQE3JzndifJ&itag=303&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303&source=yt_otf&requiressl=yes&mh=z6&mm=31%2C29&mn=sn-nhpax-ua8r%2Csn-4g5e6ne6&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=20&initcwndbps=738750&vprv=1&mime=video%2Fwebm&otf=1&otfp=1&dur=0.000&lmt=1595340322594586&mt=1604947006&fvip=5&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRAIgBuqNYK8WsIKVFwfPv3gg2uqXZDK7yigrk3V88z_j0EkCIBJTafzEQ1B6XWZG_3QlyTK7y9u5FHv5DPX9kpxJS7za&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJI0y3LiofkK_2DJ9glLFc_1q_aeiCTPFjWGj8Z5J0F_AiEAgct5tYToyVLPNMS0SoHcEakmRv8HQrdNGID3Shanfo0%3D&ratebypass=yes) URL (1080p 60 FPS with codec "vp9"), which doesn't even exist.

**Comment by fent** [comment]
it doesn't exist? i'm confused, it's a working url

**Comment by North-West-Wind** [comment]
The access to returned URL is denied.
```
https://r4---sn-nhpax-ua8r.googlevideo.com/videoplayback?expire=1604968774&ei=5oypX805poPp2w_oubWoCQ&ip=83.130.29.241&id=o-AEghQQX4G_aOfQdubrY_m7oba2GRzci8fnQE3JzndifJ&itag=303&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303&source=yt_otf&requiressl=yes&mh=z6&mm=31%2C29&mn=sn-nhpax-ua8r%2Csn-4g5e6ne6&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=20&initcwndbps=738750&vprv=1&mime=video%2Fwebm&otf=1&otfp=1&dur=0.000&lmt=1595340322594586&mt=1604947006&fvip=5&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRAIgBuqNYK8WsIKVFwfPv3gg2uqXZDK7yigrk3V88z_j0EkCIBJTafzEQ1B6XWZG_3QlyTK7y9u5FHv5DPX9kpxJS7za&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJI0y3LiofkK_2DJ9glLFc_1q_aeiCTPFjWGj8Z5J0F_AiEAgct5tYToyVLPNMS0SoHcEakmRv8HQrdNGID3Shanfo0%3D&ratebypass=yes
```
If you look closely, you will find this: `&ip=83.130.29.241`. This is probably the reason why the access is denied.
Did you generate this URL somewhere else and then chuck it into your browser?

**Comment by avi12** [comment]
I'm working on a downloader of my own and this module is on its basis.
So, I simply called the `ytdl.getInfo(url)` and got the URLs from there.

**Comment by North-West-Wind** [comment]
My Discord bot is actually having issues playing some videos, such as [this one](https://www.youtube.com/watch?v=iIcdlGW2CKU). So, I went to check it with `ytdl.getInfo(url)`, and use `ytdl.chooseFormat(info.formats)` to get [the URL I wanted](https://r1---sn-nx5e6ne6.googlevideo.com/videoplayback?expire=1605021997&ei=zVyqX8B8hbqTBo_kqNAJ&ip=18.237.110.76&id=o-AMEKpjoSZMeecO0PDpdN4olir4Cfa5LBj4V9WvMOO_PS&itag=251&source=youtube&requiressl=yes&mh=Xh&mm=31%2C26&mn=sn-nx5e6ne6%2Csn-a5mlrn76&ms=au%2Conr&mv=m&mvi=1&pl=15&initcwndbps=1671250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=493551&otfp=1&dur=31.581&lmt=1565734912718821&mt=1605000273&fvip=1&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMuFD7qt2HSetdxAVx939T5BYIhVF-70uQm3Vq7RBXn0AiAXyjqvcGb3tGNNh7Zh8Jj3em-r5dhxFT3SKHBdtpR5SQ%3D%3D&ratebypass=yes&sig=AOq0QJ8wRQIgEn7INk6FRpiLecYcDlT3z_cWSryXxLbjwI0Htg1opJcCIQCR7CIWt1wUIjR5fYkbLtIPbf7tP7bgEDElVbimebKkDg%3D%3D). Then I put it into `request-stream` and play the stream from it. The music ends immediately.

However, downloading the same video has no problem at all. That's really weird.

**Comment by avi12** [comment]
I still can't access the video link I shared in my main post.
The module should at least inform me that I can't access it because, for example, of my IP address (e.g. the country that I live in).

**Comment by fent** [comment]
> I'm working on a downloader of my own and this module is on its basis.
> So, I simply called the `ytdl.getInfo(url)` and got the URLs from there.

the format is from a m3u8 playlist. if you try to download that url, you will download an m3u8 playlist file, not a video. ytdl-core uses [m3u8stream](https://github.com/fent/node-m3u8stream/) internally to process such formats
