### ISSUE TITLE
Problem with playing some tracks on YouTube.

### ISSUE THREAD

**Issue by FlipSize** [fent/node-ytdl-core#773]
Hello everybody. I made a music bot and I can't figure out what the problem is. Some tracks play fine and some play. (for example: EAO 10 hours) I would be grateful for your help.

Error: input stream: This video is unavailable
    at downloadFromInfoCallback (C:\Users\FlipSize\Desktop\Discord-MusicBot-master\node_modules\ytdl-core\lib\index.js:76:26)
    at C:\Users\FlipSize\Desktop\Discord-MusicBot-master\node_modules\ytdl-core\lib\index.js:18:5
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by fent** [comment]
are you on latest? can you provide a link to any video not working?

**Comment by galnir** [comment]
This happens to me randomly on ytdl-core@4.0.4. Trying to play [this](https://www.youtube.com/watch?v=JFm7YDVlqnI) url emitted this error but worked fine 1 minute later

**Comment by FlipSize** [comment]
> ты на последнем? можешь дать ссылку на любое неработающее видео?

I fixed the error by updating ytdl-core.  https://www.youtube.com/watch?v=RUQl6YcMalg&ab_channel=BillieEilishVEVO

**Comment by FlipSize** [comment]
> ты на последнем? можешь дать ссылку на любое неработающее видео?

I fixed the error by updating ytdl-core. But there was a problem with the fact that sometimes the wrong music is played. For instance: https://www.youtube.com/watch?v=RUQl6YcMalg&ab_channel=BillieEilishVEVO
