### ISSUE TITLE
downloading stops at 10mb

### ISSUE THREAD

**Issue by indjbackend** [fent/node-ytdl-core#775]
When I try to download highest video and audio, it just stops download at 10mb.

 let video = await ytdl(`https://www.youtube.com/watch?v=${video_id}`, {
        filter: "videoonly",
        itag: 137,
        dlChunkSize: 0,
      });
      video.pipe(fs.createWriteStream(videoFilePathCrawl));

**Comment by LH-Lawliet** [comment]
exactly the same problem

**Comment by fent** [comment]
any particular video this happens on?

**Comment by LH-Lawliet** [comment]
> 
> 
> any particular video this happens on?

nah on every video that i tested it's stop at 10 485 761 bytes

my code is : 
ytdl('http://www.youtube.com/watch?v=' + videoId, { filter: format => format.itag === videoFormat.itag }).pipe(fs.createWriteStream('youtubeDownload/video_' + videoId))

i don't get any error or something like that

**Comment by najongjine** [comment]
When I do filter: "videoandaudio", it downloads most videos fine. But When I try to get 1080p videos, it just stops at 10mb. Doesn't depend on certain videos. Most of them.

**Comment by alexjean** [comment]
same issue for me.  link like https://www.youtube.com/watch?v=uresoWToa-k
I selected the video format to 720p the downloading would stop at 10M bytes exactly.

**Comment by fent** [comment]
which 720p itag exactly?
```
itag container quality codecs                 bitrate  audio bitrate size
  18 mp4       360p    avc1.42001E, mp4a.40.2 347.95KB 96KB          36.69MB
 136 mp4       720p    avc1.64001f            1.6MB                  64.18MB
 247 webm      720p    vp9                    877.19KB               40.54MB
 135 mp4       480p    avc1.4d401f            860.33KB               39.08MB
 244 webm      480p    vp9                    458.7KB                22.26MB
 134 mp4       360p    avc1.4d401e            485.46KB               24.86MB
 243 webm      360p    vp9                    274.75KB               15.08MB
 133 mp4       240p    avc1.4d4015            249.1KB                14.68MB
 242 webm      240p    vp9                    160.95KB               9.9MB
 160 mp4       144p    avc1.4d400c            109.45KB               7MB
 278 webm      144p    vp9                    89.57KB                7.27MB
 140 mp4               mp4a.40.2                       128KB         13.33MB
 251 webm              opus                            160KB         11.43MB
 250 webm              opus                            64KB          6.37MB
 249 webm              opus                            48KB          5.23MB
  22 mp4       720p    avc1.64001F, mp4a.40.2 733.95KB 192KB
```
i'm still not able to reproduce with itags 136 and 247, tried different versions of node too.

guessing since it downloads exactly only 10mb, it's related to chunked downloads, which can be disabled by setting `dlChunkSize: 0`. although the OP shows they've already set that.

**Comment by alexjean** [comment]
Update node v12.16.3=> v.14.15.1, not working.  Either download for itag 136 or 247 would stop at 10M bytes, but the weird thing is that the download for itag 22 will go through the 10M bytes boundary.

**Comment by alexjean** [comment]
Upgrade to **ytdl-core 4.0.5** then the bug solved ! Very glad !

**Comment by fent** [comment]
> but the weird thing is that the download for itag 22 will go through the 10M bytes boundary.

that's because only formats that have either only audio or video are chunked, itag 22 has both. further confirming my theory that it only happens on chunked formats. but your above code `dlChunkSize: 0` should stop it too.



> Upgrade to **ytdl-core 4.0.5** then the bug was solved ! Very glad !

great! @indjbackend does updating help?

**Comment by indjbackend** [comment]
It works find after upgrading to 4.0.5
Thanks for fast fix :)
