### ISSUE TITLE
Adding two videos after click one time in my project

### ISSUE THREAD

**Issue by snuckdev** [fent/node-ytdl-core#781]
Hey, I've been using node-ytdl-core since the beginning of ytdl-gui. (github.com/ytdl-gui/ytdl-gui). I used it and it worked fine, and it still works. But when I download a video, and after it finishes downloading, I add another one to download. But it adds two video objects, which contains the ytdl (); method, making it download two videos, can you help me?

**Comment by fent** [comment]
not sure i understand, do you have some code to elaborate?

**Comment by snuckdev** [comment]
Srry already fixed xD
