### ISSUE TITLE
Possibly wrong length of videos

### ISSUE THREAD

**Issue by 1vanbrav0** [fent/node-ytdl-core#782]
I dont know if its an issue or my code its wrong, but when i get the length of any video, the length its not the same, its close but its not the same, i dont know if its my problem or maybe im doing something wrong. For example this video: 

https://www.youtube.com/watch?v=QCoEm9tapFo

it length its 11:34, but when i get the data with getInfo, it returns me 693 seconds (11:55). Maybe im wrong so idk.

![imagen](https://user-images.githubusercontent.com/70708615/99470187-8a7bb000-2901-11eb-86fa-43cdc4fc3324.png)

Pd: sorry for my english, im a mexican student.

**Comment by fent** [comment]
the length is in total seconds. to get the minutes, divide by 60, the seconds is the remainder

```js
let minutes = Math.floor(length / 60);
let seconds = length % 60
```
the format is this way because this is what youtube returns, and is arguably more flexible to use within code.

**Comment by 1vanbrav0** [comment]
Ok, thank you, and thank you for this npm, its very functional.
