### ISSUE TITLE
Not playing some videos

### ISSUE THREAD

**Issue by WhiteDragon4** [fent/node-ytdl-core#787]
Hey!
I've noticed that the ytdl-core does not play some videos. Here's a couple examples:
https://www.youtube.com/watch?v=GCdwKhTtNNw
https://www.youtube.com/watch?v=isaXqowHZuU
https://www.youtube.com/watch?v=7L6qSHJrcl8
https://www.youtube.com/watch?v=aSLZFdqwh7E
It's probably not the youtube channel because it does play other songs from eminem.
Hope you can solve this.

**Comment by skick1234** [comment]
What's your error?
I can play those videos normally with `ytdl-core@4.1.0`

**Comment by WhiteDragon4** [comment]
There isn't any error, it's just silence..
Btw I asked someone else and he said that his bot also can't play theese..

**Comment by typicalninja493** [comment]
I tried the 1st link with my bot and it works i use v4.1.0
Ill try using others as well to test them

**Comment by WhiteDragon4** [comment]
Yeag I'm sure, i can show you if you add me. WhiteDragon4#8862

**Comment by LuaaDev** [comment]
I think this is also happening to my bot, and my friends' bots

**Comment by LuaaDev** [comment]
It gives a 429 error

**Comment by typicalninja493** [comment]
I had no issue i tested 2 songs and they played fine. I cant play others as i broke my bots music feature and on mobile and cant fix it

**Comment by typicalninja493** [comment]
> Yeag I'm sure, i can show you if you add me. WhiteDragon4#8862

I added u

**Comment by modscleo4** [comment]
All of these songs played on my Discord bot. It's using ytdl-core@4.1.0

**Comment by WhiteDragon4** [comment]
so what could be wrong with my code?
![error001](https://user-images.githubusercontent.com/51878698/100529699-7cc00780-31ea-11eb-9b9e-9823dae160c9.PNG)
i get this error in console:
(node:29265) UnhandledPromiseRejectionWarning: Error: input stream: Video unavailable
    at Object.exports.playError (../node_modules/ytdl-core/lib/utils.js:116:12)
    at downloadFromInfoCallback (../node_modules/ytdl-core/lib/index.js:72:19)
    at ../node_modules/ytdl-core/lib/index.js:20:5
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:29265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by modscleo4** [comment]
Are the songs embeddable where your bot is hosted?

**Comment by WhiteDragon4** [comment]
Right, that was the problem. Works fine on other host.
