### ISSUE TITLE
getInfo author videoDetails lost(?)

### ISSUE THREAD

**Issue by KRooijackers** [fent/node-ytdl-core#789]
I created an MessageEmbed which showed some details of the song and author when the used called the function '$nowplaying'. While this function is still fully functional, some of the details went 'undefined'. I printed the getInfo videoDetails onto the console and found out that the author array (and media array) are no longer inside videoDetails. Last time I played around with the bot was 5 days ago and believe I was on v4.0.3. I updated ytdl-core to v4.1.0 today only now this 'undefined' thing started to happen.

```
    async execute(message, servers) {
        var server = servers[message.guild.id];

        ytdl.getInfo(server.queue[0]).then(function(info){
            const embed = new MessageEmbed();
            const { thumbnail, title, lengthSeconds, ownerProfileUrl, viewCount, category, publishDate, ownerChannelName, uploadDate, averageRating, video_url } = info.videoDetails;
            const { name, avatar, user_url, subscriber_count } = info.videoDetails.author;

            //console.log(info.videoDetails);

            embed.setTitle(title)
            .setDescription(`This masterpiece was created by ${actualWriter}. Be sure to check out this artist for more awesome songs!\n`)
            .addField('Views', viewCount, true)
            .addField('Subscribers', subscriber_count, true)
            .setThumbnail(thumbnail.thumbnails[thumbnail.thumbnails.length - 1].url)
            .setTimestamp(publishDate)
            .setFooter(name, avatar)

            message.channel.send(embed);
        });
    }
```

Wondering what is the reason behind this and if I can still retrieve this information in any way.

**Comment by WOZARDLOZARD** [comment]
It appears that all of the properties of `videoDetails.author` have been removed and now `videoDetails.author` is a string with only the author's name. Hopefully the `author`'s properties can be added back soon though because they do provide some useful information.

**Comment by fent** [comment]
i was testing this out earlier, like an hour ago, and was indeed getting empty fields for `author`, `media`, `relatedVideos`. it was due to the endpoints that ytdl-core uses changing what they return. videos were at least still working, but not some fields.

but anyway, they seem to work again. let me know if this is working for you now

**Comment by KRooijackers** [comment]
@fent Just FYI, I did not update ytdl-core since I posted this issue. If I should have, please tell me.

Anyway, I noticed indeed that there are (still) empty fields. I'm not sure if I even saw the empty fields when I last posted, because I think I didn't. Regardless, the issue still remains for me. Lemme know if I can help you by sending more details. I could send some results of the console log if that would help.

**Comment by WOZARDLOZARD** [comment]
> but anyway, they seem to work again. let me know if this is working for you now

The `videoDetails.author` property is now returning an empty object (`{}`) for me... strange

**Comment by fent** [comment]
do you have a sample video where this happens?

**Comment by WOZARDLOZARD** [comment]
Seems like I'm running into this issue on every video, here's the link to a video that I just tested with: https://www.youtube.com/watch?v=jqkPqfOFmbY

**Comment by WOZARDLOZARD** [comment]
I updated my ytdl-core to the latest version just now and I'm still getting an empty object for `videoDetails.author`. I tested with this video: https://www.youtube.com/watch?v=n8X9_MgEdCg

**Comment by KRooijackers** [comment]
I also updated ytdl-core and I'm still having empty objects. Tested with for example https://www.youtube.com/watch?v=cKZU--qmwmE and https://www.youtube.com/watch?v=xzPiya-QfJA.

**Comment by FalledStars** [comment]
Hi, [object Object] does not mean the api get empty, and it means it get all author information but could not show all. Please try videoDetails.author.name
