### ISSUE TITLE
ytdl.getInfo Throwing error

### ISSUE THREAD

**Issue by Mesmaroth** [fent/node-ytdl-core#79]
getinfo throws an error before returning the callback error.

Example:
```
var url = somethingThatsNotAUrl
ytdl.getInfo(url, function(err, info){
     if(error) console.error(error);
     console.log(info)
});
``` 

Returns `throw new Error('No video id found: ' + link)`

**Comment by fent** [comment]
This sounds correct. If given invalid parameters, ytdl will throw. Even in core libraries, they will throw if the arguments are wrong, rather than passing an error to the callback.
