### ISSUE TITLE
getInfo return empty formats

### ISSUE THREAD

**Issue by c0b41** [fent/node-ytdl-core#791]
```js
(async () => {
 try {
  let info = await ytdl.getInfo(`Jma5p80pLgU`)
  console.log(info.formats)
 } catch (error) {
   console.log(error)
 }
})()
```

ytdl-core version: 4.1.0

**Comment by modscleo4** [comment]
also happening with /watch?v=VV2y21GjZ8E

**Comment by fent** [comment]
> also happening with /watch?v=VV2y21GjZ8E

can reproduce with this

**Comment by modscleo4** [comment]
The problem with my video was it is age restricted, and YouTube does not allow playback of age restricted videos on /embed

/watch?v=Jma5p80pLgU is region restricted, it plays fine here in Brazil, but not in United States

**Comment by fent** [comment]
> The problem with my video was it is age restricted, and YouTube does not allow playback of age restricted videos on /embed

it does not? this is new, it previously did

**Comment by modscleo4** [comment]
Now it blocks embed playback

"Viewers who click on an age-restricted video on another website, such as an embedded player, will be redirected to YouTube, where they will only be able to view the content when signed-in and over 18." (https://support.google.com/youtube/answer/2802167?hl=en)

**Comment by fent** [comment]
welp, i guess now people will have to use cookies for those :/
