### ISSUE TITLE
MinigetError: Status code: 429

### ISSUE THREAD

**Issue by MidSpike** [fent/node-ytdl-core#793]
This issue started today...

When calling `ytdl.getBasicInfo()` or `ytdl()` for any video, I will get the following
```
MinigetError: Status code: 429
```

yes I made absolutely certain that I was on the latest version `4.1.0` of `ytdl-core`

**Comment by redbrain** [comment]
A 429 error code means that YouTube is ratelimiting you. Just wait a day or so for it to go away, or use cookies or proxies to avoid it.

**Comment by MidSpike** [comment]
@redbrain Could I clued into how to set the cookie?

**Comment by redbrain** [comment]
Here's an [example](https://github.com/fent/node-ytdl-core/blob/master/example/cookies.js#L6-L12).

**Comment by MidSpike** [comment]
I can't find the cookie header in any of my browsers

**Comment by MidSpike** [comment]
thank you for the help it is working so far
