### ISSUE TITLE
MinigetError: Status code: 429 at ClientRequest

### ISSUE THREAD

**Issue by 1vanbrav0** [fent/node-ytdl-core#794]
I saw another issue like this but im not sure if is the same error, the app worked yesterday but now isnt works, only return me this:

![imagen](https://user-images.githubusercontent.com/70708615/100495235-a43da400-3106-11eb-91d8-6b06724c71ef.png)

If it is the same error, pls move it, and if somebody knows how to solved it, i would be glad of receive your help cause im relative new in this.

**Comment by fent** [comment]
dupe https://github.com/fent/node-ytdl-core/issues/635
