### ISSUE TITLE
length_seconds results to undefined

### ISSUE THREAD

**Issue by fbagjug** [fent/node-ytdl-core#796]
I'm using ytdl-core 4.1.0 to get this issue and it's when getting the length_seconds of the video. All of the other things return such as url but when console logging `info.length_seconds` it returns undefined, anyone know why?

**Comment by Synkky** [comment]
current video length -> `info.videoDetails.lengthSeconds`
related video length -> `info.related_videos[<index>].length_seconds`
Don't question it, the package is a bit of an inconsistent mess atm

**Comment by fbagjug** [comment]
> current video length -> `info.videoDetails.lengthSeconds`
> related video length -> `info.related_videos[<index>].length_seconds`
> (don't question it, the package is a bit of an inconsistent mess atm -_-)

mhm indeed lmao

**Comment by fent** [comment]
there were deprecation warnings for several months

**Comment by fbagjug** [comment]
> there were deprecation warnings for several months

It was my IDE anyway just telling me to use the old methods, for some reason it isn't updating the auto suggestion
