### ISSUE TITLE
getInfo returns empty title

### ISSUE THREAD

**Issue by zalbertl** [fent/node-ytdl-core#797]
Running ytdl-core@4.1.0

let info = await ytdl.getInfo(id);			
console.log(info.title);

The info.title field is undefined, is this expected?
Used the following URL as a test case:
https://www.youtube.com/watch?v=CSvFpBOe8eY

**Comment by skick1234** [comment]
It should be `info.videoDetails.title`

**Comment by zalbertl** [comment]
Thanks, I'll try it out

**Comment by zalbertl** [comment]
Thanks, it used to work with info.title
