### ISSUE TITLE
Missing related songs

### ISSUE THREAD

**Issue by skick1234** [fent/node-ytdl-core#800]
https://github.com/fent/node-ytdl-core/blob/3ced5ac788cfe2281231155f8dc2e07d524d2fc8/lib/info.js#L47-L51

I think we should use `getVideoInfoPage` instead of `getEmbedPage`.
Because an embed page doesn't provide any related songs and on browser, it has to use `getVideoInfoPage` to get related videos at the end of a video. Some other properties such as `like`, `dislike` is null too

**Comment by fent** [comment]
yep, embed was mainly used to get around age restricted content while not logged in. but that no longer works.

I'm also thinking of adding the regular watch.html page as backup, it has related video content too

**Comment by skick1234** [comment]
> I'm also thinking of adding the regular watch.html page as backup, it has related video content too

And you can update the client version automatically with this. It contains `INNERTUBE_CLIENT_VERSION`

**Comment by fent** [comment]
> > 
> 
> And you can update the client version automatically with this. It contains `INNERTUBE_CLIENT_VERSION`

right now the json endpoint is tried first, then the watch.html endpoint. the json endpoint hasn't been very reliable though, except with cookies i hear, so we could switch their position and then grab the client version in case the watch.html endpoint fails
