### ISSUE TITLE
I got "Error: input stream: Video unavailable", but we can see that video.

### ISSUE THREAD

**Issue by cjh980402** [fent/node-ytdl-core#802]
```
Error: input stream: Video unavailable
    at Object.exports.playError (/home/ubuntu/my_bot/node_modules/ytdl-core/lib/utils.js:116:12)
    at downloadFromInfoCallback (/home/ubuntu/my_bot/node_modules/ytdl-core/lib/index.js:72:19)
    at /home/ubuntu/my_bot/node_modules/ytdl-core/lib/index.js:20:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I use "ytdl-core" latest version (4.1.1). and using "discord-ytdl-core" module that use own ytdl-core (latest version (4.1.1)).
when I use 
```
const ytdlDiscord = require("discord-ytdl-core");
stream = ytdlDiscord("https://youtu.be/kSsAj90BSBk", {
    filter: "audioonly",
    quality: "highestaudio",
    highWaterMark: 1 << 25,
    opusEncoded: true,
    encoderArgs: ['-af', 'bass=g=10,dynaudnorm=f=200']
});
```
and play the stream, I got "Error: input stream: Video unavailable".
```
queue.connection.play(stream, { type: "opus", volume: queue.volume / 100 })
    .on("finish", async () => {
        // etc...
    })
    .on("error", async (err) => {
        console.error(err); // I got Error!
        // etc...
    });
```
But we can see the video of "https://youtu.be/kSsAj90BSBk", so that video isn't restricted.
Then why I got that error?

**Comment by skick1234** [comment]
It's not available in your vps (bot) country. Not related to your pc.

**Comment by cjh980402** [comment]
I know, so yesterday I use VPN to change country that is same bot country.
But I can see that video. (Bot doesn't)
So I open the issue.

**Comment by skick1234** [comment]
Google ip location is not correct 100%. My vps at US but Google think it is in UAE. You should use your vps as a vpn then connect to it for testing.

**Comment by cjh980402** [comment]
When I connected "https://youtu.be/kSsAj90BSBk" link using browser and node-fetch module in my bot vps, that video isn't restricted....
My vps can connected to video, but still got "Error: input stream: Video unavailable"

**Comment by SheIITear** [comment]
I have same problem. The video is indeed available, but I don't know why I get this error.

**Comment by modscleo4** [comment]
Are you sure your bot is not hosted in these locations: https://watannetwork.com/tools/blocked/#url=kSsAj90BSBk ?
And if the video is age-restricted and unembeddable, it will not be ytdl-core can not play it

I tested the video on my own bot and it works (hosted in United States)

**Comment by Alexmdz77** [comment]
Anything new? I have the same issue...

**Comment by Alexmdz77** [comment]
My VPS is hosted in France/Europe and this video "https://www.youtube.com/watch?v=dQw4w9WgXcQ" for exemple gives me the error : "Video Unavailable".

**Comment by brennanwilkes** [comment]
Any success? I'm having this problem for `https://www.youtube.com/watch?v=0NChtZCDCsY` on a bot hosted in the US. 

```
Error: Video unavailable at Object.exports.playError (/usr/src/app/node_modules/ytdl-core/lib/utils.js:124:12) at downloadFromInfoCallback (/usr/src/app/node_modules/ytdl-core/lib/index.js:72:19) at /usr/src/app/node_modules/ytdl-core/lib/index.js:20:5 at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

where downloadFromInfoCallback is my function

**Comment by brennanwilkes** [comment]
If anyone in the future sees this, my problem was that for some reason the "bestaudio" format I was looking for didn't exist for the requests coming from the server my bot was running on, but did exist for my local instance. While the video itself is available in all countries, but clearly the audioonly format must not have been.
