### ISSUE TITLE
Cannot read property 'playerMicroformatRenderer' of undefined

### ISSUE THREAD

**Issue by Romick2005** [fent/node-ytdl-core#804]
## Checklist
- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **4.1.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log
```
Cannot read property 'playerMicroformatRenderer' of undefined
```

## Description
I was trying to download multiples videos with at same time (10 at a time) and for some loading videos I got error:
`Cannot read property 'playerMicroformatRenderer' of undefined`
Next time, when I stated redownloading process for not loaded videos from previous step, that error dissapear and was never shown.

Seems like there are some memory leak or not proper async resources handling.
1) So for example this videos is available https://www.youtube.com/embed/lDYrm3UxNws, but code complains UnrecoverableError: This is a private video. Please sign in to verify that you may see it. Probably it is complaining on some other video.
 2) https://www.youtube.com/embed/cCLX4Vq-Hbo TypeError: Cannot read property 'playerMicroformatRenderer' of undefined
It happens on videos that actually is private, but first time it show this error and next time it could be  This is a private video. Please sign in to verify that you may see it.

List of private videos:
"https://www.youtube.com/embed/cCLX4Vq-Hbo",
"https://www.youtube.com/embed/5Sis_NySlBc",
"https://www.youtube.com/embed/BQI29vH9aFg",
"https://www.youtube.com/embed/f46ziMMNOxk"

[testCase.zip](https://github.com/fent/node-ytdl-core/files/5630878/testCase.zip)

Test cases results:
![image](https://user-images.githubusercontent.com/17779660/100906360-c736d200-34d1-11eb-8392-e86cef71ede3.png)
![image](https://user-images.githubusercontent.com/17779660/100906419-d584ee00-34d1-11eb-964b-3803b55e4b10.png)

Initialy I posted it [here ](https://github.com/ytdl-org/youtube-dl/issues/27273), but after investigation it seems like node wrapper library problem.

**Comment by Romick2005** [comment]
After updating to 4.1.2 issue become worse
![image](https://user-images.githubusercontent.com/17779660/101018811-b7bc9500-3574-11eb-9b5b-81924eec3258.png)
Now video file creating and then after error automatically removed.

**Comment by fent** [comment]
status code 429 is another issue, tracked in https://github.com/fent/node-ytdl-core/issues/635

ytdl-core doesn't handle creating or removing files

**Comment by Romick2005** [comment]
Yes actually that was my code that checks zero sized video downloads or files that was downloaded with error. So for the next iteration download only absent video files. The odd thing here is that yesterday with 3 iterations I was able to download 410 files, but after update I tried to load same files and got zero downloaded files.
