### ISSUE TITLE
info.videoDetails.author.name is undefined

### ISSUE THREAD

**Issue by Peppy8651** [fent/node-ytdl-core#806]
When I try to get info.videoDetails.author.name, it returns undefined. This is some basic code that I use to try to get it.
``const ytdl = require('ytdl-core');
ytdl.getBasicInfo('https://www.youtube.com/watch?v=QHVREB6fdvI').then(info => console.log(info.videoDetails.author.name));``
What it's supposed to do is to get the author name, however instead it returns undefined with no error.  All the videos that I test it with just return undefined using `info.videoDetails.author.name`. My current ytdl-core version is 4.1.2.

**Comment by emelin2004** [comment]
Can confirm that this happens to me almost on every video.

**Comment by danbulant** [comment]
`videoDetails.author` is missing for every video I tried

ytdl-core@4.1.2
node 15.2.0
npm 7.0.8

Linux Manjaro

**Comment by Peppy8651** [comment]
https://github.com/fent/node-ytdl-core/issues/809

**Comment by Peppy8651** [comment]
I think this is a better issue that describes what's going on way better.
