### ISSUE TITLE
Wrong properties

### ISSUE THREAD

**Issue by danbulant** [fent/node-ytdl-core#809]
The following properties of videoDetails are wrong:

`author` is nearly always empty object

`likes` and `dislikes` are null

`shortDescription` is missing; `description.simpleText` exists instead although it's not typed.

ytdl-core@4.1.2 (`latest` on npm)
node 15.2.0
npm 7.0.8

**Comment by Peppy8651** [comment]
Yup, I bet this is what's going on. Hopefully this gets fixed soon.
