### ISSUE TITLE
new feature: next video

### ISSUE THREAD

**Issue by Alexandre94H** [fent/node-ytdl-core#810]
Can someone add parsedBody.response.contents.twoColumnWatchNextResults.autoplay.autoplay.sets[0].autoplayVideo.watchEndpoint.videoId to have the next video ?

**Comment by fent** [comment]
?

**Comment by Bog12555** [comment]
Probably he meant related video id for an autoplay function.
Related issue: fent/node-ytdl-core#800

**Comment by fent** [comment]
is this not included in `relatedVideos`?

**Comment by Alexandre94H** [comment]
in getRelatedVideos in the file 

> Probably he meant related video id for an autoplay function.
> Related issue: #800

**Comment by Alexandre94H** [comment]
![Untitled](https://user-images.githubusercontent.com/52411215/101475135-47cf5580-394c-11eb-9f76-e8cea4f41cde.png)

I want the next song of the autoplay, you can see the picture for better explanation.

I tried something that works:
in info-extras.js i add:
exports.getNextVideoId = info => {
	let id;
	try {
		id = info.response.contents.twoColumnWatchNextResults.autoplay.autoplay.sets[0].autoplayVideo.watchEndpoint.videoId
	} catch (err) {

	}
	return (id);
}

in info.js in the function getBasicInfo i transform
  Object.assign(info, {
    formats: parseFormats(info.player_response),
    related_videos: extras.getRelatedVideos(info),
  });
to
  Object.assign(info, {
    formats: parseFormats(info.player_response),
    related_videos: extras.getRelatedVideos(info),
    nextId: extras.getNextVideoId(info)
  });

and now when i do console.log((await ytdl.getBasicInfo(id)).nextId);
i have the next song of the autoplay
:D

**Comment by Alexandre94H** [comment]
To get the related videos, you do:
```
secondaryResults = info.response.contents.twoColumnWatchNextResults.secondaryResults.secondaryResults.results;
```
and for the autoplay, it is:
```
id = info.response.contents.twoColumnWatchNextResults.autoplay.autoplay.sets[0].autoplayVideo.watchEndpoint.videoId;
```

**Comment by Alexandre94H** [comment]
> is this not included in `relatedVideos`?

no, it is not included in the `relatedVideos`
see messages above for more information

**Comment by Alexandre94H** [comment]
> Probably he meant related video id for an autoplay function.
> Related issue: #800

no, I want to have a new feature on `ytdl-core`

**Comment by Alexandre94H** [comment]
Are you going to add the feature or can I add it myself?

**Comment by fent** [comment]
that'd be great if you can add it, `nextVideo` is a good field name. since this object is very similar to related videos, look in `info-extras.js` for code both can share

**Comment by Alexandre94H** [comment]
daccord je fais ca parfait

**Comment by patrickkfkan** [comment]
If you want to achieve some sort of endless playing, it seems more is required than just getting the autoplay video id from the responses. I've done something similar and found that the number of repetitive videos encountered along the way is much higher than what you would get on YouTube. Here's a quick test (is it OK to include video ids here?):

```
const ytdl = require('ytdl-core');

async function getAutoplayVideoId(url) {
    let info = await ytdl.getInfo(url);
    return info.response.contents.twoColumnWatchNextResults.autoplay.autoplay.sets[0].autoplayVideo.watchEndpoint.videoId;
}

async function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function test() {
    let videoId = 'g8NVwN0_mks';
    let i = 0, iterations = 10, sleepMS = 5000;
    console.log(`Going to fetch Autoplay video IDs, starting with ${videoId}`);
    console.log(`Number of iterations: ${iterations}, sleeping ${sleepMS / 1000} seconds in between.`);
    console.log('');
    console.log('Autoplay Video IDs');
    console.log('==================');
    
    while (i < iterations) {
        let autoplayVideoId = await getAutoplayVideoId(videoId);
        console.log((i + 1) + ': ' + autoplayVideoId);
        videoId = autoplayVideoId;
        i++;
        if (i < iterations) {
            await sleep(sleepMS);
        }
    }
    
}

test();
```

Here's what I got from running the test:

```
$ node test-ytdl-autoplay.js 
Going to fetch Autoplay video IDs, starting with g8NVwN0_mks
Number of iterations: 10, sleeping 5 seconds in between.

Autoplay Video IDs
==================
1: GBexfwe-9j0
2: lhSuDxPw6f4
3: mJYidtfib1I
4: lhSuDxPw6f4
5: mJYidtfib1I
6: lhSuDxPw6f4
7: 05N4ppUmZPI
8: lhSuDxPw6f4
9: mJYidtfib1I
10: lhSuDxPw6f4
```
You can see the videos repeating themselves quite a lot, which you would hardly see on YouTube. So something is missing but I know too little to be able to tell what. Perhaps it's something to do with cookies?

I would really like to see this added to ytdl-core, but simply getting the autoplay video id from getBasicInfo() does not seem to be robust enough.
