### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: No video id found

### ISSUE THREAD

**Issue by jerkdavi** [fent/node-ytdl-core#812]
Hello,

I'm quite new to the discord.js programming, and to the github repository, so please be gentle.
I'm working on my own music bot, and it works fine when the youtube link you post is valid.
My question is, can you make a check in the code, if the youtube link is valid before it pushes the arguments, so you don't get the error in the title and the bot doesn't get stuck in some weird loop of not being able to use further commands.

With kind regards,
David

**Comment by Synkky** [comment]
Start by reading the documentation thoroughly next time (albeit I know it's not too well organized)
https://github.com/fent/node-ytdl-core#ytdlvalidateurlurl

**Comment by jerkdavi** [comment]
Didn't think it would be such a simple command. Thank you so much. :)
