### ISSUE TITLE
Crash bot discord

### ISSUE THREAD

**Issue by DimaD16** [fent/node-ytdl-core#814]
Hello, i have a bot music discord ans i start play ... The bot start, when the bot as a errors in console, the bot crash and a long errors ytdl-core in a console. Please help me

**Comment by TimeForANinja** [comment]
can you provide the error & stack?

**Comment by haruzinh0** [comment]
same here.

return this.encoder.decode(buffer, Opus.name === 'opusscript' ? null : this._options.frameSize);
                        ^

TypeError: The compressed data passed is corrupted

**Comment by trandung1291** [comment]
ytdl.getInfo(url, options).then(info => {});
  i can't exit my cli when i run my file example.js

**Comment by DimaD16** [comment]
It is a long errors
![image](https://user-images.githubusercontent.com/65355466/101521816-9ac5fe80-3986-11eb-9b66-8391b339dbc4.png)

**Comment by brunogomes98** [comment]
Error: Error parsing info: Unable to retrieve video metadata
    at getWatchPage (C:\Users\Bruno\Desktop\Desktop D\TestarBOT\node_modules\ytdl-core\lib\info.js:75:13)   
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async exports.getBasicInfo (C:\Users\Bruno\Desktop\Desktop D\TestarBOT\node_modules\ytdl-core\lib\info.js:84:22)
    at async Map.getOrSet (C:\Users\Bruno\Desktop\Desktop D\TestarBOT\node_modules\ytdl-core\lib\cache.js:24:19)
    at async exports.getInfo (C:\Users\Bruno\Desktop\Desktop D\TestarBOT\node_modules\ytdl-core\lib\info.js:226:14)
    at async Map.getOrSet (C:\Users\Bruno\Desktop\Desktop D\TestarBOT\node_modules\ytdl-core\lib\cache.js:24:19)
    at async download (C:\Users\Bruno\Desktop\Desktop D\TestarBOT\node_modules\ytdl-core-discord\index.js:26:15)

**Comment by TimeForANinja** [comment]
> It is a long errors
> ![image](https://user-images.githubusercontent.com/65355466/101521816-9ac5fe80-3986-11eb-9b66-8391b339dbc4.png)

the only error i see in there is `DiscordAPIError: Missing Permissions` so check if the bot is allowed to join the channel and play there
besides that doesn't look like a ytdl-core issue

**Comment by TimeForANinja** [comment]
> Error: Error parsing info: Unable to retrieve video metadata
> at getWatchPage (C:\Users\Bruno\Desktop\Desktop D\TestarBOT\node_modules\ytdl-core\lib\info.js:75:13)
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> at async exports.getBasicInfo (C:\Users\Bruno\Desktop\Desktop D\TestarBOT\node_modules\ytdl-core\lib\info.js:84:22)
> at async Map.getOrSet (C:\Users\Bruno\Desktop\Desktop D\TestarBOT\node_modules\ytdl-core\lib\cache.js:24:19)
> at async exports.getInfo (C:\Users\Bruno\Desktop\Desktop D\TestarBOT\node_modules\ytdl-core\lib\info.js:226:14)
> at async Map.getOrSet (C:\Users\Bruno\Desktop\Desktop D\TestarBOT\node_modules\ytdl-core\lib\cache.js:24:19)
> at async download (C:\Users\Bruno\Desktop\Desktop D\TestarBOT\node_modules\ytdl-core-discord\index.js:26:15)

update

**Comment by TimeForANinja** [comment]
> ytdl.getInfo(url, options).then(info => {});
> i can't exit my cli when i run my file example.js
> ![Screenshot from 2020-12-08 15-27-35](https://user-images.githubusercontent.com/8279284/101458853-03eb4900-396a-11eb-8e5e-186f04c1313c.png)

@trandung1291 no error and doesn't look like it's from `ytdl.getInfo`

**Comment by Alexandre94H** [comment]
The problem comes from opus, the most frequent problem is that your program crashes and therefore opus too.

Can you come on the discord?

**Comment by BR88C** [comment]
> same here.
> 
> return this.encoder.decode(buffer, Opus.name === 'opusscript' ? null : this._options.frameSize);
> ^
> 
> TypeError: The compressed data passed is corrupted

Did you install `@discordjs/opus` or `opusscript`, and if so what version are you running?
