### ISSUE TITLE
Multiple JSON page requests made before falling back to watch page

### ISSUE THREAD

**Issue by benkaiser** [fent/node-ytdl-core#815]
Created a comment on the relevant line here: https://github.com/fent/node-ytdl-core/commit/60cdb41a8bb2a7334edd5e464e4dc5f178f9c6e5#r44919269

Basically it appears that the token logic is setting a promise to the cache rather than the actual value now. As a result I'm seeing ytdl make a bunch of json requests all with "reload now" responses before finally falling back to the watch page.

It does eventually resolve with the right information, but it's causing the performance to be sub-par (~several seconds for getInfo).

Here is a network trace with the current logic:

First request:
![image](https://user-images.githubusercontent.com/608054/101497532-307d8000-39bf-11eb-9d82-65d26cf42b88.png)
Second request:
![image](https://user-images.githubusercontent.com/608054/101497831-818d7400-39bf-11eb-9274-1c5b3d270c4a.png)

And by updating `getIdentityToken` to this: (basically don't use `cookieCache.getOrSet`, actually make it a promise and `cookieCache.set` in the later part of the promise):
```
const getIdentityToken = async (id, options, key, throwIfNotFound) => {
  let page = await getHTMLWatchPageBody(id, options);
  let match = page.match(/(["'])ID_TOKEN\1[:,]\s?"([^"]+)"/);
  if (!match && throwIfNotFound) {
    throw new UnrecoverableError('Cookie header used in request, but unable to find YouTube identity token');
  }
  exports.cookieCache.set(key, match && match[2]);
  return match && match[2];
};
```

First request:
![image](https://user-images.githubusercontent.com/608054/101497658-52770280-39bf-11eb-911a-eb600c12e05c.png)

Second request:
![image](https://user-images.githubusercontent.com/608054/101497724-628ee200-39bf-11eb-8d0b-802887ef63e5.png)

**Comment by fent** [comment]
the json endpoint returning `{"reload":"now"}` started happening about 1 to 2 weeks ago. it's not related to the cache returning a promise. the identity token request happens after the json request, when it previously wasn't needed since we'd get a good reply on the first request

**Comment by benkaiser** [comment]
@fent surely we aren't intending on passing a header with `[object Promise]` as the value thought?

![image](https://user-images.githubusercontent.com/608054/101586040-2c8c4500-3a35-11eb-9db6-05bdafe29c58.png)

**Comment by benkaiser** [comment]
Hey @fent, I think we need to revisit. I'm still seeing promises being sent in the x-youtube-identity-token.

Would you be open to my submitting a pull-request to fix?

**Comment by TimeForANinja** [comment]
fent is currently taking a bit of a break
but if you manage to fix it a PR is always welcome 😉 
it's a good start for a discussion
