### ISSUE TITLE
Livestream audio "buffering" a lot.

### ISSUE THREAD

**Issue by snacksncode** [fent/node-ytdl-core#817]
## Issue
Hello, when I try to create stream from a livestream link audio works inconsistently. I'd describe it as working for 30s then "buffering" and playing 20s again and then "buffering" again. Also if I use the `filter: "audioonly"` the stream only holds like 1-2s of playback and then stops. I was suggested to stop using `filter` overall and now I'm facing "buffering" issue.
## Code that causes the issue:
`opusEncoded` and `encoderArgs` come from me using discord-ytdl-core but it's just a wrapper for ytdl-core. And the creator suggested that the issue might be with ytdl-core itself thus my issue. If I'm wrong feel free to close it.
```js
let audioStream = ytdl(song.id, {
  quality: "highestaudio",
  opusEncoded: true,
  encoderArgs: ["-af", "bass=g=10,dynaudnorm=f=200"],
  highWaterMark: 1 << 25
});
const voiceChannelDispatcher = guildQueue.connection.play(audioStream, {
  type: "opus"
})
//rest of the listeners chained here
```
## System info
- OS: Arch Linux
- ytdl-core: 4.1.4
- NodeJS: 15.x
- Priority: low/medium

**Comment by Alexandre94H** [comment]
The problem is with `discord-ytdl-core`, the stream is not handled by` ytdl-core`.

**Comment by Alexandre94H** [comment]
Can you do this ?
```
const opus = ytdl.arbitraryStream((await getvideo(client, id)).format, {
		opusEncoded: true,
		encoderArgs: ['-af', 'bass=g=10,dynaudnorm=f=200']
	});
	const dispatcher = client.music[guildId].connection.player.createDispatcher({
		type: 'opus',
		fec: true,
		bitrate: 48
	}, { opus });
	opus.pipe(dispatcher);
```

**Comment by TimeForANinja** [comment]
@snacksncode it's hard if not impossible for us to debug it this way
try using raw ytdl-core ([example available here](https://github.com/fent/node-ytdl-core/blob/master/example/discord.js)) to exclude ffmpeg & discord-ytdl-core related issues

**Comment by Alexandre94H** [comment]
dont use this

**Comment by Alexandre94H** [comment]
you need ffmpeg and opus for discord.js

**Comment by Alexandre94H** [comment]
when you do a `play(ytdl(` you are only using opus see [discord.js player](https://github.com/discordjs/discord.js/blob/master/src/client/voice/player/BasePlayer.js)

**Comment by snacksncode** [comment]
> Can you do this ?
> 
> ```js
> const info = await ytdl.getInfo(id);
> const format = ytdl.chooseFormat(video.formats, {
>     filter: 'audioonly',
>     quality: 'highestaudio'
> });
> const opus = ytdl.arbitraryStream(format.link, {
>     opusEncoded: true,
>     encoderArgs: ['-af', 'bass=g=10,dynaudnorm=f=200']
> });
> const dispatcher = client.music[guildId].connection.player.createDispatcher({
>     type: 'opus',
>     fec: true,
>     bitrate: 48
> }, {
>     opus
> });
> opus.pipe(dispatcher);
> ```
Where does `video.formats` come from. Is createDispatcher avaible on connection.player? I don't see it in docs and typescript says there's no such thing. Is bitrate being 48 and not 96 makes a difference?

**Comment by Alexandre94H** [comment]
sorry change `video.formats` to `info.fornats`

and i know this is not on the doc but if you search in the file all of this is available

**Comment by snacksncode** [comment]
```ts
const format = ytdl.chooseFormat(song.formats, {
  filter: "audioonly",
  quality: "highestaudio",
});

const opus = ytdl.arbitraryStream(format.url, {
  opusEncoded: true,
  encoderArgs: ["-af", "bass=g=10,dynaudnorm=f=200"],
});

const dispatcher = (guildQueue.connection.player as any).createDispatcher(
  {
    type: "opus",
    fec: true,
    bitrate: 48,
  },
  {
    opus,
  }
);

opus.pipe(dispatcher);

dispatcher.on("finish", () => {
  guildQueue.songs.shift();
  playSong(msg, guildQueue.songs[0]);
});
```
Sooo I did this. `format.link` doesn't exist but `format.url` does. Also `song.formats` holds all the formats (I don't like double fetching so I just added it temporary)
```ts
const songObject: Song = {
  id: songInfo.videoDetails.videoId,
  title: songInfo.videoDetails.title,
  url: songInfo.videoDetails.video_url,
  formats: songInfo.formats,
  length: Number(songInfo.videoDetails.lengthSeconds),
  formattedLength: formatSongLength(Number(songInfo.videoDetails.lengthSeconds)),
  requestedBy: msg.author,
};
```
And what happens is the bot joins VC, I get the "bot started playing" message from my bot and then it instantly leaves as if song was 0s long. Wtf?

**Comment by BR88C** [comment]
> ```ts
> const format = ytdl.chooseFormat(song.formats, {
>   filter: "audioonly",
>   quality: "highestaudio",
> });
> 
> const opus = ytdl.arbitraryStream(format.url, {
>   opusEncoded: true,
>   encoderArgs: ["-af", "bass=g=10,dynaudnorm=f=200"],
> });
> 
> const dispatcher = (guildQueue.connection.player as any).createDispatcher(
>   {
>     type: "opus",
>     fec: true,
>     bitrate: 48,
>   },
>   {
>     opus,
>   }
> );
> 
> opus.pipe(dispatcher);
> 
> dispatcher.on("finish", () => {
>   guildQueue.songs.shift();
>   playSong(msg, guildQueue.songs[0]);
> });
> ```
> 
> Sooo I did this. `format.link` doesn't exist but `format.url` does. Also `song.formats` holds all the formats (I don't like double fetching so I just added it temporary)
> 
> ```ts
> const songObject: Song = {
>   id: songInfo.videoDetails.videoId,
>   title: songInfo.videoDetails.title,
>   url: songInfo.videoDetails.video_url,
>   formats: songInfo.formats,
>   length: Number(songInfo.videoDetails.lengthSeconds),
>   formattedLength: formatSongLength(Number(songInfo.videoDetails.lengthSeconds)),
>   requestedBy: msg.author,
> };
> ```
> 
> And what happens is the bot joins VC, I get the "bot started playing" message from my bot and then it instantly leaves as if song was 0s long. Wtf?

Most likely it is because you aren't picking a livestream compatable itag, as most itags only grab 2-5 seconds of a livestream as their format doesn't support live streams. You can get around this by getting a format with the `isHLS` option

**Comment by BR88C** [comment]
One thing with specifying `isHLS`, it wont work if the video isn't a livestream (no valid formats will be found), so the solution to that is just having an if else statement based off of `songInfo.videoDetails.isLive` that points to specifying if `isHLS` should be true or false

**Comment by snacksncode** [comment]
raw `ytdl-core` works with `isHLS` option. (Although it's not specified in typescript definitions so I had to cast at as any). That other library still doesn't work even with `isHLS` I guess it's something on their part. I'm using raw `ytdl-core` for livestreams and `discord-ytdl-core` for normal vids now. Thank you for help! Closing issue
