### ISSUE TITLE
Add Playlist support

### ISSUE THREAD

**Issue by snuckdev** [fent/node-ytdl-core#822]
Can you add a playlist support please? Add an entire playlist. Thanks.

**Comment by TimeForANinja** [comment]
that's not a feature planned
you can use the official youtube api through sth like [simple-youtube-api](https://www.npmjs.com/package/simple-youtube-api)
or unofficial scrapers like [ytpl](https://www.npmjs.com/package/ytpl)

**Comment by H34Dlezman** [comment]
wrote a lil script that works atm
https://github.com/H34Dlezman/node-ytdl-core-playlists
