### ISSUE TITLE
[Not a bug, Question] How can i make a youtube video start downloading immediately without storing it?

### ISSUE THREAD

**Issue by deniscerri** [fent/node-ytdl-core#825]
Hi. To clear this question out. I have made a website with a simple interface that downloads videos using ytdl-core
Everything works fine but when i want to download something i have to wait for it to download on the server side where i use ytdl. meanwhile the website is just loading the requested URL. 

How do i make it so when i click it, the download starts directly on the browser and not wait.

Download starts immediately if im downloading at 'highest' quality, but when i am trying to combine video and audio with ffmpeg for higher quality vids. I have to wait for that to happen before the download starts. Is there a way to convert chunks of the video and download them immediately?

This can get really annoying if im trying to download a really long video. I don't even know if something went wrong because all im calling is 

window.location.href = 'https://localhost:3000/download/?URL=....'

I would really appreciate if you could help. Thank you for your hard work in ytdl-core

**Comment by fent** [comment]
try using a redirect status code when you get the url

**Comment by redbrain** [comment]
> How do i make it so when i click it, the download starts directly on the browser and not wait.

If I understand your question correctly, you'll want to pipe the stream directly to the route, rather than storing it somewhere else.

**Comment by deniscerri** [comment]
@redbrain yes exactly

**Comment by Aasim-A** [comment]
Hi @deniscerri , I have put together this [example](https://gist.github.com/Aasim-A/669791a9f674971cfe041ee2d7065b24) that uses express to download videos normally and through ffmpeg directly from route. Hope this helps.

**Comment by deniscerri** [comment]
> Hi @deniscerri , I have put together this [example](https://gist.github.com/Aasim-A/669791a9f674971cfe041ee2d7065b24) that uses express to download videos normally and through ffmpeg directly from route. Hope this helps.

This is exactly what i was looking for. Thank you very much.
