### ISSUE TITLE
Remove html-entities from dependencies

### ISSUE THREAD

**Issue by Hazmi35** [fent/node-ytdl-core#826]
~~It's faster, with 12.655 kB less unpacked size, I could create a PR if you want to~~ 

Remove html-entities from dependencies because we're not using it anymore (https://github.com/fent/node-ytdl-core/issues/826#issuecomment-745045766)

**Comment by fent** [comment]
i just looked through the repo, we're actually not using `html-entities` anymore and forgot to remove it. it was being used when many of the `info.videoDetails` fields were being scraped from the html, but they're not anymore

**Comment by Hazmi35** [comment]
Ah, that's why when I searched for "html-entities" on this repository it's only managed to find only in package.json, then we should remove it
