### ISSUE TITLE
Error: Error parsing info: Unable to retrieve video metadata

### ISSUE THREAD

**Issue by chiquicalris-dev** [fent/node-ytdl-core#830]
### Error: Error parsing info: Unable to retrieve video metadata

It show this error when I try to play a song in my discord bot.

![image](https://user-images.githubusercontent.com/38810865/102393328-80200500-3fd8-11eb-8bb3-34d3ceebc37a.png)

**Comment by TimeForANinja** [comment]
try updating ytdl-core

**Comment by chiquicalris-dev** [comment]
No, it continues showing the same error @TimeForANinja 

![image](https://user-images.githubusercontent.com/38810865/102396949-82d12900-3fdd-11eb-9be0-102188910693.png)

**Comment by TimeForANinja** [comment]
🤔 that second error might have to do with it
```
TypeError: Cannot read properrty 'url' of undefined
```

**Comment by TimeForANinja** [comment]
didn't spot it the first time: looks like you're using `ytdl-core-discord`
it's known to use **out-of-date** `ytdl-core` versions, which is hard to upgrade for the enduser
i advice using plain ytdl-core or switching to sth maintained like `discord-ytdl-core`

**Comment by BR88C** [comment]
> didn't spot it the first time: looks like you're using `ytdl-core-discord`
> it's known to use **out-of-date** `ytdl-core` versions, which is hard to upgrade for the enduser
> i advice using plain ytdl-core or switching to sth maintained like `discord-ytdl-core`

If you really want to stick with `ytdl-core-discord` you could manually set `ytdl-core`'s version in `package-lock.json`
