### ISSUE TITLE
Begin parameter not working

### ISSUE THREAD

**Issue by Hydreau** [fent/node-ytdl-core#838]
Hello, I'm creating a discord bot that can plays music in voice channels, but the problem is that i'm stucked because i'm trying to use the "begin" option with the "audioonly" filter, but it still starting at the beggining of the video. I don't get any error message and i've tried a lot of different videos(Long, short, begin more than 6s, video longer than 30seconds). It would be really appreciated to get some answers about how to solve this issue.

Some more informations :

Libraries version :
- **FFmepg-static** : 4.2.7
- **Ytdl-core** : Latest version (4.2.1)
---------------------------------------------------------------------------------------------
The code i'm using :

const dispatcher = connection.play(ytdl(videoUrl, { filter: 'audioonly', begin: '10s' } ));

dispatcher.on('finish', () => {
        message.member.voice.channel.leave();
});

By the way i'm not English, so sorry for any bad speaking or grammar failures. Thanks !

**Comment by fent** [comment]
well, it's always been not too reliable. maybe youtube finally removed it completely.

**Comment by HydroElit** [comment]
Yeah, i know that but do you have any solution to start the audio stream at a certain time of the video, including third party libraries or anything else ?

**Comment by fent** [comment]
try the `time_range.js` example

https://github.com/fent/node-ytdl-core/blob/master/example/time_range.js

**Comment by HydroElit** [comment]
I will look at it, thank you !

**Comment by fent** [comment]
np. i might just update the docs to reflect that `begin` will only work on live videos

**Comment by modscleo4** [comment]
Since you are using Discord.js, you can set the `seek` property on `connection.play()`

```js
serverQueue.connection.play(serverQueue.song.stream, {
    seek: 10,
    volume: serverQueue.volume / 100,
    highWaterMark,
})
```

**Comment by HydroElit** [comment]
I think that fent and modscleo have both the solution to my issue, so i close it, Thanks anyway !.

**Comment by HydroElit** [comment]
i re-open because i just want to know if the seek option is in miliseconds or in seconds ?

**Comment by BR88C** [comment]
> i re-open because i just want to know if the seek option is in miliseconds or in seconds ?

Seconds

**Comment by HydroElit** [comment]
Ok, thanks for your explanations, but I still don't understand why seek has no effect in my code, I'd like when a user enters the command that plays music to retrieve the "t=" part of the youtube url and start reading this one in relation to that. I manage to get this back, but the seek doesn't seem to have any effect, here is my code if you can help me, I admit I'm a bit lost about it. Here is my code if it could help to fix the issue (The "time" variable is in seconds) :

async runVideo(message, connection, video) 
{
        const time = message.split('?t=');
        const dispatcher = connection.play(ytdl(video, { filter: 'audioonly', seek: ms} ));
}

**Comment by BR88C** [comment]
> Ok, thanks for your explanations, but I still don't understand why seek has no effect in my code, I'd like when a user enters the command that plays music to retrieve the "t=" part of the youtube url and start reading this one in relation to that. I manage to get this back, but the seek doesn't seem to have any effect, I admit that I'm a little bit lost about it. Here is my code if it could help to fix the issue (The "time" variable is in seconds) :
> 
> async runVideo(message, connection, video)
> {
> const time = message.split('?t=');
> const dispatcher = connection.play(ytdl(video, { filter: 'audioonly', seek: time} ));
> }

`time` Needs to be an integer, you are specifying it as a string.
```
seek: parseInt(time)
```

**Comment by HydroElit** [comment]
I maked what you've sayed before but it still not working :

const dispatcher = connection.play(ytdl(video, { filter: 'audioonly', seek: parseInt(time[1]) } ));

**Comment by BR88C** [comment]
> I maked what you've sayed before but it still not working :
> 
> const dispatcher = connection.play(ytdl(video, { filter: 'audioonly', seek: parseInt(time[1]) } ));

Could you console.log time for me

**Comment by HydroElit** [comment]
Yes, here it is :

2020-12-20T13:14:36.672087+00:00 app[Worker.1]: 60

**Comment by BR88C** [comment]
> Yes, here it is :
> 
> 2020-12-20T13:14:36.672087+00:00 app[Worker.1]: 60
> 
> It logs 60.

what does console.log(typeof time) return

**Comment by HydroElit** [comment]
Here is the code if it can help understanding the log :

const time = message.content.split('?t=');
console.log(typeof time[1]);

const dispatcher = connection.play(ytdl(video, { filter: 'audioonly', seek: parseInt(time[1]) } ));

And here is the output :

2020-12-20T13:23:59.436506+00:00 app[Worker.1]: string

**Comment by BR88C** [comment]
> Here is the code if it can help understanding the log :
> 
> const time = message.content.split('?t=');
> console.log(typeof time[1]);
> 
> const dispatcher = connection.play(ytdl(video, { filter: 'audioonly', seek: parseInt(time[1]) } ));
> 
> And here is the output :
> 
> 2020-12-20T13:23:59.436506+00:00 app[Worker.1]: string

Ok, so we know it isn't an issue with the value are specifying
Personally I don't use stream options to specify a start time, rather I use an option in the ytdl wrapper I use. If you are unable to get it to work with stream options just try that out, it's `discors-ytdl-core`
If you are still unable to get it to work with that module make an issue there on that repo

**Comment by HydroElit** [comment]
Ok, i will look at discord-ytdl-core, but what's the difference between them ?

**Comment by BR88C** [comment]
> Ok, i will look at discord-ytdl-core, but what's the difference between them ?

The main difference is it allows you to specify ffmpeg args among other things, just look at the README there as it explains how to use it and what it can do

**Comment by HydroElit** [comment]
Ok, I finally managed to get the seek parameter to work, thanks to the following code and the problem did come from the stream as you said. Thanks anyway for your good explanations and your patience.

Here's the code if it can help anyone having the same issue than me.

const time = message.content.split('?t=');

const stream = ytdl(video);
const song = stream;

const dispatcher = connection.play(song, {filter: 'audioonly', seek: parseInt(time[1])});
