### ISSUE TITLE
Live stream only plays for a few seconds

### ISSUE THREAD

**Issue by modscleo4** [fent/node-ytdl-core#839]
When I try to play https://www.youtube.com/watch?v=5qap5aO4i9A on my Discord bot, the live only plays for a few seconds and then it stops. No errors thrown in the console.

My code:
```js
serverQueue.song.stream = isAsync(serverQueue.song.fn) ? await serverQueue.song.fn(serverQueue.song.url, serverQueue.song.options) : serverQueue.song.fn(serverQueue.song.url, serverQueue.song.options);

serverQueue.connection.play(serverQueue.song.stream, {
    seek: serverQueue.seek,
    volume: serverQueue.volume / 100,
    highWaterMark,
})
```

YTDL options:
```js
options: {
    filter: 'audioonly',
    highWaterMark: 4096,
    quality: 'highestaudio',
    dlChunkSize: 0,
    requestOptions: {
        host: '*****.herokuapp.com',
        headers: {
            Authorization: `Bearer ${ytapikey}`,
        }
    },
},
```

**Comment by BR88C** [comment]
This is essentially a duplicate of #817 , the issue is that you are not grabbing an itag with a format that supports livestreams, so you will only get 2-5 seconds of playback then the stream will end. I explain how to resolve this here: https://github.com/fent/node-ytdl-core/issues/817#issuecomment-747776129

**Comment by modscleo4** [comment]
Yes, it was a duplicate of #817 
I managed to solve checking if the video duration is 0 seconds, if yes, then it will use the live stream options 

```js
options: {
    filter: songInfo.duration === 0 ? null : 'audioonly',
    highWaterMark,
    quality: songInfo.duration === 0 ? null : 'highestaudio',
    dlChunkSize,
    isHLS: songInfo.duration === 0,
    requestOptions: {
        host: '*********.herokuapp.com',
        headers: {
            Authorization: `Bearer ${ytapikey}`,
        }
    },
},
```

**Comment by BR88C** [comment]
> Yes, it was a duplicate of #817
> I managed to solve checking if the video duration is 0 seconds, if yes, then it will use the live stream options
> 
> ```js
> options: {
>     filter: songInfo.duration === 0 ? null : 'audioonly',
>     highWaterMark,
>     quality: songInfo.duration === 0 ? null : 'highestaudio',
>     dlChunkSize,
>     isHLS: songInfo.duration === 0,
>     requestOptions: {
>         host: '*********.herokuapp.com',
>         headers: {
>             Authorization: `Bearer ${ytapikey}`,
>         }
>     },
> },
> ```

You can also just use `songInfo.isLive`
