### ISSUE TITLE
Error code 303 when streaming a video more than once

### ISSUE THREAD

**Issue by kettui** [fent/node-ytdl-core#84]
Hey,  
I'm having issues with ytdl-core when trying to stream the same video more than once. Subsequent requests to the same video end up firing the 'error' event due to a 303 response from YouTube.

Looking at the code I saw there was a check for the 302 redirect status code when the library attempts to download the video, but apparently [YouTube uses 303 for this purpose aswell](https://developers.google.com/youtube/v3/docs/core_errors#SEE_OTHER). I tried my hand at fixing the issue but wasn't able to pull it off.  

Not sure if this is an actual issue or if I'm just doing something wrong. Anything helps at this point, though.

Edit: This occurred on both Ubuntu 16.04 and 14.04 LTS, but not on Windows

**Comment by fent** [comment]
Can I see the implementation for it? It should be adding more checks for it here right?

https://github.com/fent/node-ytdl-core/blob/master/lib/index.js#L99

Anyway, I can do this tonight. And do you have a video where this consistently happens? For test purposes.

Looks like error codes 301 and 307 also redirect.

**Comment by kettui** [comment]
I don't have anything left from last night's fiddling, but after taking another look it's apparently [this](https://github.com/fent/node-ytdl-core/blob/master/lib/info.js#L44) request that gets 303'd consistently for me. So in addition to the file you linked, [this](https://github.com/fent/node-ytdl-core/blob/master/lib/request.js#L31) will also need additional checking, as the actual download request never happens if the info request gets redirected.  

The best thing I can say when it comes to testing is that the issue occurs consistently on Ubuntu (tried on two machines, one in a VM and the other in AWS), running the latest Node version. Other than that, there's not much value a video would bring in.

**Comment by kettui** [comment]
Seems like using a similar retry logic as the one you used with the download request did the trick. Will try to squeeze in a PR before heading to bed.

**Comment by fent** [comment]
Ah, that is strange that the error code is a redirect code.

Still, this makes me consider implementing the other redirect codes, and on all requests, not just the downloading of the video.

**Comment by kettui** [comment]
Yeah it's definitely something that should be there, even though it clearly hasn't been an issue thus far. Redirects might become more common at some point.
