### ISSUE TITLE
Resume doesn't seem to work after the newest updates

### ISSUE THREAD

**Issue by JerryFunHouse** [fent/node-ytdl-core#841]
So I recently updated my ytdl-core a few times, I'm not sure which version I ran initially but I am on 4.2.1 right now.

So I've used the pause and resume features for quite a while now, and they always worked. What I just noticed though is that I can pause the music, but I cannot resume it. I didn't change anything in the code (at least not anything that has something to do with pausing and resuming music) 
This is my code:

Pause (WORKS!)
```
function pause(message, serverQueue) {
		if (serverQueue && serverQueue.playing) {
			serverQueue.playing = false;
			serverQueue.connection.dispatcher.pause();
			message.react('✋');
			return message.channel.send('Paused')
		} else if(!serverQueue.playing) {
			return message.channel.send('The music has already been paused');
		}
	return message.channel.send("There\'s  nothing playing");

  }
```

Resume (DOESNT WORK!)
```
function resume(message,serverQueue,msg) {
	if (serverQueue && !serverQueue.playing) {
		serverQueue.playing = true;
		serverQueue.connection.dispatcher.resume();
		 message.react('🤘');
		return message.channel.send('Resuming') //This message sends - Theres no error message
	} else if(serverQueue.playing) {
		return message.channel.send("There\'s music playing already");
	}
	return message.channel.send("There\'s  nothing playing");
  }

```

No idea what could have caused this. Any suggestions and help would be appreciated! Thanks!

**Comment by MGPlayzYT** [comment]
Used to have this issue, but I fixed it by replacing `serverQueue.connection.dispatcher.pause()` with `serverQueue.connection.dispatcher.pause(true)`.
also this isn't `ytdl-core` related but rather related to discord.js' v12 changes.

**Comment by JerryFunHouse** [comment]
> Used to have this issue, but I fixed it by replacing `serverQueue.connection.dispatcher.pause()` with `serverQueue.connection.dispatcher.pause(true)`.
> also this isn't `ytdl-core` related but rather related to discord.js' v12 changes.

Yes that totally worked, thank you so much and yeah I wasn't sure where I should ask this.
