### ISSUE TITLE
how to download audio only

### ISSUE THREAD

**Issue by ferhacks** [fent/node-ytdl-core#843]
I am very new to nodejs, and I wanted to know how to download only the audio of a video

I hope not to be a nuisance

**Comment by Sten435** [comment]
let url = `YOUTUBE_LINK`
        const Output = path.resolve(`PATH/TO/STORE`);
  
        const video = ytdl(url,{ quality: 'highestaudio', format: 'webm' });
  
        video.pipe(fs.createWriteStream(Output))

**Comment by Aasim-A** [comment]
Hi @ferhacks , this is a small example with comments to explain what's happening:
```javascript
// Import fs module to write files into the filesystem, ytdl to download from youtube
const fs = require('fs');
const ytdl = require('ytdl-core');

// begin the download using a filter to download highest quality audio format
// you can refer to the quality section in README to learn more
const download = ytdl('LINK_OF_YOUTUBE_VIDEO', { quality: 'highestaudio' });

// create a write stream to write the data from ytdl to disk
const writeStream = fs.createWriteStream('PATH_TO_SAVE_FILE'); // path eg. './video.mp4'

// then pipe the download stream to the write stream, what this basically does
// is redirect whatever data comes out of download stream into the write stream
// thus writing it into disk
download.pipe(writeStream);
```

**Comment by ferhacks** [comment]
> Hi @ferhacks , this is a small example with comments to explain what's happening:
> 
> ```js
> // Import fs module to write files into the filesystem, ytdl to download from youtube
> const fs = require('fs');
> const ytdl = require('ytdl-core');
> 
> // begin the download using a filter to download audio only format
> // you can refer to the quality section in README to learn more
> const download = ytdl('LINK_OF_YOUTUBE_VIDEO', { quality: 'audioonly' });
> 
> // create a write stream to write the data from ytdl to disk
> const writeStream = fs.createWriteStream('PATH_TO_SAVE_FILE'); // path eg. './video.mp4'
> 
> // then pipe the download stream to the write stream, what this basically does
> // is redirect whatever data comes out of download stream into the write stream
> // thus writing it into disk
> download.pipe(writeStream);
> ```

Thanks for replying <3 I get this error, have I done something wrong?
node: 399330) UnhandledPromiseRejectionWarning: Error: No such format found: audioonly at Object.exports.chooseFormat (/home/Ferhacks/node_modules/ytdl-core/lib/format-utils.js:148:11) at downloadFromInfoCallback (/home/Ferhacks/node_modules/ytdl-core/lib/index.js:85:26) at /home/Ferhacks/node_modules/ytdl-core/lib/index.js:20:5 at runMicrotasks (<anonymous>) at processTicksAndRejections (internal / process / task_queues.js: 97: 5)

**Comment by Aasim-A** [comment]
Can you post the youtube video link that you tried?

**Comment by Aasim-A** [comment]
Oh well, `audioonly` seems broken, in that case you can do the following:

```javascript
// Import fs module to write files into the filesystem, ytdl to download from youtube
const fs = require('fs');
const ytdl = require('ytdl-core');

// begin the download using a filter to download audio only format
// you can refer to the quality section in README to learn more
const download = ytdl('LINK_OF_YOUTUBE_VIDEO', { filter: format => !format.hasVideo });

// create a write stream to write the data from ytdl to disk
const writeStream = fs.createWriteStream('PATH_TO_SAVE_FILE'); // path eg. './audio.mp4'

// then pipe the download stream to the write stream, what this basically does
// is redirect whatever data comes out of download stream into the write stream
// thus writing it into disk
download.pipe(writeStream);
```

I have tested it and it's working.

**Comment by Aasim-A** [comment]
Sorry, I got things mixed up, `audioonly` must be passed to `filter` not `quality` in options, this is the correct example:

```javascript
// Import fs module to write files into the filesystem, ytdl to download from youtube
const fs = require('fs');
const ytdl = require('ytdl-core');

// begin the download using a filter to download audio only format
// you can refer to quality and filter sections in README to learn more
const download = ytdl('LINK_OF_YOUTUBE_VIDEO', { filter: 'audioonly' });

// create a write stream to write the data from ytdl to disk
const writeStream = fs.createWriteStream('PATH_TO_SAVE_FILE'); // path eg. './audio.mp4'

// then pipe the download stream to the write stream, what this basically does
// is redirect whatever data comes out of download stream into the write stream
// thus writing it into disk
download.pipe(writeStream);
```

I have tested it and it's working.

**Comment by ferhacks** [comment]
> Sorry, I got things mixed up, `audioonly` must be passed to `filter` not `quality` in options, this is the correct example:
> 
> ```js
> // Import fs module to write files into the filesystem, ytdl to download from youtube
> const fs = require('fs');
> const ytdl = require('ytdl-core');
> 
> // begin the download using a filter to download audio only format
> // you can refer to quality and filter sections in README to learn more
> const download = ytdl('LINK_OF_YOUTUBE_VIDEO', { filter: 'audioonly' });
> 
> // create a write stream to write the data from ytdl to disk
> const writeStream = fs.createWriteStream('PATH_TO_SAVE_FILE'); // path eg. './audio.mp4'
> 
> // then pipe the download stream to the write stream, what this basically does
> // is redirect whatever data comes out of download stream into the write stream
> // thus writing it into disk
> download.pipe(writeStream);
> ```
> 
> I have tested it and it's working.

Hello, Merry Christmas <3

Thanks for helping me, help is appreciated <3

**Comment by shindeaditya685** [comment]
i have tried all above methods but not able to covert in audio file.
i creating mp4 file but size of that files 0 and can not play
`
// Import fs module to write files into the filesystem, ytdl to download from youtube
import fs from "fs";
import ytdl from "ytdl-core";

// begin the download using a filter to download audio only format
// you can refer to quality and filter sections in README to learn more
const download = ytdl("https://youtu.be/nqTS7ngviwQ?si=Zuebgn4L7HdoefHP", {
  filter: "audioonly",
});

// create a write stream to write the data from ytdl to disk
const writeStream = fs.createWriteStream("./audio.mp4"); // path eg. './audio.mp4'

// then pipe the download stream to the write stream, what this basically does
// is redirect whatever data comes out of download stream into the write stream
// thus writing it into disk
download.pipe(writeStream);

`

Please help to solve the issue

**Comment by shindeaditya685** [comment]
I have tried all the methods above but have not been able to convert to an audio file. I am creating an MP4 file, but the size of the file is 0 and it cannot be played.

```javascript
// Import fs module to write files into the filesystem, ytdl to download from YouTube
import fs from "fs";
import ytdl from "ytdl-core";

// Begin the download using a filter to download audio only format
// You can refer to quality and filter sections in README to learn more
const download = ytdl("https://youtu.be/nqTS7ngviwQ?si=Zuebgn4L7HdoefHP", {
  filter: "audioonly",
});

// Create a write stream to write the data from ytdl to disk
const writeStream = fs.createWriteStream("./audio.mp4"); // path eg. './audio.mp4'

// Then pipe the download stream to the write stream, what this basically does
// is redirect whatever data comes out of download stream into the write stream
// thus writing it into disk
download.pipe(writeStream);
