### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by kripii** [fent/node-ytdl-core#845]
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.x...
       Downloading and installing node 12.20.0...
       Using default npm version: 6.14.8
       
-----> Installing dependencies
       Installing node modules
       
       > jsonpath@1.0.2 postinstall /tmp/build_c4f93566_/node_modules/jsonpath
       > node lib/aesprim.js > generated/aesprim-browser.js
       
       added 115 packages in 2.595s
       
-----> Build
       
-----> Caching build
       - node_modules
       
-----> Pruning devDependencies
       audited 115 packages in 1.352s
       
       1 package is looking for funding
         run `npm fund` for details
       
       found 0 vulnerabilities
       
       
-----> Build succeeded!
-----> App not compatible with buildpack: https://github.com/fent/node-ytdl-core.git
       bash: /tmp/codon/tmp/buildpacks/11443dd76ad0133018597f04ce3b59d71d136830/bin/detect: No such file or directory
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed

I don't understand why???
I tried to deploy it on heroku but i don't know why it appears.

**Comment by fent** [comment]
this is when running the `heroku` cli?

**Comment by kripii** [comment]
> this is when running the `heroku` cli?
This is when i added it on buildpack and deployed it, I also tried it on heroku cli but the same thing appears.

**Comment by kripii** [comment]
I added it on buildpack and I also tried iton heroku cli but in both cases appeared the same thing.

**Comment by fent** [comment]
have you tried contacting them? i don't know why it would make some other tool fail. but i am willing to modify code if we're using some odd syntax, i just don't know what it is

**Comment by kripii** [comment]
But is this code compatible on node.js cause i'm doing a disocord bot or is it for anything else?

**Comment by fent** [comment]
yes, this is a node module

**Comment by kripii** [comment]
Do you know how to contact heroku cause i dont find anything else than upgrading the account to get help, or thats what i think

**Comment by kripii** [comment]
but I still dont know why the error comes up.

**Comment by fent** [comment]
the github for buildpack is at https://github.com/buildpacks/pack, maybe there's docs there or someone that can help

**Comment by kripii** [comment]
Do i have to add that buildpack also? Cause if that is the case it also appears the same error but with different numbers on it. I think that a problem of myself not of the repository.
