### ISSUE TITLE
Miniget Error 403 on some videos after update 4.3.0

### ISSUE THREAD

**Issue by Chrisr0** [fent/node-ytdl-core#854]
#### I use ytdl  for my discord bot and after updating to version 4.3.0 or later some videos refuse to play and throws this error

```
    MinigetError: input stream: Status code: 403
    at ClientRequest.<anonymous> (/home/chris/repos/roBOT/node_modules/miniget/dist/index.js:196:27)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10) {
  statusCode: 403
}
```
#### My code
```javascript
const dispatcher = connection
        .play(ytdl(song.vid.url, {
                requestOptions: {
                    headers: {
                        'X-Youtube-Identity-Token': process.env.xyit,
                        'Cookie': 'SID='+process.env.sid+'; HSID='+process.env.hsid+'; SSID='+process.env.ssid
                    }
                }
            })
        )
        .on("error", error => console.error(error));
```
### Video Links
https://www.youtube.com/watch?v=L_jWHffIx5E
https://www.youtube.com/watch?v=5NV6Rdv1a3I
https://www.youtube.com/watch?v=Um7pMggPnug

ytdl-core - 4.3.0 and newer
node - 12.18.2

**Comment by fent** [comment]
does the video still play? if yes, then this is the same as https://github.com/fent/node-ytdl-core/issues/798

**Comment by Chrisr0** [comment]
Video doesn't play and it happens only on specific videos

**Comment by fent** [comment]
what was the version you were using before v4.3.0?

**Comment by Chrisr0** [comment]
I was using 4.2.1 but tested 4.2.0 and 4.0.3 and they worked fine too

**Comment by fent** [comment]
> #### My code
> ```js
> const dispatcher = connection
>         .play(ytdl(song.vid.url, {
>                 requestOptions: {
>                     headers: {
>                         'X-Youtube-Identity-Token': process.env.xyit,
>                         'Cookie': 'SID='+process.env.sid+'; HSID='+process.env.hsid+'; SSID='+process.env.ssid
>                     }
>                 }
>             })
>         )
>         .on("error", error => console.error(error));
> ```

try removing the identity token header

**Comment by Chrisr0** [comment]
Identity token didn't work. Removing any part of cookie helps but then can't play age restricted videos.

**Comment by fent** [comment]
ah, so then the issue is related to the cookie. maybe it expired?

btw, ytdl-core should be able to play age restricted videos without a cookie

**Comment by Chrisr0** [comment]
Removing all headers worked and plays age restricted just fine. Thanks for help.

**Comment by VioletFlare** [comment]
The way I resolved it was waiting for a while (250ms) after detecting the `er.statusCode` status code 403 `.on("error", (er) => {...})`, and then re-running recursively the function containing `stream.play(ytdl(...))...` inside the event handler.
