### ISSUE TITLE
ReferenceError: URL is not defined [Temporary fix]

### ISSUE THREAD

**Issue by joek85** [fent/node-ytdl-core#859]
Hello, i am using the current version 4.4.3, i am getting
`ReferenceError: URL is not defined`

i had to comment out line 84 in info.js which was causing the error

` // storyboards: extras.getStoryboards(info),`

in case someone is facing this issue for now.

**Comment by fent** [comment]
what environment are you on? node, react-native, browser?

**Comment by joek85** [comment]
Express js

**Comment by fent** [comment]
node version?

**Comment by joek85** [comment]
v14.15.3

**Comment by fent** [comment]
strange, the `URL` constructor is part of node

if you type `node` in your shell, then type `URL`, you should be getting something like

```
> URL
[Function: URL]
```

**Comment by joek85** [comment]
i got this:

`Welcome to Node.js v14.15.3.
Type ".help" for more information.
> URL
[class URL]
> 
`

**Comment by joek85** [comment]
i ran now a mocha test and got this for basic-info-test.js

 `ReferenceError: URL is not defined
    at Object.exports.getStoryboards.info [as getStoryboards] (lib/info-extras.js:305:15)
    at exports.getBasicInfo (lib/info.js:84:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)`

**Comment by fent** [comment]
very weird

i installed and ran v14.15.3, i don't get that error. and there are checks on the repo to test against the last 3 stable node versions, including v14 https://github.com/fent/node-ytdl-core/blob/master/.github/workflows/nodejs.yml

not sure what's going on

**Comment by joek85** [comment]
`const URL = require("url").URL;`

Fixed it.

**Comment by fent** [comment]
https://nodejs.org/api/url.html#url_class_url

>The URL class is also available on the global object.

**Comment by timbly5000** [comment]
I am on Mint19 with npm version 3.5.2 and node version 8.10.0. I am now getting URL is not defined.
Also, my npm does not appear to be able to update node to >= 10.0 which I also dont understand.

**Comment by joek85** [comment]
Please add `const URL = require("url").URL;`
everytime i update it will break then run.
thank you

**Comment by subrataghosh119** [comment]
If you use old version of node the you can face the above problem.
So please update your node and get chill!
