### ISSUE TITLE
Is it supports Live streaming?

### ISSUE THREAD

**Issue by vermaslal** [fent/node-ytdl-core#86]
Hi I want to convert live stream to audio. 

For example this channel https://www.youtube.com/watch?v=H7d-eYawlRI

I have checked it, but it play only first chunk and break.

I will appreciate any help.

**Comment by fent** [comment]
Possible dupe of #64 

Although the error there was different then. And that video is down now.

**Comment by vermaslal** [comment]
Hi @fent thank you for your reply. Now I am using youtube-dl python module to achieve this.
