### ISSUE TITLE
How about chapter?

### ISSUE THREAD

**Issue by Talusor** [fent/node-ytdl-core#863]
Some youtube video has "chapters" and if click the seek-bar of video (in browser) it shows chapters of video on right
ex)
[Video](https://www.youtube.com/watch?v=gv_P5dqD0iU)
![캡처](https://user-images.githubusercontent.com/52791870/105824650-fe24f200-6001-11eb-8e91-d4b5e6a0f5ad.PNG)

and node-ytdl-core can access this chapter data by this code
```javascript
const audio_info = ytdl.getInfo("Video ID").then(info => {
  const overlay = info.response.playerOverlays.playerOverlayRenderer;
          if (overlay.decoratedPlayerBarRenderer !== undefined) {
              for (var chapter_index in overlay.decoratedPlayerBarRenderer
                  .decoratedPlayerBarRenderer.playerBar.chapteredPlayerBarRenderer
                  .chapters) {
                  const chapter =
                      overlay.decoratedPlayerBarRenderer
                          .decoratedPlayerBarRenderer.playerBar
                          .chapteredPlayerBarRenderer.chapters[chapter_index]
                          .chapterRenderer;
                  console.log(
                      `${chapter.title.simpleText} / ${chapter.timeRangeStartMillis}`
                  );
              }
          } else {
              console.log("this video has no chapters");
          }
}
```

but it's way to long. how about add chapter data in videoInfo interface or somewhere?
plz understanding my bad English i'm not familiar with English

**Comment by fent** [comment]
there's an issue that is already tracking this feature https://github.com/fent/node-ytdl-core/issues/625

that code is pretty useful thanks. i had assumed this information was only located in the video description

**Comment by Talusor** [comment]
thanks
