### ISSUE TITLE
Library is no longer webpackable

### ISSUE THREAD

**Issue by redbrain** [fent/node-ytdl-core#864]
As of 9331f5b, the library is no longer webpackable, since the browser polyfill for `url` doesn't support construction with `new URL`.
I've verified that the library is still webpackable from v4.4.4, where you use `urllib.resolve()` for this instead.
It seems like you refactored everything using the URL object to fix #859, when `new URL` was only used in code from #851.
I was wondering why you changed everything to use `new URL`, rather than changing the PR's code to use `resolve()`.
If that happened, it would both keep the issue closed and support webpacking, since it still uses the old `url` polyfill.
However, this seems like the method I would have used to resolve that issue in the first place as it's a bit less work.
Therefore, I'm asking you why you made that change, rather than submitting a PR to revert it back to `resolve()`.

**Comment by fent** [comment]
i made the change to use `URL` for a couple of reasons. node has marked the legacy url api as deprecated https://nodejs.org/api/url.html. that would mean that in future versions of node, functions like `resolve` will be removed or unsupported.

the other reason is, by using an api that the browser uses, and that's more universally available, it will also be more universally understood. so a frontend dev could read the codebase, see `new URL` and understand it faster than seeing `urllib.resolve()`




> As of [9331f5b](https://github.com/fent/node-ytdl-core/commit/9331f5b6244bcd7875b93f0326bc09330d21330e), the library is no longer webpackable, since the browser polyfill for `url` doesn't support construction with `new URL`.

so it doesn't support `new URL(url)` but `URL(url)` is fine?

**Comment by redbrain** [comment]
When webpacked, the error I get is `URL is not a constructor`.
The URL polyfill in use is 5 years old, so it doesn't have all of the changes coming to the URL library.
I didn't see that `resolve()` was deprecated recently; with this knowledge your course of action makes sense.
I've replied to an issue on the polyfill, so hopefully that is fixed. Closing because not relevant to this repo anymore.
