### ISSUE TITLE
Audio stream interrupts at 6:33 in the track

### ISSUE THREAD

**Issue by chaos87** [fent/node-ytdl-core#866]
Hi,

I'm serving audio only stream with ffmpeg using nodejs express server.

I have this behavior where the stream always interrupts exactly at 6 minutes and 33 seconds. Then after 10 seconds it resumes. It looks like the stream is not buffering properly or something like that, but I'm quite noob and not sure where to look to solve this.

And also when the interruption is triggered I see on the console I'm getting an error net::ERR_HTTP2_PROTOCOL_ERROR
(fyi I deployed the api server on a container on digitalocean app platform)

I'm pasting here the code I'm using, maybe you have an idea on how to solve this

```javascript
const ytdl = require('ytdl-core')
const FFmpeg = require('fluent-ffmpeg')
const { PassThrough } = require('stream')
const fs = require('fs')

youtubeRouter.get('/stream', (req, res) => {
    const requestUrl = `http://youtube.com/watch?v=${req.query.videoId}`
    res.setHeader('Access-Control-Allow-Origin', '*');
    opt = {
        audioFormat: 'mp3',
        quality: 'lowestaudio'
    }
    const video = ytdl(requestUrl, opt)
    const { file, audioFormat } = opt
    let stream = file ? fs.createWriteStream(file) : new PassThrough()
    const ffmpeg = new FFmpeg(video)
    process.nextTick(() => {
      const output = ffmpeg.format(audioFormat).pipe(stream)
      ffmpeg.on('error', error => {
          stream.emit('error', error)
          video.end()
          console.log('Error with video ', req.query.videoId, error.message)
          res.status(500).json({message: error.message})
      })
    })

    stream.video = video
    stream.ffmpeg = ffmpeg
    stream.pipe(res)
});
```

**Comment by fent** [comment]
does the stream stop downloading at 6 minutes, or does it stop being processed by ffmpeg?

 it could be that ffmpeg processing is much slower than download, you can increase the `highWaterMark` option to download more of the video to memoro.

`audioFormat` is not part of ytdl's options

**Comment by chaos87** [comment]
Thanks for the reply.
What is the default value of `highWaterMark` and what would be a good value here?
