### ISSUE TITLE
Error when trying to play with a discord bot

### ISSUE THREAD

**Issue by dopuke** [fent/node-ytdl-core#867]
so I tried to reinstall ytdl-core 2 times, I have the lastest version of it and it still doesn't work. I get everytime like with link or research the same error and not a single time I get any other error, so idk. One day I restarted my discord bot and boom, the error keep showing: 

`Error: input stream: Error parsing info: Unexpected token ) in JSON at position 0
2021-01-28T18:03:53.758406+00:00 app[worker.1]:     at exports.getBasicInfo (/app/node_modules/ytdl-core/lib/info.js:74:11)
2021-01-28T18:03:53.758407+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-01-28T18:03:53.758407+00:00 app[worker.1]:     at async Map.getOrSet (/app/node_modules/ytdl-core/lib/cache.js:24:19)
2021-01-28T18:03:53.758407+00:00 app[worker.1]:     at async exports.getInfo (/app/node_modules/ytdl-core/lib/info.js:215:14)
2021-01-28T18:03:53.758408+00:00 app[worker.1]:     at async Map.getOrSet (/app/node_modules/ytdl-core/lib/cache.js:24:19)`

Here is the error, I tried to find on google why I get this error but no one knows so yea :/.

**Comment by redbrain** [comment]
Are you on the latest version? `npm ls ytdl-core` should show v4.4.4. If not, update with `npm i ytdl-core@latest`.

**Comment by dopuke** [comment]
it does't want to uptade, it's stuck on version @3.2.0

**Comment by redbrain** [comment]
post the output of `npm ls ytdl-core` here

**Comment by dopuke** [comment]
![image](https://user-images.githubusercontent.com/63050953/106364556-342ee280-6330-11eb-9c3f-eb0b5e951b10.png)

**Comment by redbrain** [comment]
Try updating using this command exactly: `npm i ytdl-core@latest`

**Comment by dopuke** [comment]
i tried .. here is the output of the command
`[      ............] \ diffTrees: sill install generateActionsToTake
[       ...........] | postinstall: sill install executeActions
[       ...........] / extract:ytdl-core: verb lock using /app/.npm/_locks/stag
[          ........] - extract:m3u8stream: sill extract m3u8stream@^0.8.3 extra
[          ........] - extract:m3u8stream: sill extract m3u8stream@^0.8.3 extra
[            ......] \ remove:miniget: sill remove /app/node_modules/m3u8stream
[            ......] / refresh-package-json:ytdl-core: timing action:finalize C


> ref@1.3.5 install /app/node_modules/ref
> node-gyp rebuild

make: Entering directory '/app/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
make: g++: Command not found
binding.target.mk:111: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 127
make: Leaving directory '/app/node_modules/ref/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.4.0-1083-aws
gyp ERR! command "/app/.heroku/node/bin/node" "/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/ref
gyp ERR! node -v v12.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
[            ......] | postinstall: info lifecycle ytdl-core@4.4.5~postinstall:
[            ......] \ postinstall: info lifecycle ytdl-core@4.4.5~postinstall:

npm WARN #####bot@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 (node_modules/ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ ytdl-core@4.4.5
removed 2 packages, updated 3 packages and audited 163 packages in 3.537s

4 packages are looking for funding
  run `npm fund` for details

found 12 vulnerabilities (10 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
[            ......] / postinstall: sill install printInstalled

`

**Comment by dopuke** [comment]
my heroku app console doesn't even find the sudo command: 
![image](https://user-images.githubusercontent.com/63050953/106477576-97dc1b80-64a8-11eb-863a-65bcc3aa0b52.png)

**Comment by dopuke** [comment]
it changed nothing, i deployed again, i have the same ytdl-core version (3.2.0) and the same error :

`2021-02-01T15:27:16.822468+00:00 app[worker.1]: Error: input stream: Error parsing info: Unexpected token ) in JSON at position 0
2021-02-01T15:27:16.822470+00:00 app[worker.1]:     at exports.getBasicInfo (/app/node_modules/ytdl-core/lib/info.js:74:11)
2021-02-01T15:27:16.822470+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-02-01T15:27:16.822470+00:00 app[worker.1]:     at async Map.getOrSet (/app/node_modules/ytdl-core/lib/cache.js:24:19)
2021-02-01T15:27:16.822471+00:00 app[worker.1]:     at async exports.getInfo (/app/node_modules/ytdl-core/lib/info.js:215:14)
2021-02-01T15:27:16.822471+00:00 app[worker.1]:     at async Map.getOrSet (/app/node_modules/ytdl-core/lib/cache.js:24:19)`

**Comment by redbrain** [comment]
Well, node-gyp errors mean that you do not have the dependencies required to build some native module.
ytdl-core doesn't depend on anything that uses node-gyp to build, so I'm confused what throws this for you.

**Comment by dopuke** [comment]
idk man, my heroku app is so confusing up lmaooo

**Comment by haroongames-git** [comment]
I'm having the exact same issues; I've updated to the latest version too.

**Comment by redbrain** [comment]
Are you also hosting on Heroku? That platform will do unpredictable things sometimes.

**Comment by haroongames-git** [comment]
Nope; also problem fixed.

**Comment by TimeForANinja** [comment]
closing as stale 😉
