### ISSUE TITLE
QUESTION: Is it possible to get the url where the video is currently being hosted?

### ISSUE THREAD

**Issue by tcortega** [fent/node-ytdl-core#868]
It's just a question that I have, is it possible to get the url such urls like: `https://r4---sn-p5qs7n7z.googlevideo.com/videoplayback?`
where the video is usually being hosted at?

If not, can you guys add it as a feature?

**Comment by hucario** [comment]
If you want a full link, you have to choose which format you want first. What do you want, highest audio quality? Highest video quality?  Here's some example code to get that link for highest audio-only download:
```js
import ytdl from 'ytdl-core'
function getAudioLink(url) {
				ytdl.getInfo(url).then(e => {
					let audioFormat = ytdl.chooseFormat(info.formats, { quality: 'highestaudio', filter: 'audioonly' });
					return audioFormat.url;
				})
}
```

**Comment by tcortega** [comment]
> If you want a full link, you have to choose which format you want first. What do you want, highest audio quality? Highest video quality? Here's some example code to get that link for highest audio-only download:
> 
> ```js
> import ytdl from 'ytdl-core'
> async function getAudioLink(url) {
> 	let e = await ytdl.getInfo(url);
> 	let audioFormat = ytdl.chooseFormat(info.formats, { quality: 'highestaudio', filter: 'audioonly' });
> 	return audioFormat.url;
> }
> ```

what if I want the best video possible? ( with audio of course )

**Comment by hucario** [comment]
```js
import ytdl from 'ytdl-core'
async function highestVideo(url) {
	let e = await ytdl.getInfo(url);
	let audioFormat = ytdl.chooseFormat(info.formats, { quality: 'highest' });
	return audioFormat.url;
}
```

**Comment by tcortega** [comment]
> ```js
> import ytdl from 'ytdl-core'
> async function highestVideo(url) {
> 	let e = await ytdl.getInfo(url);
> 	let format = ytdl.chooseFormat(info.formats, { quality: 'highest' });
> 	return format.url;
> }
> ```

what is info.formats supposed to be tho?

**Comment by tcortega** [comment]
> ```js
> import ytdl from 'ytdl-core'
> async function highestVideo(url) {
> 	let e = await ytdl.getInfo(url);
> 	let format = ytdl.chooseFormat(info.formats, { quality: 'highest' });
> 	return format.url;
> }
> ```

This doesn't really seem to be getting the best video with audio possible, I tried with the id: `2O49gf7fiPQ`
and it returned me this:

```json
{
audioQuality:'AUDIO_QUALITY_LOW'
audioSampleRate:'44100'
averageBitrate:487421
bitrate:487624
codecs:'avc1.42001E, mp4a.40.2'
container:'mp4'
contentLength:'8925533'
fps:30
hasAudio:true
hasVideo:true
height:360
isDashMPD:false
isHLS:false
isLive:false
itag:18
lastModified:'1611534362208503'
mimeType:'video/mp4; codecs="avc1.42001E, mp4a.40.2"'
projectionType:'RECTANGULAR'
quality:'medium'
qualityLabel:'360p'
url:'**********************************'
videoCodec:'avc1.42001E'
width:640
}
```

**Comment by fent** [comment]
use `quality: 'highestvideo', filter: 'audioandvideo'`

**Comment by sntran** [comment]
YouTube doesn't seem to provide full container format with both audio and video at resolution higher than 720p. From what I understand, our best bet is to grab highest audio and highest video streams, and mux them with `ffmpeg`.

**Comment by tcortega** [comment]
> use `quality: 'highestvideo', filter: 'audioandvideo'`

found this solution about a week ago, forgot to update the issue.
