### ISSUE TITLE
This video is only available to Music Premium members

### ISSUE THREAD

**Issue by jameslinimk** [fent/node-ytdl-core#869]
![image](https://user-images.githubusercontent.com/63650909/106372177-2468cb80-633b-11eb-8a08-32e42ebb5c96.png)
Song: 心臓を捧げよ！
Link: https://www.youtube.com/watch?v=8QPyFlJNmus&list=PLc4FwQ3tNBinaDSpgqf30cjBTpMZU0kI5&index=22

**Comment by Peppy8651** [comment]
This video requires Youtube Music Premium, so you can't access the video itself without being logged in to a Google Account and being subscribed to Music Premium.

**Comment by jameslinimk** [comment]
> This video requires Youtube Music Premium, so you can't access the video itself without being logged in to a Google Account and being subscribed to Music Premium.

Is there a way to catch this error?

**Comment by Peppy8651** [comment]
> Is there a way to catch this error?

Use a try catch statement on the ytdl function

**Comment by jameslinimk** [comment]
> > Is there a way to catch this error?
> 
> Use a try catch statement on the ytdl function

ok
