### ISSUE TITLE
Range options not working

### ISSUE THREAD

**Issue by vp-vmenard** [fent/node-ytdl-core#87]
Hi,
I have a problem when I define a byte range in the options, the download not working
An idea ?

example byte range :  "3807387-3909133"
url : https://www.youtube.com/watch?v=CehAKQL463M

Thanks

**Comment by fent** [comment]
I just tried the following and the video plays fine.

```js
var path = require('path');
var fs   = require('fs');
var ytdl = require('..');

var url = 'https://www.youtube.com/watch?v=CehAKQL463M';
var output = path.resolve(__dirname, 'video.mp4');

var video = ytdl(url, { range: '0-1000' });
video.pipe(fs.createWriteStream(output));

video.on('end', function() {
  ytdl(url, { range: '1001-' })
    .pipe(fs.createWriteStream(output, { flags: 'a' }));
});
```

Keep in mind that range downloads a portion of the file, and not a working video file with a portion of the content. It's meant to be used to continue broken downloads.
