### ISSUE TITLE
Error: input stream: Video unavailable

### ISSUE THREAD

**Issue by orfox32** [fent/node-ytdl-core#873]
does anyone knows how to fix these ?

**Comment by redbrain** [comment]
We're going to need more information than that.
What video are you trying to play, and what's the code you're using to play it?

**Comment by orfox32** [comment]
Im playing my playlist https://youtube.com/playlist?list=PLnMWUlinkz9AViHHxJaRjsd_yViPpRxCg but theres a song in there which is unavailable in a country

**Comment by orfox32** [comment]
Im using ytdl-core 4.0.5

**Comment by redbrain** [comment]
You should start by updating ytdl-core to the latest version: `npm install ytdl-core@latest`
If you want to get around country/region limits, you need to send the request through a proxy server in an allowed region.
Look at the `examples` folder for an example of how to use a proxy with ytdl-core.

**Comment by orfox32** [comment]
the proxy is not working just stuck at starting download

**Comment by orfox32** [comment]
how do i setup the proxy for my music bot ?

**Comment by redbrain** [comment]
You'll need to find an http(s) proxy in the desired country to use in your code.

**Comment by orfox32** [comment]
how do i put that in my code is that bannable ?

**Comment by TimeForANinja** [comment]
No, YouTube is not banning users of proxys.
An example can be found here: https://github.com/fent/node-ytdl-core/blob/master/example/proxy.js
