### ISSUE TITLE
[BUG] Music randomly stops/pause

### ISSUE THREAD

**Issue by Alexmdz77** [fent/node-ytdl-core#875]
**Bug Description**
The music randomly stops after 10 to 50 seconds, the bot is still connected, the song is still in the queue but the bot doesn't play anymore and the progress bar is stopped. It happens on all songs.
No errors message.

**Versioning:**
- OS: Debian10
- NPM Version 6.14.10
- Discord.js Version 12.5.1
- ytdl-core Version 4.4.5

**Comment by redbrain** [comment]
Are you handling errors on both the ytdl stream and the dispatcher?

**Comment by Alexmdz77** [comment]
no errors with ytdl :
![image](https://user-images.githubusercontent.com/32090268/107269539-09d4d780-6a4a-11eb-9796-d34d0a87ef87.png)

**Comment by Alexmdz77** [comment]
Ok sorry, I have this error now on the dispatcher : 
![image](https://user-images.githubusercontent.com/32090268/107335720-94ecb680-6ab8-11eb-8ec8-a35bf3aa55fd.png)

**Comment by redbrain** [comment]
That's probably an issue with whatever FFmpeg arguments you're using.

**Comment by Alexmdz77** [comment]
You know what I need to change?

**Comment by redbrain** [comment]
You haven't shared your FFmpeg args/code, so I can't help you modify them until I know what you currently have.

**Comment by Alexmdz77** [comment]
I don't know where I should find these arguments FFmpeg

**Comment by Alexmdz77** [comment]
My problem is still there, do you have a solution to propose me ? I don't know where I can find FFmpeg arguments

**Comment by fent** [comment]
it would help us narrow down the issue if you could reduce the issue to its smaller form. test simply downloading the video and seeing if you get a file that's only 10 to 50 secs in length. if so, it could be an issue with your discord.js interaction, or ffmpeg arguments.

does this happen on any video or specific ones?

**Comment by Alexmdz77** [comment]
Thank you, Ok, I'm looking to do that.

It happens on any video

**Comment by Alexmdz77** [comment]
When I do this:: 
```js
const fs = require('fs');
const ytdl = require('ytdl-core');

ytdl('http://www.youtube.com/watch?v=aqz-KE-bpKQ')
  .pipe(fs.createWriteStream('video.mp4'));
```
I don't have any errors and the video is complete.

**Comment by fbagjug** [comment]
I have a similar issue, I'm currently testing every event on the dispatcher as well as every YTDL event to see which one is closing the connection half way through the video. I also figured out "Alan Walker faded low quality" doesn't even begin to play for some reason. The only arguments give is to the play command and the first one is the YTDL Stream, the second is the options which only has the highWaterMark and that is set to 1<<15. Essentially I don't know the issue yet

**Comment by Alexmdz77** [comment]
For some people setting the highWaterMark to '1<<25' can solve this issue (not for me) you can try for yourself.

**Comment by fbagjug** [comment]
I had my highWaterMark set to '1<<25' but it was laggy at the beginning of the stream so I lowered it thinking it could be to connection speed and it improved the lag

**Comment by redbrain** [comment]
highWaterMark dictates how much of the video is downloaded at a time. Setting higher/lower chunk size can solve some latency issues, but increases your chance of being ratelimited. If your internet speed is normal, this option probably does not need to be set.

**Comment by fbagjug** [comment]
If by normal you mean slow then you could set it slightly higher from it's extremely low default or yes you could leave it but you may face the same issues I did. If not and by normal you meant somewhat fast then I recommend increasing it slightly as it does make the buffer larger in the likely event your internet can not buffer in time
