### ISSUE TITLE
Music Instantly stops

### ISSUE THREAD

**Issue by workframes** [fent/node-ytdl-core#877]
I get the error in my build logs on Heroku when I try to deploy my branch.
```
App not compatible with buildpack: https://github.com/fent/node-ytdl-core.git
```

**Comment by TheNozomi** [comment]
What are you trying to do? ytdl-core is not a Heroku buildpack.

**Comment by fent** [comment]
i don't use buildpack, post any error logs it gives

**Comment by workframes** [comment]
Well, I got the build pack thing solved, but now the music just stop instantly when it joins the VC, and it clears the que
