### ISSUE TITLE
Music Instantly stop as the bot joins.

### ISSUE THREAD

**Issue by workframes** [fent/node-ytdl-core#878]
So right when the bot joins the queue gets cleared and as well as the song playing currently. I'm not getting any errors so I'm not sure how to fix this.

**Comment by RageList** [comment]
I think this is the same issue I'm having rn.
it seems like ytdl can't play some youtube videos, sometime it works, sometime it doesn't.
there's also no error message

**Comment by workframes** [comment]
I'm still having this issue too, I'm trying to mess around with it and figure it out but no luck

**Comment by GF-Amy** [comment]
I have the same problem some videos are working though i also get this on not working videos
2 different errors
![grafik](https://user-images.githubusercontent.com/67457085/108079929-a3663f80-706f-11eb-8138-6a2cb651a519.png)
The first error is this video: https://www.youtube.com/watch?v=BxDN8QVGjK8
on the first error, the bot exits immediately without playing.
The second error is this video: https://www.youtube.com/watch?v=RJPODX7Ftk4
on the second error, the bot stays in the VC and plays nothing.
let me know if more information is needed!

**Comment by fbagjug** [comment]
Hmm I've been getting this issue, I wonder why other bigger bots don't get the same issues, surely they use this module or something similar right?

**Comment by Unfit-Donkey** [comment]
I had this same issue where the video would end before it started. I checked some other guides and they had added the filter "audioonly" to the bot, so I added that to the function call and it works on every video now. The function call looks like ` ytdl(url, {filter: "audioonly"});` Hopefully this will work as a temporary fix.

**Comment by fbagjug** [comment]
There's a reason I haven't added audioonly myself and it's because I want seeking aka being able to change the time, I believe I read that if you have audioonly it doesn't work.

**Comment by Safoide** [comment]
same issue here :p

**Comment by TimeForANinja** [comment]
> There's a reason I haven't added audioonly myself and it's because I want seeking aka being able to change the time, I believe I read that if you have audioonly it doesn't work.

seeking is not a feature of node-ytdl-core
`begin` is an option but deprecated since it is very unconsistent
seeking using sth. like ffmpeg works on all inputs

**Comment by TimeForANinja** [comment]
if you experience these issues make sure you have an error listener directly on the stream returned by node-ytdl-core... not just on piped streams... the ffmpeg EPIPE error is not a lot to work with 😅

**Comment by fbagjug** [comment]
> if you experience these issues make sure you have an error listener directly on the stream returned by node-ytdl-core... not just on piped streams... the ffmpeg EPIPE error is not a lot to work with 😅

I found that weirdly if I set up error events it would either not give me much or it wouldn't work anyway. I have not tested with this in a while but probably will soon

**Comment by workframes** [comment]
I think this has been fixed, It works perfectly fine. If it still breaks for you just try to update the npm package
