### ISSUE TITLE
Issue with Chew.TV

### ISSUE THREAD

**Issue by TheChez14** [fent/node-ytdl-core#88]
So I am trying to use the player to play Chew.TV streams. And it seems to work for some and not all. For instance, If I use https://chew.tv/echobreaker/spin-chill Works fine. But, if I use https://chew.tv/millar/practice, the player freaks out, and refers it to a completely unrelated youtube link. If it could work with all Chew streams, that would be awesome.

**Comment by fent** [comment]
Player?

This library doesn't support chew.tv, are you perhaps using [youtube-dl](https://rg3.github.io/youtube-dl/) instead?

**Comment by TheChez14** [comment]
Probably. I'll look there. This was used in a discord bot had seen. I
thought this was the library
