### ISSUE TITLE
[Feature] Add suport for short urls

### ISSUE THREAD

**Issue by tcortega** [fent/node-ytdl-core#881]
Simple feature request, it'd be nice if the lib could support for `shorts` urls, such as:
https://youtube.com/shorts/aaXwvpe3ucQ

They're the same as normal urls, youtube just changed the syntax.
https://www.youtube.com/watch?v=aaXwvpe3ucQ

**Comment by fbagjug** [comment]
I believe you could create some RegEx to isolate the ID of the short and put it into the 'watch?v=' syntax until this does get added (Assuming it will be).

**Comment by tcortega** [comment]
> I believe you could create some RegEx to isolate the ID of the short and put it into the 'watch?v=' syntax until this does get added (Assuming it will be).

did that already, was just wondered if it's possible to add the support, the same way the lib supports `watch?v=`

**Comment by fbagjug** [comment]
Yeah it would be cool
