### ISSUE TITLE
Weird issue with youtu.be links (no audio output)

### ISSUE THREAD

**Issue by amitojsingh366** [fent/node-ytdl-core#885]
### Before creating an issue, please try the following

- Are you on the latest version of ytdl-core?
  - Yes, my version is `ytdl-core@4.5.0`

### Otherwise, feel free to open an issue

Include the following if your issue is a bug

- If you're getting a specific error message, include the full stack trace
   - No error code
- If you're getting unexpected behavior without an error message
  - What should happen?
       - Videos with youtu.be links should play normally
  - What happens instead?
      - No audio output whatsoever
- If this error happens only on some videos, include a link or links to videos.
   - One of the videos I tested this on was [https://youtu.be/vb28YPZgU3s](https://youtu.be/vb28YPZgU3s)

**Comment by redbrain** [comment]
ytdl-core can parse youtu.be links correctly; the issue isn't in the link format.
Some videos won't return audio unless you add `filter: highestaudio` to the `ytdl()` function (see also issues 836 and 770)
