### ISSUE TITLE
[QUESTION] Small filesizes of songs downloaded from YouTube Music

### ISSUE THREAD

**Issue by Wengiel31** [fent/node-ytdl-core#887]
Hey, so... recently I've tried downloading a song from YouTube Music with ytdl-core and... it worked, but I noticed that the size of the downloaded file is **significantly** smaller (about 50%) than the one that I downloaded manually (by getting a link with webtools). Such a huge decrease has probably decreased the quality of the audio (although I haven't noticed any difference in the way it sounds).
So my question is: WHY is the file downloaded by ytdl-core smaller than the one downloaded by me?

**Comment by redbrain** [comment]
If you're not using any filters, ytdl-core just grabs itag 18 and returns it as a Stream. ytdl-core doesn't process the audio

**Comment by Wengiel31** [comment]
I use "highestaudio" quality and "audioonly" filter

**Comment by TimeForANinja** [comment]
🤔 sth is off here
* does this happen on multiple videos?
* can you provide a video this happens with?
* what exactly do you mean by webtools?

**Comment by redbrain** [comment]
YouTube Music sources the music from YouTube videos, so there's not a quality loss on the source, as far as I can tell.
There could be some oddity in the code as well, so consider sharing that along with the example video.

**Comment by Wengiel31** [comment]
> 🤔 sth is off here
> 
> * does this happen on multiple videos?
> * can you provide a video this happens with?
> * what exactly do you mean by webtools? / How can we recreate the way you download the video?

Does this happen on multiple videos?
Yes

Can you provide a video this happens with?
https://music.youtube.com/watch?v=ls-tOa_f7KE [Downloaded with ytdl: 3,342,336 B | Downloaded manually: 6,713,344 B]
https://music.youtube.com/watch?v=fI69eQnMIvo [Downloaded with ytdl: 3,485,696 B | Downloaded manually: 6,983,680 B]

What exactly do you mean by webtools? / How can we recreate the way you download the video?
I use chrome's webtools, enter the network tab and get the latest videoplayback request. Then change the ranges in the request's URL and send the request.

> YouTube Music sources the music from YouTube videos, so there's not a quality loss on the source, as far as I can tell.
> There could be some oddity in the code as well, so consider sharing that along with the example video.

Codebase:
`const ytdl = require("ytdl-core");
const fs = require("fs");
// Contains downloaded songs
fs.readFile("./songs.json", {
    encoding: "utf-8"
}, (error, songs) => {
    if (error) console.error(error);
    else {
        songs = JSON.parse(songs);
        // Contains an array of URLs to download
        fs.readFile("./urls.json", {
            encoding: "utf-8"
        }, (error, urls) => {
            if (error) console.error(error);
            else {
                urls = JSON.parse(urls);
                function temp() {
                    return new Promise((resolve, reject) => {
                        urls.forEach((urlObject, index, array) => {
                            ytdl.getInfo(urlObject.url).then(info => {
                                songs.push({
                                    id: songs.length,
                                    title: info.videoDetails.title,
                                    author: info.videoDetails.author.name.slice(0, info.videoDetails.author.name.indexOf(" - Topic"))
                                });
                                const stream = ytdl(urlObject.url, {
                                    quality: "highestaudio",
                                    filter: "audioonly"
                                });
                                stream.pipe(fs.createWriteStream(`./audio/${songs.length - 1}.mp3`));
                                stream.on("error", error => reject(error));
                                stream.on("end", () => index <= array.length ? resolve(songs) : reject(undefined));
                            });
                        });
                    });
                }
                temp().then(newSongs => fs.writeFile("./songs.json", JSON.stringify(newSongs), {
                    encoding: "utf-8"
                }, () => fs.readFile("./songs.json", {
                    encoding: "utf-8"
                }, (error, data) => error ? console.error(error) : console.log("Done.")))).catch(error => error ? console.error(error) : console.log("error"));
            }
        });
    }
});`

**Comment by fent** [comment]
make sure the video you downloaded through dev tools matches the same itag. you can find the itag in the url (i.e. `&itag=xxx&`

**Comment by Wengiel31** [comment]
The itag of the file downloaded manually is 141.
I couldn't get the itag of the one downloaded with ytdl and when I tried downloading with: `quality: 141` I got:
Error: No such format found: 141

**Comment by Wengiel31** [comment]
The issue is still here. I found out that `formats` variable in `chooseFormat` function in format-utils.js does not does not contain an object with itag 141 even though it should be there, because the video is available in it's quality.

I'm referring to the first link (https://music.youtube.com/watch?v=ls-tOa_f7KE)

**Comment by fent** [comment]
it's possible that ytdl-core is failing to retrieve all formats available for the video. but, i'm not able to reproduce downloading itag 141 from the link above. when i go to webtools, i get formats 150 and 151, which both show up with ytdl-core
