### ISSUE TITLE
Does getInfo provide the published date? 

### ISSUE THREAD

**Issue by JimmyBoh** [fent/node-ytdl-core#89]
I tried looking through all of the properties and nothing jumped out at me regarding a specific date of when the video was published. Do you know of anything in there? If not I can try to get it using [scany](https://github.com/JimmyBoh/scany).

**Comment by JimmyBoh** [comment]
I might be able to pull it from the page, just like description. I'll take a look today and see if I can throw together a PR.

**Comment by fent** [comment]
Look for `timestamp` https://gist.github.com/fent/6c8251132e1addb5121e#file-format-json-L148

**Comment by JimmyBoh** [comment]
`timestamp` looks like it references the time the request was made, not when the video was published (call `new Date(1367002963*1000)` and the date matches the last change to that file).

**Comment by JimmyBoh** [comment]
So after looking into it, let me know what your thoughts are on the following:

When looking at the page, right now your description is being pulled from the `#eow-description` element. There seems to be a set of `meta` tags with lots of other useful info too, for example `<meta itemprop="datePublished" content="2013-04-12" />`. Any reason why parsing that would be a bad idea? If not I can try to get it implemented.

**Comment by fent** [comment]
Ah, didn't notice the `timestamp` thing before, sorry 😮 

The description from the meta tags is truncated. Getting the the published date from them seems fine though.

**Comment by JimmyBoh** [comment]
What is your preferred method for retrieving an element from the DOM? Use [`RegExp` like description](https://github.com/fent/node-ytdl-core/blob/850d49130bc9ddd26be8e9f04240340733369d1f/lib/util.js#L281-L287) does? Use [`util.between` to search the body](https://github.com/fent/node-ytdl-core/blob/850d49130bc9ddd26be8e9f04240340733369d1f/lib/info.js#L50)? 

In the future, if parsing/searching the DOM is becoming more common, I recommend using something like [`cheerio`](https://cheerio.js.org/). I'm not sure how performance would compare to `RegExp`/`indexOf`, but it definitely makes it easier to work with.

**Comment by fent** [comment]
Use whichever one you prefer :). `RegExp` may have been used for `description` because the tag for it was more inconsistent, more likely to change. There's the possibility that the closing `</div>` could be confused by a future `<div>` that YouTube may add in descriptions some time in the future.

Cheerio was actually used [at one point](https://github.com/fent/node-ytdl-core/commit/b034334). It. It was removed in favor of `RegExp` because too little of it was used to justify another dependency. But if we ever do require some complex DOM traversal, we'll have to reconsider.

**Comment by anhiao** [comment]
If you are reading this now and want to get the publish date and type like "3 minutes ago, 2 days ago , 1 year ago...", you can try this code


``` js
      const  res = await ytdl.getInfo(“video link“);
console.log(res.response.contents.twoColumnWatchNextResults.results.results.contents[0].videoPrimaryInfoRenderer.relativeDateText.simpleText);

```
I hope it will help you
