### ISSUE TITLE
Bot doesn't play the song

### ISSUE THREAD

**Issue by Giorgio615** [fent/node-ytdl-core#891]
### Before creating an issue, please try the following

- Are you on the latest version of ytdl-core?
`-- ytdl-core@4.5.0

The error is that, the bot joins the voice channel but it doens't play the song.

```
async function execute(commandArgs, serverQueue, message) {
    const voiceChannel = message.member.voice.channel;
    if (!voiceChannel)
      return message.channel.send(
        "**Debes estar en un canal para poner musica**"
      );
    const permissions = voiceChannel.permissionsFor(message.client.user);
    if (!permissions.has("CONNECT") || !permissions.has("SPEAK")) {
      return message.channel.send(
        "**No tengo los permisos necesarios"
      );
    }
    const songInfo = await ytdl.getInfo(commandArgs);
  const song = {
    title: songInfo.videoDetails.title,
    url: songInfo.videoDetails.video_url,
};


  if (!serverQueue) {
    const queueContruct = {
      textChannel: message.channel,
      voiceChannel: voiceChannel,
      connection: null,
      songs: [],
      volume: 5,
      playing: true
    };

    queue.set(message.guild.id, queueContruct);

    queueContruct.songs.push(song);

    try {
      var connection = await voiceChannel.join();
      queueContruct.connection = connection;
      play(message.guild, queueContruct.songs[0]);
    } catch (err) {
      console.log(err);
      queue.delete(message.guild.id);
      return message.channel.send(err);
    }
  } else {
    serverQueue.songs.push(song);
    return message.channel.send(`${song.title} ha sido añadida a la lista`);
  }
}
```

**Comment by UltraCookie1780** [comment]
Yes I have the same problem. On my windows machine it works totally fine but when I upload it to my Ubuntu VPS it just immediately triggers the finish event.

**Comment by UltraCookie1780** [comment]
Nevermind, my Ubuntu machine had no ffmpeg installed. 2 days searching for this problem... I would recommend adding an error message when ffmpeg is not avaible/missing.

**Comment by fent** [comment]
ytdl-core does not use ffmpeg, there'd be no error on our end to report on

**Comment by Giorgio615** [comment]
Nevermind, it seems that it is my bot, because i did a tts command and didn't work too.

**Comment by Dorfnox** [comment]
I'm having this issue too when running locally on my Mac machine.

**Comment by TimeForANinja** [comment]
closing this issue since OPs Problem resolved itself
@Dorfnox check your dependencies or try asking the guys over at discord.js for help - they have a quite active support discord
