### ISSUE TITLE
ytdl-core not creating a proper readable stream

### ISSUE THREAD

**Issue by orpheus** [fent/node-ytdl-core#893]
ytdl-core: 4.5.0
node: v12.18.2

I have two videos that both run without error, but the `bad` url creates an unrecognizable/unplayable format, while the `good` url, processes just fine. 

```
const good = 'https://www.youtube.com/watch?v=CHsnrVP3oC0'
const bad = 'https://www.youtube.com/watch?v=M5CnicMvLsk'

// creates playable .mp4 
ytdl(good).pipe(fs.createWriteStream('good.mp4'))

// does not create playable .mp4
ytdl(bad).pipe(fs.createWriteStream('bad.mp4'))
```

Neither process errors, but when trying to open the `bad` mp4, it won't open and the `byte` size is very small (less than 1MB)

I'm not sure where to start debugging this and could use some help.

I saw this issue more clearly when passing the stream to `ffmpeg` to process and I received this error:

`Output file #0 does not contain any stream`

If you would like to see the code where I pipe into `ffmpeg` lmk, but it works fine with the `good` url

**Comment by Svallinn** [comment]
As far as I can tell, this isn't strictly an issue with `ytdl-core` (although the lib can be improved to deal with this scenario).
The bad video seems to have a bunch of broken formats (a bunch of them return 404s)
I've noticed that all of the formats that didn't work don't actually contain a `contentLength` property, so a working workaround would be:
```js
ytdl(bad, { filter: format => format.contentLength }).pipe(fs.createWriteStream('bad.mp4'))
```
You'll have to wait for @fent for more information.

**Comment by orpheus** [comment]
@Svallinn I see. That was very helpful advice. Will `ytdl` still use the highest quality video out of the formats that are left? If I pass in a `quality: 'highestaudio'` I should be good right?

```js
ytdlr(bad, { filter: format => format.contentLength, quality: 'highestaudio' }).pipe(fs.createWriteStream('bad.mp4')
```

**Comment by Svallinn** [comment]
I tried that exact code on my rig
```js
ytdl(bad, { filter: format => format.contentLength, quality: 'highestaudio' }).pipe(fs.createWriteStream('bad.mp4')
```
and it worked for me, so that's odd.

**Comment by TimeForANinja** [comment]
@orpheus
You should watch out with dumping everything into `.mp4`
It doesn't support all encodings and some players might fail playing combinations that shouldn't exist
I always advice using `.mkv`
