### ISSUE TITLE
SyntaxError: Unexpected token '['

### ISSUE THREAD

**Issue by jordanlee-dev** [fent/node-ytdl-core#896]
I get the following error with WebKit 538.2 from ytdl-core version 4.1.0 and higher. So I'm still using version 4.0.5.

**SyntaxError: Unexpected token '['**

Node: 14.15.0
React: 17.0.1
core-js: 3.9.1

**Comment by twarped** [comment]
Is that all the logs? what function were you using?

**Comment by jordanlee-dev** [comment]
import ytdl from "ytdl-core"; in my index.js file. So it happens without using any functions yet. Also, as I wrote, this problem was not available in 4.0.5 and earlier versions.

I'm just building and as soon as I open webos SmartTV(WebKit 538.2) it gives the above error.

**Comment by fent** [comment]
this is for a frontend environment? what are you using to build?

**Comment by xorion2** [comment]
I'm sorry for the late reply.

I use it with React CRA and **import ytdl from "ytdl-core"** in my index.js file.

As I said before, this error was not happening in 4.0.5 and earlier versions. I think it has a polyfill problem and it doesn't translate correctly for WebKit 538.2. I'm using core-js for polyfill.

I think some updates you made from 4.1.0 cause this and I cannot get the details of the error.

only **SyntaxError: Unexpected token '['**

Ps:
React-Cra: Create React App (CRA) is the easiest way to get started building React applications. It provides a default setup with a number of core features baked in, including a build system containing a module bundler (webpack) and a transpiler (Babel)

**Comment by jordanlee-dev** [comment]
I'm sorry for the late reply.

I use it with React CRA and **import ytdl from "ytdl-core"** in my index.js file.

As I said before, this error was not happening in 4.0.5 and earlier versions. I think it has a polyfill problem and it doesn't translate correctly for WebKit 538.2. I'm using core-js for polyfill.

I think some updates you made from 4.1.0 cause this and I cannot get the details of the error.

only **SyntaxError: Unexpected token '['**

Ps:
React-Cra: Create React App (CRA) is the easiest way to get started building React applications. It provides a default setup with a number of core features baked in, including a build system containing a module bundler (webpack) and a transpiler (Babel)

**Comment by jordanlee-dev** [comment]
The built code that gives an error is as follows.

SyntaxError: Unexpected token '['

```
 [Symbol.toPrimitive]: function () { ***********// This line gives an error *******
              return (
                console.warn(
                  "`relatedVideo.author` will be removed in a near future release, use `relatedVideo.author.name` instead."
                ),
                m.author.name
              );
  },
```

**Comment by TimeForANinja** [comment]
This looks more like polyfill not supporting all node.js features to me 🤔
