### ISSUE TITLE
Does not download some formates.

### ISSUE THREAD

**Issue by SyedMuzamilM** [fent/node-ytdl-core#897]
So when I am trying to download the 740p or 480p quality video. It downloads only 360p. Beyond that eveything works fine. So just find the issue with that.

**Comment by fent** [comment]
how are you calling ytdl-core?

**Comment by SyedMuzamilM** [comment]
`
const ytdl = require('ytdl-core')

ytdl(url, {
    format: 136
}).pipe(res)
`

**Comment by SyedMuzamilM** [comment]
``` js
const ytdl = require('ytdl-core')

ytdl(url, {
   format: 136
}.pipe(res)
```

**Comment by fent** [comment]
`format` takes a format object. `quality` can take an itag

https://github.com/fent/node-ytdl-core#ytdlchooseformatformats-options
