### ISSUE TITLE
Doesn't exists all the qualities

### ISSUE THREAD

**Issue by 1ncursio** [fent/node-ytdl-core#905]
When I try to download Youtube videos, some qualities doesn't exists, e.g. 1080p.

```javascript
app.get('/api/video', async (req, res) => {
  try {
    const { url } = req.query;
    const info = await ytdl.getInfo(url);
    const formats = ytdl.filterFormats(info.formats, 'audioandvideo');
    return res.json(format);
  } catch (error) {
    return res.status(404).send('No video found.');
  }
});
```

But, when I set filter value to `video` or `videoonly`, I could get all the qualities of the video.

In conclusion, How can I get all the qualities of the video? 

Greetings,
1ncursio

**Comment by fent** [comment]
youtube only has formats that have both audio and video up to 720p. for higher qualities, it mixes them together.

**Comment by 1ncursio** [comment]
Thank you for answer!
