### ISSUE TITLE
Does getInfo include the author's image? 

### ISSUE THREAD

**Issue by FireController1847** [fent/node-ytdl-core#91]
I'd like to use it to embed on Discord the image of the author, but I can't seem to find the URL for it in getInfo.

**Comment by fent** [comment]
It does not include it. But it is something that is on the player page that we could include. I'll keep this opened for when I have time to add that.

**Comment by FireController1847** [comment]
Awesome! Thank you.

**Comment by FireController1847** [comment]
Can't wait for this, lol. It'll be nice not having to look at a YouTube logo each time a song comes up! x3

http://img.hexacircle.com/images/Fire/e9zq1be.png

**Comment by fent** [comment]
That's encouraging. :) I plan on adding this eventually.

**Comment by fent** [comment]
New version published with user avatar [thanks to @TimeForANinja](https://github.com/fent/node-ytdl-core/pull/101)
