### ISSUE TITLE
googlevideo url take too long responds

### ISSUE THREAD

**Issue by DzakwanDawsie** [fent/node-ytdl-core#912]
when i opened some audio format url from ytdl.getInfo function , it's always getting 'take too long responds' ,  this happens on my hosting server , but in my local computer , it's going well

![image](https://user-images.githubusercontent.com/49717406/115010782-04778b80-9ed8-11eb-86b7-c546a0b045b1.png)

**Comment by TimeForANinja** [comment]
might have to do with youtube blocking your hosting provider
you can try stuff like putting a proxy inbetween
besides that the format urls are not designed to be opened with a simple web browser
