### ISSUE TITLE
Get the ID of a Youtube Channel

### ISSUE THREAD

**Issue by ExpErgio** [fent/node-ytdl-core#914]
Hello. I'm writing here because I don't know exactly where to do it.

I'm trying to find a way to get the ID of a YouTube channel, through your "npm".

For example:
If I use this URL (https://www.youtube.com/user/warnerbrosespana) I want to obtain the ID of the youtube channel

Is it possible?

**Comment by redbrain** [comment]
I doubt that ytdl-core can do that.
However, I'm able to get the ID by fetching the URL, following the redirect, and getting the new slug.

**Comment by TimeForANinja** [comment]
Yep, not a feature in / for ytdl-core
ytpl has a utility method to resolve users into the channel uploads list - which is the channel ID with a changed prefix
Use that and change the prefix back or have a look at the source code [here](https://github.com/TimeForANinja/node-ytpl/blob/master/lib/main.js#L240) which should be easy to adapt
