### ISSUE TITLE
How to know when the file was downloaded? [question]

### ISSUE THREAD

**Issue by SeaN0X** [fent/node-ytdl-core#915]
I want to know how to know when the file finishes downloading

**Comment by redbrain** [comment]
Listen for the end of the ytdl() stream.

**Comment by SeaN0X** [comment]
@redbrain giv me a exmpla of it

**Comment by TimeForANinja** [comment]
The link i provided in #916 shows you examples of reader streams and how to use the end, error and data event.
Sorry again, but we can't provide general node.js support

**Comment by hucario** [comment]
well I mean we _can_ provide general node.js support

but we don't want to

**Comment by kamal-hossain** [comment]
@SeaN0X here is an example for you:
```
ytdl(url).pipe(fs.createWriteStream('video.mp4')).on('finish', function () {
        console.log('Download finished.')
})
```
