### ISSUE TITLE
is the quality: "highest" not working?

### ISSUE THREAD

**Issue by nonopolarity** [fent/node-ytdl-core#917]
https://www.npmjs.com/package/ytdl-core#ytdl.downloadfrominfo(info%2C-options)

I tried to use

```js
ytdl.chooseFormat(
    info.formats,
    {
      quality: 'highest',
```
but is it because the quality right now is no longer `720p` as on your page, but it is `hd720`... so if you use `parseInt()`, it won't work.   The video I am trying is https://www.youtube.com/watch?v=kgiriZphpMk

and I always only get the one that is 360p with audio.

By the way, also, the name `chooseFormat()` sounded like it will "set" the download format to be that one, but it seems it won't. We still need to specify a format when downloading... so I wonder if there can be a better name... maybe `getFormat()`?

**Comment by TimeForANinja** [comment]
From the README:
> 360p will be chosen first since it's the highest quality format with both video and audio

so 
> I always only get the one that is 360p with audio.

sounds just right 🤔

**Comment by nonopolarity** [comment]
> From the README:
> 
> > 360p will be chosen first since it's the highest quality format with both video and audio
> 
> so
> 
> > I always only get the one that is 360p with audio.
> 
> sounds just right 🤔

but I looked through the array, and also did my own filtering. I was able to get 720 and with audio and video.

**Comment by TimeForANinja** [comment]
can you provide the itag / format object of that 720p audio + video?
