### ISSUE TITLE
[Wiki] a  walkground  to get it to work on cloudflare worker

### ISSUE THREAD

**Issue by gonzalezvaguiner** [fent/node-ytdl-core#919]
im totally noob with js

**Comment by redbrain** [comment]
Because of Cloudflare Workers' 10 ms CPU limit and subrequest limiting (on free tier), you're not likely to get it to work well.
I'd recommend you use a different serverless platform (eg AWS Lambda, Google Cloud Functions) or host your own server.

**Comment by gonzalezvaguiner** [comment]
> Because of Cloudflare Workers' 10 ms CPU limit and subrequest limiting (on free tier), you're not likely to get it to work well.
> I'd recommend you use a different serverless platform (eg AWS Lambda, Google Cloud Functions) or host your own server.

i see many people using it here

**Comment by WaqasIbrahim** [comment]
@redbrain Google cloud functions assigns a different IP for each request? Could be useful for bypassing the dreaded 429. Tried it with AWS but YouTube just blocks the whole range of AWS IPs.

**Comment by gonzalezvaguiner** [comment]
> Google cloud functions

it is paid
if i gonna pay better   just pay for  a vps

**Comment by redbrain** [comment]
> i see many people using it here

@gonzalezvaguiner If it does work on Cloudflare Workers, you'd be able to use ytdl-core like normal, and pipe results to whatever Response object they make available to you. For that part you should check Cloudflare's docs.

**Comment by redbrain** [comment]
I've started to look back into this, out of personal interest in using Cloudflare Workers.
To create a Worker, everything has to be webpacked before use.
When I webpack latest ytdl-core, I'm getting `Cannot read property 'protocol' of undefined` upon making a request.
I'm guessing miniget's incompatible with webpack.
In my spare time I'll work on getting ytdl-core and the Worker to cooperate.
Hopefully I don't have to create a ytdl-core fork and rewrite all the requests to use fetch.

**Comment by TimeForANinja** [comment]
> ytdl-core fork and rewrite all the requests to use fetch
guess you already spotted that all requests are indeed wrapped into miniget 😉

**Comment by redbrain** [comment]
Looked further into Cloudflare Workers, looks like using them to serve video streams is against ToS.
I'm going to stop looking into doing this now.
Edit: We can also probably close the related miniget issue since it just dealt with Workers.
