### ISSUE TITLE
IOS support

### ISSUE THREAD

**Issue by Maurice037** [fent/node-ytdl-core#922]
Hello, I have problems with audio only the format is unfortunately not compatible with ios

**Comment by redbrain** [comment]
Filter the formats to select a different container. For example, "m4a" container will work on iOS devices.

**Comment by Maurice037** [comment]
yes but i don't have m4a only webm and mp4

**Comment by Maurice037** [comment]
Does somebody has any idea

**Comment by TimeForANinja** [comment]
`m4a` is a derivate of `mp4` with only audio
besides that:
this lib only provides you with the encodings youtube offers
if you need another format it's up to you to reencode
we provided an example (in the examples folder) that shows how you could use ffmpeg to achieve this

**Comment by Maurice037** [comment]
thanks!
