### ISSUE TITLE
NO OUTPUT NO ERROR

### ISSUE THREAD

**Issue by Maurice037** [fent/node-ytdl-core#927]
Hello, i have add a proxy and cookie but ytdl-core dosn't work 
i become no error or something 
has everybody a idea?
the same code run success on my local but not on my server
my express route load Infinity

**Comment by redbrain** [comment]
Welcome to the bug tracker. Please refrain from using all caps.
If it works locally but not on the server, make sure the server is not blocked by your proxy and/or ratelimited by yt itself.
These things would probably result in an error, so ensure that you're not somehow silencing errors on the server.
