### ISSUE TITLE
Access to fetch at '' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### ISSUE THREAD

**Issue by maifeeulasad** [fent/node-ytdl-core#929]
I'm trying to download videos using `ytdl-core` in a web application without having a backend.

My code looks like this :
```
const ytdl = require('ytdl-core');

const { Url } = require('url');
const URL = Url;
const url = require('url');


const HttpsProxyAgent = require('https-proxy-agent');

const proxy = 'http://111.111.111.111:8080';
const agent = HttpsProxyAgent(proxy);
...
  download(url){
    ytdl(url,{
      requestOptions: { agent },
    });
  }
...
```
But I encounter some error saying : 
```
Access to fetch at 'https://www.youtube.com/get_video_info?video_id=sF1pLec0cIY&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FsF1pLec0cIY&ps=default&gl=US&hl=en&html5=1' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

The full log is available here: https://gist.github.com/maifeeulasad/1bdbd2c42985af2b6388f60d559005e8#file-error-md

Full repo: https://github.com/maifeeulasad/ytdl-mua/tree/5ff3279568aa6b9144b2b42d1a618e1a024d017a

Complete file reference: https://github.com/maifeeulasad/ytdl-mua/blob/5ff3279568aa6b9144b2b42d1a618e1a024d017a/src/App.js

**Comment by amitojsingh366** [comment]
the browser by default will not allow you to make requests to foreign domains due to the [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) policy, the only way to circumvent this is to set a `Access-Control-Allow-Origin` header on the server side

**Comment by TimeForANinja** [comment]
Yep, not a library problem
you can search for stuff like CORS-Proxys but nothing we can change about it in the library
