### ISSUE TITLE
some mp3s work, some dont...?

### ISSUE THREAD

**Issue by jonnydodad** [fent/node-ytdl-core#935]
hey great work on ytdl-core, its really cool !

Im trying to get a small audio only example working and it works for some videos like this : https://www.youtube.com/watch?v=yiCyKdLWOeU
but for example this video returns an unplayable mp3 : https://www.youtube.com/watch?v=qtGeeLhF_cI

i looked through the issues and didnt find any solutions... thanks for your help :)

       app.get('/downloadmp3', async (req, res, next) => {
	     try {
		var url = req.query.url;
		if(!ytdl.validateURL(url)) {
			return res.sendStatus(400);
	        }
	     let title = 'audio';

	     res.header('Content-Disposition', `attachment; filename="${title}.mp3"`);
		ytdl(url, {
			filter: 'audioonly',
			format: 'mp3'
		}).pipe(res);

	  } catch (err) {
		console.error(err);
	  }
});

**Comment by gatecrasher777** [comment]
I'm getting a lot of downloads failing too. 

This is the same as issue #932.   Getting 403 forbidden.

It happens on cyphered streams.

For example your video: https://www.youtube.com/watch?v=qtGeeLhF_cI
For me this uses this player: https://www.youtube.com/s/player/a0094ae9/player_ias.vflset/en_GB/base.js
to produce these signature keys: ["r", "w47", "r", "p1"] but this encodes the wrong signature and gets a 403.  

Normally, there are 6 keys, not 4. 

Something changed recently.

**Comment by gatecrasher777** [comment]
https://www.youtube.com/watch?v=qtGeeLhF_cI works for me now. So do others that previously failed. hmmm.

**Comment by TimeForANinja** [comment]
might just be youtube screwing up 🤷 
i'll keep an eye open for more reports
