### ISSUE TITLE
UnrecoverableError: input stream: Cookie header used in request, but unable to find YouTube identity token

### ISSUE THREAD

**Issue by XOM9lK1** [fent/node-ytdl-core#942]
```
const stream = ytdl(song.url, {
    filter: "audio",
    quality: "highestaudio",
    highWaterMark: 1 << 25,
    opusEncoded: false,
    fmt: "mp3",
    requestOptions: {
      headers: {
        Cookie: `${config.COOKIE}`,
      }
    }
  });
```

**Error:**
UnrecoverableError: input stream: Cookie header used in request, but unable to find YouTube identity token

Please help to fix

**Comment by mh4ck** [comment]
Yes it seems that they updated something.

I was also forced to update the cookie in the last days and haven't found the identity token and version number on the usual place (i haven't found it). But in my case it was enough to change the cookie and leave the identity token and version number on the old state.

**Comment by XOM9lK1** [comment]
> Yes it seems that they updated something.
> 
> I was also forced to update the cookie in the last days and haven't found the identity token and version number on the usual place (i haven't found it). But in my case it was enough to change the cookie and leave the identity token and version number on the old state.
> 
> **Edit:** In the example is a hint that you can find the identity token in the page source by searching for "ID_TOKEN"

Please get example
