### ISSUE TITLE
download stuck at 1.02mb

### ISSUE THREAD

**Issue by pkuislm** [fent/node-ytdl-core#944]
I tried to integrate this into a chatbot, but having a problem when downloading videos.
I've tried different links and it sometimes works fine, but In most cases, the downloading process will be stuck at 1MB.
I have no idea how this happens, can anyone help me? thanks a lot.
details:
using this in china via VPN
![image](https://user-images.githubusercontent.com/69719051/123024253-56262000-d40b-11eb-897c-e483246c5753.png)
![image](https://user-images.githubusercontent.com/69719051/123024284-63dba580-d40b-11eb-9185-f5518c1d5934.png)

**Comment by TimeForANinja** [comment]
i'd usually say try in a minimalistic use-case... but guess not using a vpn is not an option for you
do other formats (e.g. other quality) and no login work?

**Comment by pkuislm** [comment]
When I delete the args related to the logins, it did work the first time. But it fails when I try to download another. Tried a different format but seems helpless.BTW, Is this problem related to the quality of my connection?

**Comment by TimeForANinja** [comment]
it might be, but again... this is a use case hard for us to support / debug

**Comment by pkuislm** [comment]
Get it. Anyway, thank you for answering my questions

**Comment by TimeForANinja** [comment]
No problem
Sorry i couldn't help
feel free to write again if you got any updates
