### ISSUE TITLE
lengthSeconds undefined

### ISSUE THREAD

**Issue by YungCaedo** [fent/node-ytdl-core#949]
Code:
```
        if(ytdl.validateURL(url)) {
            let song_info = await ytdl.getInfo(args[0]);
            song = {
                title: song_info.videoDetails.title,
                artist: null,
                audiourl: song_info.videoDetails.video_url,
                duration: song_info.videoDetails.lengthSeconds,
                url: song_info.videoDetails.video_url,
                image: song_info.videoDetails.thumbnails[3].url
            }
            console.log(song_info.videoDetails);
        } 
```
for every video it keeps telling me:
`undefined`

can someone say me what I'm doing wrong

**Comment by TimeForANinja** [comment]
I am wondering you get any info at all... 
I guess you are using the hotfix provided in one of the PRs? If so then this is a known issue

**Comment by Sleepytt1210** [comment]
Hi, I've gotten the same error as well but managed to fix it.

Since microformat returned undefined for me, I appended `|| info.player_response.videoDetails.lengthSeconds` to line 287 in info-extra.js.

`
videoDetails.lengthSeconds =
    info.player_response.microformat &&
    info.player_response.microformat.playerMicroformatRenderer.lengthSeconds
    || info.player_response.videoDetails.lengthSeconds;
`

Hope it fixes for you too.

**Comment by TimeForANinja** [comment]
closing as problem with #938 and not the current main branch
