### ISSUE TITLE
Error Code 100 - This video does not exist.

### ISSUE THREAD

**Issue by tripl3dogdare** [fent/node-ytdl-core#95]
I'm getting an error code 100 trying to create a stream from [this video](https://www.youtube.com/watch?v=2Tvy_Pbe5NA). The url is correct, the video exists, but no matter what I do, I get an error code 100.

My current code:
```javascript
ytdl.getInfo("https://www.youtube.com/watch?v=2Tvy_Pbe5NA", {quality:140,filter:"audio"}, (err, i) => {
    if(err || !i) return onError("Could not find song, skipping.", err)
    playSong(ytdl.downloadFromInfo(i))
})
```

The error is being thrown from the getInfo() call and caught by my onError function. Please help, I've searched just about everywhere for a solution with no results.

**Comment by fent** [comment]
Hmm. This video gives me no errors when I try running the code above.

Would have thought that it might be related to the video being blocked in some countries, but we both seem to be in the same country, and the error code for that is [150](90).

**Comment by tripl3dogdare** [comment]
I've tried about a dozen different videos, all working fine, with the same result. I'm completing stumped.

**Comment by tripl3dogdare** [comment]
Has there been any progress on this issue? I've been getting the same error from several different packages, and I really need to be able to work with videos in this way.

**Comment by fent** [comment]
There's been no progress on this issue, I haven't been able to replicate it.

From what packages?

> EDIT: It may be important, i don't know; I'm running this as a desktop command line app rather than the back end to a website (it's for a Discord bot). Not sure if that changes anything.

Not sure what you mean by this.

**Comment by tripl3dogdare** [comment]
Particularly from [youtube-audio-stream](https://www.npmjs.com/package/youtube-audio-stream), and a few others I tried but can't remember off the top of my head. I'm currently working on finding my own manual way around the problem for now... but I'd really prefer to use an existing package if possible.

If you don't know what it means, it's probably unimportant. Sorry for the confusion.

**Comment by tripl3dogdare** [comment]
My apologies - it appears I've been an idiot and not realized two things:

- Youtube's IDs are case sensitive.
- My program was not.

Sorry for the bother.

**Comment by fent** [comment]
Ah. Well good thing it's cleared up.
