### ISSUE TITLE
No such format found on audioandvideo filter with live stream

### ISSUE THREAD

**Issue by dnm13** [fent/node-ytdl-core#953]
I'm having trouble on getting audio live stream from [a youtube live stream](https://www.youtube.com/watch?v=5qap5aO4i9A)

The stream is used for my Discord bot

```js
//...
const liveFilter: downloadOptions = { filter: 'audioandvideo', quality: 'highestaudio', highWaterMark: 1 << 25 };
//...
server.stream = ytdl(server.queue[0].link, server.filter /*in this case, use liveFilter*/);
//...
```

Tried all other filter, but not working well
audio / audioonly - Only plays the first chunk of the live stream
video / videoonly - Obviously no sound comes out
no filter - Same as video

The error I got: 

```js
Error: input stream: No such format found: highestaudio
    at Object.exports.chooseFormat (D:\MusicBot\node_modules\ytdl-core\lib\format-utils.js:168:11)
    at downloadFromInfoCallback (D:\MusicBot\node_modules\ytdl-core\lib\index.js:86:26)
    at D:\MusicBot\node_modules\ytdl-core\lib\index.js:20:5
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
I also tried all other quality, but still got the same kind of error

Where did I went wrong?
Regarding to the subject, can we add a feature where we can explicitly use HLS?

**Comment by TimeForANinja** [comment]
`No such format found` usually means that your filter `audioandvideo` resulted in all videos being removed
what you can do again is try with out the filter - might just be youtube not serving a format with both - might be the parser failing

for the `explicitly use HLS`-Question lemme just cite the code
https://github.com/fent/node-ytdl-core/blob/master/lib/format-utils.js#L107

**Comment by dnm13** [comment]
> `No such format found` usually means that your filter `audioandvideo` resulted in all videos being removed
> what you can do again is try with out the filter - might just be youtube not serving a format with both - might be the parser failing
> 
> for the `explicitly use HLS`-Question lemme just cite the code
> https://github.com/fent/node-ytdl-core/blob/master/lib/format-utils.js#L107

Hi, thanks for your reply

I wanted to try your advice, which is to try again without the filter, but the problem becomes inconsistent
somehow it's now working with the same options, which is a good thing I guess?

I've updated ytdl-core to its latest version (4.8.3, before it's 4.8.2) this morning, so I guess that's the cause?

I'll reply to this thread if it happens to throw the same error again

**Comment by dnm13** [comment]
No further error was thrown after 24 hours of testing, which is a good thing but kind of confusing
let's just hope this issue won't ever appear again for no cause / reason
closing the issue

**Comment by TimeForANinja** [comment]
if it reappears feel free to reopen 😉
