### ISSUE TITLE
Could not get `Error: Status Code: 429` fixed.

### ISSUE THREAD

**Issue by muhitrhn** [fent/node-ytdl-core#957]
I have tried installing the pr #938 and then i started getting the `Status code: 429` error. Then i tried applying the changes mentioned in #946 by manually changing the lines from node_modules but still get the same error.

**Comment by TimeForANinja** [comment]
you can try the new v4.8.3 release but 429s are usually related to ratelimits

i'm just gonna screenshot you the message we usually point to in discord
![image](https://user-images.githubusercontent.com/17046330/123500804-f31dce80-d640-11eb-9b4c-31b6fb57f163.png)
even when you follow those steps though, you have to first wait for the 429s to disappear (takes a few days) before the steps can improve your situation

**Comment by muhitrhn** [comment]
Hmm, thanks for that. Let me try those fixes. A question, is the last one necessary?

**Comment by pprathameshmore** [comment]
Same issue

**Comment by muhitrhn** [comment]
Fixed. Thank you!
