### ISSUE TITLE
Error: Could not find `player config`

### ISSUE THREAD

**Issue by FireController1847** [fent/node-ytdl-core#96]
I only have an image to describe what happened. http://img.hexacircle.com/images/Fire/vwtifo4.png

**Comment by isuckatprogram** [comment]
How did you fix?

**Comment by isuckatprogram** [comment]
bruh

**Comment by isuckatprogram** [comment]
that image is nsfw.

**Comment by fent** [comment]
if you're running into this error now, it was just fixed in the latest version
