### ISSUE TITLE
Audio data deletes itself after some time

### ISSUE THREAD

**Issue by svg94** [fent/node-ytdl-core#961]
Hi,
I'm sorry I don't know where else to ask. 
I've built a youtube downloader with the (m)ean stack and your library for downloading.
I have a small node server that does the download and pipes the download directly to the respond and by that on the client side. The clientside is an ionic app.
I don't use ffmpeg to convert the audio from mp4 to mp3 due to performance reasons (the server is very slow). I just give the mp4 an mp3 ending and it does work on my phone. 
However the audio just vanishes after I guess 2 Weeks or so.
I really don't know how to debug this because I have no starting point to search. Is it possible that the youtube audio can delete itself after a specific time? Or do you maybe know if thats a problem with the library? 
Thanks in advance. 

Sincerely
Svg

**Comment by TimeForANinja** [comment]
Did i understood you right that you download audio to your phone and 2 weeks later that same file does not work anymore?

**Comment by svg94** [comment]
Thanks for the fast reply.
Yes I download it on the phone and 2 weeks later it just vanishes. Its not corrupted the audio files are just gone

**Comment by svg94** [comment]
![serverside](https://user-images.githubusercontent.com/59804901/123549694-535c5f80-d76a-11eb-9ec1-f5e2a4a3d6f6.png)
![clientside](https://user-images.githubusercontent.com/59804901/123549696-53f4f600-d76a-11eb-9ab9-f131745bcd04.png)

These two snippets btw are the server- (white background) and clientside (dark background). Maybe this helps.

**Comment by TimeForANinja** [comment]
i'm sorry but this is out of scope
the initial download works and is playable
means the library works
there is no way to mark a mp4 or mp3 as auto-delete...
i'm not deep enough into smartphone programming 2 help

all i can propose is ask for support at a more related source
e.g. stackoverflow
or the `The Coding Den` Discord

**Comment by svg94** [comment]
Ok but its good to know that theres no auto-delete. Thanks for your help :)
