### ISSUE TITLE
No sound is playing

### ISSUE THREAD

**Issue by DARK-ECNELIS** [fent/node-ytdl-core#962]
Since the last update, there is no more problem with the details of the video but now there is no more song. Is there something to add or not since the last update?

**Comment by TimeForANinja** [comment]
default settings should still favour a video & audio format
can you provide any specific video this happens on?

**Comment by DARK-ECNELIS** [comment]
This occurs on all video

**Comment by julianvink17** [comment]
same is happening to me..

**Comment by DemonExposer** [comment]
same for me

**Comment by DemonExposer** [comment]
also, it tells me to update even though I have got the latest update (v4.8.3), so I'm just going to open up a separate issue for that

**Comment by pafad** [comment]
For all videos no song is playing, bot join a channel then leave instantly

**Comment by TrvstxdAb** [comment]
U might not have ffmpeg installed or you don’t have the ytdl discord dependency 

1. npm i ffmpeg-static
2. npm i ytdl-core-discord

**Comment by mikemaster98** [comment]
I still have the same problem even after I updated both. It hasn't been able to play any sound for some time now.

**Comment by pafad** [comment]
> U might not have ffmpeg installed or you don’t have the ytdl discord dependency
> 
> 1. npm i ffmpeg-static
> 2. npm i ytdl-core-discord

It works thx

**Comment by Bebiezaza** [comment]
> U might not have ffmpeg installed or you don’t have the ytdl discord dependency
> 
> 1. npm i ffmpeg-static
> 2. npm i ytdl-core-discord

why does this problem happens to ytdl-core but (I infer that this does) not to ytdl-core-discord?

**Comment by TimeForANinja** [comment]
> why does this problem happens to ytdl-core but (I infer that this does) not to ytdl-core-discord?

ytdl-core is not made solely for discord / music bots
ytdl-core-discord is a wrapper that tries to do set all settings nessessary to make ytdl-core work well with discord

if you use raw ytdl-core and you're having problems check which format ytdl-core actually chose, if audio is present and if the picked audio encoding works with your pipeline

**Comment by TimeForANinja** [comment]
closing this for now as i'm expecting a user error

if you do still experience this problem and the format looks fine feel free to reopen (and if possible provide a (short) code example)
