### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by newtox** [fent/node-ytdl-core#963]
Hey there, I'm currently trying to install ytdl-core on my server where I want to host my discord bot.
But for some reason I'm getting this weird error:

root@45376:~# cd Shiro
root@45376:~/Shiro# npm i ytdl-core@latest
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'shiro-ngnl@1.0',
npm WARN EBADENGINE   required: { node: '14.x' },
npm WARN EBADENGINE   current: { node: 'v16.1.0', npm: '7.11.2' }
npm WARN EBADENGINE }

**Comment by TimeForANinja** [comment]
the package `shiro-ngnl` is not related to ytdl-core
check your other dependencies 😉

**Comment by newtox** [comment]
the weird thing is, this is the name of the project in the package.json

**Comment by TimeForANinja** [comment]
do you have sth like `"engines": {"node": "14"}` set for your project?
