### ISSUE TITLE
ytdl-core v4.8.3 (latest version at the time of writing) says it is out of date

### ISSUE THREAD

**Issue by DemonExposer** [fent/node-ytdl-core#965]
When calling `ytdl()` it outputs `WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".` to console.

This should not happen, as `npm ls ytdl-core` outputs:
```
pi@ /home/pi
└── ytdl-core@4.8.3
```
and v4.8.3 is the latest version at the time of writing.

**Comment by TimeForANinja** [comment]
can't replicate
can you ensure that the version you `npm ls` is the same you use?
sth like `sudo find / | grep "ytdl-core/package.json"` should list you all places you have ytdl-core installed

**Comment by DemonExposer** [comment]
Ah thanks. It did indeed show two places for some weird reason and it was using the outdated one.
I just removed the entire `node_modules` folder in the incorrect place and did some updates to the correct one and that fixed it.

**Comment by TimeForANinja** [comment]
good to hear 👍
