### ISSUE TITLE
Related videos from getInfo() is empty

### ISSUE THREAD

**Issue by EvasiveXkiller** [fent/node-ytdl-core#966]
Hello,

I am currently using this library to get related videos from a YouTube link. Most of the videos are fine and return an array of videos.

However, I have noticed that the array can be empty. Is that the intended behavior? 

The video in question is [this](https://www.youtube.com/watch?v=x8VYWazR5mE)

Thanks in advance.

**Comment by EvasiveXkiller** [comment]
I have realized that the video is age restricted. My bad. Closing the issue

**Comment by TimeForANinja** [comment]
actually i'd say this is part of https://github.com/fent/node-ytdl-core/issues/958
