### ISSUE TITLE
Error : Error: FFmpeg/avconv not found!

### ISSUE THREAD

**Issue by uguraltinsoy** [fent/node-ytdl-core#967]
## I am getting this error after the last update please help
Discord.js

# Error
```
Error : Error: FFmpeg/avconv not found!
```
# use
```JavaScript
const dispatcher = serverQueue.connection.play(ytdl(song.url, { quality: 'highestaudio' }))
```
It used to work when I did this but after the last update it doesn't work either
```
npm i ffmpeg-static
```
Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-1160.11.1.el7.x86_64
Architecture: x86-64

**Comment by TheWilfrido** [comment]
Try this `const dispatcher = serverQueue.connection.play(await ytdl(song.url, { filter: "audioonly", type: "opus", quality: "highestaudio" })).on("error", err => { return console.log("Dispatcher error: ", err) });` and let me now if it works

**Comment by TheWilfrido** [comment]
Try this `const dispatcher = serverQueue.connection.play(await ytdl(song.url, { filter: "audioonly", type: "opus", quality: "highestaudio" })).on("error", err => { return console.log("Dispatcher error: ", err) });` and let me know if it works.

**Comment by uguraltinsoy** [comment]
The problem has not changed, unfortunately it works in Windows but not in Linux Centos.

```Java Script
const dispatcher = serverQueue.connection.play(await ytdl(song.url, { filter: "audioonly", type: "opus", quality: "highestaudio"}))
            .on('finish', () => {
                serverQueue.songs.shift()
                play(guild, serverQueue.songs[0])
            })
            .on('error', error => {
                console.log(error)
            })
```

![L6LYaOgUyy](https://user-images.githubusercontent.com/48494791/125077722-14af9900-e0ca-11eb-9734-b2fc6f8422d9.png)

**Comment by redbrain** [comment]
Install FFmpeg system-wide, that is, to the PATH.

**Comment by TheWilfrido** [comment]
Make sure you are calling the ffmpeg module, if you don't have it installed there are many modules you can use, this one for example https://www.npmjs.com/package/ffmpeg-static you just need to put a `require('ffmpeg- static ');` it's automatically invoked every time you use `.play(...)`.

**Comment by moon91210** [comment]
no need to require it, just need to do ``npm i ffmpeg-static`` and you're good
