### ISSUE TITLE
UnrecoverableError: input stream: Cookie header used in request, but unable to find YouTube identity token

### ISSUE THREAD

**Issue by Jingexz01** [fent/node-ytdl-core#969]
When my discord bot joins the voice channel it directly leaves and gives an error on logs saying: 
UnrecoverableError: input stream: Cookie header used in request, but unable to find YouTube identity token

**Comment by TimeForANinja** [comment]
It looks like you tried to use Cookies to prevent the StatusCode 429 Problem
as the Error states you need to not only set the `Cookie` header but also the YouTube identity token (should be sth like `x-youtube-identity`
