### ISSUE TITLE
Issue with videos that are not available in youtube.

### ISSUE THREAD

**Issue by Syque** [fent/node-ytdl-core#970]
![image](https://user-images.githubusercontent.com/60582843/125520460-f22e7362-1a10-4329-81d9-0c4776332b19.png)

For example if the video is: https://www.youtube.com/watch?v=zI2qbr99H64

How can I get over this?

**Comment by TheWilfrido** [comment]
![image](https://user-images.githubusercontent.com/67902290/125526904-b4883e67-9a33-450f-99cb-9d8bc02d9b59.png)
It's not a ytdl-core issue your video it's blocked in some countries, you should make a filter for blocked videos from your IP for example: 
```javascript
let videoInfo = await ytdl.getInfo(url);
if(videoInfo.player_response.playabilityStatus.status === "UNPLAYABLE"){
	return msg.channel.send("Video unplayable...");
} else {
	//your code for playable videos...
};
```
or you can also use Proxy to access the blocked content https://github.com/fent/node-ytdl-core/blob/master/example/proxy.js

**Comment by Syque** [comment]
Acquired VPN service for this.

Thank you for your quick response!

**Comment by Syque** [comment]
![image](https://user-images.githubusercontent.com/60582843/125648181-46cfb717-85b4-4738-a5c7-d2676153ef9f.png)

Got another one. This one is a bit strange. Script starts downloading the videos but without giving any errors some of them seem to be corrupted or something. Any ideas how I can quickly get what the problem is?

**Comment by redbrain** [comment]
Try manually opening the corrupted files with VLC. If it works, than the it's likely that you're simply missing file extensions.

**Comment by Syque** [comment]
> Try manually opening the corrupted files with VLC. If it works, than the it's likely that you're simply missing file extensions.

Nah, tried all of this. :/

**Comment by Syque** [comment]
> Try manually opening the corrupted files with VLC. If it works, than the it's likely that you're simply missing file extensions.

Could it be somehow related to VPN?

**Comment by Syque** [comment]
**The problem was that filesystems doesn't allow special characters and I piped movie title as filename that included some of prohibited ones.**
