### ISSUE TITLE
Play videos that are account required?

### ISSUE THREAD

**Issue by NNickey** [fent/node-ytdl-core#98]
Wondering if it's possible to provide an account for it to use if a video it tried to play is 18+ account required?

**Comment by fent** [comment]
18+ videos should be downloadable, there's a test for it

https://github.com/fent/node-ytdl-core/blob/master/test/irl-test.js#L10

Is there a video where this didn't work?

**Comment by fent** [comment]
And to answer your question more directly, you can pass in a cookie with `requestOptions`

https://github.com/fent/node-ytdl-core#ytdlurl-options

**Comment by NNickey** [comment]
The ytdl-core wasn't able to process
Tzuvfy4jFwE

**Comment by NNickey** [comment]
I'm still unsure how you would set a cookie through requestOptions when that adds headers.

**Comment by fent** [comment]
> The ytdl-core wasn't able to process
> Tzuvfy4jFwE

I'll keep this issue opened for this.

**Comment by fent** [comment]
> I'm still unsure how you would set a cookie through requestOptions when that adds headers.

http://stackoverflow.com/questions/24365600/passing-cookies-in-nodejs-http-request
