### ISSUE TITLE
[feature request] livechart replay

### ISSUE THREAD

**Issue by TentacleSama4254** [fent/node-ytdl-core#988]
Is it possible to obtain the livechat replay info if youtube videos

**Comment by TimeForANinja** [comment]
Haven't heard from anyone even trying... The info might be in the info though 🤷‍♀️

**Comment by TentacleSama4254** [comment]
> Haven't heard from anyone even trying... The info might be in the info though 🤷‍♀️

Info?

**Comment by TimeForANinja** [comment]
actually it is way easier...

a quick google search got me this q&a
https://support.google.com/youtube/answer/2524549?hl=en

The interesting part:
> Embed live chat
During a live stream, you can embed live chat on your own site by using an iframe.
Note: embedding live chat isn't available on mobile web.
> * Get the video ID for the live stream. You can get the video ID from the watch page URL (youtube.com/watch?v=12345). In this case, the video ID is ‘12345’.
> * Get the domain URL for the site you want to embed chat on. If you're embedding chat on www.example.com/youtube_chat, your embedding domain is "www.example.com."
> * Combine the embedded URL in the following way: https://www.youtube.com/live_chat?v=12345&embed_domain=www.example.com.
>
> This is the URL for your iframe. Note the embed_domain must match the the URL of the page you’re embedding the chat on. If they are different, the embedded chat will not load.

try reverse engineering the iframe 🤷 
should be some kinda regular irc

**Comment by TentacleSama4254** [comment]
> actually it is way easier...
> 
> a quick google search got me this q&a
> https://support.google.com/youtube/answer/2524549?hl=en
> 
> The interesting part:
> > Embed live chat
> During a live stream, you can embed live chat on your own site by using an iframe.
> Note: embedding live chat isn't available on mobile web.
> > * Get the video ID for the live stream. You can get the video ID from the watch page URL (youtube.com/watch?v=12345). In this case, the video ID is ‘12345’.
> > * Get the domain URL for the site you want to embed chat on. If you're embedding chat on www.example.com/youtube_chat, your embedding domain is "www.example.com."
> > * Combine the embedded URL in the following way: https://www.youtube.com/live_chat?v=12345&embed_domain=www.example.com.
> >
> > This is the URL for your iframe. Note the embed_domain must match the the URL of the page you’re embedding the chat on. If they are different, the embedded chat will not load.
> 
> try reverse engineering the iframe 🤷 
> should be some kinda regular irc

Damn that's great. But can you also acess the livechat in that way after the stream has ended?

**Comment by TimeForANinja** [comment]
for replays there's the `https://www.youtube.com/live_chat_replay` endpoint
query parameters are
`continuation`
and
`playerOffsetMs`
the second should explain itself
the first identifies the video and you're likely to find it somewhere inside the player data or the page
