### ISSUE TITLE
The downloaded mp3 cannot be edited (metatags)

### ISSUE THREAD

**Issue by gianlop3z** [fent/node-ytdl-core#991]
I'm making a music downloader, i'm getting the audio from youtube (mp3), when i go to edit the downloaded mp3 tags, these are not getting added.

**Comment by TimeForANinja** [comment]
try breaking your workflow into parts
* does the download work fine?
* does playing the downloaded file work?
* does setting meta info for a different mp3 from a verified source work?

... and so on

besides that make sure you actually do receive an mp3
* youtube fires you an event with the chosen format
* ffprobe should be able to tell you the encoding
* you can just use ffmpeg to convert it to mp3 no matter what it is

**Comment by gianlop3z** [comment]
I solved it. I don't know why, i just re-converted the .mp3 to .mp3 using fluent-ffmpeg, thanks

**Comment by TimeForANinja** [comment]
that most likely means the file you downloaded is not an mp3 😉 
closing this isssue since this is not a library problem
