### ISSUE TITLE
Low quality videos

### ISSUE THREAD

**Issue by NoahNationYT** [fent/node-ytdl-core#993]
The videos have really low quality when downloaded. Is there any way to make it a higher resolution?

**Comment by redbrain** [comment]
The default is 360p. Perhaps what you're looking for is the 'highestvideo' quality parameter?

**Comment by RiyanRIS** [comment]
Ah, i see.. @TimeForANinja, my problem is i was set filter to audioandvideo. When i delete it, i got video with good quality but no sound. Can u recomended source code or package to add audio on my hd video? Thanks before..

**Comment by TimeForANinja** [comment]
you can try the npm package `ytmux`
we do also have examples (in the examples folder) on how to merge audio + video 😉

**Comment by RiyanRIS** [comment]
> npm package `ytmux`

helo, can you give me direct link to this package, i dont find anything when search it on npmjs or on google, thanks before.

**Comment by redbrain** [comment]
I believe he's referring to https://www.npmjs.com/package/ytdl-core-muxer
