### ISSUE TITLE
[feature request] clips

### ISSUE THREAD

**Issue by TentacleSama4254** [fent/node-ytdl-core#996]
Add support to download /clip/ links for the clipped video feature

Eg https://youtube.com/clip/UgyME6e4kWbVsjQ4O0Z4AaABCQ

**Comment by redbrain** [comment]
It looks like clips are just ranges of an existing video.
It's impossible to download video ranges without using something like ffmpeg on the receiving end.
A wrapper library could fulfill this purpose.
