### ISSUE TITLE
Shorts Video

### ISSUE THREAD

**Issue by SploeCyber** [fent/node-ytdl-core#999]
Add support for this thing 'https://youtube.com/shorts/UIDLrsO2tjo'

**Comment by llsc12** [comment]
shorts work fine just grab the video id and download using that instead.

**Comment by SploeCyber** [comment]
for some reason it returns a 403 error

**Comment by llsc12** [comment]
thats odd, it works fine for me

**Comment by TimeForANinja** [comment]
closing this since
a) noone else seems to have this problem
b) the video mentioned got removed
c) shorts work fine (on my machine 😉 )
